import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import { mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { isAbsolute, relative, resolve, sep } from 'node:path';
import type { OrganizationId, OrganizationScope, WorkspaceId } from '@scoutops/contracts';
import { assertOrganizationScope } from '@scoutops/contracts';

export class StorageBoundaryError extends Error { constructor(readonly code:'invalid_scope'|'invalid_segment'|'path_escape'|'invalid_grant'|'grant_expired',message:string){super(message);this.name='StorageBoundaryError';} }
function safeSegment(value:string,field:string){const v=value.trim();if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,159}$/.test(v)||v==='.'||v==='..')throw new StorageBoundaryError('invalid_segment',`${field} is invalid`);return v;}
function assertInside(root:string,target:string){const rel=relative(root,target);if(!rel||rel==='..'||rel.startsWith(`..${sep}`)||isAbsolute(rel))throw new StorageBoundaryError('path_escape','file path must remain inside the configured root');}
export interface ScopedFileInput extends OrganizationScope { category:'evidence'|'export'|'attachment';resource_id:string;filename:string }
export function buildScopedFilePath(root:string,input:ScopedFileInput):string{try{assertOrganizationScope(input,{workspaceRequired:true});}catch{throw new StorageBoundaryError('invalid_scope','organization_id and workspace_id are required');}const absoluteRoot=resolve(root);const target=resolve(absoluteRoot,'organizations',safeSegment(input.organization_id,'organization_id'),'workspaces',safeSegment(input.workspace_id!,'workspace_id'),input.category,safeSegment(input.resource_id,'resource_id'),safeSegment(input.filename,'filename'));assertInside(absoluteRoot,target);return target;}
export async function writeScopedFile(root:string,input:ScopedFileInput,data:Uint8Array):Promise<string>{const target=buildScopedFilePath(root,input);await mkdir(resolve(target,'..'),{recursive:true});const temporary=`${target}.${randomUUID()}.tmp`;try{await writeFile(temporary,data,{flag:'wx'});await rename(temporary,target);return target;}catch(error){await rm(temporary,{force:true});throw error;}}

interface DownloadClaims {organization_id:string;workspace_id:string;relative_path:string;expires_at:number;nonce:string}
const encode=(value:string)=>Buffer.from(value).toString('base64url');
export function issueDownloadGrant(root:string,input:ScopedFileInput,signingKey:Uint8Array,ttlSeconds:number,nowSeconds=Math.floor(Date.now()/1000)):string{if(signingKey.byteLength<32)throw new StorageBoundaryError('invalid_grant','download signing key must contain at least 32 bytes');if(!Number.isSafeInteger(ttlSeconds)||ttlSeconds<1||ttlSeconds>300)throw new StorageBoundaryError('invalid_grant','download grant TTL must be 1 to 300 seconds');const target=buildScopedFilePath(root,input);const claims:DownloadClaims={organization_id:input.organization_id,workspace_id:input.workspace_id!,relative_path:relative(resolve(root),target).split(sep).join('/'),expires_at:nowSeconds+ttlSeconds,nonce:randomUUID()};const payload=encode(JSON.stringify(claims));const signature=createHmac('sha256',signingKey).update(payload).digest('base64url');return `${payload}.${signature}`;}
export function verifyDownloadGrant(token:string,signingKey:Uint8Array,scope:{organization_id:string;workspace_id:string},nowSeconds=Math.floor(Date.now()/1000)):DownloadClaims{const [payload,signature,...extra]=token.split('.');if(!payload||!signature||extra.length)throw new StorageBoundaryError('invalid_grant','download grant is malformed');const expected=createHmac('sha256',signingKey).update(payload).digest();let actual:Buffer;try{actual=Buffer.from(signature,'base64url');}catch{throw new StorageBoundaryError('invalid_grant','download grant signature is invalid');}if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new StorageBoundaryError('invalid_grant','download grant signature is invalid');let claims:DownloadClaims;try{claims=JSON.parse(Buffer.from(payload,'base64url').toString('utf8'));}catch{throw new StorageBoundaryError('invalid_grant','download grant payload is invalid');}if(claims.organization_id!==scope.organization_id||claims.workspace_id!==scope.workspace_id)throw new StorageBoundaryError('invalid_scope','download grant scope does not match');if(claims.expires_at<nowSeconds)throw new StorageBoundaryError('grant_expired','download grant has expired');if(isAbsolute(claims.relative_path)||claims.relative_path.split('/').includes('..'))throw new StorageBoundaryError('path_escape','download path is invalid');return claims;}

const SENSITIVE=/(password|secret|token|cookie|authorization|api[_-]?key|private[_-]?key)/i;
export function redactAuditMetadata(value:unknown,depth=0):unknown{if(depth>8)return'[TRUNCATED]';if(Array.isArray(value))return value.map(item=>redactAuditMetadata(item,depth+1));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,SENSITIVE.test(key)?'[REDACTED]':redactAuditMetadata(item,depth+1)]));return typeof value==='string'&&value.length>2000?`${value.slice(0,2000)}[TRUNCATED]`:value;}
export interface AuditEventInput {organization_id:OrganizationId;workspace_id?:WorkspaceId;actor_id:string;action:string;resource_type:string;resource_id:string;request_id:string;trace_id:string;metadata?:Record<string,unknown>}
export function createAuditEvent(input:AuditEventInput,occurredAt=new Date()){assertOrganizationScope(input);return{audit_id:randomUUID(),organization_id:input.organization_id,...(input.workspace_id?{workspace_id:input.workspace_id}:{}),actor_id:safeSegment(input.actor_id,'actor_id'),action:safeSegment(input.action,'action'),resource_type:safeSegment(input.resource_type,'resource_type'),resource_id:safeSegment(input.resource_id,'resource_id'),request_id:input.request_id,trace_id:input.trace_id,metadata:redactAuditMetadata(input.metadata??{}),occurred_at:occurredAt.toISOString(),schema_version:1 as const};}
