window.REVIEW_C_DATA = {
  version: "REVIEW-C-r1",
  fixedNow: "2026-08-23T03:00:00.000Z",
  facts: {
    detail: {
      id: "00000000-0000-4000-8000-000000000701",
      name: "便携净水杯机会",
      market: "US",
      category: "outdoor",
      source_type: "manual",
      source_ref_id: null,
      owner_id: null,
      lifecycle_status: "ready",
      recommendation_status: "insufficient_data",
      overall_score: null,
      trend_score: null,
      competition_score: null,
      profit_status: "insufficient_data",
      risk_level: "unknown",
      confidence: {
        status: "insufficient_data",
        score: null,
      },
      evidence_count: 1,
      source_count: 1,
      coverage_status: "partial",
      decision_status: "pending",
      version: 1,
      updated_at: "2026-08-08T12:00:00.000Z",
      score_rule_version: null,
      scored_at: null,
      latest_score_run: null,
      score_components: [],
      evidence: [],
      decisions: [],
      section_status: {
        market: "covered",
        competition: "insufficient_data",
        profit: "insufficient_data",
        risk: "insufficient_data",
        execution: "not_available",
      },
    },
    analyses: [
      {
        id: "00000000-0000-4000-8000-000000000705",
        status: "succeeded",
        attempt_count: 1,
        last_error_code: null,
        input_sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        prompt_contract_version: "opportunity-assist-v1",
        created_at: "2026-08-08T12:01:00.000Z",
        result: {
          id: "00000000-0000-4000-8000-000000000702",
          content: {
            summary: "当前机会已有市场方向，但评分、利润和风险证据仍不足。",
            classifications: [
              {
                label: "需要人工补充",
                rationale: "现有事实不足以支持可靠结论。",
                source_refs: ["opportunity:00000000-0000-4000-8000-000000000701"],
              },
            ],
            missing_fields: [
              {
                field: "profit",
                reason: "尚无确定性利润运行。",
                source_refs: ["opportunity:00000000-0000-4000-8000-000000000701"],
              },
            ],
          },
          ai_generated: true,
          model_name: "Qwen3.5-9B-AWQ-4bit",
          provider_request_id: "provider-test",
          review_status: "pending",
          review: null,
        },
      },
    ],
  },
  lineage: {
    freshness: {
      observed_at: "2026-08-23T02:00:00.000Z",
      age_seconds: 3600,
    },
    failure_impact: {
      level: "blocked",
      codes: [
        "completed_with_warnings",
        "failed_terminal:parser_failed",
        "open:critical",
        "warning",
      ],
      affected_stages: ["collection_task", "collection_attempt", "quality_issue", "notification"],
    },
    request_ids: [
      "request-source",
      "request-collection",
      "request-attempt",
      "request-quality",
      "request-trend",
      "request-opportunity",
      "request-score",
      "request-profit",
      "request-task",
      "request-notification",
    ],
    trace_ids: ["trace-business"],
    nodes: [
      {
        kind: "source",
        id: "source-1",
        label: "Google 新闻",
        status: "enabled",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-source",
        trace_id: "trace-business",
        route: "/platform-admin/providers/sources?provider_id=source-1",
      },
      {
        kind: "collection_task",
        id: "collection-1",
        label: "采集任务",
        status: "completed_with_warnings",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-collection",
        trace_id: "trace-business",
        route: "/platform-admin/collection?task_id=collection-1",
      },
      {
        kind: "collection_attempt",
        id: "attempt-1",
        label: "采集尝试",
        status: "failed_terminal:parser_failed",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-attempt",
        trace_id: "trace-business",
        route: "/platform-admin/collection?task_id=collection-1",
      },
      {
        kind: "evidence",
        id: "evidence-1",
        label: "原始证据",
        status: "active",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-source",
        trace_id: "trace-business",
        route: "/platform-admin/data?evidence_id=evidence-1",
      },
      {
        kind: "quality_issue",
        id: "quality-1",
        label: "质量问题：source_freshness",
        status: "open:critical",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-quality",
        trace_id: "trace-business",
        route: "/platform-admin/data?issue_id=quality-1",
      },
      {
        kind: "trend",
        id: "trend-1",
        label: "便携净水",
        status: "active",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-trend",
        trace_id: "trace-business",
        route: "/trends?topic_id=trend-1",
      },
      {
        kind: "opportunity",
        id: "opportunity-1",
        label: "便携净水机会",
        status: "observing",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-opportunity",
        trace_id: "trace-business",
        route: "/opportunities/opportunity-1?tab=lineage",
      },
      {
        kind: "score",
        id: "score-1",
        label: "机会评分",
        status: "calculated",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-score",
        trace_id: "trace-business",
        route: "/opportunities/opportunity-1?tab=overview",
      },
      {
        kind: "profit",
        id: "profit-1",
        label: "利润核算",
        status: "calculated",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-profit",
        trace_id: "trace-business",
        route: "/opportunities/opportunity-1?tab=profit",
      },
      {
        kind: "task",
        id: "task-1",
        label: "补齐证据",
        status: "todo",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-task",
        trace_id: "trace-business",
        route: "/tasks/task-1",
      },
      {
        kind: "notification",
        id: "notification-1",
        label: "需要重新决策",
        status: "warning",
        occurred_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-notification",
        trace_id: "trace-business",
        route: "/notifications?notification=notification-1",
      },
    ],
  },
  feedbackVersions: {
    history: {
      facts: [
        {
          id: "fact-1",
          period_start: "2026-08-01",
          period_end: "2026-08-22",
          sales_units: 100,
          revenue_amount: 1000,
          ad_spend_amount: 100,
          returned_units: 5,
          purchase_lead_time_days: 12,
          actual_profit_amount: 280,
          currency: "USD",
          source_ref: "ERP-SALES-202608",
          notes: null,
          score_rule_version_snapshot: "score-v3",
          profit_rule_version_snapshot: "profit-v2",
          decision_status_snapshot: "adopted",
          predicted_profit_amount: 300,
          predicted_currency: "USD",
          quoted_lead_time_days: 8,
          observed_at: "2026-08-23T02:00:00.000Z",
          request_id: "request-feedback",
          trace_id: "trace-feedback",
          created_at: "2026-08-23T02:00:00.000Z",
        },
      ],
      calibration: {
        fact_id: "fact-1",
        return_rate_percent: 5,
        ad_spend_ratio_percent: 10,
        profit_variance_amount: -20,
        profit_variance_currency: "USD",
        lead_time_variance_days: 4,
        score_rule_version: "score-v3",
        profit_rule_version: "profit-v2",
        decision_status_snapshot: "adopted",
        human_review_required: true,
        automatic_rule_update: false,
        automatic_decision: false,
      },
    },
    incomparable: {
      facts: [
        {
          id: "fact-1",
          period_start: "2026-08-01",
          period_end: "2026-08-22",
          sales_units: 100,
          revenue_amount: 1000,
          ad_spend_amount: 100,
          returned_units: 5,
          purchase_lead_time_days: 12,
          actual_profit_amount: 280,
          currency: "USD",
          source_ref: "ERP-SALES-202608",
          notes: null,
          score_rule_version_snapshot: "score-v3",
          profit_rule_version_snapshot: "profit-v2",
          decision_status_snapshot: "adopted",
          predicted_profit_amount: 300,
          predicted_currency: "CNY",
          quoted_lead_time_days: null,
          observed_at: "2026-08-23T02:00:00.000Z",
          request_id: "request-feedback",
          trace_id: "trace-feedback",
          created_at: "2026-08-23T02:00:00.000Z",
        },
      ],
      calibration: {
        fact_id: "fact-1",
        return_rate_percent: 5,
        ad_spend_ratio_percent: 10,
        profit_variance_amount: null,
        profit_variance_currency: null,
        lead_time_variance_days: null,
        score_rule_version: "score-v3",
        profit_rule_version: "profit-v2",
        decision_status_snapshot: "adopted",
        human_review_required: true,
        automatic_rule_update: false,
        automatic_decision: false,
      },
    },
    zero: {
      facts: [
        {
          id: "fact-1",
          period_start: "2026-08-01",
          period_end: "2026-08-22",
          sales_units: 0,
          revenue_amount: 0,
          ad_spend_amount: 0,
          returned_units: 0,
          purchase_lead_time_days: 0,
          actual_profit_amount: 0,
          currency: "USD",
          source_ref: "ERP-SALES-202608",
          notes: null,
          score_rule_version_snapshot: "score-v3",
          profit_rule_version_snapshot: "profit-v2",
          decision_status_snapshot: "adopted",
          predicted_profit_amount: 0,
          predicted_currency: "USD",
          quoted_lead_time_days: 0,
          observed_at: "2026-08-23T02:00:00.000Z",
          request_id: "request-feedback",
          trace_id: "trace-feedback",
          created_at: "2026-08-23T02:00:00.000Z",
        },
      ],
      calibration: {
        fact_id: "fact-1",
        return_rate_percent: null,
        ad_spend_ratio_percent: null,
        profit_variance_amount: 0,
        profit_variance_currency: "USD",
        lead_time_variance_days: 0,
        score_rule_version: "score-v3",
        profit_rule_version: "profit-v2",
        decision_status_snapshot: "adopted",
        human_review_required: true,
        automatic_rule_update: false,
        automatic_decision: false,
      },
    },
    loss: {
      facts: [
        {
          id: "fact-1",
          period_start: "2026-08-01",
          period_end: "2026-08-22",
          sales_units: 100,
          revenue_amount: 1000,
          ad_spend_amount: 100,
          returned_units: 5,
          purchase_lead_time_days: 12,
          actual_profit_amount: -20,
          currency: "USD",
          source_ref: "ERP-SALES-202608",
          notes: null,
          score_rule_version_snapshot: "score-v3",
          profit_rule_version_snapshot: "profit-v2",
          decision_status_snapshot: "adopted",
          predicted_profit_amount: 300,
          predicted_currency: "USD",
          quoted_lead_time_days: 8,
          observed_at: "2026-08-23T02:00:00.000Z",
          request_id: "request-feedback",
          trace_id: "trace-feedback",
          created_at: "2026-08-23T02:00:00.000Z",
        },
      ],
      calibration: {
        fact_id: "fact-1",
        return_rate_percent: 5,
        ad_spend_ratio_percent: 10,
        profit_variance_amount: -320,
        profit_variance_currency: "USD",
        lead_time_variance_days: 4,
        score_rule_version: "score-v3",
        profit_rule_version: "profit-v2",
        decision_status_snapshot: "adopted",
        human_review_required: true,
        automatic_rule_update: false,
        automatic_decision: false,
      },
    },
  },
  feedbackSubmission: {
    facts: [
      {
        id: "isolated-submitted-fact-1",
        period_start: "2026-08-01",
        period_end: "2026-08-22",
        sales_units: 100,
        revenue_amount: 1000,
        ad_spend_amount: 100,
        returned_units: 5,
        purchase_lead_time_days: 12,
        actual_profit_amount: 280,
        currency: "USD",
        source_ref: "ERP-SALES-202608",
        notes: "财务与采购已核对",
        score_rule_version_snapshot: null,
        profit_rule_version_snapshot: null,
        decision_status_snapshot: "pending",
        predicted_profit_amount: null,
        predicted_currency: null,
        quoted_lead_time_days: null,
        observed_at: "2026-08-23T03:00:00.000Z",
        request_id: "isolated-feedback-submission",
        trace_id: "isolated-feedback-trace",
        created_at: "2026-08-23T03:00:00.000Z",
      },
      {
        id: "fact-1",
        period_start: "2026-08-01",
        period_end: "2026-08-22",
        sales_units: 100,
        revenue_amount: 1000,
        ad_spend_amount: 100,
        returned_units: 5,
        purchase_lead_time_days: 12,
        actual_profit_amount: 280,
        currency: "USD",
        source_ref: "ERP-SALES-202608",
        notes: null,
        score_rule_version_snapshot: "score-v3",
        profit_rule_version_snapshot: "profit-v2",
        decision_status_snapshot: "adopted",
        predicted_profit_amount: 300,
        predicted_currency: "USD",
        quoted_lead_time_days: 8,
        observed_at: "2026-08-23T02:00:00.000Z",
        request_id: "request-feedback",
        trace_id: "trace-feedback",
        created_at: "2026-08-23T02:00:00.000Z",
      },
    ],
    calibration: {
      fact_id: "isolated-submitted-fact-1",
      return_rate_percent: 5,
      ad_spend_ratio_percent: 10,
      profit_variance_amount: null,
      profit_variance_currency: null,
      lead_time_variance_days: null,
      score_rule_version: null,
      profit_rule_version: null,
      decision_status_snapshot: "pending",
      human_review_required: true,
      automatic_rule_update: false,
      automatic_decision: false,
    },
  },
  defaults: {
    period_start: "2026-08-23",
    period_end: "2026-08-23",
    sales_units: 0,
    revenue_amount: 0,
    ad_spend_amount: 0,
    returned_units: 0,
    purchase_lead_time_days: 0,
    actual_profit_amount: 0,
    currency: "USD",
    source_ref: "",
    notes: "",
    observed_at: "2026-08-23T03:00:00.000Z",
  },
  feedbackForm: {
    period_start: "2026-08-01",
    period_end: "2026-08-22",
    sales_units: 100,
    revenue_amount: 1000,
    ad_spend_amount: 100,
    returned_units: 5,
    purchase_lead_time_days: 12,
    actual_profit_amount: 280,
    currency: "usd",
    source_ref: "ERP-SALES-202608",
    notes: "财务与采购已核对",
    observed_at: "2026-08-23T02:00:00.000Z",
  },
  feedbackIntent: {
    method: "POST",
    path: "/opportunities/00000000-0000-4000-8000-000000000701/operating-feedback",
    body: {
      period_start: "2026-08-01",
      period_end: "2026-08-22",
      sales_units: 100,
      revenue_amount: 1000,
      ad_spend_amount: 100,
      returned_units: 5,
      purchase_lead_time_days: 12,
      actual_profit_amount: 280,
      currency: "USD",
      source_ref: "ERP-SALES-202608",
      notes: "财务与采购已核对",
      observed_at: "2026-08-23T03:00:00.000Z",
      expected_version: 1,
    },
  },
  intents: {
    approved: {
      method: "POST",
      path: "/ai-analyses/00000000-0000-4000-8000-000000000702/reviews",
      body: {
        outcome: "approved",
        notes: "已核对原始证据范围",
      },
    },
    rejected: {
      method: "POST",
      path: "/ai-analyses/00000000-0000-4000-8000-000000000702/reviews",
      body: {
        outcome: "rejected",
        notes: "已核对原始证据范围",
      },
    },
    queue: {
      method: "POST",
      path: "/opportunities/00000000-0000-4000-8000-000000000701/ai-analyses",
      body: {
        expected_version: 1,
      },
    },
  },
  reason: "  已核对原始证据范围  ",
  knownGaps: {
    aiReadFailureKeepsOldResults: true,
    malformedAiResponseBecomesEmpty: true,
    reviewClosesBeforeWriteAndFailure: true,
    frontendReviewMin2BackendMin1Max1000: true,
    lineageNullAgeRenderedAsZero: true,
    sourceFixed: false,
  },
  boundary:
    "Historical isolated AI/lineage/operating-feedback fixtures; source functions and inert repository read adapters, no real Vue/API/DB/RBAC/worker/production. Lineage fixture retains opportunity-1 and its routes separately from the AI fixture; no cross-object causal graph. Scenario mutations are explicitly synthetic. Calibration is calculated by extracted repository code offline, never by the browser or from AI output.",
};
