import { randomUUID } from 'node:crypto';
import type { Pool,PoolConnection,RowDataPacket } from 'mysql2/promise';
type Job={id:string;organizationId:string;workspaceId:string;competitorId:string;snapshotId:string;requestId:string;traceId:string;attemptCount:number};
export class CompetitorMonitorError extends Error{constructor(readonly code:string,readonly retryable:boolean){super(code);}}
export class MySqlCompetitorMonitorWorker{
 constructor(private readonly pool:Pool,private readonly workerId:string,private readonly leaseSeconds:number,private readonly now=()=>new Date()){}
 async processOnce(){const job=await this.claim();if(!job)return{status:'idle' as const};try{const result=await this.compare(job);return{status:'succeeded' as const,job_id:job.id,...result};}catch(e){const error=e instanceof CompetitorMonitorError?e:new CompetitorMonitorError('competitor_monitor_internal_error',true);const status=!error.retryable?'failed_terminal':job.attemptCount>=4?'dead_letter':'scheduled';await this.finish(job,status,error.code);return{status,job_id:job.id,error_code:error.code};}}
 private async claim():Promise<Job|null>{const c=await this.pool.getConnection(),now=this.now(),expires=new Date(now.getTime()+this.leaseSeconds*1000);try{await c.beginTransaction();const[rows]=await c.query<RowDataPacket[]>("SELECT * FROM competitor_snapshot_jobs WHERE status IN ('queued','retry_scheduled','leased') AND available_at<=? AND (lease_expires_at IS NULL OR lease_expires_at<=?) ORDER BY created_at,id LIMIT 1 FOR UPDATE",[now,now]);const r=rows[0];if(!r){await c.commit();return null;}await c.query("UPDATE competitor_snapshot_jobs SET status='leased',attempt_count=attempt_count+1,lease_owner=?,lease_expires_at=?,updated_at=? WHERE id=?",[this.workerId,expires,now,r.id]);await c.commit();return{id:String(r.id),organizationId:String(r.organization_id),workspaceId:String(r.workspace_id),competitorId:String(r.competitor_id),snapshotId:String(r.snapshot_id),requestId:String(r.request_id),traceId:String(r.trace_id),attemptCount:Number(r.attempt_count)+1};}catch(e){await c.rollback();throw e;}finally{c.release();}}
 private async compare(job:Job){const c=await this.pool.getConnection(),now=this.now();try{await c.beginTransaction();const[rows]=await c.query<RowDataPacket[]>('SELECT c.latest_snapshot_id,s.* FROM competitors c JOIN competitor_snapshots s ON s.id=? AND s.competitor_id=c.id WHERE c.id=? AND c.organization_id=? AND c.workspace_id=? FOR UPDATE',[job.snapshotId,job.competitorId,job.organizationId,job.workspaceId]);const current=rows[0];if(!current)throw new CompetitorMonitorError('competitor_snapshot_missing',false);let previous:RowDataPacket|undefined;if(current.latest_snapshot_id&&String(current.latest_snapshot_id)!==job.snapshotId){const[p]=await c.query<RowDataPacket[]>('SELECT * FROM competitor_snapshots WHERE id=? AND competitor_id=?',[current.latest_snapshot_id,job.competitorId]);previous=p[0];}const changes:Record<string,{old:string;now:string}>={};if(previous){for(const field of ['current_price','rank_value','review_count','rating_value','availability']){const old=String(previous[field]),value=String(current[field]);if(old!==value)changes[field]={old,now:value};}}
  for(const[field,value]of Object.entries(changes)){const changeId=randomUUID(),impact=this.impact(field,value.old,value.now);await c.query('INSERT INTO competitor_changes (id,organization_id,workspace_id,competitor_id,snapshot_id,field_name,previous_value,current_value,changed_at,evidence_id,impact_explanation,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[changeId,job.organizationId,job.workspaceId,job.competitorId,job.snapshotId,field,value.old,value.now,current.captured_at,current.evidence_id,impact,now]);const[rules]=await c.query<RowDataPacket[]>("SELECT * FROM competitor_monitor_rules WHERE organization_id=? AND workspace_id=? AND status='enabled' AND (competitor_id IS NULL OR competitor_id=?) AND metric=?",[job.organizationId,job.workspaceId,job.competitorId,this.metric(field)]);for(const rule of rules)if(this.trigger(rule,value.old,value.now)){const alertId=randomUUID(),payload={competitor_id:job.competitorId,change_id:changeId,rule_id:String(rule.id),field,previous:value.old,current:value.now,changed_at:iso(current.captured_at),evidence_id:String(current.evidence_id),impact_explanation:impact};await c.query("INSERT INTO competitor_alerts (id,organization_id,workspace_id,competitor_id,change_id,rule_id,notification_status,task_status,payload_json,created_at,updated_at) VALUES (?,?,?,?,?,?,'queued','queued',?,?,?)",[alertId,job.organizationId,job.workspaceId,job.competitorId,changeId,rule.id,JSON.stringify(payload),now,now]);await c.query("INSERT INTO competitor_outbox (id,organization_id,workspace_id,aggregate_id,event_type,payload_json,status,available_at,created_at) VALUES (?,?,?,?,?,?,'pending',?,?)",[alertId,job.organizationId,job.workspaceId,job.competitorId,'competitor.threshold.triggered',JSON.stringify(payload),now,now]);}}
  await c.query('UPDATE competitors SET latest_snapshot_id=?,updated_at=? WHERE id=?',[job.snapshotId,now,job.competitorId]);await c.query("UPDATE competitor_snapshot_jobs SET status='succeeded',lease_owner=NULL,lease_expires_at=NULL,last_error_code=NULL,updated_at=? WHERE id=? AND lease_owner=?",[now,job.id,this.workerId]);await c.query('INSERT INTO competitor_events (id,organization_id,workspace_id,competitor_id,event_type,actor_id,payload_json,request_id,trace_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',[randomUUID(),job.organizationId,job.workspaceId,job.competitorId,'competitor.snapshot.compared',this.workerId,JSON.stringify({snapshot_id:job.snapshotId,change_count:Object.keys(changes).length}),job.requestId,job.traceId,now]);await c.commit();return{change_count:Object.keys(changes).length};}catch(e){await c.rollback();throw e;}finally{c.release();}}
 private metric(field:string){return field==='current_price'?'price':field==='rank_value'?'rank':field;}
 private trigger(r:RowDataPacket,old:string,value:string){if(r.metric==='availability')return r.direction==='change'?old!==value:old!=='out_of_stock'&&value==='out_of_stock';const delta=Number(value)-Number(old),threshold=Number(r.threshold_value);if(r.direction==='increase')return delta>=threshold;if(r.direction==='decrease')return-delta>=threshold;return Math.abs(delta)>=threshold;}
 private impact(field:string,old:string,value:string){const label:Record<string,string>={current_price:'价格',rank_value:'排名',review_count:'评论数',rating_value:'评分',availability:'库存'};return`${label[field]??field}由 ${old} 变为 ${value}；请结合来源证据复核影响。`;}
 private async finish(job:Job,status:'failed_terminal'|'dead_letter'|'scheduled',code:string){const now=this.now(),stored=status==='scheduled'?'retry_scheduled':status,delay=[60000,300000,900000][Math.min(job.attemptCount-1,2)]!,available=status==='scheduled'?new Date(now.getTime()+delay):now;await this.pool.query('UPDATE competitor_snapshot_jobs SET status=?,available_at=?,lease_owner=NULL,lease_expires_at=NULL,last_error_code=?,updated_at=? WHERE id=? AND lease_owner=?',[stored,available,code,now,job.id,this.workerId]);}
}
const iso=(v:unknown)=>(v instanceof Date?v:new Date(String(v))).toISOString();
