import { loadRuntimeConfig } from '@scoutops/config';
import { createDatabasePool } from '@scoutops/database';
import { createRedisConnection, ScopedRedisStore } from '@scoutops/redis';
import { ProviderAdapterRegistry } from '@scoutops/provider-adapters';
import { createBuiltinSourceAdapters } from '@scoutops/provider-sources';
import { PendingMailProvider, processAuthDeliveryOnce } from './auth-delivery-worker.js';
import { MySqlCollectionTaskWorkerRepository, ScopedRedisCollectionCoordinator, processCollectionTaskOnce } from './collection-task-worker.js';
import { MySqlEvidencePersistence } from './evidence-persistence.js';
import { ProviderSourceExecutor } from './provider-source-executor.js';

const config=loadRuntimeConfig(process.env,'worker'),pool=createDatabasePool(config),redisClient=createRedisConnection(config),redisStore=new ScopedRedisStore(redisClient),registry=new ProviderAdapterRegistry({healthTimeoutMs:config.providerAdapters.healthTimeoutMs,maxResponseBytes:config.providerAdapters.maxResponseBytes,maxItemsPerBatch:config.providerAdapters.maxItemsPerBatch});for(const adapter of createBuiltinSourceAdapters())registry.register(adapter);const collectionRepository=new MySqlCollectionTaskWorkerRepository(pool),coordinator=new ScopedRedisCollectionCoordinator(redisStore),executor=new ProviderSourceExecutor(pool,registry,new MySqlEvidencePersistence(pool,config.storage.evidenceRoot,config.evidence.maxRawBytes),config.identity.workerId);let stopping=false,authPolling=false,collectionPolling=false;
const heartbeat=()=>console.log(JSON.stringify({service:'product-scout-worker',status:stopping?'stopping':'idle',worker_id:config.identity.workerId,registered_sources:registry.describe().map(item=>item.key),config_fingerprint:config.configFingerprint,observed_at:new Date().toISOString()}));
const pollAuth=async()=>{if(stopping||authPolling||!config.security.credentialsMasterKey)return;authPolling=true;try{const result=await processAuthDeliveryOnce({pool,workerId:config.identity.workerId,masterKey:config.security.credentialsMasterKey,provider:new PendingMailProvider()});if(result.status!=='idle')console.log(JSON.stringify({service:'product-scout-worker',queue:'auth_delivery',...result,observed_at:new Date().toISOString()}));}catch{console.error(JSON.stringify({service:'product-scout-worker',queue:'auth_delivery',status:'dependency_failed',observed_at:new Date().toISOString()}));}finally{authPolling=false;}};
const pollCollection=async()=>{if(stopping||collectionPolling)return;collectionPolling=true;try{await redisStore.connect();const result=await processCollectionTaskOnce({repository:collectionRepository,coordinator,executor,workerId:config.identity.workerId,leaseSeconds:config.collectionTasks.leaseSeconds});if(result.status!=='idle')console.log(JSON.stringify({service:'product-scout-worker',queue:'collection_tasks',...result,observed_at:new Date().toISOString()}));}catch(error){console.error(JSON.stringify({service:'product-scout-worker',queue:'collection_tasks',status:'dependency_failed',error:error instanceof Error?error.message:'unknown',observed_at:new Date().toISOString()}));}finally{collectionPolling=false;}};
heartbeat();const heartbeatTimer=setInterval(heartbeat,config.runtime.workerHeartbeatMs),authTimer=setInterval(()=>void pollAuth(),config.auth.outboxPollMs),collectionTimer=setInterval(()=>void pollCollection(),config.collectionTasks.pollMs);void pollAuth();void pollCollection();
const stop=async(signal:string)=>{if(stopping)return;stopping=true;clearInterval(heartbeatTimer);clearInterval(authTimer);clearInterval(collectionTimer);while(authPolling||collectionPolling)await new Promise(resolve=>setTimeout(resolve,25));await redisStore.close();await pool.end();console.log(JSON.stringify({service:'product-scout-worker',status:'stopped',signal,worker_id:config.identity.workerId,observed_at:new Date().toISOString()}));};process.once('SIGTERM',()=>void stop('SIGTERM'));process.once('SIGINT',()=>void stop('SIGINT'));
