window.PLATFORM_OVERVIEW_C_DATA = {
  dashboard: {
    window: "24h",
    summary: {
      active_organizations: 42,
      active_users: 318,
      enabled_providers: 3,
      task_success_rate: 96.4,
      queue_backlog: 7,
      open_alerts: 2,
      storage_bytes: 734003200,
      file_growth_bytes: 12582912,
    },
    queues: [
      { status: "queued", total: 5 },
      { status: "retry_scheduled", total: 2 },
    ],
    provider_health: [
      {
        id: "p1",
        code: "news_rss",
        name: "公开趋势 RSS",
        status: "healthy",
        observed_count: 28,
        success_count: 28,
        failed_count: 0,
        last_observed_at: "2026-08-08T11:50:00.000Z",
      },
      {
        id: "p2",
        code: "supplier",
        name: "供应商公开页",
        status: "degraded",
        observed_count: 12,
        success_count: 10,
        failed_count: 2,
        last_observed_at: "2026-08-08T11:40:00.000Z",
      },
      {
        id: "p3",
        code: "new",
        name: "待观测来源",
        status: "unknown",
        observed_count: 0,
        success_count: 0,
        failed_count: 0,
        last_observed_at: null,
      },
    ],
    task_trend: [],
    health_signals: [
      { code: "mysql", status: "healthy", value: "query_succeeded" },
      { code: "queue", status: "healthy", value: 7 },
      { code: "expired_leases", status: "critical", value: 1 },
      { code: "data_quality", status: "warning", value: 1 },
    ],
    alerts: [
      {
        id: "a1",
        organization_id: "00000000-0000-4000-8000-000000000601",
        workspace_id: "00000000-0000-4000-8000-000000000602",
        kind: "quality",
        severity: "warning",
        code: "title_accuracy",
        observed_at: "2026-08-08T11:45:00.000Z",
      },
      {
        id: "a2",
        organization_id: "00000000-0000-4000-8000-000000000601",
        workspace_id: "00000000-0000-4000-8000-000000000602",
        kind: "task",
        severity: "critical",
        code: "parser_changed",
        observed_at: "2026-08-08T11:40:00.000Z",
      },
    ],
    activity: [],
    observed_at: "2026-08-08T12:00:00.000Z",
  },
  providers15: [
    {
      id: "provider-1",
      code: "provider_1",
      name: "待观测来源 1",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-2",
      code: "provider_2",
      name: "待观测来源 2",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-3",
      code: "provider_3",
      name: "待观测来源 3",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-4",
      code: "provider_4",
      name: "待观测来源 4",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-5",
      code: "provider_5",
      name: "待观测来源 5",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-6",
      code: "provider_6",
      name: "待观测来源 6",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-7",
      code: "provider_7",
      name: "待观测来源 7",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-8",
      code: "provider_8",
      name: "待观测来源 8",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-9",
      code: "provider_9",
      name: "待观测来源 9",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-10",
      code: "provider_10",
      name: "待观测来源 10",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-11",
      code: "provider_11",
      name: "待观测来源 11",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-12",
      code: "provider_12",
      name: "待观测来源 12",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-13",
      code: "provider_13",
      name: "待观测来源 13",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-14",
      code: "provider_14",
      name: "待观测来源 14",
      status: "unknown",
      observed_count: 0,
      success_count: 0,
      failed_count: 0,
      last_observed_at: null,
    },
    {
      id: "provider-15",
      code: "provider_15",
      name: "异常来源 15",
      status: "degraded",
      observed_count: 4,
      success_count: 1,
      failed_count: 3,
      last_observed_at: "2026-08-08T11:40:00.000Z",
    },
  ],
  trend: [
    { bucket: "2026-08-08T10:00:00.000Z", succeeded: 8, failed: 2 },
    { bucket: "2026-08-08T11:00:00.000Z", succeeded: 14, failed: 1 },
    { bucket: "2026-08-08T12:00:00.000Z", succeeded: 21, failed: 0 },
  ],
  points: {
    succeeded: "0,112.85714285714286 300,70 600,20",
    failed: "0,155.71428571428572 300,162.85714285714286 600,170",
  },
  windows: {
    "15m": "/platform/dashboard?window=15m",
    "24h": "/platform/dashboard?window=24h",
    "7d": "/platform/dashboard?window=7d",
    "30d": "/platform/dashboard?window=30d",
  },
  sourceChecks: {
    fixture:
      "Original dashboard, independent 15-provider and three-point trend fixtures extracted from existing E2E AST; values not reconciled or recomputed.",
    vue: "Actual inert functions/computed: 8/15 priority, 43/3 trend, null/0 rate, bytes, fallback labels, four window URLs, preserved query, invalid default, pending single-flight and 12000ms abort callback.",
    reproduced:
      "Selected 7d with failed refresh retains 24h; existing-ready 401/403 retains data; trend-only is empty; TechnicalDetails copy rejection is uncaught.",
    limits:
      "Not mounted Vue, real API, SQL, authorization, browser history, OS clipboard or production proof. Metric scope and audit writes are source inspection only.",
  },
};
