window.MYSQL_DATA = {
  sourcePaths: [
    "packages/database/src/index.ts",
    "apps/api/src/mysql-resilience-probe.ts",
    "apps/api/src/mysql-resilience-service.ts",
    "apps/api/src/mysql-resilience-repository.ts",
    "apps/api/src/mysql-resilience-routes.ts",
    "apps/web/src/components/MySqlResilienceCenter.vue",
    "apps/web/src/components/TechnicalDetails.vue",
    "tests/e2e/m08-03-mysql-resilience.spec.ts",
    "infra/baota/mysql-single-primary-manifest.json",
    "packages/config/src/index.ts",
  ],
  sourceChecks: [
    "Actual probe with inert SHOW/history/recovery/asset rows and statfs: interval>=1-minute versus uptime slow-rate, nonnegative delta/reset, zero requests->10000 hit-rate, 20-row query and full/binlog recovery-copy requirements, isolation, fixed15/240/90, null numeric intermediate versus null DTO, future age clamping/two-decimal round. No real filesystem or SQL executed.",
    "Actual evaluator/service: 5.7/write/binlog/ROW/exclusion/flush2/sync1/master/no replica, independent resource thresholds, cumulative waits, recovery missing/stale/unknown, clamped storage and raw negative recovery, stricter/relaxed policy versus fixed probe state; public DTO excludes raw identity/paths/SQL. Original E2E kept separate.",
    "Actual Vue script: single-flight exact GET/IDs, 15s, null empty, auth clearing/transient retention, generic empty requestID and unmount abort. Severity/row-lock/slow-query helpers extracted from source; new prototype qualifies slow-rate window rather than copying unproven current-window claims. Not mounted Vue/preserve or shared clipboard proof.",
    "Actual service abort checkpoints before/after probe and after record; actual repository inert connection verifies three inserts/commit, audit-fail rollback and abort after first insert rollback/release. Probe has no signal; cancellation after record may occur after its work. No running-SQL interruption, real durability or transaction proof.",
    "Actual route handler with inert auth/service/timers/events: exact private GET and operate guard before service, default14s race abort, dependency503, correlation and finish cleanup. No real session/RBAC server, socket disconnect or production request executed.",
  ],
  datasets: {
    ready: {
      state: "ready",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "availability-boundary": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_unavailable",
          severity: "blocked",
          action_hint: "在宝塔检查并恢复当前 MySQL 5.7 服务后重新核验。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    version: {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_version_incompatible",
          severity: "blocked",
          action_hint: "只允许当前宝塔 MySQL 5.7 单主合同。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "read-only": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_primary_read_only",
          severity: "blocked",
          action_hint: "在宝塔核对单主状态，禁止把只读节点冒充当前主库。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "binlog-off": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: false,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_binlog_disabled",
          severity: "blocked",
          action_hint: "通过宝塔恢复二进制日志并重新执行隔离恢复验证。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    format: {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "MIXED",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_binlog_format_invalid",
          severity: "blocked",
          action_hint: "通过宝塔将 binlog_format 恢复为 ROW。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    excluded: {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_product_database_binlog_excluded",
          severity: "blocked",
          action_hint: "通过宝塔移除 product_scout 的 binlog 排除规则。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    flush: {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 1,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_flush_contract_invalid",
          severity: "blocked",
          action_hint: "通过宝塔恢复 innodb_flush_log_at_trx_commit=2。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    sync: {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 0,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_sync_binlog_invalid",
          severity: "blocked",
          action_hint: "通过宝塔恢复 sync_binlog=1。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    master: {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_master_status_unavailable",
          severity: "blocked",
          action_hint: "核对 product_scout 的 REPLICATION CLIENT 与 binlog 主状态。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    replica: {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_replica_unexpected",
          severity: "blocked",
          action_hint: "当前 S0 只允许一个 MySQL 主库，不启用只读副本。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "connections-unbounded": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 0, usage_basis_points: 10000 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_connections_unbounded",
          severity: "blocked",
          action_hint: "通过宝塔恢复明确的 max_connections 上限。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "capacity-unknown": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 0, total_bytes: 0, usage_basis_points: 10000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_data_capacity_unknown",
          severity: "blocked",
          action_hint: "在当前主机核验 MySQL 数据文件系统容量。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "slow-warning": {
      state: "warning",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 5, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_slow_query_warning",
          severity: "warning",
          action_hint: "检查慢查询增量、索引和执行计划。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "slow-stop": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 20, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_slow_query_stop",
          severity: "blocked",
          action_hint: "停止高成本任务并在宝塔慢查询日志定位根因。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "buffer-warning": {
      state: "warning",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9899,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_buffer_pool_hit_warning",
          severity: "warning",
          action_hint: "检查工作集、索引和 4 GiB 缓冲池命中率。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "log-waits": {
      state: "warning",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 1,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_innodb_log_waits",
          severity: "warning",
          action_hint: "检查 InnoDB 日志等待增量和磁盘 I/O。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "row-waits": {
      state: "warning",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 23,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_row_lock_waits",
          severity: "warning",
          action_hint: "检查行锁等待增量与长事务。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "rpo-null": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: null,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_rpo_exceeded",
          severity: "blocked",
          action_hint: "恢复演练必须证明 RPO 不超过 15 分钟。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "rto-null": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: null,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_rto_exceeded",
          severity: "blocked",
          action_hint: "恢复演练必须证明 RTO 不超过 4 小时。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "age-null": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: null,
      },
      findings: [
        {
          code: "mysql_recovery_stale",
          severity: "blocked",
          action_hint: "在宝塔重新执行 90 天内的隔离恢复演练。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "connections-warning": {
      state: "warning",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 75, running: 2, maximum: 100, usage_basis_points: 7500 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_connections_warning",
          severity: "warning",
          action_hint: "检查 API、Worker 与 Crawler 的连接使用。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "connections-stop": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 90, running: 2, maximum: 100, usage_basis_points: 9000 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_connections_stop",
          severity: "blocked",
          action_hint: "停止新增异步工作并检查 MySQL 连接占用。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "storage-warning": {
      state: "warning",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 7500, total_bytes: 10000, usage_basis_points: 7500 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_data_capacity_warning",
          severity: "warning",
          action_hint: "检查数据、binlog、临时表与备份增长。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "storage-stop": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 9000, total_bytes: 10000, usage_basis_points: 9000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_data_capacity_stop",
          severity: "blocked",
          action_hint: "停止新增大任务并通过宝塔释放或扩展受控存储。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "storage-over": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 10100, total_bytes: 10000, usage_basis_points: 10000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_data_capacity_stop",
          severity: "blocked",
          action_hint: "停止新增大任务并通过宝塔释放或扩展受控存储。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "zero-values": {
      state: "ready",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 0, running: 0, maximum: 512, usage_basis_points: 0 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 0, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 0,
        actual_rto_minutes: 0,
        drill_age_days: 1,
      },
      findings: [],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "negative-recovery": {
      state: "ready",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: -1,
        actual_rto_minutes: -2,
        drill_age_days: 1,
      },
      findings: [],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    long: {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format:
          "synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-synthetic-long-binlog-format-",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_binlog_format_invalid",
          severity: "blocked",
          action_hint: "通过宝塔将 binlog_format 恢复为 ROW。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "interval-short": {
      state: "ready",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 2, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "no-previous": {
      state: "ready",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 0.2, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "counter-reset": {
      state: "ready",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 0, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "no-buffer-requests": {
      state: "ready",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 10000,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "recovery-empty": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "empty",
        actual_rpo_minutes: null,
        actual_rto_minutes: null,
        drill_age_days: null,
      },
      findings: [
        {
          code: "mysql_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔完成同机加密备份与隔离恢复核验。",
        },
        {
          code: "mysql_recovery_stale",
          severity: "blocked",
          action_hint: "在宝塔重新执行 90 天内的隔离恢复演练。",
        },
        {
          code: "mysql_rpo_exceeded",
          severity: "blocked",
          action_hint: "恢复演练必须证明 RPO 不超过 15 分钟。",
        },
        {
          code: "mysql_rto_exceeded",
          severity: "blocked",
          action_hint: "恢复演练必须证明 RTO 不超过 4 小时。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "asset-missing": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "blocked",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔完成同机加密备份与隔离恢复核验。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "drill-not-isolated": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "blocked",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔完成同机加密备份与隔离恢复核验。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "drill-stale": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "stale",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 90,
      },
      findings: [
        {
          code: "mysql_recovery_stale",
          severity: "blocked",
          action_hint: "在宝塔重新执行 90 天内的隔离恢复演练。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "drill-boundary": {
      state: "ready",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 90,
      },
      findings: [],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "drill-future": {
      state: "ready",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 0,
      },
      findings: [],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "probe-null-rpo": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: null,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_rpo_exceeded",
          severity: "blocked",
          action_hint: "恢复演练必须证明 RPO 不超过 15 分钟。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "rpo-probe-stop": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "blocked",
        actual_rpo_minutes: 16,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔完成同机加密备份与隔离恢复核验。",
        },
        {
          code: "mysql_rpo_exceeded",
          severity: "blocked",
          action_hint: "恢复演练必须证明 RPO 不超过 15 分钟。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "rto-probe-stop": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "blocked",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 241,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔完成同机加密备份与隔离恢复核验。",
        },
        {
          code: "mysql_rto_exceeded",
          severity: "blocked",
          action_hint: "恢复演练必须证明 RTO 不超过 4 小时。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "twenty-drills": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "blocked",
        actual_rpo_minutes: null,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔完成同机加密备份与隔离恢复核验。",
        },
        {
          code: "mysql_rpo_exceeded",
          severity: "blocked",
          action_hint: "恢复演练必须证明 RPO 不超过 15 分钟。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "policy-stricter": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_rpo_exceeded",
          severity: "blocked",
          action_hint: "恢复演练必须证明 RPO 不超过 15 分钟。",
        },
        {
          code: "mysql_rto_exceeded",
          severity: "blocked",
          action_hint: "恢复演练必须证明 RTO 不超过 4 小时。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "policy-relaxed": {
      state: "blocked",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 163840000, total_bytes: 409600000, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 1, long_query_time_seconds: 2 },
      recovery: {
        status: "blocked",
        actual_rpo_minutes: 16,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "mysql_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔完成同机加密备份与隔离恢复核验。",
        },
      ],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    original: {
      state: "ready",
      mode: "single_primary",
      durability: {
        log_bin_enabled: true,
        binlog_format: "ROW",
        innodb_flush_log_at_trx_commit: 2,
        sync_binlog: 1,
      },
      connections: { connected: 20, running: 2, maximum: 512, usage_basis_points: 391 },
      storage: { used_bytes: 171798691840, total_bytes: 429496729600, usage_basis_points: 4000 },
      io: {
        buffer_pool_bytes: 4294967296,
        buffer_pool_data_bytes: 2147483648,
        buffer_pool_hit_rate_basis_points: 9999,
        innodb_log_waits: 0,
        innodb_row_lock_waits: 0,
      },
      slow_queries: { per_minute: 0, long_query_time_seconds: 2 },
      recovery: {
        status: "verified",
        actual_rpo_minutes: 1,
        actual_rto_minutes: 3,
        drill_age_days: 1,
      },
      findings: [],
      single_primary: true,
      replica_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-08-14T13:00:00.000Z",
    },
  },
  labels: {
    ready: "单主运行与恢复证据齐备",
    "availability-boundary": "available=false评估边界（非探针回退）",
    version: "版本不符合5.7",
    "read-only": "主库只读",
    "binlog-off": "未启用binlog",
    format: "日志非ROW",
    excluded: "业务库被排除",
    flush: "刷盘合同不符",
    sync: "同步合同不符",
    master: "主状态不可用",
    replica: "发现非预期副本",
    "connections-unbounded": "连接上限未设置",
    "capacity-unknown": "数据盘容量未知",
    "slow-warning": "慢查询预警边界",
    "slow-stop": "慢查询停止边界",
    "buffer-warning": "缓冲命中低于99%",
    "log-waits": "累计日志等待非零",
    "row-waits": "累计行锁等待非零",
    "rpo-null": "RPO未记录",
    "rto-null": "RTO未记录",
    "age-null": "演练年龄未记录",
    "connections-warning": "连接75%边界",
    "connections-stop": "连接90%边界",
    "storage-warning": "数据盘75%边界",
    "storage-stop": "数据盘90%边界",
    "storage-over": "可用空间异常负值",
    "zero-values": "真实零用量与零耗时",
    "negative-recovery": "源返回负RPO/RTO仍可能ready",
    long: "长日志格式值",
    "interval-short": "短间隔按至少一分钟分母",
    "no-previous": "没有上次观测用uptime平均",
    "counter-reset": "慢查询累计计数下降",
    "no-buffer-requests": "零缓冲请求回退100%",
    "recovery-empty": "没有返回恢复记录",
    "asset-missing": "恢复副本缺binlog资产",
    "drill-not-isolated": "演练未隔离",
    "drill-stale": "超过90天但显示取整90.00",
    "drill-boundary": "恰好90天",
    "drill-future": "未来时间归零年龄",
    "probe-null-rpo": "探针verified但RPO为空",
    "rpo-probe-stop": "探针固定RPO15分钟之外",
    "rto-probe-stop": "探针固定RTO240分钟之外",
    "twenty-drills": "最近20条只有演练",
    "policy-stricter": "运行policy比探针更严格",
    "policy-relaxed": "放宽运行policy仍不能绕过探针",
    original: "原始历史E2E夹具",
  },
  clock: "2026-09-09T08:00:00.000Z",
  provenance:
    "Synthetic source outputs; original E2E independent; no live database/recovery observations.",
};
