window.DATA_RECORDS_DATA = {
  originals: {
    trends: {
      domain: "data",
      entity: "trends",
      summary: { total: 1, active: 1 },
      items: [
        {
          id: "trend-54",
          title: "隔离热点",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "active",
          metric_primary: 8,
          metric_secondary: 2,
          updated_at: "2026-09-08T00:00:00.000Z",
        },
      ],
      observed_at: "2026-09-08T00:00:00.000Z",
    },
    suppliers: {
      domain: "data",
      entity: "suppliers",
      summary: { total: 1, ready: 1 },
      items: [
        {
          id: "supplier-54",
          title: "隔离供应商",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "ready",
          metric_primary: 8,
          metric_secondary: 2,
          updated_at: "2026-09-08T00:00:00.000Z",
        },
      ],
      observed_at: "2026-09-08T00:00:00.000Z",
    },
  },
  synthetic: {
    trends: {
      domain: "data",
      entity: "trends",
      summary: { total: 4, active: 1, irrelevant: 1, stale: 1, archived: 1 },
      items: [
        {
          id: "synthetic-trends-0",
          title: "家居趋势记录",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "active",
          metric_primary: 0,
          metric_secondary: 0,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "家居照明",
          market: "US",
        },
        {
          id: "synthetic-trends-1",
          title: "家居趋势记录",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "irrelevant",
          metric_primary: 9,
          metric_secondary: 3,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "家居照明",
          market: "US",
        },
        {
          id: "synthetic-trends-2",
          title: "家居趋势记录",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "stale",
          metric_primary: 10,
          metric_secondary: 4,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "家居照明",
          market: "US",
        },
        {
          id: "synthetic-trends-3",
          title: "家居趋势记录",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "archived",
          metric_primary: 11,
          metric_secondary: 5,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "家居照明",
          market: "US",
        },
      ],
      observed_at: "2026-09-08T00:00:00.000Z",
    },
    opportunities: {
      domain: "data",
      entity: "opportunities",
      summary: { total: 4, pending: 1, adopted: 1, observing: 1, rejected: 1 },
      items: [
        {
          id: "synthetic-opportunities-0",
          title: "便携照明机会",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "pending",
          metric_primary: 0,
          metric_secondary: 0,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "家居照明",
          market: "US",
        },
        {
          id: "synthetic-opportunities-1",
          title: "便携照明机会",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "adopted",
          metric_primary: 9,
          metric_secondary: 3,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "家居照明",
          market: "US",
        },
        {
          id: "synthetic-opportunities-2",
          title: "便携照明机会",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "observing",
          metric_primary: 10,
          metric_secondary: 4,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "家居照明",
          market: "US",
        },
        {
          id: "synthetic-opportunities-3",
          title: "便携照明机会",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "rejected",
          metric_primary: 11,
          metric_secondary: 5,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "家居照明",
          market: "US",
        },
      ],
      observed_at: "2026-09-08T00:00:00.000Z",
    },
    competitors: {
      domain: "data",
      entity: "competitors",
      summary: { total: 2, active: 1, paused: 1 },
      items: [
        {
          id: "synthetic-competitors-0",
          title: "充电灯竞品",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "active",
          metric_primary: 0,
          metric_secondary: 0,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "示例站点",
          market: "US",
        },
        {
          id: "synthetic-competitors-1",
          title: "充电灯竞品",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "paused",
          metric_primary: 9,
          metric_secondary: 3,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "示例站点",
          market: "US",
        },
      ],
      observed_at: "2026-09-08T00:00:00.000Z",
    },
    suppliers: {
      domain: "data",
      entity: "suppliers",
      summary: { total: 3, incomplete: 1, ready: 1, quarantined: 1 },
      items: [
        {
          id: "synthetic-suppliers-0",
          title: "便携灯供应候选",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "incomplete",
          metric_primary: 0,
          metric_secondary: 0,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "示例供应商",
          market: "广东",
        },
        {
          id: "synthetic-suppliers-1",
          title: "便携灯供应候选",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "ready",
          metric_primary: 9,
          metric_secondary: 3,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "示例供应商",
          market: "广东",
        },
        {
          id: "synthetic-suppliers-2",
          title: "便携灯供应候选",
          organization_name: "测试组织",
          workspace_name: "测试工作区",
          status: "quarantined",
          metric_primary: 10,
          metric_secondary: 4,
          updated_at: "2026-09-08T00:00:00.000Z",
          category: "示例供应商",
          market: "广东",
        },
      ],
      observed_at: "2026-09-08T00:00:00.000Z",
    },
  },
  boundaries: [
    { count: 0, pagination: { page: 1, page_size: 20, total: 0, total_pages: 0 }, rows: 0 },
    { count: 1, pagination: { page: 1, page_size: 20, total: 1, total_pages: 1 }, rows: 1 },
    { count: 20, pagination: { page: 1, page_size: 20, total: 20, total_pages: 1 }, rows: 20 },
    { count: 21, pagination: { page: 2, page_size: 20, total: 21, total_pages: 2 }, rows: 1 },
    { count: 100, pagination: { page: 5, page_size: 20, total: 100, total_pages: 5 }, rows: 20 },
  ],
  csvCases: [
    { input: "=SUM(A1:A2)", output: '"\'=SUM(A1:A2)"' },
    { input: "+value", output: '"\'+value"' },
    { input: "-1", output: '"\'-1"' },
    { input: "@value", output: '"\'@value"' },
    { input: 'a"b', output: '"a""b"' },
    { input: null, output: '""' },
  ],
  checks: [
    "Actual Vue four entity labels, 13 status labels and local 0/1/20/21/100 row pagination/clamp; original trend/supplier fixture separated from synthetic boundaries.",
    "Ten first/preserved source read failures and 15-second abort callback retain entity interpretation; generation supersession is covered by mounted Vue E2E, with no real request or timer wait here.",
    "Snapshot mismatch blocks export until successful requested scope; initial URL trimming/invalid status/page clamp; an ignored-abort late read cannot replace the successful supplier snapshot after unmount.",
    "Actual export keeps the successful trend snapshot through reason wait and response-time entity changes, including its filename. Inert DOM records download intention only; no file, audit or POST executed.",
    "Actual service accepts 13 entity/status pairs, trims query and rejects invalid entity/status/121 query plus export reason 1/301; accepts 2/300. Inert repository only.",
    "Actual four repository readManagement data branches on synthetic SQL-row adapter: LIMIT100, returned-set summary, supplier search excluding workspace and null/undefined converted to zero; SQL was not executed.",
    "Actual csvCell six cases and data export route BOM/non-idempotency contract checked; no CSV file, audit row, customer material or real download created.",
  ],
  entities: [
    { value: "trends", label: "热点", primary: "信号", secondary: "来源" },
    { value: "opportunities", label: "机会", primary: "证据", secondary: "来源" },
    { value: "competitors", label: "竞品", primary: "版本", secondary: "变更" },
    { value: "suppliers", label: "供应商", primary: "最小起订量", secondary: "报价" },
  ],
  statuses: {
    trends: ["active", "irrelevant", "stale", "archived"],
    opportunities: ["pending", "adopted", "observing", "rejected"],
    competitors: ["active", "paused"],
    suppliers: ["incomplete", "ready", "quarantined"],
  },
  labels: {
    trends: { active: "展示中", irrelevant: "无关", stale: "已过期", archived: "已归档" },
    opportunities: {
      pending: "待决策",
      adopted: "已采纳",
      observing: "观察中",
      rejected: "已拒绝",
    },
    competitors: { active: "监控中", paused: "已暂停" },
    suppliers: { incomplete: "信息不完整", ready: "可评估", quarantined: "已隔离" },
  },
  sourcePaths: [
    "apps/web/src/components/PlatformDataCenter.vue",
    "tests/e2e/m06-02-platform-dashboard.spec.ts",
    "apps/web/src/use-audited-reason.ts",
    "apps/api/src/platform-dashboard-service.ts",
    "apps/api/src/mysql-platform-dashboard-repository.ts",
    "apps/api/src/platform-dashboard-routes.ts",
    "apps/web/src/components/AuditedReasonDialog.vue",
    "apps/web/src/components/ResponsiveDataView.vue",
    "apps/web/src/components/ResponsiveFilterDrawer.vue",
    "apps/web/src/components/TableViewControls.vue",
    "apps/web/src/components/TechnicalDetails.vue",
  ],
};
