import { ALIBABA_1688_BROWSER_PARSER_VERSION } from "../1688-browser-contract.js";

export type SourceCategory = "news" | "ecommerce" | "data" | "community" | "product_supply";
export type SourceAvailability = "automatic" | "setup_required" | "manual";
export interface BuiltinSourceDefinition {
  code: string;
  name: string;
  access_mode: "public_rss" | "authenticated_browser" | "public_page" | "import" | "manual";
  target_url: string;
  markets: string[];
  languages: string[];
  fields: string[];
  schedule_minutes: number;
  concurrency_limit: number;
  timeout_ms: number;
  retry_limit: number;
  circuit_failure_threshold: number;
  dedupe_key: string;
  retention_days: number;
  failure_rules: string[];
  parser_version: string;
  healthcheck_url: string | null;
  owner_label: string;
  status: "disabled" | "enabled";
  category: SourceCategory;
  availability: SourceAvailability;
  production_policy: "automatic_public_feed" | "setup_required" | "ready_for_owner_enablement";
  policy_note: string;
}
const GOOGLE_TEMPLATE =
  "https://news.google.com/rss/search?q={urlEncodedQuery}&hl=en-US&gl=US&ceid=US:en";
const locales = [
  {
    code: "us",
    name: "美国",
    market: "US",
    language: "en-US",
    hl: "en-US",
    gl: "US",
    ceid: "US:en",
  },
  {
    code: "gb",
    name: "英国",
    market: "GB",
    language: "en-GB",
    hl: "en-GB",
    gl: "GB",
    ceid: "GB:en",
  },
  {
    code: "de",
    name: "德国",
    market: "DE",
    language: "de-DE",
    hl: "de",
    gl: "DE",
    ceid: "DE:de",
  },
  {
    code: "fr",
    name: "法国",
    market: "FR",
    language: "fr-FR",
    hl: "fr",
    gl: "FR",
    ceid: "FR:fr",
  },
  {
    code: "jp",
    name: "日本",
    market: "JP",
    language: "ja-JP",
    hl: "ja",
    gl: "JP",
    ceid: "JP:ja",
  },
  {
    code: "kr",
    name: "韩国",
    market: "KR",
    language: "ko-KR",
    hl: "ko",
    gl: "KR",
    ceid: "KR:ko",
  },
  {
    code: "sg",
    name: "新加坡",
    market: "SG",
    language: "en-SG",
    hl: "en-SG",
    gl: "SG",
    ceid: "SG:en",
  },
  {
    code: "au",
    name: "澳大利亚",
    market: "AU",
    language: "en-AU",
    hl: "en-AU",
    gl: "AU",
    ceid: "AU:en",
  },
] as const;
const topics = [
  {
    code: "consumer_trends",
    name: "消费趋势",
    query: "consumer product trend",
    category: "news",
  },
  {
    code: "viral_products",
    name: "爆款商品",
    query: "viral products shopping",
    category: "ecommerce",
  },
  {
    code: "amazon",
    name: "Amazon 热点",
    query: "Amazon marketplace trending products",
    category: "ecommerce",
  },
  {
    code: "tiktok_shop",
    name: "TikTok Shop 热点",
    query: "TikTok Shop trending products",
    category: "ecommerce",
  },
  {
    code: "etsy",
    name: "Etsy 热点",
    query: "Etsy trending products",
    category: "ecommerce",
  },
  {
    code: "ebay",
    name: "eBay 热点",
    query: "eBay trending products",
    category: "ecommerce",
  },
  {
    code: "retail_data",
    name: "零售数据",
    query: "retail sales data consumer demand",
    category: "data",
  },
  {
    code: "search_data",
    name: "搜索趋势数据",
    query: "search trends shopping data",
    category: "data",
  },
  {
    code: "social_buzz",
    name: "社交讨论",
    query: "social media product buzz",
    category: "community",
  },
  {
    code: "reddit",
    name: "Reddit 讨论",
    query: "site:reddit.com product recommendation trending",
    category: "community",
  },
  {
    code: "youtube",
    name: "YouTube 评测",
    query: "site:youtube.com product review trending",
    category: "community",
  },
  {
    code: "new_products",
    name: "新品发布",
    query: "new consumer product launch",
    category: "news",
  },
] as const satisfies readonly {
  code: string;
  name: string;
  query: string;
  category: Exclude<SourceCategory, "product_supply">;
}[];
const syndicationFeeds = [
  {
    code: "techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    category: "news",
    market: "US",
    language: "en-US",
  },
  {
    code: "the_verge",
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    category: "news",
    market: "US",
    language: "en-US",
  },
  {
    code: "bbc_business",
    name: "BBC Business",
    url: "https://feeds.bbci.co.uk/news/business/rss.xml",
    category: "news",
    market: "GB",
    language: "en-GB",
  },
  {
    code: "wired",
    name: "WIRED",
    url: "https://www.wired.com/feed/rss",
    category: "news",
    market: "US",
    language: "en-US",
  },
  {
    code: "ars_technica",
    name: "Ars Technica",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    category: "news",
    market: "US",
    language: "en-US",
  },
  {
    code: "guardian_business",
    name: "The Guardian Business",
    url: "https://www.theguardian.com/uk/business/rss",
    category: "news",
    market: "GB",
    language: "en-GB",
  },
  {
    code: "japan_times_business",
    name: "The Japan Times Business",
    url: "https://www.japantimes.co.jp/feed/business/",
    category: "news",
    market: "JP",
    language: "en-JP",
  },
  {
    code: "straits_times_business",
    name: "The Straits Times Business",
    url: "https://www.straitstimes.com/news/business/rss.xml",
    category: "news",
    market: "SG",
    language: "en-SG",
  },
  {
    code: "shopify_blog",
    name: "Shopify 电商资讯",
    url: "https://www.shopify.com/blog.atom",
    category: "ecommerce",
    market: "GLOBAL",
    language: "en",
  },
  {
    code: "etsy_seller_handbook",
    name: "Etsy Seller Handbook",
    url: "https://www.etsy.com/seller-handbook/rss",
    category: "ecommerce",
    market: "GLOBAL",
    language: "en",
  },
  {
    code: "woocommerce_blog",
    name: "WooCommerce 电商资讯",
    url: "https://woocommerce.com/posts/feed/",
    category: "ecommerce",
    market: "GLOBAL",
    language: "en",
  },
  {
    code: "bigcommerce_blog",
    name: "BigCommerce 电商资讯",
    url: "https://www.bigcommerce.com/blog/feed/",
    category: "ecommerce",
    market: "GLOBAL",
    language: "en",
  },
  {
    code: "ebay_announcements",
    name: "eBay 社区公告",
    url: "https://community.ebay.com/t5/Announcements/bg-p/Announcements/rss",
    category: "ecommerce",
    market: "US",
    language: "en-US",
  },
  {
    code: "practical_ecommerce",
    name: "Practical Ecommerce",
    url: "https://www.practicalecommerce.com/feed",
    category: "ecommerce",
    market: "US",
    language: "en-US",
  },
  {
    code: "ecommercebytes",
    name: "EcommerceBytes",
    url: "https://www.ecommercebytes.com/feed/",
    category: "ecommerce",
    market: "US",
    language: "en-US",
  },
  {
    code: "retail_dive",
    name: "Retail Dive",
    url: "https://www.retaildive.com/feeds/news/",
    category: "ecommerce",
    market: "US",
    language: "en-US",
  },
  {
    code: "hacker_news",
    name: "Hacker News 热门讨论",
    url: "https://news.ycombinator.com/rss",
    category: "community",
    market: "GLOBAL",
    language: "en",
  },
  {
    code: "product_hunt",
    name: "Product Hunt 新品社区",
    url: "https://www.producthunt.com/feed",
    category: "community",
    market: "GLOBAL",
    language: "en",
  },
  {
    code: "reddit_buyitforlife",
    name: "Reddit · BuyItForLife",
    url: "https://www.reddit.com/r/BuyItForLife/.rss",
    category: "community",
    market: "US",
    language: "en-US",
  },
  {
    code: "reddit_gadgets",
    name: "Reddit · Gadgets",
    url: "https://www.reddit.com/r/gadgets/.rss",
    category: "community",
    market: "GLOBAL",
    language: "en",
  },
  {
    code: "reddit_ecommerce",
    name: "Reddit · Ecommerce",
    url: "https://www.reddit.com/r/ecommerce/.rss",
    category: "community",
    market: "GLOBAL",
    language: "en",
  },
  {
    code: "reddit_smallbusiness",
    name: "Reddit · Small Business",
    url: "https://www.reddit.com/r/smallbusiness/.rss",
    category: "community",
    market: "US",
    language: "en-US",
  },
  {
    code: "reddit_askuk",
    name: "Reddit · AskUK",
    url: "https://www.reddit.com/r/AskUK/.rss",
    category: "community",
    market: "GB",
    language: "en-GB",
  },
  {
    code: "reddit_de",
    name: "Reddit · Germany",
    url: "https://www.reddit.com/r/de/.rss",
    category: "community",
    market: "DE",
    language: "de-DE",
  },
  {
    code: "reddit_france",
    name: "Reddit · France",
    url: "https://www.reddit.com/r/france/.rss",
    category: "community",
    market: "FR",
    language: "fr-FR",
  },
  {
    code: "reddit_japanlife",
    name: "Reddit · Japan Life",
    url: "https://www.reddit.com/r/japanlife/.rss",
    category: "community",
    market: "JP",
    language: "en-JP",
  },
  {
    code: "reddit_korea",
    name: "Reddit · Korea",
    url: "https://www.reddit.com/r/korea/.rss",
    category: "community",
    market: "KR",
    language: "en-KR",
  },
  {
    code: "reddit_australia",
    name: "Reddit · Australia",
    url: "https://www.reddit.com/r/australia/.rss",
    category: "community",
    market: "AU",
    language: "en-AU",
  },
  {
    code: "reddit_singapore",
    name: "Reddit · Singapore",
    url: "https://www.reddit.com/r/singapore/.rss",
    category: "community",
    market: "SG",
    language: "en-SG",
  },
  {
    code: "hatena_hotentry",
    name: "Hatena 日本热门内容",
    url: "https://b.hatena.ne.jp/hotentry.rss",
    category: "community",
    market: "JP",
    language: "ja-JP",
  },
  ...["US", "GB", "DE", "FR", "JP", "KR", "SG", "AU", "CA", "BR"].map((market) => ({
    code: `google_trends_${market.toLowerCase()}`,
    name: `Google Trends · ${market}`,
    url: `https://trends.google.com/trending/rss?geo=${market}`,
    category: "data" as const,
    market,
    language: "multi",
  })),
] as const satisfies readonly {
  code: string;
  name: string;
  url: string;
  category: Exclude<SourceCategory, "product_supply">;
  market: string;
  language: string;
}[];
const publicCatalogPages = [
  {
    code: "amazon_bestsellers_us",
    name: "Amazon 美国畅销榜",
    url: "https://www.amazon.com/Best-Sellers/zgbs",
    market: "US",
    language: "en-US",
  },
  {
    code: "ebay_deals_us",
    name: "eBay 美国热门折扣",
    url: "https://www.ebay.com/deals",
    market: "US",
    language: "en-US",
  },
] as const;
const syndicationChannel = (feed: (typeof syndicationFeeds)[number]): BuiltinSourceDefinition => {
  const pageOverride =
    feed.code === "shopify_blog"
      ? { url: "https://www.shopify.com/blog", owner: "平台电商来源中心" }
      : feed.code === "ebay_announcements"
        ? {
            url: "https://community.ebay.com/forum/announcements-57928/",
            owner: "平台电商来源中心",
          }
        : null;
  return {
    code: `feed_${feed.code}`,
    name: feed.name,
    access_mode: pageOverride ? "public_page" : "public_rss",
    target_url: pageOverride?.url ?? feed.url,
    markets: [feed.market],
    languages: [feed.language],
    fields: pageOverride
      ? ["title", "position", "source_url", "publisher", "observed_at"]
      : ["title", "summary", "published_at", "source_url", "publisher"],
    schedule_minutes: 15,
    concurrency_limit: 1,
    timeout_ms: 20000,
    retry_limit: 3,
    circuit_failure_threshold: 5,
    dedupe_key: "guid_or_link",
    retention_days: 90,
    failure_rules: [
      "network_error",
      "timeout",
      "rate_limited",
      "source_changed",
      "parse_failed",
      "empty_result",
    ],
    parser_version: pageOverride ? "structured-public-page-v1" : "syndication-feed-v1",
    healthcheck_url: pageOverride?.url ?? feed.url,
    owner_label: pageOverride?.owner ?? "平台热点中心",
    status: "enabled",
    category: feed.category,
    availability: "automatic",
    production_policy: "automatic_public_feed",
    policy_note: pageOverride
      ? "固定抓取平台公开内容列表页面，不需要官方 API Key；页面结构变化会明确标记为解析失败。"
      : "公开 RSS/Atom 频道；系统按 15 分钟周期自动采集并保留原文证据，也可在热点页手动刷新。",
  };
};
const publicCatalogChannel = (
  page: (typeof publicCatalogPages)[number],
): BuiltinSourceDefinition => ({
  code: `page_${page.code}`,
  name: page.name,
  access_mode: "public_page",
  target_url: page.url,
  markets: [page.market],
  languages: [page.language],
  fields: ["title", "price", "currency", "position", "source_url", "publisher", "observed_at"],
  schedule_minutes: 60,
  concurrency_limit: 1,
  timeout_ms: 30000,
  retry_limit: 2,
  circuit_failure_threshold: 4,
  dedupe_key: "canonical_url",
  retention_days: 90,
  failure_rules: [
    "network_error",
    "timeout",
    "rate_limited",
    "source_changed",
    "parse_failed",
    "empty_result",
  ],
  parser_version: "structured-public-page-v1",
  healthcheck_url: page.url,
  owner_label: "平台电商来源中心",
  status: "enabled",
  category: "ecommerce",
  availability: "automatic",
  production_policy: "automatic_public_feed",
  policy_note:
    "直接抓取平台公开榜单页面的结构化商品数据，不需要官方 API Key；页面结构变化会明确标记为解析失败。",
});
const googleChannel = (
  locale: (typeof locales)[number],
  topic: (typeof topics)[number],
): BuiltinSourceDefinition => ({
  code: `gnews_${locale.code}_${topic.code}`,
  name: `Google News · ${locale.name} · ${topic.name}`,
  access_mode: "public_rss",
  target_url: `https://news.google.com/rss/search?q=${encodeURIComponent(topic.query)}&hl=${locale.hl}&gl=${locale.gl}&ceid=${locale.ceid}`,
  markets: [locale.market],
  languages: [locale.language],
  fields: ["title", "summary", "published_at", "source_url", "publisher"],
  schedule_minutes: 15,
  concurrency_limit: 1,
  timeout_ms: 20000,
  retry_limit: 3,
  circuit_failure_threshold: 5,
  dedupe_key: "guid",
  retention_days: 90,
  failure_rules: [
    "network_error",
    "timeout",
    "rate_limited",
    "source_changed",
    "parse_failed",
    "empty_result",
  ],
  parser_version: "google-news-fixed-rss-v1",
  healthcheck_url: `https://news.google.com/rss?hl=${locale.hl}&gl=${locale.gl}&ceid=${locale.ceid}`,
  owner_label: "平台热点中心",
  status: "enabled",
  category: topic.category,
  availability: "automatic",
  production_policy: "automatic_public_feed",
  policy_note: "公开 RSS 热点频道；系统每 15 分钟自动采集，也可在热点页手动刷新。",
});
const setupTargetUrls: Readonly<Record<string, string>> = {
  amazon_product: "https://www.amazon.com/",
  keepa: "https://keepa.com/#!finder",
  amazon_bestsellers: "https://www.amazon.com/Best-Sellers/zgbs",
  tiktok_shop: "https://shop.tiktok.com/",
  temu: "https://www.temu.com/",
  shein: "https://www.shein.com/",
  aliexpress: "https://www.aliexpress.com/",
  ebay_browse: "https://www.ebay.com/",
  etsy_listings: "https://www.etsy.com/",
  walmart: "https://www.walmart.com/",
  target: "https://www.target.com/",
  bestbuy: "https://www.bestbuy.com/",
  wayfair: "https://www.wayfair.com/",
  homedepot: "https://www.homedepot.com/",
  lowes: "https://www.lowes.com/",
  costco: "https://www.costco.com/",
  "1688_search": "https://s.1688.com/selloffer/offer_search.htm",
  taobao: "https://www.taobao.com/",
  tmall: "https://www.tmall.com/",
  jd: "https://www.jd.com/",
  pinduoduo: "https://mobile.yangkeduo.com/",
  douyin: "https://www.douyin.com/",
  xiaohongshu: "https://www.xiaohongshu.com/explore",
  reddit_search: "https://www.reddit.com/search/",
  youtube_search: "https://www.youtube.com/results",
  pinterest: "https://www.pinterest.com/",
  instagram: "https://www.instagram.com/",
  facebook: "https://www.facebook.com/",
  quora: "https://www.quora.com/",
  google_trends: "https://trends.google.com/trending",
  similarweb: "https://www.similarweb.com/top-websites/",
  semrush: "https://www.semrush.com/trending-websites/",
  exploding_topics: "https://explodingtopics.com/",
  statista: "https://www.statista.com/",
  kaggle: "https://www.kaggle.com/datasets",
  world_bank: "https://data.worldbank.org/",
  oecd: "https://data-explorer.oecd.org/",
};
const setupSources: readonly BuiltinSourceDefinition[] = [
  ["amazon_product", "Amazon 商品页面", "public_page", "ecommerce"],
  ["keepa", "Keepa 网页价格历史", "authenticated_browser", "data"],
  ["amazon_bestsellers", "Amazon 畅销榜", "public_page", "ecommerce"],
  ["tiktok_shop", "TikTok Shop", "authenticated_browser", "ecommerce"],
  ["temu", "Temu", "authenticated_browser", "ecommerce"],
  ["shein", "SHEIN", "authenticated_browser", "ecommerce"],
  ["aliexpress", "AliExpress", "authenticated_browser", "ecommerce"],
  ["ebay_browse", "eBay 商品页面", "public_page", "ecommerce"],
  ["etsy_listings", "Etsy 商品页面", "public_page", "ecommerce"],
  ["walmart", "Walmart", "public_page", "ecommerce"],
  ["target", "Target", "public_page", "ecommerce"],
  ["bestbuy", "Best Buy", "public_page", "ecommerce"],
  ["wayfair", "Wayfair", "public_page", "ecommerce"],
  ["homedepot", "Home Depot", "public_page", "ecommerce"],
  ["lowes", "Lowe's", "public_page", "ecommerce"],
  ["costco", "Costco", "public_page", "ecommerce"],
  ["1688_search", "1688 搜索", "authenticated_browser", "product_supply"],
  ["taobao", "淘宝", "authenticated_browser", "ecommerce"],
  ["tmall", "天猫", "authenticated_browser", "ecommerce"],
  ["jd", "京东", "authenticated_browser", "ecommerce"],
  ["pinduoduo", "拼多多", "authenticated_browser", "ecommerce"],
  ["douyin", "抖音电商", "authenticated_browser", "ecommerce"],
  ["xiaohongshu", "小红书", "authenticated_browser", "community"],
  ["reddit_search", "Reddit 论坛搜索", "public_page", "community"],
  ["youtube_search", "YouTube 公开搜索", "public_page", "community"],
  ["pinterest", "Pinterest", "public_page", "community"],
  ["instagram", "Instagram", "authenticated_browser", "community"],
  ["facebook", "Facebook", "authenticated_browser", "community"],
  ["quora", "Quora", "public_page", "community"],
  ["google_trends", "Google Trends", "public_page", "data"],
  ["similarweb", "Similarweb 公开榜单", "public_page", "data"],
  ["semrush", "Semrush 网页趋势", "authenticated_browser", "data"],
  ["exploding_topics", "Exploding Topics", "public_page", "data"],
  ["statista", "Statista", "public_page", "data"],
  ["kaggle", "Kaggle 数据集", "public_page", "data"],
  ["world_bank", "World Bank Data", "public_page", "data"],
  ["oecd", "OECD Data", "public_page", "data"],
].map(([code, name, access, category]) => ({
  code: String(code),
  name: String(name),
  access_mode: access as BuiltinSourceDefinition["access_mode"],
  target_url: setupTargetUrls[String(code)]!,
  markets: ["GLOBAL"],
  languages: ["und"],
  fields:
    code === "1688_search"
      ? [
          "title",
          "supplier_name",
          "quoted_price",
          "currency",
          "moq",
          "specification",
          "lead_time_days",
          "location",
          "canonical_url",
          "observed_at",
        ]
      : code === "amazon_product"
        ? [
            "asin",
            "title",
            "price",
            "currency",
            "position",
            "review_count",
            "rating_value",
            "availability",
            "image_url",
            "source_url",
          ]
        : ["title", "observed_at", "source_url"],
  schedule_minutes: 30,
  concurrency_limit: 1,
  timeout_ms: 20000,
  retry_limit: 2,
  circuit_failure_threshold: 5,
  dedupe_key: "external_id",
  retention_days: 90,
  failure_rules: ["permission_denied", "login_required", "rate_limited", "source_changed"],
  parser_version:
    code === "1688_search"
      ? ALIBABA_1688_BROWSER_PARSER_VERSION
      : code === "amazon_product"
        ? "amazon-structured-product-v2"
        : "setup-required-v1",
  healthcheck_url: null,
  owner_label: "平台来源中心",
  status: code === "amazon_product" ? "enabled" : "disabled",
  category: category as SourceCategory,
  availability: code === "amazon_product" ? "manual" : "setup_required",
  production_policy: code === "amazon_product" ? "ready_for_owner_enablement" : "setup_required",
  policy_note:
    code === "amazon_product"
      ? "用户发起竞品采集时抓取公开 Amazon 商品页，不需要官方 API；价格、评分和评论只保留页面真实披露值。"
      : code === "1688_search"
        ? "搜索、商品详情与供应商采集能力已登记；完成网页登录准备和来源检查后才能启用。"
        : access === "authenticated_browser"
          ? "已配置平台真实登录入口；上传 Cookie 或读取当前浏览器 Cookie 后，还需完成该平台页面解析合同才会进入自动采集，不要求官方 API Key。"
          : "已配置平台真实公开入口；完成来源可用性检查后即可启用匿名爬虫，不要求登录或官方 API Key。",
}));
export const BUILTIN_PROVIDER_SOURCES: readonly BuiltinSourceDefinition[] = [
  {
    code: "google_news_search",
    name: "Google News 手动关键词",
    access_mode: "public_rss",
    target_url: GOOGLE_TEMPLATE,
    markets: ["GLOBAL"],
    languages: ["multi"],
    fields: ["title", "summary", "published_at", "source_url", "publisher"],
    schedule_minutes: 15,
    concurrency_limit: 1,
    timeout_ms: 20000,
    retry_limit: 3,
    circuit_failure_threshold: 5,
    dedupe_key: "guid",
    retention_days: 90,
    failure_rules: [
      "network_error",
      "timeout",
      "rate_limited",
      "source_changed",
      "parse_failed",
      "empty_result",
    ],
    parser_version: "google-news-rss-v1",
    healthcheck_url: "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",
    owner_label: "平台热点中心",
    status: "enabled",
    category: "news",
    availability: "manual",
    production_policy: "ready_for_owner_enablement",
    policy_note: "用于用户输入关键词后立即采集；不会在浏览器暴露密钥。",
  },
  ...locales.flatMap((locale) => topics.map((topic) => googleChannel(locale, topic))),
  ...syndicationFeeds.map(syndicationChannel),
  ...publicCatalogPages.map(publicCatalogChannel),
  ...setupSources,
  {
    code: "erp_product_catalog",
    name: "米豆 ERP 商品库",
    access_mode: "import",
    target_url: "https://medou.medouai.com/#/ProductList",
    markets: ["GLOBAL"],
    languages: ["zh-CN"],
    fields: [
      "spu",
      "title",
      "image_url",
      "asin_list",
      "supplier_code",
      "cost_cny",
      "cost_usd",
      "store_id",
      "observed_at",
    ],
    schedule_minutes: 1440,
    concurrency_limit: 1,
    timeout_ms: 120000,
    retry_limit: 1,
    circuit_failure_threshold: 3,
    dedupe_key: "spu_or_row_id",
    retention_days: 365,
    failure_rules: ["login_required", "validation_failed", "empty_result"],
    parser_version: "erp-product-catalog-v1",
    healthcheck_url: null,
    owner_label: "平台选品中心",
    status: "enabled",
    category: "product_supply",
    availability: "manual",
    production_policy: "ready_for_owner_enablement",
    policy_note:
      "通过本机浏览器助手读取用户已登录的 ERP 商品列表；登录令牌不上传，只接收商品结果并保留原始证据。",
  },
  {
    code: "made_in_china_search",
    name: "中国制造网供应商搜索",
    access_mode: "public_page",
    target_url: "https://www.made-in-china.com/",
    markets: ["GLOBAL"],
    languages: ["en-US", "zh-CN"],
    fields: [
      "title",
      "supplier_name",
      "price",
      "currency",
      "moq",
      "image_url",
      "source_url",
      "observed_at",
    ],
    schedule_minutes: 1440,
    concurrency_limit: 1,
    timeout_ms: 30000,
    retry_limit: 2,
    circuit_failure_threshold: 4,
    dedupe_key: "source_url",
    retention_days: 180,
    failure_rules: ["network_error", "rate_limited", "source_changed"],
    parser_version: "made-in-china-search-v1",
    healthcheck_url: "https://www.made-in-china.com/",
    owner_label: "平台供应链中心",
    status: "enabled",
    category: "product_supply",
    availability: "manual",
    production_policy: "ready_for_owner_enablement",
    policy_note:
      "用户发起找货时抓取公开供应商搜索页，不需要官方 API；价格和供应商均保留原页证据，MOQ 缺失时不会填充默认值。",
  },
  {
    code: "ec21_supplier_search",
    name: "EC21 国际供应商搜索",
    access_mode: "public_page",
    target_url: "https://www.ec21.com/",
    markets: ["GLOBAL"],
    languages: ["en-US"],
    fields: [
      "title",
      "supplier_name",
      "price",
      "currency",
      "moq",
      "image_url",
      "source_url",
      "observed_at",
    ],
    schedule_minutes: 1440,
    concurrency_limit: 1,
    timeout_ms: 30000,
    retry_limit: 2,
    circuit_failure_threshold: 4,
    dedupe_key: "source_url",
    retention_days: 180,
    failure_rules: ["network_error", "rate_limited", "source_changed"],
    parser_version: "ec21-supplier-search-v1",
    healthcheck_url: "https://www.ec21.com/ec-market/storage-box.html",
    owner_label: "平台供应链中心",
    status: "enabled",
    category: "product_supply",
    availability: "manual",
    production_policy: "ready_for_owner_enablement",
    policy_note:
      "用户发起找货时抓取 EC21 公开供应商商品列表；与中国制造网并行执行，单一来源受限时不会伪造结果。",
  },
  {
    code: "dhgate_supplier_search",
    name: "DHgate 批发供应商搜索",
    access_mode: "public_page",
    target_url: "https://www.dhgate.com/wholesale/{slug}.html",
    markets: ["GLOBAL"],
    languages: ["en-US"],
    fields: [
      "title",
      "supplier_name",
      "price",
      "currency",
      "moq",
      "image_url",
      "source_url",
      "observed_at",
    ],
    schedule_minutes: 1440,
    concurrency_limit: 1,
    timeout_ms: 30000,
    retry_limit: 2,
    circuit_failure_threshold: 4,
    dedupe_key: "source_url",
    retention_days: 180,
    failure_rules: ["network_error", "rate_limited", "source_changed"],
    parser_version: "dhgate-supplier-search-v1",
    healthcheck_url: "https://www.dhgate.com/wholesale/storage-box.html",
    owner_label: "平台供应链中心",
    status: "enabled",
    category: "product_supply",
    availability: "manual",
    production_policy: "ready_for_owner_enablement",
    policy_note:
      "用户发起找货时抓取 robots 允许的 DHgate 批发公开页；价格、币种、店铺和商品链接均保留原页证据，MOQ 缺失时不会填充默认值。",
  },
  {
    code: "manual_product_supply_csv",
    name: "商品与供应链 CSV 导入",
    access_mode: "import",
    target_url: "inline://product-supply-csv-v1",
    markets: ["GLOBAL"],
    languages: ["und"],
    fields: [
      "external_id",
      "title",
      "price",
      "currency",
      "supplier_name",
      "moq",
      "canonical_url",
      "observed_at",
    ],
    schedule_minutes: 10080,
    concurrency_limit: 1,
    timeout_ms: 10000,
    retry_limit: 0,
    circuit_failure_threshold: 1,
    dedupe_key: "external_id",
    retention_days: 365,
    failure_rules: ["validation_failed", "empty_result"],
    parser_version: "product-supply-csv-v1",
    healthcheck_url: null,
    owner_label: "平台来源中心",
    status: "disabled",
    category: "product_supply",
    availability: "manual",
    production_policy: "ready_for_owner_enablement",
    policy_note: "处理用户明确上传的商品与供应链 CSV，不连接或伪造外部平台数据。",
  },
];

export const AUTOMATIC_PROVIDER_SOURCE_HOSTS = Object.freeze([
  ...new Set(
    BUILTIN_PROVIDER_SOURCES.filter(
      (item) =>
        item.availability === "automatic" ||
        [
          "amazon_product",
          "made_in_china_search",
          "ec21_supplier_search",
          "dhgate_supplier_search",
        ].includes(item.code),
    ).map((item) => new URL(item.target_url).hostname.toLowerCase()),
  ),
]);
