import test from 'node:test';
import assert from 'node:assert/strict';
import { buildApp } from '../../apps/api/dist/app.js';
import { InMemoryTenancyRepository, TenancyService } from '../../packages/tenancy/dist/index.js';

const userA='00000000-0000-4000-8000-000000000311',userB='00000000-0000-4000-8000-000000000312';
async function fixture(){const repository=new InMemoryTenancyRepository();const service=new TenancyService(repository);const auth={authenticate:async(token)=>{if(token==='token-a')return{user:{id:userA,status:'active'},session:{id:'00000000-0000-4000-8000-000000000313'}};if(token==='token-b')return{user:{id:userB,status:'active'},session:{id:'00000000-0000-4000-8000-000000000314'}};throw new Error('bad_token');}};const context={requestId:'setup',traceId:'setup'};const first=await service.provisionOrganization({name:'华南增长中心',slug:'south-growth',timezone:'Asia/Shanghai',dataRetentionDays:365,defaultWorkspaceName:'新品工作区',defaultWorkspaceSlug:'new-products'},{...context,actorId:userA});const second=await service.provisionOrganization({name:'隔离组织',slug:'isolated',timezone:'Asia/Shanghai',dataRetentionDays:365,defaultWorkspaceName:'隔离工作区',defaultWorkspaceSlug:'isolated'},{...context,actorId:userB});const seen=new Map();const execute=async(input,work)=>{const key=`${input.route}:${input.scope}:${input.key}`;if(seen.has(key))return{...seen.get(key),replayed:true};const result=await work();seen.set(key,result);return result;};const idempotency={execute,executeSensitive:execute};const app=buildApp({tenancy:{service,auth,idempotency,webOrigin:'http://127.0.0.1:5173',secureCookie:false}});return{app,repository,first,second};}
const cookie={cookie:'scoutops_session=token-a'};

test('M01-03.A06/A09 membership-backed lists use only current HttpOnly session identity',async()=>{const f=await fixture();const organizations=await f.app.inject({method:'GET',url:'/api/v1/org/memberships',headers:cookie});assert.equal(organizations.statusCode,200);assert.equal(organizations.json().data.length,1);assert.equal(organizations.json().data[0].id,f.first.organization.id);const workspaces=await f.app.inject({method:'GET',url:`/api/v1/org/${f.first.organization.id}/workspaces`,headers:cookie});assert.equal(workspaces.statusCode,200);assert.equal(workspaces.json().data[0].id,f.first.workspace.id);const teams=await f.app.inject({method:'GET',url:`/api/v1/org/${f.first.organization.id}/teams`,headers:cookie});assert.equal(teams.statusCode,200);assert.deepEqual(teams.json().data,[]);await f.app.close();});

test('M01-03.A08/A09/A16 foreign organization access is forbidden with stable envelope',async()=>{const f=await fixture();const response=await f.app.inject({method:'GET',url:`/api/v1/org/${f.second.organization.id}/workspaces`,headers:cookie});assert.equal(response.statusCode,403);assert.equal(response.json().error.code,'organization_forbidden');assert.ok(response.json().request_id);assert.ok(response.json().trace_id);await f.app.close();});

test('M01-03.A06/A11 context selection requires origin/idempotency and replays without duplicate audit',async()=>{const f=await fixture();const payload={organization_id:f.first.organization.id,workspace_id:f.first.workspace.id};const noKey=await f.app.inject({method:'POST',url:'/api/v1/auth/context',headers:{...cookie,origin:'http://127.0.0.1:5173'},payload});assert.equal(noKey.statusCode,400);const headers={...cookie,origin:'http://127.0.0.1:5173','idempotency-key':'select-context-1'};const first=await f.app.inject({method:'POST',url:'/api/v1/auth/context',headers,payload});const replay=await f.app.inject({method:'POST',url:'/api/v1/auth/context',headers,payload});assert.equal(first.statusCode,200);assert.equal(first.json().data.workspace.id,f.first.workspace.id);assert.equal(replay.headers['idempotency-replayed'],'true');assert.equal(f.repository.audits.filter(item=>item.action==='context.selected').length,1);assert.equal(f.repository.contexts.length,1);await f.app.close();});
