import { createHash } from 'node:crypto';
import { ProviderAdapterFailure, type AdapterHealthContext, type AdapterHealthSignal, type AdapterInvocationContext, type ProviderAdapter, type ProviderCollectBatch, type ProviderCollectRequest, type ProviderNormalizedRecord, type ProviderRawRecord } from '@scoutops/provider-adapters';

export interface BuiltinSourceDefinition{code:'google_news_search'|'manual_product_supply_csv';name:string;access_mode:'public_rss'|'import';target_url:string;markets:string[];languages:string[];fields:string[];schedule_minutes:number;concurrency_limit:number;timeout_ms:number;retry_limit:number;circuit_failure_threshold:number;dedupe_key:string;retention_days:number;failure_rules:string[];parser_version:string;healthcheck_url:string|null;owner_label:string;status:'disabled';category:'trend'|'product_supply';production_policy:'owner_review_required'|'ready_for_owner_enablement';policy_note:string;}
export const BUILTIN_PROVIDER_SOURCES:readonly BuiltinSourceDefinition[]=[
  {code:'google_news_search',name:'Google News 关键词 RSS',access_mode:'public_rss',target_url:'https://news.google.com/rss/search?q={urlEncodedQuery}&hl=en-US&gl=US&ceid=US:en',markets:['US'],languages:['en-US'],fields:['title','summary','published_at','source_url','publisher'],schedule_minutes:15,concurrency_limit:1,timeout_ms:20000,retry_limit:3,circuit_failure_threshold:5,dedupe_key:'guid',retention_days:90,failure_rules:['network_error','timeout','rate_limited','source_changed','parse_failed','empty_result'],parser_version:'google-news-rss-v1',healthcheck_url:'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en',owner_label:'平台运营',status:'disabled',category:'trend',production_policy:'owner_review_required',policy_note:'端点可用不等于生产授权；所有者须复核 Google 当前条款、频率和保存字段后显式启用。'},
  {code:'manual_product_supply_csv',name:'商品与供应链 CSV 导入',access_mode:'import',target_url:'inline://product-supply-csv-v1',markets:['GLOBAL'],languages:['und'],fields:['external_id','title','price','currency','supplier_name','moq','canonical_url','observed_at'],schedule_minutes:10080,concurrency_limit:1,timeout_ms:10000,retry_limit:0,circuit_failure_threshold:1,dedupe_key:'external_id',retention_days:365,failure_rules:['validation_failed','empty_result'],parser_version:'product-supply-csv-v1',healthcheck_url:null,owner_label:'平台运营',status:'disabled',category:'product_supply',production_policy:'ready_for_owner_enablement',policy_note:'仅处理显式上传的 CSV 内容；不连接外部商品平台，不包含客户凭证。'}
] as const;

export interface SourceEvidencePayload{raw_content:string;content_type:string;canonical_url:string;fields:Record<string,string|number|null>;source_paths:Record<string,string>;}
const text=(value:unknown,name:string,max:number)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new ProviderAdapterFailure(`${name}_invalid`,false);return value.trim();};
const entity=(value:string)=>value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([a-f0-9]+);/gi,(_,n)=>String.fromCodePoint(Number.parseInt(n,16))).trim();
const tag=(xml:string,name:string)=>{const match=xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'));return match?.[1]?entity(match[1]):'';};
const stripHtml=(value:string)=>entity(value.replace(/<[^>]+>/g,' ').replace(/\s+/g,' '));
const httpUrl=(value:string)=>{let url:URL;try{url=new URL(value);}catch{throw new ProviderAdapterFailure('source_url_invalid',false);}if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.hash)throw new ProviderAdapterFailure('source_url_invalid',false);return url.toString();};
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');

export function parseGoogleNewsRss(xml:string,limit=20):ProviderRawRecord[]{if(typeof xml!=='string'||Buffer.byteLength(xml)>2_000_000||!/<rss\b/i.test(xml)||!/<channel\b/i.test(xml))throw new ProviderAdapterFailure('invalid_payload',false);const blocks=[...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/gi)].slice(0,Math.min(100,limit));return blocks.map(match=>{const raw=match[0],guid=text(tag(raw,'guid'),'rss_guid',2048),title=text(tag(raw,'title'),'rss_title',1000),link=httpUrl(text(tag(raw,'link'),'rss_link',2048)),published=text(tag(raw,'pubDate'),'rss_pub_date',120),publisher=text(tag(raw,'source'),'rss_publisher',300),summary=stripHtml(tag(raw,'description')).slice(0,2000),observedAt=new Date(published);if(!Number.isFinite(observedAt.getTime()))throw new ProviderAdapterFailure('rss_pub_date_invalid',false);const payload:SourceEvidencePayload={raw_content:raw,content_type:'application/rss+xml',canonical_url:link,fields:{title,summary,published_at:observedAt.toISOString(),source_url:link,publisher},source_paths:{title:'rss.item.title',summary:'rss.item.description',published_at:'rss.item.pubDate',source_url:'rss.item.link',publisher:'rss.item.source'}};return{externalId:sha(guid),observedAt:observedAt.toISOString(),evidenceRef:`google-news-rss:${sha(guid)}`,payload};});}

function parseCsvRows(input:string){if(typeof input!=='string'||Buffer.byteLength(input)>1_048_576)throw new ProviderAdapterFailure('csv_size_invalid',false);const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<input.length;i++){const char=input[i];if(quoted){if(char==='"'&&input[i+1]==='"'){cell+='"';i++;}else if(char==='"')quoted=false;else cell+=char;}else if(char==='"')quoted=true;else if(char===','){row.push(cell);cell='';}else if(char==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=char;}if(quoted)throw new ProviderAdapterFailure('csv_quote_invalid',false);if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows.filter(value=>value.some(cell=>cell.trim()));}
const CSV_HEADERS=['external_id','title','price','currency','supplier_name','moq','canonical_url','observed_at'] as const;
export function parseProductSupplyCsv(csv:string,limit=20):ProviderRawRecord[]{const rows=parseCsvRows(csv),header=rows[0];if(rows.length<2||rows.length>101||!header||header.length!==CSV_HEADERS.length||header.some((value,index)=>value.trim()!==CSV_HEADERS[index]))throw new ProviderAdapterFailure('csv_header_invalid',false);return rows.slice(1,Math.min(rows.length,limit+1)).map((values,index)=>{if(values.length!==CSV_HEADERS.length)throw new ProviderAdapterFailure('csv_column_count_invalid',false);const row=Object.fromEntries(CSV_HEADERS.map((name,i)=>[name,(values[i]??'').trim()])) as Record<typeof CSV_HEADERS[number],string>,externalId=text(row.external_id,'external_id',200),title=text(row.title,'title',1000),price=Number(row.price),currency=text(row.currency,'currency',3).toUpperCase(),supplier=text(row.supplier_name,'supplier_name',500),moq=Number(row.moq),canonical=httpUrl(text(row.canonical_url,'canonical_url',2048)),observed=new Date(text(row.observed_at,'observed_at',120));if(!Number.isFinite(price)||price<0||!Number.isSafeInteger(moq)||moq<1||!/^[A-Z]{3}$/.test(currency)||!Number.isFinite(observed.getTime()))throw new ProviderAdapterFailure('csv_value_invalid',false);const fields={external_id:externalId,title,price,currency,supplier_name:supplier,moq,canonical_url:canonical,observed_at:observed.toISOString()},sourcePaths=Object.fromEntries(CSV_HEADERS.map(name=>[name,`csv.row[${index+2}].${name}`])),payload:SourceEvidencePayload={raw_content:JSON.stringify(row),content_type:'application/json',canonical_url:canonical,fields,source_paths:sourcePaths};return{externalId,observedAt:observed.toISOString(),evidenceRef:`manual-product-supply:${sha(`${externalId}\0${canonical}`)}`,payload};});}

function payload(record:ProviderRawRecord){const value=record.payload as Partial<SourceEvidencePayload>;if(!value||typeof value.raw_content!=='string'||typeof value.content_type!=='string'||typeof value.canonical_url!=='string'||!value.fields||!value.source_paths)throw new ProviderAdapterFailure('invalid_payload',false);return value as SourceEvidencePayload;}
abstract class SourceAdapter implements ProviderAdapter{abstract readonly key:string;abstract readonly accessMode:'public_rss'|'import';abstract readonly version:string;abstract collect(request:ProviderCollectRequest,signal:AbortSignal):Promise<ProviderCollectBatch>;abstract healthCheck(context:AdapterHealthContext,signal:AbortSignal):Promise<AdapterHealthSignal>;normalize(record:ProviderRawRecord,context:AdapterInvocationContext):ProviderNormalizedRecord{const value=payload(record);return{external_id:record.externalId,observed_at:record.observedAt,canonical_url:value.canonical_url,fields:value.fields,evidence_ref:record.evidenceRef,provenance:{provider_id:context.provider.id,adapter_key:this.key,adapter_version:this.version,parser_version:context.provider.parserVersion}};}}

export class GoogleNewsRssAdapter extends SourceAdapter{readonly key='google_news_search';readonly accessMode='public_rss' as const;readonly version='google-news-rss-adapter-v1';constructor(private readonly fetcher:typeof fetch=fetch){super();}private url(target:string,query:string){if(target!=='https://news.google.com/rss/search?q={urlEncodedQuery}&hl=en-US&gl=US&ceid=US:en')throw new ProviderAdapterFailure('source_configuration_invalid',false);return target.replace('{urlEncodedQuery}',encodeURIComponent(text(query,'query',200)));}async collect(request:ProviderCollectRequest,signal:AbortSignal){const query=(request as ProviderCollectRequest&{target?:Record<string,unknown>}).target?.query,url=this.url(request.provider.targetUrl,query as string),response=await this.fetcher(url,{signal,redirect:'error',headers:{accept:'application/rss+xml, application/xml;q=0.9','user-agent':'ScoutOps/0.1 source-admission'}});if(response.status===429)throw new ProviderAdapterFailure('rate_limited',true);if(response.status>=500)throw new ProviderAdapterFailure('network_error',true);if(!response.ok)throw new ProviderAdapterFailure('permission_denied',false);const type=response.headers.get('content-type')??'';if(!/(xml|rss)/i.test(type))throw new ProviderAdapterFailure('source_changed',false);const xml=await response.text(),records=parseGoogleNewsRss(xml,Math.min(request.limit,20));return{records,nextCursor:null};}async healthCheck(context:AdapterHealthContext,signal:AbortSignal):Promise<AdapterHealthSignal>{const started=Date.now(),url=this.url(context.provider.targetUrl,'product');try{const response=await this.fetcher(url,{signal,redirect:'error',headers:{accept:'application/rss+xml, application/xml;q=0.9','user-agent':'ScoutOps/0.1 source-health'}});if(response.status===429)return{status:'degraded',latencyMs:Date.now()-started,errorCode:'rate_limited',message:'Google News RSS 返回限流。'};if(!response.ok)return{status:'degraded',latencyMs:Date.now()-started,errorCode:'network_error',message:`Google News RSS 返回 HTTP ${response.status}。`};const sample=await response.text();parseGoogleNewsRss(sample,1);return{status:'ready',latencyMs:Date.now()-started,errorCode:null,message:'Google News RSS XML 合同可读取；生产启用仍需所有者政策复核。'};}catch(error){if(error instanceof ProviderAdapterFailure)throw error;throw new ProviderAdapterFailure('network_error',true);}}}
export class ManualProductSupplyCsvAdapter extends SourceAdapter{readonly key='manual_product_supply_csv';readonly accessMode='import' as const;readonly version='manual-product-supply-csv-adapter-v1';async collect(request:ProviderCollectRequest){if(request.provider.targetUrl!=='inline://product-supply-csv-v1')throw new ProviderAdapterFailure('source_configuration_invalid',false);const csv=(request as ProviderCollectRequest&{target?:Record<string,unknown>}).target?.csv_text;return{records:parseProductSupplyCsv(csv as string,Math.min(request.limit,20)),nextCursor:null};}async healthCheck(){return{status:'ready' as const,latencyMs:0,errorCode:null,message:'CSV Parser 合同已就绪；仅处理显式导入内容。'};}}
export function createBuiltinSourceAdapters(fetcher:typeof fetch=fetch){return[new GoogleNewsRssAdapter(fetcher),new ManualProductSupplyCsvAdapter()] as const;}
export function sourceEvidencePayload(record:ProviderRawRecord){return payload(record);}
