<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import type { CurrentAuthorizationSummary,RoleCapabilitySummary } from '@scoutops/contracts';
const props=defineProps<{apiBaseUrl:string}>();type State='loading'|'ready'|'empty'|'error'|'forbidden'|'expired';const state=ref<State>('loading'),current=ref<CurrentAuthorizationSummary|null>(null),roles=ref<RoleCapabilitySummary[]>([]),selected=ref<RoleCapabilitySummary|null>(null),query=ref(''),requestId=ref('');
const filtered=computed(()=>roles.value.filter(role=>!query.value.trim()||`${role.name} ${role.code} ${role.description} ${role.capabilities.join(' ')}`.toLowerCase().includes(query.value.trim().toLowerCase())));
async function request<T>(path:string){const response=await fetch(`${props.apiBaseUrl}${path}`,{credentials:'include',headers:{accept:'application/json'}});const body=await response.json().catch(()=>null);if(!response.ok){requestId.value=body?.request_id??'';throw new Error(response.status===401?'expired':response.status===403?'forbidden':'error');}return body.data as T;}
async function load(){state.value='loading';try{current.value=await request<CurrentAuthorizationSummary>('/me/authorization');roles.value=await request<RoleCapabilitySummary[]>(`/org/${current.value.organization_id}/roles`);selected.value=roles.value[0]??null;state.value=roles.value.length?'ready':'empty';}catch(error){state.value=(error instanceof Error?error.message:'error') as State;}}
const scopeLabel=(scope:string)=>({own:'本人',team:'团队',workspace:'工作区',organization:'组织',platform:'平台'}[scope]??scope);onMounted(load);
</script>
<template><main class="authz-page" data-testid="authorization"><aside class="authz-sidebar"><a href="/" class="identity-brand"><span>S</span>ai选品</a><p>组织管理后台</p><nav><a href="/select-context">组织资料</a><a href="/?view=authorization" class="active">角色与权限</a><span>成员与邀请</span><span>工作区与团队</span><span>组织审计</span></nav><small>权限来自服务端策略</small></aside><section class="authz-main"><header><div><p>ORGANIZATION SECURITY</p><h1>角色与权限</h1><span>动作决定能做什么，数据范围决定能看到哪些记录。</span></div><a href="/select-context">切换组织</a></header>
 <div v-if="state==='loading'" class="authz-state"><span class="spinner"></span><strong>正在读取服务端授权</strong><p>页面不会根据菜单或浏览器状态推断权限。</p></div>
 <div v-else-if="state==='error'||state==='forbidden'||state==='expired'" class="authz-state authz-state--error"><b>{{ state==='forbidden'?'403':state==='expired'?'401':'!' }}</b><strong>{{ state==='forbidden'?'缺少 role:read 权限':state==='expired'?'登录已过期':'权限服务暂不可用' }}</strong><p>{{ state==='forbidden'?'联系组织管理员查看角色矩阵。':state==='expired'?'重新登录并选择组织工作区。':'稍后重试，并向管理员提供请求标识。' }}</p><small v-if="requestId">请求标识：{{ requestId }}</small><a v-if="state==='expired'" href="/login">重新登录</a><button v-else type="button" @click="load">重新加载</button></div>
 <div v-else-if="state==='empty'" class="authz-state"><b>○</b><strong>暂无活动角色</strong><p>角色目录未初始化，管理动作保持默认拒绝。</p><button type="button" @click="load">重新加载</button></div>
 <template v-else-if="current"><section class="authz-summary"><div><span>当前角色</span><strong>{{ current.roles.length }}</strong><small>{{ current.roles.join(' · ') }}</small></div><div><span>有效动作</span><strong>{{ current.capabilities.length }}</strong><small>由服务端聚合后返回</small></div><div><span>数据范围</span><strong>{{ current.data_scopes.length }}</strong><small>{{ current.data_scopes.map(item=>scopeLabel(item.scope)).join(' · ') }}</small></div></section><div class="authz-toolbar"><label>搜索角色或能力<input v-model="query" type="search" placeholder="例如 opportunity:approve"></label><span>{{ filtered.length }} 个角色</span></div><div class="authz-layout"><div class="role-list"><button v-for="role in filtered" :key="role.code" type="button" :class="{selected:selected?.code===role.code}" @click="selected=role"><span>{{ role.name.slice(0,1) }}</span><div><strong>{{ role.name }}</strong><small>{{ role.code }}</small><p>{{ role.description }}</p></div><em>{{ role.capabilities.length }} 项动作</em></button><p v-if="!filtered.length" class="role-empty">没有匹配的角色或能力。</p></div><article v-if="selected" class="role-detail"><p>只读权限预览</p><h2>{{ selected.name }}</h2><span>{{ selected.description }}</span><div><code v-for="capability in selected.capabilities" :key="capability">{{ capability }}</code></div><small>前端仅展示；API、Worker、导出、文件、事件与 SSE 使用同一能力名称再次检查。</small></article></div></template></section></main></template>
