<script setup lang="ts">
import { computed,onMounted,ref } from "vue";
import type { FileResilienceDto } from "@scoutops/contracts";
import "../file-resilience.css";
type ViewState="loading"|"ready"|"warning"|"blocked"|"empty"|"forbidden"|"expired"|"rate_limited"|"unavailable"|"recovering";
const props=defineProps<{apiBaseUrl:string}>(),state=ref<ViewState>("loading"),data=ref<FileResilienceDto|null>(null),requestId=ref(""),actionHint=ref("");
const verdict=computed(()=>({loading:["正在核对本机受控目录","读取容量、索引、校验和与同机恢复事实。"],ready:["本机文件韧性门已满足","证据与导出目录符合当前 S0 单机边界。"],warning:["本机文件接近预警线","当前可用，但需要按告警项处理。"],blocked:["本机文件韧性门已阻断","停止新增大文件任务，并通过宝塔核验目录与恢复副本。"],empty:["尚无本机文件观测","确认宝塔 Node API 与受控目录后重新核验。"],forbidden:["没有平台运维权限",actionHint.value||"需要 platform:operate 能力。"],expired:["登录已失效","重新登录后再核验。"],rate_limited:["刷新过于频繁","稍后重试。"],unavailable:["本机文件事实暂不可用",actionHint.value||"在宝塔检查 Node API、目录挂载与 MySQL。"],recovering:["正在核验同机文件恢复","恢复和校验结论确认前保持阻断。"]} satisfies Record<ViewState,[string,string]>)[state.value]);
const percent=(value:number)=>`${(value/100).toFixed(1)}%`;const bytes=(value:number)=>value>=1099511627776?`${(value/1099511627776).toFixed(2)} TiB`:value>=1073741824?`${(value/1073741824).toFixed(1)} GiB`:`${(value/1048576).toFixed(1)} MiB`;const time=(value:string)=>new Date(value).toLocaleString("zh-CN",{hour12:false});
async function load(){state.value="loading";actionHint.value="";try{const response=await fetch(`${props.apiBaseUrl}/platform/operations/files`,{credentials:"include",headers:{accept:"application/json"}}),body=await response.json().catch(()=>null);requestId.value=body?.request_id??"";actionHint.value=body?.error?.action_hint??"";if(!response.ok){state.value=response.status===401?"expired":response.status===403?"forbidden":response.status===429?"rate_limited":"unavailable";return;}if(!body?.data){data.value=null;state.value="empty";return;}data.value=body.data;state.value=body.data.state;}catch{state.value="unavailable";}}
onMounted(load);
</script>
<template>
  <section class="file-resilience" :data-state="state">
    <header class="file-resilience__hero"><div><p>LOCAL MANAGED STORAGE · M08-04</p><h2>本机文件韧性</h2><span>证据与导出只写入惠州当前主机的宝塔受控目录；不使用共享存储或备用服务器。</span></div><button type="button" @click="load">刷新文件事实</button></header>
    <section v-if="state==='loading'||state==='recovering'" class="file-resilience__state" aria-live="polite"><i></i><div><b>{{verdict[0]}}</b><p>{{verdict[1]}}</p></div></section>
    <section v-else-if="['forbidden','expired','rate_limited','unavailable','empty'].includes(state)" class="file-resilience__state file-resilience__state--danger" aria-live="polite"><strong>!</strong><div><b>{{verdict[0]}}</b><p>{{verdict[1]}}</p><code v-if="requestId">request_id {{requestId}}</code></div><button type="button" @click="load">重新核验</button></section>
    <template v-else-if="data">
      <section class="file-resilience__verdict" :data-verdict="state"><div><small>S0 · {{state.toUpperCase()}}</small><strong>{{verdict[0]}}</strong></div><p>{{verdict[1]}}</p><em>本机 · 容量未验证</em></section>
      <section class="file-resilience__metrics"><article v-for="root in data.directories" :key="root.kind"><span>{{root.kind==='evidence'?'证据目录':'导出目录'}}</span><strong>{{percent(root.usage_basis_points)}}</strong><small>{{bytes(root.used_bytes)}} / {{bytes(root.total_bytes)}} · {{root.active_files}} 个活动文件</small></article><article><span>校验和</span><strong>{{data.integrity.verified_files}} / {{data.integrity.sampled_files}}</strong><small>不一致 {{data.integrity.mismatch_files}} · 缺失 {{data.integrity.missing_files}}</small></article><article><span>恢复演练</span><strong>{{data.recovery.status}}</strong><small>{{data.recovery.drill_age_days??'—'}} 天 · 同机加密副本</small></article></section>
      <div class="file-resilience__layout"><section class="file-resilience__panel"><header><div><p>DIRECTORIES</p><h3>宝塔受控目录</h3></div><span>组织 / 工作区隔离</span></header><div class="file-resilience__roots"><article v-for="root in data.directories" :key="root.kind"><div><b>{{root.kind==='evidence'?'不可变证据':'限时导出'}}</b><span>{{root.available&&root.writable?'可读写':'不可用'}}</span></div><progress :value="root.usage_basis_points" max="10000"></progress><dl><div><dt>索引体积</dt><dd>{{bytes(root.indexed_bytes)}}</dd></div><div><dt>公网访问</dt><dd>{{data.public_access_enabled?'已启用':'已禁用'}}</dd></div></dl></article></div></section><aside class="file-resilience__panel"><header><div><p>RECOVERY</p><h3>同机恢复边界</h3></div></header><dl class="file-resilience__facts"><div><dt>加密恢复副本</dt><dd>{{data.recovery.encrypted_same_host_copy?'已核验':'未核验'}}</dd></div><div><dt>隔离恢复</dt><dd>{{data.recovery.isolated_restore_verified?'已核验':'未核验'}}</dd></div><div><dt>共享存储</dt><dd>{{data.shared_storage_enabled?'已启用':'未启用'}}</dd></div><div><dt>备用服务器</dt><dd>{{data.backup_server_used?'已启用':'未启用'}}</dd></div></dl></aside></div>
      <section class="file-resilience__panel file-resilience__findings"><header><div><p>FAIL-CLOSED GATES</p><h3>容量、完整性与恢复告警</h3></div><span>{{data.findings.length}} 项</span></header><div v-if="data.findings.length"><article v-for="(item,index) in data.findings" :key="item.code" :data-severity="item.severity"><span>{{String(index+1).padStart(2,'0')}}</span><code>{{item.code}}</code><p>{{item.action_hint}}</p></article></div><div v-else class="file-resilience__clear"><b>当前无本机文件韧性阻断</b><span>这不代表共享存储、整机、磁盘、机房或容量受到保证。</span></div></section>
      <footer class="file-resilience__footer"><span>观测 {{time(data.observed_at)}}</span><span>request_id {{requestId||'—'}}</span><strong>目录、备份、恢复与清理只允许通过宝塔</strong></footer>
    </template>
  </section>
</template>
