import { defineAsyncComponent, type Component } from "vue";

const componentModules: Record<string, () => Promise<{ default: Component }>> = {
  "./DiscoveryOverlay.vue": () => import("./DiscoveryOverlay.vue"),
  "./HomeDashboard.vue": () => import("./HomeDashboard.vue"),
  "./TaskWorkspace.vue": () => import("./TaskWorkspace.vue"),
  "./ApprovalWorkspace.vue": () => import("./ApprovalWorkspace.vue"),
  "./NotificationCenter.vue": () => import("./NotificationCenter.vue"),
  "./AutomationRuleCenter.vue": () => import("./AutomationRuleCenter.vue"),
  "./ReportCenter.vue": () => import("./ReportCenter.vue"),
  "./PersonalCenter.vue": () => import("./PersonalCenter.vue"),
  "./OrganizationAdminCenter.vue": () => import("./OrganizationAdminCenter.vue"),
  "./PlatformDashboard.vue": () => import("./PlatformDashboard.vue"),
  "./PlatformAccountCenter.vue": () => import("./PlatformAccountCenter.vue"),
  "./PlatformManagementCenter.vue": () => import("./PlatformManagementCenter.vue"),
  "./PlatformLogCenter.vue": () => import("./PlatformLogCenter.vue"),
  "./PlatformGovernanceCenter.vue": () => import("./PlatformGovernanceCenter.vue"),
  "./BackupRecoveryCenter.vue": () => import("./BackupRecoveryCenter.vue"),
  "./ReleaseRolloutCenter.vue": () => import("./ReleaseRolloutCenter.vue"),
  "./RuntimeTopologyCenter.vue": () => import("./RuntimeTopologyCenter.vue"),
  "./RedisResilienceCenter.vue": () => import("./RedisResilienceCenter.vue"),
  "./MySqlResilienceCenter.vue": () => import("./MySqlResilienceCenter.vue"),
  "./FileResilienceCenter.vue": () => import("./FileResilienceCenter.vue"),
  "./CrawlerSchedulerCenter.vue": () => import("./CrawlerSchedulerCenter.vue"),
  "./CapacityBoundaryCenter.vue": () => import("./CapacityBoundaryCenter.vue"),
  "./TrendDashboard.vue": () => import("./TrendDashboard.vue"),
  "./ScoreRuleConsole.vue": () => import("./ScoreRuleConsole.vue"),
  "./SelectionJourney.vue": () => import("./SelectionJourney.vue"),
  "./OpportunityWorkspace.vue": () => import("./OpportunityWorkspace.vue"),
  "./CompetitorMonitor.vue": () => import("./CompetitorMonitor.vue"),
  "./SourcingWorkspace.vue": () => import("./SourcingWorkspace.vue"),
  "./CostRuleConsole.vue": () => import("./CostRuleConsole.vue"),
  "./ProviderRuntimeSurface.vue": () => import("./ProviderRuntimeSurface.vue"),
  "./CollectionRuntimeSurface.vue": () => import("./CollectionRuntimeSurface.vue"),
  "./PlatformDataCenter.vue": () => import("./PlatformDataCenter.vue"),
  "./SecurityOperationsCenter.vue": () => import("./SecurityOperationsCenter.vue"),
  "./OpenPlatformCenter.vue": () => import("./OpenPlatformCenter.vue"),
  "./CommercialOperationsCenter.vue": () => import("./CommercialOperationsCenter.vue"),
};

const lazy = (name: string) => {
  const loader = componentModules[`./${name}.vue`];
  if (!loader) throw new Error(`missing lazy component: ${name}`);
  return defineAsyncComponent(loader);
};

export const DiscoveryOverlay = lazy("DiscoveryOverlay");

export const surfaceComponents: Record<string, Component> = {
  "home-dashboard": lazy("HomeDashboard"),
  "task-workspace": lazy("TaskWorkspace"),
  "approval-workspace": lazy("ApprovalWorkspace"),
  "notification-center": lazy("NotificationCenter"),
  "automation-rule-center": lazy("AutomationRuleCenter"),
  "report-center": lazy("ReportCenter"),
  "personal-center": lazy("PersonalCenter"),
  "organization-admin-center": lazy("OrganizationAdminCenter"),
  "platform-dashboard": lazy("PlatformDashboard"),
  "platform-account-center": lazy("PlatformAccountCenter"),
  "platform-management-center": lazy("PlatformManagementCenter"),
  "platform-log-center": lazy("PlatformLogCenter"),
  "platform-governance-center": lazy("PlatformGovernanceCenter"),
  "backup-recovery-center": lazy("BackupRecoveryCenter"),
  "release-rollout-center": lazy("ReleaseRolloutCenter"),
  "runtime-topology-center": lazy("RuntimeTopologyCenter"),
  "redis-resilience-center": lazy("RedisResilienceCenter"),
  "mysql-resilience-center": lazy("MySqlResilienceCenter"),
  "file-resilience-center": lazy("FileResilienceCenter"),
  "crawler-scheduler-center": lazy("CrawlerSchedulerCenter"),
  "capacity-boundary-center": lazy("CapacityBoundaryCenter"),
  "trend-dashboard": lazy("TrendDashboard"),
  "score-rule-console": lazy("ScoreRuleConsole"),
  "selection-journey": lazy("SelectionJourney"),
  "opportunity-workspace": lazy("OpportunityWorkspace"),
  "competitor-monitor": lazy("CompetitorMonitor"),
  "sourcing-workspace": lazy("SourcingWorkspace"),
  "cost-rule-console": lazy("CostRuleConsole"),
  "provider-runtime-surface": lazy("ProviderRuntimeSurface"),
  "collection-runtime-surface": lazy("CollectionRuntimeSurface"),
  "platform-data-center": lazy("PlatformDataCenter"),
  "security-operations-center": lazy("SecurityOperationsCenter"),
  "open-platform-center": lazy("OpenPlatformCenter"),
  "commercial-operations-center": lazy("CommercialOperationsCenter"),
};
