<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import UiStatePanel from './UiStatePanel.vue';
import '../opportunities.css';
type State='loading'|'ready'|'empty'|'error'|'expired'|'forbidden'|'blocked';
type Tab='overview'|'market'|'competition'|'profit'|'risk'|'evidence'|'decisions';
interface Opportunity {id:string;name:string;market:string;category:string|null;source_type:'manual'|'trend_topic';source_ref_id:string|null;owner_id:string|null;lifecycle_status:string;recommendation_status:string;overall_score:number|null;trend_score:number|null;competition_score:number|null;profit_status:string;risk_level:string;confidence:{status:string;score:number|null};evidence_count:number;source_count:number;coverage_status:string;decision_status:string;version:number;updated_at:string}
interface Detail extends Opportunity {score_rule_version:string|null;scored_at:string|null;evidence:Array<{id:string;title:string;publisher:string;canonical_url:string;observed_at:string}>;decisions:Array<{id:string;action:string;reason:string;actor_id:string;created_at:string;opportunity_version:number}>;section_status:{market:string;competition:string;profit:string;risk:string;execution:string}}
const props=defineProps<{apiBaseUrl:string;opportunityId?:string}>(),state=ref<State>('loading'),items=ref<Opportunity[]>([]),detail=ref<Detail|null>(null),total=ref(0),requestId=ref(''),message=ref(''),busy=ref(false),tab=ref<Tab>('overview'),showCreate=ref(false),showDecision=ref(false),decisionAction=ref<'adopt'|'observe'|'reject'>('observe'),decisionReason=ref(''),filters=reactive({q:'',market:'',decision_status:''}),form=reactive({name:'',market:'US',category:'',source_topic_id:''});
const tabs:[Tab,string][]=[['overview','概览'],['market','市场证据'],['competition','竞争对比'],['profit','利润与成本'],['risk','风险分析'],['evidence','证据管理'],['decisions','决策历史']];
const stateFrom=(status:number):State=>status===401?'expired':status===403?'forbidden':[408,425,429,502,503,504].includes(status)?'blocked':'error';
const freshness=(value:string)=>new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));
async function read(path:string){const response=await fetch(`${props.apiBaseUrl}${path}`,{credentials:'include',headers:{accept:'application/json'}}),body=await response.json().catch(()=>null);requestId.value=body?.request_id??'';if(!response.ok){state.value=stateFrom(response.status);throw new Error('read_failed');}return body;}
async function load(){state.value='loading';message.value='';try{if(props.opportunityId){detail.value=(await read(`/opportunities/${props.opportunityId}`)).data;state.value='ready';return;}const params=new URLSearchParams({page:'1',page_size:'20'});for(const[key,value]of Object.entries(filters))if(value)params.set(key,value);const result=await read(`/opportunities?${params}`);items.value=result.data;total.value=result.meta.total;state.value=items.value.length?'ready':'empty';}catch(error){if((error as Error).message!=='read_failed')state.value='blocked';}}
async function write(path:string,body:unknown){busy.value=true;message.value='';try{const response=await fetch(`${props.apiBaseUrl}${path}`,{method:'POST',credentials:'include',headers:{accept:'application/json','content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(body)}),result=await response.json().catch(()=>null);requestId.value=result?.request_id??'';if(!response.ok){message.value=result?.error?.action_hint??'操作未完成。';return null;}return result.data;}catch{message.value='依赖暂不可用，未写入任何状态。';return null;}finally{busy.value=false;}}
async function create(){const result=await write('/opportunities',{name:form.name,market:form.market,category:form.category||null,source_topic_id:form.source_topic_id||null});if(result){showCreate.value=false;window.location.href=`/opportunities/${result.id}`;}}
function startDecision(action:'adopt'|'observe'|'reject'){decisionAction.value=action;decisionReason.value='';showDecision.value=true;}
async function decide(){if(!detail.value)return;const result=await write(`/opportunities/${detail.value.id}/decisions`,{action:decisionAction.value,reason:decisionReason.value,expected_version:detail.value.version});if(result){showDecision.value=false;await load();message.value='决策已记录；原始评分与证据未被改写。';}}
onMounted(()=>{const query=new URLSearchParams(window.location.search);if(!props.opportunityId&&query.get('source_topic_id')){form.source_topic_id=query.get('source_topic_id')??'';form.name=query.get('name')??'';form.market=query.get('market')??'US';form.category=query.get('category')??'';showCreate.value=true;}void load();});
</script>
<template>
 <section class="opportunity-workspace">
  <header class="opportunity-hero"><div><p>DECISION WORKSPACE / M04-02</p><h2>{{opportunityId?'机会详情':'选品机会'}}</h2><span>评分、利润、风险和证据均展示真实状态；缺少下游输入时明确标记数据不足。</span></div><button v-if="!opportunityId" type="button" @click="showCreate=true">＋ 创建机会</button><a v-else href="/opportunities">← 返回机会列表</a></header>
  <p v-if="message" class="opportunity-message" role="status">{{message}} <code v-if="requestId">{{requestId}}</code></p>
  <template v-if="!opportunityId"><form class="opportunity-filters" @submit.prevent="load"><label>市场<input v-model="filters.market" maxlength="40" placeholder="全部市场"></label><label>决策状态<select v-model="filters.decision_status"><option value="">全部状态</option><option value="pending">待决策</option><option value="adopted">已采纳</option><option value="observing">继续观察</option><option value="rejected">已驳回</option></select></label><label>机会名称<input v-model="filters.q" maxlength="200" placeholder="搜索机会"></label><button type="submit">筛选</button></form><UiStatePanel v-if="state!=='ready'" :kind="state" :request-id="requestId" @primary="load" /><section v-else class="opportunity-list"><header><div><p>OPPORTUNITY PIPELINE</p><h3>机会列表</h3></div><span>共 {{total}} 个机会 · 按更新时间排序</span></header><a v-for="item in items" :key="item.id" :href="`/opportunities/${item.id}`"><span class="opportunity-mark">◇</span><span><strong>{{item.name}}</strong><small>{{item.market}} · {{item.category||'未分类'}} · {{freshness(item.updated_at)}}</small></span><dl><div><dt>综合评分</dt><dd>{{item.overall_score??'数据不足'}}</dd></div><div><dt>趋势</dt><dd>{{item.trend_score??'数据不足'}}</dd></div><div><dt>竞争</dt><dd>{{item.competition_score??'数据不足'}}</dd></div><div><dt>利润</dt><dd>{{item.profit_status}}</dd></div><div><dt>风险</dt><dd>{{item.risk_level}}</dd></div></dl><b :data-status="item.decision_status">{{item.decision_status}}</b></a></section></template>
  <template v-else><UiStatePanel v-if="state!=='ready'||!detail" :kind="state" :request-id="requestId" @primary="load" /><article v-else class="opportunity-detail"><header><div><p>{{detail.lifecycle_status}} · {{detail.market}} · {{detail.category||'未分类'}}</p><h3>{{detail.name}}</h3><span>更新 {{freshness(detail.updated_at)}} · v{{detail.version}} · 来源 {{detail.source_type}}</span></div><div><strong>{{detail.overall_score??'—'}}</strong><small>综合评分<br>{{detail.overall_score==null?'数据不足':'已计算'}}</small></div></header><section class="opportunity-decision-bar"><div><span>推荐结论</span><strong>{{detail.recommendation_status}}</strong><small>规则版本：{{detail.score_rule_version??'尚未计算'}} · 置信度：{{detail.confidence.status}}</small></div><button @click="startDecision('adopt')">✓ 采纳</button><button @click="startDecision('observe')">◉ 继续观察</button><button class="reject" @click="startDecision('reject')">× 驳回</button></section><nav class="opportunity-tabs" aria-label="机会详情分区"><button v-for="item in tabs" :key="item[0]" type="button" :aria-current="tab===item[0]?'page':undefined" @click="tab=item[0]">{{item[1]}}</button></nav>
   <section v-if="tab==='overview'" class="opportunity-overview"><article class="opportunity-score"><p>SCORE EXPLANATION</p><h4>机会评分解读</h4><strong>{{detail.overall_score??'数据不足'}}</strong><span>评分规则由 M04-03 交付；当前不会用默认分数补齐。</span><dl><div><dt>市场</dt><dd>{{detail.trend_score??'缺失'}}</dd></div><div><dt>竞争</dt><dd>{{detail.competition_score??'缺失'}}</dd></div><div><dt>置信度</dt><dd>{{detail.confidence.status}}</dd></div></dl></article><article><p>EVIDENCE COVERAGE</p><h4>证据覆盖</h4><strong>{{detail.evidence_count}} 条 / {{detail.source_count}} 个来源</strong><span>覆盖状态：{{detail.coverage_status}}。市场、竞争、成本三类未齐全时不能自动推荐。</span></article><article><p>PROFIT</p><h4>利润与成本</h4><strong>{{detail.profit_status}}</strong><span>数据不足，不能生成可靠 ROI；M04-04 将补充版本化费用与公式。</span></article><article><p>RISK</p><h4>风险</h4><strong>{{detail.risk_level}}</strong><span>尚无适用风险输入，不以“低风险”代替未知。</span></article></section>
   <section v-else-if="tab==='market'" class="opportunity-section"><p>MARKET EVIDENCE</p><h4>市场证据</h4><strong>{{detail.section_status.market}}</strong><span>已关联 {{detail.evidence_count}} 条趋势信号，来自 {{detail.source_count}} 个真实来源。</span></section><section v-else-if="tab==='competition'" class="opportunity-section"><p>COMPETITION</p><h4>竞争对比</h4><strong>数据不足</strong><span>M04-05 尚未写入竞品快照；不显示示例价格、评价或排名。</span></section><section v-else-if="tab==='profit'" class="opportunity-section warning"><p>PROFIT & COST</p><h4>利润与成本</h4><strong>数据不足，不能生成可靠 ROI</strong><span>采购价、物流、平台费、支付手续费、税费或履约成本尚未完整确认。</span></section><section v-else-if="tab==='risk'" class="opportunity-section"><p>RISK</p><h4>风险分析</h4><strong>数据不足</strong><span>合规、侵权、供应、趋势、利润和数据质量风险尚未全部评估。</span></section>
   <section v-else-if="tab==='evidence'" class="opportunity-evidence"><header><div><p>TRACEABLE EVIDENCE</p><h4>证据管理</h4></div><span>{{detail.evidence.length}} 条</span></header><p v-if="!detail.evidence.length" class="opportunity-empty-copy">尚无真实证据；不会展示示例来源。</p><a v-for="item in detail.evidence" :key="item.id" :href="item.canonical_url" target="_blank" rel="noopener noreferrer"><span><strong>{{item.title}}</strong><small>{{item.publisher}} · {{freshness(item.observed_at)}}</small></span><b>查看原文 ↗</b></a></section><section v-else class="opportunity-decisions"><header><div><p>DECISION HISTORY</p><h4>决策历史</h4></div><span>{{detail.decisions.length}} 条</span></header><p v-if="!detail.decisions.length" class="opportunity-empty-copy">尚无决策记录。</p><article v-for="item in detail.decisions" :key="item.id"><b>{{item.action}}</b><div><strong>{{item.reason}}</strong><small>{{freshness(item.created_at)}} · 版本 v{{item.opportunity_version}} · 操作者 {{item.actor_id.slice(0,8)}}…</small></div></article></section>
  </article></template>
  <div v-if="showCreate" class="opportunity-modal" role="dialog" aria-modal="true" aria-labelledby="opportunity-create-title"><form @submit.prevent="create"><header><div><p>NEW CANDIDATE</p><h3 id="opportunity-create-title">创建机会候选</h3></div><button type="button" aria-label="关闭" @click="showCreate=false">×</button></header><label>机会名称<input v-model="form.name" required maxlength="200"></label><div><label>市场<input v-model="form.market" required maxlength="40"></label><label>分类（可选）<input v-model="form.category" maxlength="80"></label></div><label>来源趋势 ID（可选，只接受当前工作区主题）<input v-model="form.source_topic_id" maxlength="36"></label><aside>创建后由宝塔 Node Worker 刷新真实证据覆盖；评分、利润与风险不会自动填充。</aside><footer><button type="button" @click="showCreate=false">取消</button><button type="submit" :disabled="busy">{{busy?'创建中…':'创建机会'}}</button></footer></form></div>
  <div v-if="showDecision&&detail" class="opportunity-modal" role="dialog" aria-modal="true" aria-labelledby="opportunity-decision-title"><form @submit.prevent="decide"><header><div><p>AUDITED DECISION</p><h3 id="opportunity-decision-title">记录{{decisionAction==='adopt'?'采纳':decisionAction==='observe'?'继续观察':'驳回'}}决定</h3></div><button type="button" aria-label="关闭" @click="showDecision=false">×</button></header><label>原因（必填）<textarea v-model="decisionReason" required maxlength="1000"></textarea></label><aside>此决定会覆盖推荐展示，但不会改写原始分数、证据或历史。</aside><footer><button type="button" @click="showDecision=false">取消</button><button type="submit" :disabled="busy">{{busy?'保存中…':'确认记录'}}</button></footer></form></div>
 </section>
</template>
