<script setup lang="ts">
import { computed,onMounted,ref } from "vue";
import "../organization-admin.css";
const props=defineProps<{apiBaseUrl:string;routePath:string;organizationId:string}>(),state=ref("loading"),data=ref<any>(null),summary=ref<any>(null),notice=ref(""),requestId=ref(""),busy=ref(false),secret=ref(""),form=ref<any>({reason:""});
const view=computed(()=>props.routePath==="/org-admin"?"summary":props.routePath.split("/").pop()||"summary"),title=computed(()=>({summary:"组织资料",members:"成员与邀请",roles:"角色与权限",workspaces:"工作区与团队",approvals:"任务与审批",data:"组织数据",tokens:"组织 Token",audit:"组织审计"} as any)[view.value]||"组织资料");
async function api(path:string,init?:RequestInit){const r=await fetch(`${props.apiBaseUrl}${path}`,{credentials:"include",headers:{accept:"application/json","content-type":"application/json",...(init?.method&&init.method!=="GET"?{"idempotency-key":crypto.randomUUID()}:{}),...(init?.headers??{})},...init}),b=await r.json().catch(()=>null);requestId.value=b?.request_id??"";if(!r.ok){state.value=r.status===401?"expired":r.status===403?"forbidden":r.status===429?"rate_limited":r.status===409?"conflict":"error";notice.value=b?.error?.action_hint??"稍后重试。";throw new Error("request_failed");}return b.data;}
async function load(){state.value="loading";notice.value="";try{summary.value=await api("/org/admin/summary");if(view.value==="summary"){data.value=await api("/org/admin/profile");form.value={name:data.value.name,logo_url:data.value.logo_url??"",timezone:data.value.timezone,data_retention_days:data.value.data_retention_days,default_workspace_id:data.value.default_workspace_id,reason:""};}else if(view.value==="audit")data.value=await api(`/organizations/${props.organizationId}/audit-events?limit=50`);else if(view.value==="data")data.value={exports:await api("/report-exports")};else if(view.value==="workspaces"){const [workspaces,teams]=await Promise.all([api("/org/admin/workspaces"),api("/org/admin/teams")]);data.value={workspaces,teams};}else data.value=await api(`/org/admin/${view.value}`);state.value=(Array.isArray(data.value)?data.value.length:Object.keys(data.value??{}).length)?"ready":"empty";}catch{}}
async function submit(path:string,value:any,method="POST"){busy.value=true;try{const result=await api(path,{method,body:JSON.stringify(value)});secret.value=result?.secret??"";notice.value=secret.value?"Token 明文仅显示这一次，请立即保存到受限位置。":"操作已完成并写入审计。";form.value={reason:""};await load();if(result?.secret)secret.value=result.secret;}catch{}finally{busy.value=false;}}
const rows=computed(()=>view.value==="members"?(data.value?.items??[]):view.value==="roles"?(data.value??[]):view.value==="workspaces"?(data.value??[]):view.value==="approvals"?(data.value?.items??[]):view.value==="tokens"?(data.value??[]):view.value==="audit"?(data.value?.items??[]):view.value==="data"?(data.value?.exports??[]):[]),fmt=(v:any)=>v==null?"数据不足":new Date(v).toString()!=="Invalid Date"&&String(v).includes("T")?new Date(v).toLocaleString("zh-CN",{hour12:false}):String(v);
const roleText=(v:string)=>({member:"普通成员",selection_manager:"选品经理",procurement_member:"采购成员",organization_admin:"组织管理员",auditor:"审计员",platform_super_admin:"平台超级管理员",platform_operations_admin:"平台运营管理员",platform_security_admin:"平台安全管理员"}as Record<string,string>)[v]??"自定义角色";
const statusText=(v:string)=>({active:"正常使用",archived:"已停用",disabled:"已停用",locked:"已锁定",pending_delivery:"等待邮件服务",pending_acceptance:"等待接受",accepted:"已接受",expired:"已过期",revoked:"已撤销",rotated:"已轮换",queued:"等待处理",leased:"正在处理",succeeded:"已完成",dead_letter:"多次失败"}as Record<string,string>)[v]??"其他状态";
const scopeText=(v:string)=>({organization:"组织范围",workspace:"工作区范围"}as Record<string,string>)[v]??"指定范围";
const capabilityText=(v:string)=>({"task:read":"查看任务","task:create":"创建任务","task:update":"更新任务","task:assign":"分配任务","trend:read":"查看热点","opportunity:read":"查看选品","opportunity:decide":"提交选品决定","opportunity:approve":"审核选品","competitor:read":"查看竞品","sourcing:read":"查看供应链","supplier_quote:manage":"维护供应商报价","cost:confirm":"确认成本","notification:read":"查看通知","organization:manage":"管理组织","membership:read":"查看成员","membership:manage":"管理成员","workspace:manage":"管理工作区","team:manage":"管理团队","role:read":"查看角色权限","role:manage":"分配角色","organization_token:manage":"管理组织 Token","audit:read":"查看审计","report:read":"查看报表"}as Record<string,string>)[v]??"其他授权";
const summaryText=(v:string)=>({pending:"待处理",approved:"已通过",rejected:"已驳回",expired:"已过期",total:"全部"}as Record<string,string>)[v]??"其他";
onMounted(load);
</script>
<template>
 <section class="org-admin-center" :data-state="state">
  <header class="org-admin-hero"><div><p>组织后台</p><h2>{{title}}</h2><span>管理当前组织的成员、权限、工作区和审计记录。</span></div><button @click="load">刷新数据</button></header>
  <div v-if="notice" class="org-admin-notice">{{notice}} <code v-if="requestId">{{requestId}}</code></div>
  <section v-if="state==='loading'" class="org-admin-state">正在读取当前组织数据…</section>
  <section v-else-if="['error','expired','forbidden','rate_limited','conflict'].includes(state)" class="org-admin-state"><h3>{{state==='expired'?'登录已失效':state==='forbidden'?'无权管理当前组织':state==='rate_limited'?'请求过于频繁':state==='conflict'?'数据版本已变化':'组织后台暂不可用'}}</h3><p>{{notice}}</p><button @click="load">重新加载</button></section>
  <template v-else>
   <section class="org-admin-metrics"><article><span>活动成员</span><b>{{summary?.members?.active??0}}</b><small>共 {{summary?.members?.total??0}}</small></article><article><span>活动工作区</span><b>{{summary?.workspaces?.active??0}}</b><small>共 {{summary?.workspaces?.total??0}}</small></article><article><span>团队</span><b>{{summary?.teams?.active??0}}</b><small>共 {{summary?.teams?.total??0}}</small></article><article><span>待处理审批</span><b>{{summary?.pending_approvals??0}}</b><small>实时汇总</small></article><article><span>有效 Token</span><b>{{summary?.active_tokens??0}}</b><small>不展示明文</small></article><article><span>近 7 日审计</span><b>{{summary?.recent_audit_events??0}}</b><small>组织范围</small></article></section>
   <section v-if="view==='summary'" class="org-admin-grid"><article class="org-admin-card org-admin-profile"><header><div><p>组织基本资料</p><h3>{{data?.name}}</h3></div><i>{{statusText(data?.status)}}</i></header><dl><div><dt>组织标识</dt><dd>{{data?.slug}}</dd></div><div><dt>时区</dt><dd>{{data?.timezone}}</dd></div><div><dt>数据保留</dt><dd>{{data?.data_retention_days}} 天</dd></div><div><dt>默认工作区</dt><dd>{{data?.default_workspace_id}}</dd></div></dl></article><form class="org-admin-card" @submit.prevent="submit('/org/admin/profile',{...form,expected_version:data.version},'PATCH')"><h3>更新组织资料</h3><label>名称<input v-model="form.name" :placeholder="data?.name" required maxlength="120"></label><label>Logo HTTPS 地址<input v-model="form.logo_url" placeholder="https://…"></label><label>时区<input v-model="form.timezone" :placeholder="data?.timezone" required></label><label>数据保留天数<input v-model.number="form.data_retention_days" type="number" min="30" max="3650" :placeholder="String(data?.data_retention_days)"></label><label>默认工作区 ID<input v-model="form.default_workspace_id" :placeholder="data?.default_workspace_id" required></label><label>变更原因<textarea v-model="form.reason" required maxlength="500"></textarea></label><button :disabled="busy">保存并审计</button></form></section>
   <section v-else-if="view==='members'" class="org-admin-grid"><form class="org-admin-card" @submit.prevent="submit('/org/admin/invitations',form)"><h3>邀请成员</h3><label>邮箱<input v-model="form.email" type="email" required></label><label>角色<select v-model="form.role_code" required><option value="member">普通成员</option><option value="selection_manager">选品经理</option><option value="procurement_member">采购成员</option><option value="organization_admin">组织管理员</option><option value="auditor">审计员</option></select></label><label>原因<textarea v-model="form.reason" required></textarea></label><button :disabled="busy">创建邀请</button><small>邮件服务尚未配置时，邀请会显示“等待邮件服务”，不会假装已经发送。</small></form><article class="org-admin-card"><h3>待接受邀请</h3><p v-if="!data?.invitations?.length">暂无待处理邀请。</p><div v-for="x in data?.invitations" :key="x.id" class="org-admin-line"><div><b>{{x.email}}</b><small>{{roleText(x.role_code)}} · {{fmt(x.expires_at)}}</small></div><i>{{statusText(x.status)}}</i></div></article><article class="org-admin-card org-admin-wide"><h3>组织成员</h3><div v-for="x in data?.items" :key="x.id" class="org-admin-line"><div><b>{{x.email}}</b><small>{{x.roles.map(roleText).join('、')||'尚未分配角色'}} · {{x.scopes.map(scopeText).join('、')||'无数据范围'}} · 第 {{x.version}} 版</small></div><i>{{statusText(x.status)}}</i></div></article></section>
   <section v-else-if="view==='roles'" class="org-admin-role-grid"><article v-for="x in rows" :key="x.code" class="org-admin-card"><i>{{roleText(x.code)}}</i><h3>{{x.name}}</h3><p>{{x.description}}</p><div class="org-admin-chips"><span v-for="c in x.capabilities" :key="c">{{capabilityText(c)}}</span></div></article></section>
   <section v-else-if="view==='workspaces'" class="org-admin-grid"><form class="org-admin-card" @submit.prevent="submit('/org/admin/workspaces',form)"><h3>创建工作区</h3><label>名称<input v-model="form.name" required></label><label>英文标识<input v-model="form.slug" pattern="[a-z0-9-]+" required></label><label>创建原因<textarea v-model="form.reason" required></textarea></label><button :disabled="busy">创建工作区</button></form><form class="org-admin-card" @submit.prevent="submit('/org/admin/teams',form)"><h3>创建团队</h3><label>名称<input v-model="form.name" required></label><label>负责人（成员 ID，可选）<input v-model="form.lead_membership_id"></label><label>默认工作流程（可选）<input v-model="form.default_workflow_key"></label><label>创建原因<textarea v-model="form.reason" required></textarea></label><button :disabled="busy">创建团队</button></form><article class="org-admin-card"><h3>工作区</h3><div v-for="x in data?.workspaces" :key="x.id" class="org-admin-line"><div><b>{{x.name}}</b><small>{{x.slug}} · {{x.member_count}} 名成员 · 第 {{x.version}} 版</small></div><i>{{statusText(x.status)}}</i></div></article><article class="org-admin-card"><h3>团队</h3><div v-for="x in data?.teams" :key="x.id" class="org-admin-line"><div><b>{{x.name}}</b><small>{{x.member_count}} 名成员 · 负责人 {{x.lead_email||'未设置'}}</small></div><i>{{statusText(x.status)}}</i></div></article></section>
   <section v-else-if="view==='approvals'" class="org-admin-card"><div class="org-admin-summary-row"><span v-for="(v,k) in data?.summary" :key="k"><b>{{v}}</b><small>{{summaryText(String(k))}}</small></span></div><div v-for="x in rows" :key="x.id" class="org-admin-line"><div><b>业务申请 · {{x.resource_id}}</b><small>当前步骤 {{x.current_node_key}} · {{fmt(x.requested_at)}}</small></div><i>{{statusText(x.status)}}</i></div><p v-if="!rows.length">暂无组织级审批记录。</p></section>
   <section v-else-if="view==='tokens'" class="org-admin-grid"><form class="org-admin-card" @submit.prevent="submit('/org/admin/tokens',{...form,scopes:form.scopes||['task:read'],ttl_days:form.ttl_days||90})"><h3>创建只读访问令牌</h3><label>名称<input v-model="form.name" required></label><label>允许查看的内容<select v-model="form.scopes" multiple required><option value="task:read">任务</option><option value="trend:read">热点趋势</option><option value="opportunity:read">选品机会</option><option value="report:read">报表</option></select></label><label>有效天数<input v-model.number="form.ttl_days" type="number" min="1" max="365" value="90"></label><label>创建原因<textarea v-model="form.reason" required></textarea></label><button :disabled="busy">创建令牌</button></form><article class="org-admin-card"><h3>令牌明文</h3><code v-if="secret" class="org-admin-secret">{{secret}}</code><p v-else>明文只在创建或轮换成功后显示一次。</p></article><article class="org-admin-card org-admin-wide"><div v-for="x in rows" :key="x.id" class="org-admin-line"><div><b>{{x.name}}</b><small>{{x.token_prefix}}… · {{x.scopes.map(capabilityText).join('、')}} · 到期 {{fmt(x.expires_at)}}</small></div><i>{{statusText(x.status)}}</i></div><p v-if="!rows.length">尚无组织访问令牌。</p></article></section>
   <section v-else class="org-admin-card"><div v-for="x in rows" :key="x.id" class="org-admin-line"><div><b>{{x.action||x.report_type}}</b><small>{{x.resource_type||x.status}} · {{fmt(x.occurred_at||x.created_at)}}</small></div><i>{{x.outcome||x.status}}</i></div><p v-if="!rows.length">暂无记录；不会用示例数据补齐。</p></section>
  </template>
 </section>
</template>
