<script setup lang="ts">
import { computed,onMounted,ref } from "vue";
import "../organization-admin.css";
const props=defineProps<{apiBaseUrl:string;routePath:string;organizationId:string}>(),state=ref("loading"),data=ref<any>(null),summary=ref<any>(null),notice=ref(""),requestId=ref(""),busy=ref(false),secret=ref(""),form=ref<any>({reason:""});
const view=computed(()=>props.routePath==="/org-admin"?"summary":props.routePath.split("/").pop()||"summary"),title=computed(()=>({summary:"组织资料",members:"成员与邀请",roles:"角色与权限",workspaces:"工作区与团队",approvals:"任务与审批",data:"组织数据",tokens:"组织 Token",audit:"组织审计"} as any)[view.value]||"组织资料");
async function api(path:string,init?:RequestInit){const r=await fetch(`${props.apiBaseUrl}${path}`,{credentials:"include",headers:{accept:"application/json","content-type":"application/json",...(init?.method&&init.method!=="GET"?{"idempotency-key":crypto.randomUUID()}:{}),...(init?.headers??{})},...init}),b=await r.json().catch(()=>null);requestId.value=b?.request_id??"";if(!r.ok){state.value=r.status===401?"expired":r.status===403?"forbidden":r.status===429?"rate_limited":r.status===409?"conflict":"error";notice.value=b?.error?.action_hint??"稍后重试。";throw new Error("request_failed");}return b.data;}
async function load(){state.value="loading";notice.value="";try{summary.value=await api("/org/admin/summary");if(view.value==="summary"){data.value=await api("/org/admin/profile");form.value={name:data.value.name,logo_url:data.value.logo_url??"",timezone:data.value.timezone,data_retention_days:data.value.data_retention_days,default_workspace_id:data.value.default_workspace_id,reason:""};}else if(view.value==="audit")data.value=await api(`/organizations/${props.organizationId}/audit-events?limit=50`);else if(view.value==="data")data.value={exports:await api("/report-exports")};else if(view.value==="workspaces"){const [workspaces,teams]=await Promise.all([api("/org/admin/workspaces"),api("/org/admin/teams")]);data.value={workspaces,teams};}else data.value=await api(`/org/admin/${view.value}`);state.value=(Array.isArray(data.value)?data.value.length:Object.keys(data.value??{}).length)?"ready":"empty";}catch{}}
async function submit(path:string,value:any,method="POST"){busy.value=true;try{const result=await api(path,{method,body:JSON.stringify(value)});secret.value=result?.secret??"";notice.value=secret.value?"Token 明文仅显示这一次，请立即保存到受限位置。":"操作已完成并写入审计。";form.value={reason:""};await load();if(result?.secret)secret.value=result.secret;}catch{}finally{busy.value=false;}}
const rows=computed(()=>view.value==="members"?(data.value?.items??[]):view.value==="roles"?(data.value??[]):view.value==="workspaces"?(data.value??[]):view.value==="approvals"?(data.value?.items??[]):view.value==="tokens"?(data.value??[]):view.value==="audit"?(data.value?.items??[]):view.value==="data"?(data.value?.exports??[]):[]),fmt=(v:any)=>v==null?"数据不足":new Date(v).toString()!=="Invalid Date"&&String(v).includes("T")?new Date(v).toLocaleString("zh-CN",{hour12:false}):String(v);
onMounted(load);
</script>
<template>
 <section class="org-admin-center" :data-state="state">
  <header class="org-admin-hero"><div><p>ADMIN CONTROL / M06-01</p><h2>{{title}}</h2><span>所有数量、状态和审计均来自当前组织真实数据。</span></div><button @click="load">刷新数据</button></header>
  <div v-if="notice" class="org-admin-notice">{{notice}} <code v-if="requestId">{{requestId}}</code></div>
  <section v-if="state==='loading'" class="org-admin-state">正在读取当前组织数据…</section>
  <section v-else-if="['error','expired','forbidden','rate_limited','conflict'].includes(state)" class="org-admin-state"><h3>{{state==='expired'?'登录已失效':state==='forbidden'?'无权管理当前组织':state==='rate_limited'?'请求过于频繁':state==='conflict'?'数据版本已变化':'组织后台暂不可用'}}</h3><p>{{notice}}</p><button @click="load">重新加载</button></section>
  <template v-else>
   <section class="org-admin-metrics"><article><span>活动成员</span><b>{{summary?.members?.active??0}}</b><small>共 {{summary?.members?.total??0}}</small></article><article><span>活动工作区</span><b>{{summary?.workspaces?.active??0}}</b><small>共 {{summary?.workspaces?.total??0}}</small></article><article><span>团队</span><b>{{summary?.teams?.active??0}}</b><small>共 {{summary?.teams?.total??0}}</small></article><article><span>待处理审批</span><b>{{summary?.pending_approvals??0}}</b><small>实时汇总</small></article><article><span>有效 Token</span><b>{{summary?.active_tokens??0}}</b><small>不展示明文</small></article><article><span>近 7 日审计</span><b>{{summary?.recent_audit_events??0}}</b><small>组织范围</small></article></section>
   <section v-if="view==='summary'" class="org-admin-grid"><article class="org-admin-card org-admin-profile"><header><div><p>ORGANIZATION PROFILE</p><h3>{{data?.name}}</h3></div><i>{{data?.status}}</i></header><dl><div><dt>组织标识</dt><dd>{{data?.slug}}</dd></div><div><dt>时区</dt><dd>{{data?.timezone}}</dd></div><div><dt>数据保留</dt><dd>{{data?.data_retention_days}} 天</dd></div><div><dt>默认工作区</dt><dd>{{data?.default_workspace_id}}</dd></div></dl></article><form class="org-admin-card" @submit.prevent="submit('/org/admin/profile',{...form,expected_version:data.version},'PATCH')"><h3>更新组织资料</h3><label>名称<input v-model="form.name" :placeholder="data?.name" required maxlength="120"></label><label>Logo HTTPS 地址<input v-model="form.logo_url" placeholder="https://…"></label><label>时区<input v-model="form.timezone" :placeholder="data?.timezone" required></label><label>数据保留天数<input v-model.number="form.data_retention_days" type="number" min="30" max="3650" :placeholder="String(data?.data_retention_days)"></label><label>默认工作区 ID<input v-model="form.default_workspace_id" :placeholder="data?.default_workspace_id" required></label><label>变更原因<textarea v-model="form.reason" required maxlength="500"></textarea></label><button :disabled="busy">保存并审计</button></form></section>
   <section v-else-if="view==='members'" class="org-admin-grid"><form class="org-admin-card" @submit.prevent="submit('/org/admin/invitations',form)"><h3>邀请成员</h3><label>邮箱<input v-model="form.email" type="email" required></label><label>角色<select v-model="form.role_code" required><option value="member">普通成员</option><option value="selection_manager">选品经理</option><option value="procurement_member">采购成员</option><option value="organization_admin">组织管理员</option><option value="auditor">审计员</option></select></label><label>原因<textarea v-model="form.reason" required></textarea></label><button :disabled="busy">创建待投递邀请</button><small>邮件 Provider 未确认，不伪造已发送状态。</small></form><article class="org-admin-card"><h3>待接受邀请</h3><p v-if="!data?.invitations?.length">暂无待处理邀请。</p><div v-for="x in data?.invitations" :key="x.id" class="org-admin-line"><div><b>{{x.email}}</b><small>{{x.role_code}} · {{fmt(x.expires_at)}}</small></div><i>{{x.status}}</i></div></article><article class="org-admin-card org-admin-wide"><h3>组织成员</h3><div v-for="x in data?.items" :key="x.id" class="org-admin-line"><div><b>{{x.email}}</b><small>{{x.roles.join(', ')||'尚未分配角色'}} · {{x.scopes.join(', ')||'无数据范围'}} · v{{x.version}}</small></div><i>{{x.status}}</i></div></article></section>
   <section v-else-if="view==='roles'" class="org-admin-role-grid"><article v-for="x in rows" :key="x.code" class="org-admin-card"><i>{{x.code}}</i><h3>{{x.name}}</h3><p>{{x.description}}</p><div class="org-admin-chips"><span v-for="c in x.capabilities" :key="c">{{c}}</span></div></article></section>
   <section v-else-if="view==='workspaces'" class="org-admin-grid"><form class="org-admin-card" @submit.prevent="submit('/org/admin/workspaces',form)"><h3>创建工作区</h3><label>名称<input v-model="form.name" required></label><label>标识<input v-model="form.slug" pattern="[a-z0-9-]+" required></label><label>原因<textarea v-model="form.reason" required></textarea></label><button :disabled="busy">创建工作区</button></form><form class="org-admin-card" @submit.prevent="submit('/org/admin/teams',form)"><h3>创建团队</h3><label>名称<input v-model="form.name" required></label><label>负责人成员 ID<input v-model="form.lead_membership_id"></label><label>默认工作流键<input v-model="form.default_workflow_key"></label><label>原因<textarea v-model="form.reason" required></textarea></label><button :disabled="busy">创建团队</button></form><article class="org-admin-card"><h3>工作区</h3><div v-for="x in data?.workspaces" :key="x.id" class="org-admin-line"><div><b>{{x.name}}</b><small>{{x.slug}} · {{x.member_count}} 名成员 · v{{x.version}}</small></div><i>{{x.status}}</i></div></article><article class="org-admin-card"><h3>团队</h3><div v-for="x in data?.teams" :key="x.id" class="org-admin-line"><div><b>{{x.name}}</b><small>{{x.member_count}} 名成员 · 负责人 {{x.lead_email||'未设置'}}</small></div><i>{{x.status}}</i></div></article></section>
   <section v-else-if="view==='approvals'" class="org-admin-card"><div class="org-admin-summary-row"><span v-for="(v,k) in data?.summary" :key="k"><b>{{v}}</b><small>{{k}}</small></span></div><div v-for="x in rows" :key="x.id" class="org-admin-line"><div><b>{{x.resource_type}} · {{x.resource_id}}</b><small>{{x.current_node_key}} · {{fmt(x.requested_at)}}</small></div><i>{{x.status}}</i></div><p v-if="!rows.length">暂无组织级审批记录。</p></section>
   <section v-else-if="view==='tokens'" class="org-admin-grid"><form class="org-admin-card" @submit.prevent="submit('/org/admin/tokens',{...form,scopes:form.scopes||['task:read'],ttl_days:form.ttl_days||90})"><h3>创建组织 Token</h3><label>名称<input v-model="form.name" required></label><label>只读 scope<select v-model="form.scopes" multiple required><option value="task:read">task:read</option><option value="trend:read">trend:read</option><option value="opportunity:read">opportunity:read</option><option value="report:read">report:read</option></select></label><label>有效天数<input v-model.number="form.ttl_days" type="number" min="1" max="365" value="90"></label><label>原因<textarea v-model="form.reason" required></textarea></label><button :disabled="busy">创建 Token</button></form><article class="org-admin-card"><h3>Token 明文</h3><code v-if="secret" class="org-admin-secret">{{secret}}</code><p v-else>明文只在创建或轮换成功后显示一次。</p></article><article class="org-admin-card org-admin-wide"><div v-for="x in rows" :key="x.id" class="org-admin-line"><div><b>{{x.name}}</b><small>{{x.token_prefix}}… · {{x.scopes.join(', ')}} · 到期 {{fmt(x.expires_at)}}</small></div><i>{{x.status}}</i></div><p v-if="!rows.length">尚无组织 Token。</p></article></section>
   <section v-else class="org-admin-card"><div v-for="x in rows" :key="x.id" class="org-admin-line"><div><b>{{x.action||x.report_type}}</b><small>{{x.resource_type||x.status}} · {{fmt(x.occurred_at||x.created_at)}}</small></div><i>{{x.outcome||x.status}}</i></div><p v-if="!rows.length">暂无记录；不会用示例数据补齐。</p></section>
  </template>
 </section>
</template>
