<script setup lang="ts">
import{computed,onMounted,ref}from"vue";
const props=defineProps<{apiBaseUrl:string}>();
type State="loading"|"ready"|"empty"|"expired"|"forbidden"|"rate_limited"|"blocked";
const state=ref<State>("loading"),data=ref<any>(null),windowCode=ref("24h"),requestId=ref(""),hint=ref("");
const stateText=computed(()=>({loading:["正在聚合平台运行事实","读取来源、任务、质量、文件和告警；不会展示凭证或 Cookie。"],empty:["当前时间窗没有运行数据","可扩大时间窗；组织与账号总量仍来自当前数据库。"],expired:["登录已失效","重新登录后返回平台驾驶舱。"],forbidden:["你没有此项权限","需要平台运营管理员或平台超级管理员角色。"],rate_limited:["请求过于频繁","稍后再刷新驾驶舱。"],blocked:["驾驶舱依赖暂时受阻","运维人员可在宝塔检查 Node API 与 MySQL。"],ready:["",""]}as Record<State,string[]>)[state.value]);
const percent=(v:number|null)=>v==null?"暂无终态":`${v.toFixed(1)}%`,bytes=(v:number)=>{if(v<1024)return`${v} B`;if(v<1048576)return`${(v/1024).toFixed(1)} KB`;if(v<1073741824)return`${(v/1048576).toFixed(1)} MB`;return`${(v/1073741824).toFixed(1)} GB`;},short=(v:string)=>v?`${v.slice(0,8)}…`:"—";
async function load(){state.value="loading";requestId.value="";try{const r=await fetch(`${props.apiBaseUrl}/platform/dashboard?window=${windowCode.value}`,{credentials:"include",headers:{accept:"application/json"}}),b=await r.json().catch(()=>null);requestId.value=b?.request_id??"";hint.value=b?.error?.action_hint??"";if(!r.ok){state.value=r.status===401?"expired":r.status===403?"forbidden":r.status===429?"rate_limited":"blocked";return;}data.value=b.data;const operational=b.data.queues.length+b.data.provider_health.reduce((n:number,p:any)=>n+p.observed_count,0)+b.data.alerts.length;state.value=operational===0?"empty":"ready";}catch{state.value="blocked";}}
onMounted(load);
</script>
<template><section class="platform-dashboard" aria-live="polite">
 <div class="platform-dashboard-toolbar"><div><p>PLATFORM OPERATIONS / REAL FACTS</p><h2>平台运行全景</h2><span>所有指标来自 MySQL 当前读模型；没有样本时保留“未知”，不补造百分比。</span></div><label>时间窗<select v-model="windowCode" @change="load"><option value="15m">最近 15 分钟</option><option value="24h">最近 24 小时</option><option value="7d">最近 7 天</option><option value="30d">最近 30 天</option></select></label><button type="button" @click="load">刷新</button></div>
 <section v-if="state!=='ready'" class="platform-dashboard-state" :data-kind="state"><span>{{state==='loading'?'···':'!'}}</span><h3>{{stateText[0]}}</h3><p>{{stateText[1]}}</p><small v-if="hint">{{hint}}</small><code v-if="requestId">request_id: {{requestId}}</code><button v-if="!['loading','expired','forbidden'].includes(state)" type="button" @click="load">重新读取</button><a v-if="state==='expired'" href="/login">重新登录</a></section>
 <template v-else-if="data"><div class="platform-kpis"><article><span>活动组织</span><strong>{{data.summary.active_organizations}}</strong><small>当前 active</small></article><article><span>活动用户</span><strong>{{data.summary.active_users}}</strong><small>当前 active</small></article><article><span>启用来源</span><strong>{{data.summary.enabled_providers}}</strong><small>enabled</small></article><article><span>任务成功率</span><strong>{{percent(data.summary.task_success_rate)}}</strong><small>仅终态任务</small></article><article><span>队列积压</span><strong>{{data.summary.queue_backlog}}</strong><small>处理中与待处理</small></article><article><span>开放告警</span><strong>{{data.summary.open_alerts}}</strong><small>错误、租约与质量</small></article></div>
 <div class="platform-dashboard-grid"><section><header><h3>来源健康</h3><span>{{data.provider_health.length}} 个启用来源</span></header><div v-if="!data.provider_health.length" class="platform-inline-empty">尚无启用来源</div><table v-else><thead><tr><th>来源</th><th>状态</th><th>成功 / 失败</th><th>最近观测</th></tr></thead><tbody><tr v-for="p in data.provider_health" :key="p.id"><td><b>{{p.name}}</b><small>{{p.code}}</small></td><td><i :data-health="p.status">{{p.status==='healthy'?'健康':p.status==='degraded'?'降级':'未知'}}</i></td><td>{{p.success_count}} / {{p.failed_count}}</td><td>{{p.last_observed_at?new Date(p.last_observed_at).toLocaleString():'无样本'}}</td></tr></tbody></table></section>
 <section><header><h3>系统信号</h3><span>阈值状态</span></header><ul class="platform-signals"><li v-for="s in data.health_signals" :key="s.code"><i :data-health="s.status"></i><span>{{s.code}}</span><strong>{{s.value}}</strong></li></ul><dl class="platform-storage"><div><dt>活动文件体积</dt><dd>{{bytes(data.summary.storage_bytes)}}</dd></div><div><dt>窗内文件增长</dt><dd>+{{bytes(data.summary.file_growth_bytes)}}</dd></div></dl></section>
 <section><header><h3>任务与队列</h3><span>{{windowCode}}</span></header><div class="platform-queue-bars"><div v-for="q in data.queues" :key="q.status"><span>{{q.status}}</span><b :style="{width:`${Math.max(4,Math.min(100,q.total*10))}%`}"></b><strong>{{q.total}}</strong></div><p v-if="!data.queues.length">当前没有积压或失败任务</p></div></section>
 <section><header><h3>告警与错误</h3><span>最近 {{data.alerts.length}} 条</span></header><ul class="platform-alerts"><li v-for="a in data.alerts" :key="a.id"><i :data-health="a.severity"></i><div><b>{{a.kind}} · {{a.code}}</b><small>{{short(a.organization_id)}} / {{short(a.workspace_id)}} · {{new Date(a.observed_at).toLocaleString()}}</small></div></li><li v-if="!data.alerts.length">当前没有开放告警</li></ul></section></div>
 <footer class="platform-observed">观测时间 {{new Date(data.observed_at).toLocaleString()}} · request_id {{requestId}}</footer></template>
</section></template>
