window.AUTOMATION_FORM_FIELDS = [
  {
    id: "name",
    binding: "form.name",
    label: "规则名称",
    tag: "input",
    required: true,
    maxlength: 200,
    hint: "必填，用名称区分这条规则。",
  },
  {
    id: "trigger_event_type",
    binding: "form.trigger_event_type",
    label: "触发事件",
    tag: "select",
    options: [
      "approval.overdue",
      "approval.node.rejected",
      "competitor.alert.queued",
      "task.created",
    ],
    hint: "选择已有事务事件；任务事件不能再次创建任务。",
  },
  {
    id: "condition_severity",
    binding: "form.condition_severity",
    label: "严重程度",
    tag: "select",
    options: ["any", "info", "warning", "critical"],
    hint: "任意表示不按严重程度限制，不代表没有事件条件。",
  },
  {
    id: "action_type",
    binding: "form.action_type",
    label: "后续动作",
    tag: "select",
    options: ["notify_owner", "create_task"],
    hint: "仅通知负责人或创建人工任务，不自动作出业务决定。",
  },
  {
    id: "owner_id",
    binding: "form.owner_id",
    label: "规则负责人",
    tag: "select",
    required: true,
    hint: "必填，只能选择当前工作区返回的成员。",
  },
  {
    id: "action_assignee_id",
    binding: "form.action_assignee_id",
    label: "任务负责人",
    tag: "select",
    required: true,
    hint: "创建人工任务时必填；通知动作不提交任务负责人。",
  },
  {
    id: "action_title",
    binding: "form.action_title",
    label: "动作标题",
    tag: "input",
    required: true,
    maxlength: 200,
    hint: "必填，写清需要人工跟进的事项。",
  },
  {
    id: "reason",
    binding: "editReason",
    label: "修改原因",
    tag: "textarea",
    required: true,
    maxlength: 500,
    hint: "编辑时必填；界面上限500，服务上限1000，保留现有差异。仅改原因不清除规则预览。",
  },
  {
    id: "rate_limit_count",
    binding: "form.rate_limit_count",
    label: "最多执行次数",
    tag: "input",
    type: "number",
    required: true,
    min: 1,
    max: 1000,
    hint: "必填，1–1000 的整数；是执行上限，不是已执行次数。",
  },
  {
    id: "rate_limit_window_minutes",
    binding: "form.rate_limit_window_minutes",
    label: "时间窗（分钟）",
    tag: "input",
    type: "number",
    required: true,
    min: 1,
    max: 1440,
    hint: "必填，1–1440 的整数，单位为分钟。",
  },
];
