window.CREDENTIAL_C_DATA = {
  original: {
    provider: {
      id: "00000000-0000-4000-8000-000000000802",
      code: "browser_source",
      name: "登录页来源",
      target_url: "https://example.test/login",
      access_mode: "authenticated_browser",
    },
    secondProvider: {
      id: "00000000-0000-4000-8000-000000000805",
      code: "second_browser_source",
      name: "第二登录来源",
      target_url: "https://second.example.test/login",
      access_mode: "authenticated_browser",
    },
    asset: {
      id: "00000000-0000-4000-8000-000000000803",
      provider_id: "00000000-0000-4000-8000-000000000802",
      name: "北美浏览器档案",
      kind: "browser_profile",
      status: "active",
      key_version: "v1",
      fingerprint: "0123456789abcdef",
      expires_at: null,
      rotated_at: "2026-08-07T18:00:00.000Z",
      version: 2,
      updated_at: "2026-08-07T18:00:00.000Z",
    },
    profile: {
      id: "00000000-0000-4000-8000-000000000804",
      provider_id: "00000000-0000-4000-8000-000000000802",
      credential_asset_id: "00000000-0000-4000-8000-000000000803",
      code: "browser_us_a",
      name: "北美采集档案 A",
      browser_family: "chromium",
      locale: "en-US",
      timezone: "America/Los_Angeles",
      status: "disabled",
      version: 1,
      updated_at: "2026-08-07T18:00:00.000Z",
    },
  },
  clock: "2026-09-09T04:00:00.000Z",
  checks: [
    "Actual compatibility at exact expiry, active/revoked candidates and disabled manual profile defaults; ready is metadata only",
    "Ten actual initial/preserved three-read failure paths; atomic snapshots, single flight, 12-second timer callback and unmount abort, not real elapsed timeout/KeepAlive",
    "Actual create/rotate/manual-profile/revoke exact bodies and duplicate guards; errors retain editor and clear asset secret, no real writes",
    "All three actual login modes: exact independent asset then active zh-CN/Asia-Shanghai profile bodies; partial success clears payload, stays open, no automatic refresh or second asset",
    "Reproduced actual first login write failure retaining material and old failed write clearing a newly opened asset secret; no protection inferred",
    "Reproduced actual delayed in-memory file completion repopulating closed editor and source switch retaining old payload; no OS file read",
    "Actual file extension/byte boundaries and inert same-window helper reply: 15-second timer and delayed closed-editor repopulation; no extension called",
    "Actual mounted exact source deep link and invalid-ID fallback to first authenticated provider; not router history lifecycle proof",
    "Source review: asset/rotate message exists; profile message absent. UTC rotation initial value/local save and service null fallback remain unresolved contracts, not fixed",
  ],
  sourcePaths: [
    "apps/web/src/components/CredentialAssetCenter.vue",
    "apps/web/src/components/ConfirmDialog.vue",
    "apps/web/src/components/ResponsiveDataView.vue",
    "apps/web/src/components/TableViewControls.vue",
    "apps/web/src/ui/state-contract.ts",
    "apps/api/src/credential-asset-service.ts",
    "apps/api/src/credential-asset-routes.ts",
    "apps/api/src/mysql-credential-asset-repository.ts",
    "tests/e2e/m03-02-credential-assets.spec.ts",
  ],
};
