window.INSIGHTS_C_DATA = {
  version: "INSIGHTS-C-r1",
  facts: {
    detail: {
      id: "00000000-0000-4000-8000-000000000434",
      name: "便携式智能净水杯机会",
      market: "US",
      category: "outdoor",
      source_type: "trend_topic",
      source_ref_id: null,
      owner_id: "00000000-0000-4000-8000-000000000437",
      lifecycle_status: "ready",
      lifecycle_entered_at: "2026-08-07T08:30:00.000Z",
      lifecycle_dwell_seconds: 14400,
      recommendation_status: "recommend",
      overall_score: 80.2,
      trend_score: 82,
      competition_score: 70,
      profit_status: "insufficient_data",
      risk_level: "unknown",
      confidence: {
        status: "measured",
        score: 100,
      },
      evidence_count: 8,
      source_count: 3,
      coverage_status: "complete",
      decision_status: "pending",
      version: 7,
      updated_at: "2026-08-07T12:30:00.000Z",
      score_rule_version: "org-v1",
      scored_at: "2026-08-07T12:30:00.000Z",
      latest_score_run: {
        id: "00000000-0000-4000-8000-000000000435",
        status: "calculated",
        coverage_percent: 100,
        confidence_score: 100,
        recommendation_status: "recommend",
        missing_fields: [],
        scored_at: "2026-08-07T12:30:00.000Z",
      },
      score_components: [
        {
          dimension_code: "market_demand",
          weight_percent: 40,
          input_score: 82,
          weighted_score: 32.8,
          evidence_ids: ["00000000-0000-4000-8000-000000000435"],
          missing_fields: [],
        },
        {
          dimension_code: "competition",
          weight_percent: 30,
          input_score: 70,
          weighted_score: 21,
          evidence_ids: ["00000000-0000-4000-8000-000000000436"],
          missing_fields: [],
        },
        {
          dimension_code: "profit",
          weight_percent: 30,
          input_score: 88,
          weighted_score: 26.4,
          evidence_ids: ["00000000-0000-4000-8000-000000000434"],
          missing_fields: [],
        },
      ],
      adoption_blockers: [
        {
          code: "evidence_insufficient",
          status: "cleared",
          progress_percent: 100,
          next_action: "证据覆盖阻断已解除。",
          task_id: null,
          task_status: null,
          score_job_status: "succeeded",
        },
        {
          code: "recommendation_insufficient",
          status: "cleared",
          progress_percent: null,
          next_action: "推荐结论阻断已解除。",
          task_id: null,
          task_status: null,
          score_job_status: "succeeded",
        },
      ],
      redecision_ready: false,
      evidence: [],
      decisions: [],
      section_status: {
        market: "covered",
        competition: "covered",
        profit: "insufficient_data",
        risk: "insufficient_data",
        execution: "not_available",
      },
    },
    dimensions: [
      {
        code: "market_demand",
        label: "市场需求",
        weight: 40,
        required: true,
        evidence_group: "market",
      },
      {
        code: "competition",
        label: "竞争",
        weight: 30,
        required: true,
        evidence_group: "competition",
      },
      {
        code: "profit",
        label: "利润",
        weight: 30,
        required: true,
        evidence_group: "cost",
      },
    ],
  },
  competitors: [
    {
      id: "00000000-0000-4000-8000-000000000505",
      opportunity_id: "00000000-0000-4000-8000-000000000434",
      market: "US",
      source_site: "Amazon US",
      external_id: "B0SCOUTOPS",
      title:
        "Wallet Case for iPhone 16,RFID Blocking,Crossbody,Purple | 8 Card Slots|Magnetic|Kickstand|Detachable Wallet",
      snapshot_count: 2,
      latest_snapshot: {
        current_price: 26.99,
        currency: "USD",
        rating_value: 4.6,
        review_count: 825,
        captured_at: "2026-08-08T12:01:00.000Z",
        freshness: "fresh",
      },
    },
  ],
  downstream: {
    competitors: 1,
    snapshots: 2,
    searches: 2,
    suppliers: 5,
  },
  intents: {
    competitor: {
      method: "POST",
      path: "/opportunities/00000000-0000-4000-8000-000000000434/competitor-discovery",
      body: {},
    },
    supplier: {
      method: "POST",
      path: "/sourcing/searches",
      body: {
        input_type: "opportunity",
        input_ref: "00000000-0000-4000-8000-000000000434",
      },
    },
    score: {
      method: "POST",
      path: "/opportunities/00000000-0000-4000-8000-000000000434/score-runs",
      body: {
        expected_version: 7,
      },
    },
  },
  outputs: {
    both: {
      calls: ["/competitors", "/sourcing/searches"],
      downstream: {
        competitors: 1,
        snapshots: 2,
        searches: 2,
        suppliers: 5,
      },
      competitors: [
        {
          id: "00000000-0000-4000-8000-000000000505",
          opportunity_id: "00000000-0000-4000-8000-000000000434",
          market: "US",
          source_site: "Amazon US",
          external_id: "B0SCOUTOPS",
          title:
            "Wallet Case for iPhone 16,RFID Blocking,Crossbody,Purple | 8 Card Slots|Magnetic|Kickstand|Detachable Wallet",
          snapshot_count: 2,
          latest_snapshot: {
            current_price: 26.99,
            currency: "USD",
            rating_value: 4.6,
            review_count: 825,
            captured_at: "2026-08-08T12:01:00.000Z",
            freshness: "fresh",
          },
        },
      ],
      state: "ready",
    },
    competitor: {
      calls: ["/competitors"],
      downstream: {
        competitors: 1,
        snapshots: 2,
        searches: 0,
        suppliers: 0,
      },
      competitors: [
        {
          id: "00000000-0000-4000-8000-000000000505",
          opportunity_id: "00000000-0000-4000-8000-000000000434",
          market: "US",
          source_site: "Amazon US",
          external_id: "B0SCOUTOPS",
          title:
            "Wallet Case for iPhone 16,RFID Blocking,Crossbody,Purple | 8 Card Slots|Magnetic|Kickstand|Detachable Wallet",
          snapshot_count: 2,
          latest_snapshot: {
            current_price: 26.99,
            currency: "USD",
            rating_value: 4.6,
            review_count: 825,
            captured_at: "2026-08-08T12:01:00.000Z",
            freshness: "fresh",
          },
        },
      ],
      state: "ready",
    },
    supplier: {
      calls: ["/sourcing/searches"],
      downstream: {
        competitors: 0,
        snapshots: 0,
        searches: 2,
        suppliers: 5,
      },
      competitors: [],
      state: "ready",
    },
    neither: {
      calls: [],
      downstream: {
        competitors: 0,
        snapshots: 0,
        searches: 0,
        suppliers: 0,
      },
      competitors: [],
      state: "ready",
    },
    supplierFailure: {
      calls: ["/competitors", "/sourcing/searches"],
      downstream: {
        old: true,
      },
      competitors: ["old"],
      state: "error",
    },
  },
  actionResults: {
    "competitor-true": {
      reads: 0,
      message: "Amazon 竞品采集已排队，任务编号 isolated-task-layout。",
    },
    "competitor-false": {
      reads: 0,
      message: "",
    },
    "supplier-true": {
      reads: 0,
      message: "公开供应商采集已排队，任务编号 isolated-task-layout。",
    },
    "supplier-false": {
      reads: 0,
      message: "",
    },
    "score-true": {
      reads: 1,
      message: "评分任务已进入宝塔 Node Worker 队列；完成后刷新可见新运行记录。",
    },
    "score-false": {
      reads: 0,
      message: "",
    },
  },
  knownGaps: {
    supplierFailureHidesCompetitorSuccess: true,
    failedReadKeepsOldArrays: true,
    sourceFixed: false,
  },
  boundary:
    "Historical isolated M04-03/M04-05 fixtures. Cross-product association, supplier counts and scenario mutations are explicitly synthetic layout examples, not current business facts. VM source functions only; no real Vue/API/DB/RBAC or production. No market-demand chart, risk-category results or automatic post-queue score/count mutation.",
};
