import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { OrganizationAdminService,OrganizationAdminError } from "../../apps/api/dist/organization-admin-service.js";
const org="00000000-0000-4000-8000-000000000601",ws="00000000-0000-4000-8000-000000000602";
function fake(){const calls=[];return{calls,repo:new Proxy({}, {get:(_t,k)=>async i=>{calls.push([k,i]);return i;}})}}
test("M06-01.A01/A02/A04/A12 validates scoped admin contracts",async()=>{const f=fake(),s=new OrganizationAdminService(f.repo,72,90,2,()=>new Date("2026-08-08T00:00:00Z"));await s.updateProfile({organizationId:org,value:{name:"ScoutOps",timezone:"Asia/Shanghai",data_retention_days:365,default_workspace_id:ws,expected_version:1,reason:"approved change"}});assert.equal(f.calls[0][0],"updateProfile");assert.throws(()=>s.updateProfile({value:{name:"x",timezone:"UTC",data_retention_days:1,default_workspace_id:ws,reason:"x"}}),e=>e instanceof OrganizationAdminError&&e.code==="retention_invalid");assert.throws(()=>s.invite({value:{email:"bad",role_code:"member",reason:"x"}}),e=>e.code==="invitation_email_invalid");assert.throws(()=>s.createToken({value:{name:"write",scopes:["organization:manage"],reason:"x"}}),e=>e.code==="token_scope_invalid");});
test("M06-01.A06/A09/A13 token is random, hashed and read-only scoped",async()=>{const f=fake(),s=new OrganizationAdminService(f.repo);const x=await s.createToken({organizationId:org,value:{name:"reporting",scopes:["report:read"],ttl_days:30,reason:"integration"}}),input=f.calls[0][1];assert.match(input.value.secret,/^sco_org_/);assert.equal(input.value.token_hash.length,64);assert.ok(!input.value.token_hash.includes(input.value.secret));assert.deepEqual(input.value.scopes,["report:read"]);assert.equal(x.value.secret,input.value.secret);});
test("M06-01.A03/A05/A11/A16 migration is MySQL57, auditable and reversible",async()=>{const up=await readFile("database/migrations/0019_organization_admin_m06_01.up.sql","utf8"),down=await readFile("database/migrations/0019_organization_admin_m06_01.down.sql","utf8"),repo=await readFile("apps/api/src/mysql-organization-admin-repository.ts","utf8");assert.match(up,/organization_invitations/);assert.match(up,/organization_api_tokens/);assert.match(up,/team_memberships/);assert.match(up,/DEFAULT CHARSET=utf8mb4/);assert.doesNotMatch(up,/CHECK\s*\(|utf8mb4_0900|GENERATED ALWAYS/i);assert.match(down,/DROP TABLE IF EXISTS `organization_api_tokens`/);assert.match(repo,/last_admin_forbidden/);assert.match(repo,/default_workspace_archive_forbidden/);assert.match(repo,/INSERT INTO audit_logs/);assert.match(repo,/INSERT INTO outbox_events/);assert.match(repo,/delete stored\.secret/);});
