window.PN_DATA = {
  sourcePaths: [
    "apps/web/src/components/use-platform-notification-list.ts",
    "apps/web/src/components/PlatformManagementCenter.vue",
    "apps/web/src/components/PlatformMessageEditor.vue",
    "apps/web/src/components/PlatformMessageWorkbench.vue",
    "apps/web/src/components/PlatformNotificationOperations.vue",
    "apps/web/src/components/PlatformNotificationManagement.vue",
    "apps/web/src/components/PlatformNotificationPagination.vue",
    "apps/web/src/components/PlatformManagementFilter.vue",
    "apps/web/src/components/platform-management-presentation.ts",
    "apps/web/src/components/ResponsiveDataView.vue",
    "apps/web/src/components/ResponsiveFilterDrawer.vue",
    "apps/web/src/components/TableViewControls.vue",
    "apps/web/src/use-modal-dialog.ts",
    "apps/web/src/use-audited-reason.ts",
    "apps/web/src/components/AuditedReasonDialog.vue",
    "apps/api/src/platform-dashboard-service.ts",
    "apps/api/src/mysql-platform-dashboard-repository.ts",
    "apps/api/src/platform-dashboard-routes.ts",
    "tests/unit/platform-notification-operations.test.mjs",
    "tests/e2e/platform-message-management.spec.ts",
    "tests/e2e/m06-02-platform-dashboard.spec.ts",
  ],
  sourceChecks: [
    "Actual list: 15s/single-flight skips second request but mutable query reaches success URL; stop ignored-abort updates refs; creating resets message page only; first failure falsely claims retained data; both empty hides auxiliary panels in parent. Not production fixes.",
    "Actual parent defaults and create body; function-level save is not single-flight, earlier success closes a newer editor and overwrites failed reload with success. No HTTP.",
    "Actual publish confirmation reads item version after awaited reason (mutable target boundary); success counts overwrite reload error; cancelling reason yields no call, new shared reason cancels prior unresolved reason.",
    "Actual service: 36 audience/category/severity combinations; create has no reason contract; title2-200/body2-2000, edit/action reason2-300, numeric version conversion, inactive selectors not preflight; mail/all-channels-off rejected. No invented recipient rules.",
    "Actual read repository: 20 combinations of independent 20-row deliveries/10-row messages, query/category excluded from message query; actual fixed templates, global subscriptions/channels, clamped pages and bounded active 200/500 audience options. Inert SQL strings, not MySQL execution.",
    "Actual publish/cancel transaction: all/org/user target SQL and earlier-membership dedup predicate, two inert recipients yield 2 in-app and 0 mail; no preferences/Worker read, published outbox inserted synchronously. Empty/conflict/non-draft/mail rollback, cancel/replay no deliveries. Predicate inspected, not proven against real membership data.",
    "Actual create/update transaction in inert connection: draft-only save, version increments, invalid FK mapping, missing/non-draft/version conflicts rollback, idempotent replay, no notification delivery on save. No SQL execution.",
  ],
  originalMessages: {
    draft: {
      domain: "notifications",
      summary: { total: 0, unread: 0, critical: 0 },
      items: [],
      templates: [],
      channels: [],
      subscriptions: {},
      alert_routes: [],
      pagination: { page: 1, page_size: 20, total: 0, total_pages: 1 },
      message_pagination: { page: 1, page_size: 10, total: 1, total_pages: 1 },
      messages: [
        {
          id: "00000000-0000-4000-8000-000000000801",
          kind: "notification",
          title: "长正文审核通知",
          body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
          status: "draft",
          version: 2,
          category: "system",
          severity: "info",
          audience_type: "all_users",
          in_app_enabled: true,
          email_enabled: false,
          updated_at: "2026-09-08T00:00:00.000Z",
        },
      ],
      audience_options: { organizations: [], users: [] },
      observed_at: "2026-09-08T00:00:00.000Z",
    },
    published: {
      domain: "notifications",
      summary: { total: 0, unread: 0, critical: 0 },
      items: [],
      templates: [],
      channels: [],
      subscriptions: {},
      alert_routes: [],
      pagination: { page: 1, page_size: 20, total: 0, total_pages: 1 },
      message_pagination: { page: 1, page_size: 10, total: 1, total_pages: 1 },
      messages: [
        {
          id: "00000000-0000-4000-8000-000000000801",
          kind: "notification",
          title: "长正文审核通知",
          body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
          status: "published",
          version: 2,
          category: "system",
          severity: "info",
          audience_type: "all_users",
          in_app_enabled: true,
          email_enabled: false,
          updated_at: "2026-09-08T00:00:00.000Z",
        },
      ],
      audience_options: { organizations: [], users: [] },
      observed_at: "2026-09-08T00:00:00.000Z",
    },
    cancelled: {
      domain: "notifications",
      summary: { total: 0, unread: 0, critical: 0 },
      items: [],
      templates: [],
      channels: [],
      subscriptions: {},
      alert_routes: [],
      pagination: { page: 1, page_size: 20, total: 0, total_pages: 1 },
      message_pagination: { page: 1, page_size: 10, total: 1, total_pages: 1 },
      messages: [
        {
          id: "00000000-0000-4000-8000-000000000801",
          kind: "notification",
          title: "长正文审核通知",
          body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
          status: "cancelled",
          version: 2,
          category: "system",
          severity: "info",
          audience_type: "all_users",
          in_app_enabled: true,
          email_enabled: false,
          updated_at: "2026-09-08T00:00:00.000Z",
        },
      ],
      audience_options: { organizations: [], users: [] },
      observed_at: "2026-09-08T00:00:00.000Z",
    },
  },
  originalOperations: {
    domain: "notifications",
    summary: { total: 1, unread: 1, critical: 0 },
    messages: [],
    templates: [
      { category: "task", title: "任务状态通知", event_pattern: "task.*", status: "active" },
    ],
    channels: [
      {
        code: "in_app",
        name: "站内通知",
        status: "enabled",
        deliveries: [{ status: "delivered", total: 1 }],
      },
    ],
    subscriptions: { in_app: 3, email: 0, disabled: 0 },
    alert_routes: [
      {
        id: "route-1",
        name: "竞品变更提醒",
        event_type: "competitor.changed",
        action_type: "notify",
        status: "enabled",
      },
    ],
    items: [
      {
        id: "notice-1",
        title: "采集任务完成",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
    ],
    observed_at: "2026-08-18T12:00:00.000Z",
  },
  synthetic: {
    domain: "notifications",
    summary: { total: 1, unread: 1, critical: 0 },
    items: [
      {
        id: "synthetic-delivery-1",
        title: "合成投递 1",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
    ],
    pagination: { page: 1, page_size: 20, total: 1, total_pages: 1 },
    templates: [
      { category: "task", title: "任务状态更新", event_pattern: "task.*", status: "system_fixed" },
      {
        category: "approval",
        title: "审批状态更新",
        event_pattern: "approval.*",
        status: "system_fixed",
      },
      {
        category: "competitor",
        title: "竞品监控更新",
        event_pattern: "competitor.*",
        status: "system_fixed",
      },
      {
        category: "system",
        title: "系统与自动化通知",
        event_pattern: "automation.*",
        status: "system_fixed",
      },
    ],
    channels: [
      {
        code: "in_app",
        name: "站内通知",
        status: "enabled",
        deliveries: [{ status: "delivered", total: 21 }],
      },
      {
        code: "email",
        name: "邮件",
        status: "pending_provider_selection",
        deliveries: [{ status: "failed", total: 2 }],
      },
    ],
    subscriptions: {
      total: 3,
      in_app_enabled: 3,
      email_enabled: 0,
      task_enabled: 2,
      approval_enabled: 2,
      competitor_enabled: 1,
    },
    alert_routes: [
      {
        id: "synthetic-route",
        name: "合成竞品变化通知",
        event_type: "competitor.changed",
        action_type: "notify_owner",
        status: "active",
        version: 1,
        organization_name: "合成组织",
        workspace_name: "合成工作区",
        updated_at: "2026-09-09T00:00:00.000Z",
      },
    ],
    messages: [
      {
        id: "00000000-0000-4000-8000-000000000801",
        kind: "notification",
        title: "合成消息 1",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
    ],
    message_pagination: { page: 1, page_size: 10, total: 1, total_pages: 1 },
    audience_options: {
      organizations: [{ id: "00000000-0000-4000-8000-000000000801", name: "合成组织" }],
      users: [{ id: "00000000-0000-4000-8000-000000000801", email: "synthetic@example.test" }],
    },
    observed_at: "2026-09-09T00:00:00.000Z",
  },
  pagination: {
    domain: "notifications",
    summary: { total: 21, unread: 21, critical: 0 },
    items: [
      {
        id: "synthetic-delivery-1",
        title: "合成投递 1",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-2",
        title: "合成投递 2",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-3",
        title: "合成投递 3",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-4",
        title: "合成投递 4",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-5",
        title: "合成投递 5",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-6",
        title: "合成投递 6",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-7",
        title: "合成投递 7",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-8",
        title: "合成投递 8",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-9",
        title: "合成投递 9",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-10",
        title: "合成投递 10",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-11",
        title: "合成投递 11",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-12",
        title: "合成投递 12",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-13",
        title: "合成投递 13",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-14",
        title: "合成投递 14",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-15",
        title: "合成投递 15",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-16",
        title: "合成投递 16",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-17",
        title: "合成投递 17",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-18",
        title: "合成投递 18",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-19",
        title: "合成投递 19",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
      {
        id: "synthetic-delivery-20",
        title: "合成投递 20",
        recipient_email: "member@example.test",
        organization_name: "米豆选品",
        category: "task",
        severity: "info",
        read_at: null,
        delivery_status: "in_app:delivered",
        created_at: "2026-08-18T12:00:00.000Z",
      },
    ],
    pagination: { page: 1, page_size: 20, total: 21, total_pages: 2 },
    templates: [
      { category: "task", title: "任务状态更新", event_pattern: "task.*", status: "system_fixed" },
      {
        category: "approval",
        title: "审批状态更新",
        event_pattern: "approval.*",
        status: "system_fixed",
      },
      {
        category: "competitor",
        title: "竞品监控更新",
        event_pattern: "competitor.*",
        status: "system_fixed",
      },
      {
        category: "system",
        title: "系统与自动化通知",
        event_pattern: "automation.*",
        status: "system_fixed",
      },
    ],
    channels: [
      {
        code: "in_app",
        name: "站内通知",
        status: "enabled",
        deliveries: [{ status: "delivered", total: 21 }],
      },
      {
        code: "email",
        name: "邮件",
        status: "pending_provider_selection",
        deliveries: [{ status: "failed", total: 2 }],
      },
    ],
    subscriptions: {
      total: 3,
      in_app_enabled: 3,
      email_enabled: 0,
      task_enabled: 2,
      approval_enabled: 2,
      competitor_enabled: 1,
    },
    alert_routes: [
      {
        id: "synthetic-route",
        name: "合成竞品变化通知",
        event_type: "competitor.changed",
        action_type: "notify_owner",
        status: "active",
        version: 1,
        organization_name: "合成组织",
        workspace_name: "合成工作区",
        updated_at: "2026-09-09T00:00:00.000Z",
      },
    ],
    messages: [
      {
        id: "00000000-0000-4000-8000-000000000801",
        kind: "notification",
        title: "合成消息 1",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000802",
        kind: "notification",
        title: "合成消息 2",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000803",
        kind: "notification",
        title: "合成消息 3",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000804",
        kind: "notification",
        title: "合成消息 4",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000805",
        kind: "notification",
        title: "合成消息 5",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000806",
        kind: "notification",
        title: "合成消息 6",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000807",
        kind: "notification",
        title: "合成消息 7",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000808",
        kind: "notification",
        title: "合成消息 8",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000809",
        kind: "notification",
        title: "合成消息 9",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000810",
        kind: "notification",
        title: "合成消息 10",
        body: "第 1 行：通知正文应当完整可读。\n第 2 行：通知正文应当完整可读。\n第 3 行：通知正文应当完整可读。\n第 4 行：通知正文应当完整可读。\n第 5 行：通知正文应当完整可读。\n第 6 行：通知正文应当完整可读。\n第 7 行：通知正文应当完整可读。\n第 8 行：通知正文应当完整可读。\n第 9 行：通知正文应当完整可读。\n第 10 行：通知正文应当完整可读。\n第 11 行：通知正文应当完整可读。\n第 12 行：通知正文应当完整可读。\n第 13 行：通知正文应当完整可读。\n第 14 行：通知正文应当完整可读。\n第 15 行：通知正文应当完整可读。\n第 16 行：通知正文应当完整可读。\n第 17 行：通知正文应当完整可读。\n第 18 行：通知正文应当完整可读。",
        status: "draft",
        version: 2,
        category: "system",
        severity: "info",
        audience_type: "all_users",
        in_app_enabled: true,
        email_enabled: false,
        updated_at: "2026-09-08T00:00:00.000Z",
        created_at: "2026-09-09T00:00:00.000Z",
        published_at: null,
      },
    ],
    message_pagination: { page: 1, page_size: 10, total: 11, total_pages: 2 },
    audience_options: {
      organizations: [{ id: "00000000-0000-4000-8000-000000000801", name: "合成组织" }],
      users: [{ id: "00000000-0000-4000-8000-000000000801", email: "synthetic@example.test" }],
    },
    observed_at: "2026-09-09T00:00:00.000Z",
  },
  labels: {
    draft: "草稿",
    published: "已发布",
    cancelled: "已取消",
    task: "任务",
    approval: "审批",
    competitor: "竞品",
    system: "系统",
    info: "普通",
    warning: "警告",
    critical: "严重",
    delivered: "已送达",
    failed: "失败",
    pending_placeholder: "待配置",
    system_fixed: "系统内置",
    enabled: "启用",
    active: "展示中",
    pending_provider_selection: "邮件服务待配置",
    queued: "排队中",
    blocked_provider: "服务商受阻",
  },
};
