window.CAPACITY_DATA = {
  clock: "2026-09-09T08:00:00.000Z",
  sourcePaths: [
    "apps/api/src/capacity-boundary-service.ts",
    "apps/api/src/capacity-boundary-repository.ts",
    "apps/api/src/capacity-boundary-routes.ts",
    "apps/web/src/components/CapacityBoundaryCenter.vue",
    "apps/web/src/components/ConfirmDialog.vue",
    "apps/web/src/ui/state-contract.ts",
    "apps/web/src/components/TechnicalDetails.vue",
    "tests/e2e/m08-06-capacity-boundary.spec.ts",
    "packages/config/src/index.ts",
    "infra/baota/capacity-boundary-manifest.json",
  ],
  sourceChecks: [
    "Actual evaluator/service: fixed strict/inclusive gates, exact60min/future/invalid time, three degradation modes, fixed topology claims, limited stop facts, metric-only warning and source acceptance of off-plan7/21 values. Null read fails before view audit; pre-aborted read rejected. Synthetic output is not measured capacity.",
    "Actual repository read with inert pool: latest production row without build/signature filter, canonical UTC parse/failure, malformed stop-code handling and first valid next-stop precedence. Numeric null coerces to0; original raw null is unavailable in DTO. No real SQL execution.",
    "Actual service attestation guards kind/reason/recovery flags but accepts stale/performance-blocked flags-true snapshot and passes no observation ID. Actual repository inert transaction independently selects newest verified row, replays string/object, inserts three records, rolls back missing/audit failure; view writes two records with abort/rollback/release. Does not prove concurrency, row identity binding, durable idempotency, SQL or real recovery.",
    "Actual Vue script with inert request: GET single-flight/15s/null/auth clear/other failures retain, generic and timeout keep previous ID; POST exact fixed body, duplicate guard and same key after every failure including409/401, no-snapshot visible failure, concurrent GET suppresses success reload and overwrites operation ID. Metric-only warning still uses next-stage wording in source; no unmount/activation hook. Not mounted Vue or preserve-lifecycle proof.",
    "Static route/shared consumers: private read, platform operate, same-origin and idempotency-key write, default14s read abort; one non-destructive confirm-word dialog, two request-details consumers and native finding disclosures. No real session/authorization/route handler or shared clipboard proof.",
  ],
  policy: {
    readP95StopMs: 300,
    writeP95StopMs: 600,
    errorRateStopBasisPoints: 100,
    asyncLagStopSeconds: 60,
    maximumLoadBasisPoints: 8500,
    minimumAvailableMemoryMb: 1024,
    minimumFreeDiskMb: 4096,
    maximumEvidenceAgeMinutes: 60,
  },
  datasets: {
    ready: {
      state: "ready",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "normal", actions: [] },
      findings: [],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "limited-5": {
      state: "warning",
      boundary: {
        measured_concurrency: 5,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "next_stage_gate_failed",
        failed_next_concurrency: 10,
        failed_next_code: "capacity_write_latency_exceeded",
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "shed_background",
        actions: [
          "并发 10 已触发 capacity_write_latency_exceeded；容量声明仅限已通过的并发 5，不得继续扩大。",
        ],
      },
      findings: [
        {
          code: "capacity_next_stage_gate_failed",
          severity: "warning",
          reason: "并发 10 的下一档生产测量未通过。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint:
            "并发 10 已触发 capacity_write_latency_exceeded；容量声明仅限已通过的并发 5，不得继续扩大。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "limited-10": {
      state: "warning",
      boundary: {
        measured_concurrency: 10,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "next_stage_gate_failed",
        failed_next_concurrency: 20,
        failed_next_code: "capacity_write_latency_exceeded",
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "shed_background",
        actions: [
          "并发 20 已触发 capacity_write_latency_exceeded；容量声明仅限已通过的并发 10，不得继续扩大。",
        ],
      },
      findings: [
        {
          code: "capacity_next_stage_gate_failed",
          severity: "warning",
          reason: "并发 20 的下一档生产测量未通过。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint:
            "并发 20 已触发 capacity_write_latency_exceeded；容量声明仅限已通过的并发 10，不得继续扩大。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    missing: {
      state: "blocked",
      boundary: {
        measured_concurrency: 0,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: null,
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: [
          "固定并发 5 必须先完整通过，禁止用规划值或未通过档位代替实测边界。",
          "低于规划测量上限的边界必须保留下一档真实失败码和失败档位。",
        ],
      },
      findings: [
        {
          code: "capacity_measurement_missing",
          severity: "blocked",
          reason: "固定并发 5 尚未形成完整通过的生产测量。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "固定并发 5 必须先完整通过，禁止用规划值或未通过档位代替实测边界。",
        },
        {
          code: "capacity_boundary_stop_missing",
          severity: "blocked",
          reason: "低于规划上限的证据没有保留正确的下一档失败事实。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "低于规划测量上限的边界必须保留下一档真实失败码和失败档位。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    stale: {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: ["重新运行惠州单机受控容量基线并签发同提交证据。"],
      },
      findings: [
        {
          code: "capacity_evidence_stale",
          severity: "blocked",
          reason: "当前容量证据已超过允许的新鲜度窗口。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "重新运行惠州单机受控容量基线并签发同提交证据。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T06:59:59.999Z",
    },
    "fresh-boundary": {
      state: "ready",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "normal", actions: [] },
      findings: [],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T07:00:00.000Z",
    },
    future: {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: ["重新运行惠州单机受控容量基线并签发同提交证据。"],
      },
      findings: [
        {
          code: "capacity_evidence_stale",
          severity: "blocked",
          reason: "当前容量证据已超过允许的新鲜度窗口。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "重新运行惠州单机受控容量基线并签发同提交证据。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.001Z",
    },
    "read-warning": {
      state: "warning",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 270,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "shed_background",
        actions: ["读 P95 接近停止线，暂停后台非关键工作并持续观察。"],
      },
      findings: [
        {
          code: "capacity_read_latency_warning",
          severity: "warning",
          reason: "核心读取 P95 已进入停止线前 10% 的预警区间。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "读 P95 接近停止线，暂停后台非关键工作并持续观察。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "read-boundary": {
      state: "warning",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 300,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "shed_background",
        actions: ["读 P95 接近停止线，暂停后台非关键工作并持续观察。"],
      },
      findings: [
        {
          code: "capacity_read_latency_warning",
          severity: "warning",
          reason: "核心读取 P95 已进入停止线前 10% 的预警区间。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "读 P95 接近停止线，暂停后台非关键工作并持续观察。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "read-stop": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 301,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: ["保持降载并检查 API、MySQL 与 Redis 读路径。"],
      },
      findings: [
        {
          code: "capacity_read_latency_exceeded",
          severity: "blocked",
          reason: "核心读取 P95 已超过固定停止线。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "保持降载并检查 API、MySQL 与 Redis 读路径。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "write-warning": {
      state: "warning",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 540,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "shed_background",
        actions: ["写 P95 接近停止线，维持单 Worker/Crawler 并降低任务进入速度。"],
      },
      findings: [
        {
          code: "capacity_write_latency_warning",
          severity: "warning",
          reason: "核心写入 P95 已进入停止线前 10% 的预警区间。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "写 P95 接近停止线，维持单 Worker/Crawler 并降低任务进入速度。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "write-boundary": {
      state: "warning",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 600,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "shed_background",
        actions: ["写 P95 接近停止线，维持单 Worker/Crawler 并降低任务进入速度。"],
      },
      findings: [
        {
          code: "capacity_write_latency_warning",
          severity: "warning",
          reason: "核心写入 P95 已进入停止线前 10% 的预警区间。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "写 P95 接近停止线，维持单 Worker/Crawler 并降低任务进入速度。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "write-stop": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 601,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: ["停止新增后台工作并检查 MySQL 持久写路径。"],
      },
      findings: [
        {
          code: "capacity_write_latency_exceeded",
          severity: "blocked",
          reason: "核心写入 P95 已超过固定停止线。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "停止新增后台工作并检查 MySQL 持久写路径。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "error-warning": {
      state: "warning",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 80,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "shed_background",
        actions: ["错误率接近停止线，保持当前实测边界不再扩大。"],
      },
      findings: [
        {
          code: "capacity_error_rate_warning",
          severity: "warning",
          reason: "生产测量错误率已进入停止线前 20% 的预警区间。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "错误率接近停止线，保持当前实测边界不再扩大。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "error-stop": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 100,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "stop_new_work", actions: ["停止扩大并发并按 trace_id 排查失败请求。"] },
      findings: [
        {
          code: "capacity_error_rate_exceeded",
          severity: "blocked",
          reason: "生产测量错误率已达到固定停止线。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "停止扩大并发并按 trace_id 排查失败请求。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "lag-warning": {
      state: "warning",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 48,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "shed_background", actions: ["异步滞后接近停止线，优先处理既有队列。"] },
      findings: [
        {
          code: "capacity_async_lag_warning",
          severity: "warning",
          reason: "异步任务滞后已进入停止线前 20% 的预警区间。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "异步滞后接近停止线，优先处理既有队列。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "lag-boundary": {
      state: "warning",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 60,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "shed_background", actions: ["异步滞后接近停止线，优先处理既有队列。"] },
      findings: [
        {
          code: "capacity_async_lag_warning",
          severity: "warning",
          reason: "异步任务滞后已进入停止线前 20% 的预警区间。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "异步滞后接近停止线，优先处理既有队列。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "lag-stop": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 61,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "stop_new_work", actions: ["保持任务排队并暂停非关键异步处理。"] },
      findings: [
        {
          code: "capacity_async_lag_exceeded",
          severity: "blocked",
          reason: "异步任务滞后已超过固定停止线。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "保持任务排队并暂停非关键异步处理。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "load-warning": {
      state: "warning",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 7650, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "shed_background", actions: ["主机负载接近停止线，保持降载策略。"] },
      findings: [
        {
          code: "capacity_host_load_warning",
          severity: "warning",
          reason: "单机归一化负载已进入上限前 10% 的预警区间。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "主机负载接近停止线，保持降载策略。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "load-stop": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 8500, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "stop_new_work", actions: ["通过宝塔停止新增后台工作并核查主机资源。"] },
      findings: [
        {
          code: "capacity_host_load_exceeded",
          severity: "blocked",
          reason: "单机归一化负载已达到固定上限。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "通过宝塔停止新增后台工作并核查主机资源。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "memory-stop": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 1023, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "stop_new_work", actions: ["保持降载并通过宝塔检查内存使用。"] },
      findings: [
        {
          code: "capacity_memory_exceeded",
          severity: "blocked",
          reason: "单机可用内存低于固定安全下限。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "保持降载并通过宝塔检查内存使用。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "disk-stop": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 4095 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: ["停止新增文件任务并通过宝塔清理或扩容受控目录。"],
      },
      findings: [
        {
          code: "capacity_disk_exceeded",
          severity: "blocked",
          reason: "单机可用磁盘低于固定安全下限。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "停止新增文件任务并通过宝塔清理或扩容受控目录。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "resource-boundary": {
      state: "ready",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 1024, free_disk_mb: 4096 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "normal", actions: [] },
      findings: [],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "archive-missing": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: false, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: ["通过宝塔有限任务验证归档副本后再签发容量边界。"],
      },
      findings: [
        {
          code: "capacity_archive_unverified",
          severity: "blocked",
          reason: "当前容量证据尚未签认加密归档事实。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "通过宝塔有限任务验证归档副本后再签发容量边界。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "recovery-missing": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: false },
      degradation: {
        mode: "stop_new_work",
        actions: ["在隔离库和隔离目录完成恢复演练后再签发容量边界。"],
      },
      findings: [
        {
          code: "capacity_recovery_unverified",
          severity: "blocked",
          reason: "当前容量证据尚未签认隔离恢复事实。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "在隔离库和隔离目录完成恢复演练后再签发容量边界。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "both-missing": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: false, recovery_verified: false },
      degradation: {
        mode: "stop_new_work",
        actions: [
          "通过宝塔有限任务验证归档副本后再签发容量边界。",
          "在隔离库和隔离目录完成恢复演练后再签发容量边界。",
        ],
      },
      findings: [
        {
          code: "capacity_archive_unverified",
          severity: "blocked",
          reason: "当前容量证据尚未签认加密归档事实。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "通过宝塔有限任务验证归档副本后再签发容量边界。",
        },
        {
          code: "capacity_recovery_unverified",
          severity: "blocked",
          reason: "当前容量证据尚未签认隔离恢复事实。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "在隔离库和隔离目录完成恢复演练后再签发容量边界。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "stop-missing": {
      state: "blocked",
      boundary: {
        measured_concurrency: 10,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: null,
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: ["低于规划测量上限的边界必须保留下一档真实失败码和失败档位。"],
      },
      findings: [
        {
          code: "capacity_boundary_stop_missing",
          severity: "blocked",
          reason: "低于规划上限的证据没有保留正确的下一档失败事实。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "低于规划测量上限的边界必须保留下一档真实失败码和失败档位。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "stop-wrong": {
      state: "blocked",
      boundary: {
        measured_concurrency: 5,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "next_stage_gate_failed",
        failed_next_concurrency: 20,
        failed_next_code: "capacity_write_latency_exceeded",
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: ["低于规划测量上限的边界必须保留下一档真实失败码和失败档位。"],
      },
      findings: [
        {
          code: "capacity_boundary_stop_missing",
          severity: "blocked",
          reason: "低于规划上限的证据没有保留正确的下一档失败事实。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "低于规划测量上限的边界必须保留下一档真实失败码和失败档位。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "ceiling-invalid": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: 20,
        failed_next_code: "capacity_write_latency_exceeded",
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: ["并发 20 证据必须明确以规划测量上限结束且没有伪造下一档。"],
      },
      findings: [
        {
          code: "capacity_boundary_stop_invalid",
          severity: "blocked",
          reason: "并发 20 的生产证据与规划上限结束语义不一致。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "并发 20 证据必须明确以规划测量上限结束且没有伪造下一档。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "over-ceiling": {
      state: "ready",
      boundary: {
        measured_concurrency: 21,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "normal", actions: [] },
      findings: [],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "off-stage": {
      state: "warning",
      boundary: {
        measured_concurrency: 7,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "next_stage_gate_failed",
        failed_next_concurrency: null,
        failed_next_code: "synthetic_failure",
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "shed_background",
        actions: ["并发 null 已触发 synthetic_failure；容量声明仅限已通过的并发 7，不得继续扩大。"],
      },
      findings: [
        {
          code: "capacity_next_stage_gate_failed",
          severity: "warning",
          reason: "并发 null 的下一档生产测量未通过。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint:
            "并发 null 已触发 synthetic_failure；容量声明仅限已通过的并发 7，不得继续扩大。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "negative-resource": {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: -10, available_memory_mb: -1, free_disk_mb: -2 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "stop_new_work",
        actions: [
          "保持降载并通过宝塔检查内存使用。",
          "停止新增文件任务并通过宝塔清理或扩容受控目录。",
        ],
      },
      findings: [
        {
          code: "capacity_memory_exceeded",
          severity: "blocked",
          reason: "单机可用内存低于固定安全下限。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "保持降载并通过宝塔检查内存使用。",
        },
        {
          code: "capacity_disk_exceeded",
          severity: "blocked",
          reason: "单机可用磁盘低于固定安全下限。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "停止新增文件任务并通过宝塔清理或扩容受控目录。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "large-resource": {
      state: "ready",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 65536, free_disk_mb: 1048576 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "normal", actions: [] },
      findings: [],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    long: {
      state: "warning",
      boundary: {
        measured_concurrency: 5,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "next_stage_gate_failed",
        failed_next_concurrency: 10,
        failed_next_code:
          "synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_",
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: {
        mode: "shed_background",
        actions: [
          "并发 10 已触发 synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_；容量声明仅限已通过的并发 5，不得继续扩大。",
        ],
      },
      findings: [
        {
          code: "capacity_next_stage_gate_failed",
          severity: "warning",
          reason: "并发 10 的下一档生产测量未通过。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint:
            "并发 10 已触发 synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_synthetic_long_failure_；容量声明仅限已通过的并发 5，不得继续扩大。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    multiple: {
      state: "blocked",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "unverified",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 301,
        write_p95_ms: 540,
        error_rate_basis_points: 100,
        async_lag_seconds: 48,
      },
      resource: { load_basis_points: 8500, available_memory_mb: 1023, free_disk_mb: 4095 },
      resilience: { archive_verified: false, recovery_verified: false },
      degradation: {
        mode: "stop_new_work",
        actions: [
          "保持降载并检查 API、MySQL 与 Redis 读路径。",
          "写 P95 接近停止线，维持单 Worker/Crawler 并降低任务进入速度。",
          "停止扩大并发并按 trace_id 排查失败请求。",
          "异步滞后接近停止线，优先处理既有队列。",
          "通过宝塔停止新增后台工作并核查主机资源。",
          "保持降载并通过宝塔检查内存使用。",
          "停止新增文件任务并通过宝塔清理或扩容受控目录。",
          "通过宝塔有限任务验证归档副本后再签发容量边界。",
          "在隔离库和隔离目录完成恢复演练后再签发容量边界。",
        ],
      },
      findings: [
        {
          code: "capacity_read_latency_exceeded",
          severity: "blocked",
          reason: "核心读取 P95 已超过固定停止线。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "保持降载并检查 API、MySQL 与 Redis 读路径。",
        },
        {
          code: "capacity_write_latency_warning",
          severity: "warning",
          reason: "核心写入 P95 已进入停止线前 10% 的预警区间。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "写 P95 接近停止线，维持单 Worker/Crawler 并降低任务进入速度。",
        },
        {
          code: "capacity_error_rate_exceeded",
          severity: "blocked",
          reason: "生产测量错误率已达到固定停止线。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "停止扩大并发并按 trace_id 排查失败请求。",
        },
        {
          code: "capacity_async_lag_warning",
          severity: "warning",
          reason: "异步任务滞后已进入停止线前 20% 的预警区间。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "异步滞后接近停止线，优先处理既有队列。",
        },
        {
          code: "capacity_host_load_exceeded",
          severity: "blocked",
          reason: "单机归一化负载已达到固定上限。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "通过宝塔停止新增后台工作并核查主机资源。",
        },
        {
          code: "capacity_memory_exceeded",
          severity: "blocked",
          reason: "单机可用内存低于固定安全下限。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "保持降载并通过宝塔检查内存使用。",
        },
        {
          code: "capacity_disk_exceeded",
          severity: "blocked",
          reason: "单机可用磁盘低于固定安全下限。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "停止新增文件任务并通过宝塔清理或扩容受控目录。",
        },
        {
          code: "capacity_archive_unverified",
          severity: "blocked",
          reason: "当前容量证据尚未签认加密归档事实。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "通过宝塔有限任务验证归档副本后再签发容量边界。",
        },
        {
          code: "capacity_recovery_unverified",
          severity: "blocked",
          reason: "当前容量证据尚未签认隔离恢复事实。",
          owner_role_code: "platform_operations_admin",
          owner_label: "平台运维管理员",
          action_hint: "在隔离库和隔离目录完成恢复演练后再签发容量边界。",
        },
      ],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "policy-difference": {
      state: "ready",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 350,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "normal", actions: [] },
      findings: [],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "null-coercion": {
      state: "ready",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 0,
        write_p95_ms: 0,
        error_rate_basis_points: 0,
        async_lag_seconds: 0,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "normal", actions: [] },
      findings: [],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    original: {
      state: "ready",
      boundary: {
        measured_concurrency: 20,
        planning_users: 100,
        planning_concurrency_min: 5,
        planning_concurrency_max: 20,
        capacity_claim: "measured_single_host_limited",
        stop_reason: "planning_ceiling_reached",
        failed_next_concurrency: null,
        failed_next_code: null,
      },
      performance: {
        read_p95_ms: 118,
        write_p95_ms: 284,
        error_rate_basis_points: 0,
        async_lag_seconds: 2,
      },
      resource: { load_basis_points: 3260, available_memory_mb: 6144, free_disk_mb: 245760 },
      resilience: { archive_verified: true, recovery_verified: true },
      degradation: { mode: "normal", actions: [] },
      findings: [],
      single_host: true,
      load_balancing_enabled: false,
      backup_server_used: false,
      multi_node_claim: false,
      observed_at: "2026-08-15T08:00:00.000Z",
    },
  },
  labels: {
    ready: "20档规划上限",
    "limited-5": "5档通过/下一档失败",
    "limited-10": "10档通过/下一档失败",
    missing: "未通过5档",
    stale: "观测过期",
    "fresh-boundary": "恰好60分钟",
    future: "未来观测",
    "read-warning": "读取预警270",
    "read-boundary": "读取等于300",
    "read-stop": "读取超过300",
    "write-warning": "写入预警540",
    "write-boundary": "写入等于600",
    "write-stop": "写入超过600",
    "error-warning": "错误率0.80%",
    "error-stop": "错误率1%",
    "lag-warning": "异步滞后48秒",
    "lag-boundary": "异步滞后60秒",
    "lag-stop": "异步滞后61秒",
    "load-warning": "归一化负载76.5%",
    "load-stop": "归一化负载85%",
    "memory-stop": "可用内存不足",
    "disk-stop": "可用磁盘不足",
    "resource-boundary": "内存磁盘恰好下限",
    "archive-missing": "归档未核验",
    "recovery-missing": "隔离恢复未核验",
    "both-missing": "两项恢复证据未核验",
    "stop-missing": "10档停止事实缺失",
    "stop-wrong": "下一档与当前档不匹配",
    "ceiling-invalid": "20档仍附下一档失败",
    "over-ceiling": "源评价接受21档异常样本",
    "off-stage": "源评价7档及null下一档边界",
    "negative-resource": "负资源保留原值",
    "large-resource": "资源高于旧显示上限",
    long: "长失败码和处置文本",
    multiple: "多项阻断与预警",
    "policy-difference": "运行策略与合同参考不同",
    "null-coercion": "仓储null数值转0",
    original: "独立历史E2E夹具",
  },
  attestationBody: { kind: "archive_recovery", reason: "平台运维确认本轮单机容量收尾演练" },
  attestationResult: { status: "verified", observed_at: "2026-09-09T08:00:00.000Z" },
  provenance: "Inert source outputs and independent historical E2E; not production measurements.",
};
