window.GOVERNANCE_DATA = {
  sourcePaths: [
    "apps/web/src/components/PlatformGovernanceCenter.vue",
    "apps/api/src/platform-dashboard-service.ts",
    "apps/api/src/platform-dashboard-routes.ts",
    "apps/api/src/mysql-platform-dashboard-repository.ts",
    "tests/e2e/m06-02-platform-dashboard.spec.ts",
  ],
  sourceChecks: [
    "Actual five section routes, 25 category/status combinations and automatic-rule-only ID query",
    "Actual retained score snapshot under target automation held/error request; single-flight and successful recovery",
    "Actual ten first/retained failures, including old data after permission errors; ignored abort still updates refs (unfixed lifecycle boundary)",
    "Actual URL initial validation and server-corrected pagination range/URL",
    "Actual management service accepts 25 category/status pairs and normalizes query/page; rejects invalid section/status/length/page size",
    "Actual repository branch with inert query adapter: five sections × 0/1/20/21/100 totals, global versus filtered counts, escaped LIKE and clamped offsets; no SQL execution",
  ],
  originals: {
    score_rules: {
      domain: "governance",
      section: "score_rules",
      summary: { score_rules: 1, automation_rules: 1, provider_versions: 0 },
      items: [
        {
          id: "score-55",
          name: "隔离评分",
          status: "active",
          revision: 2,
          updated_at: "2026-09-08T00:00:00.000Z",
        },
      ],
      pagination: { page: 1, page_size: 20, total: 1, total_pages: 1 },
      observed_at: "2026-09-08T00:00:00.000Z",
    },
    automation_rules: {
      domain: "governance",
      section: "automation_rules",
      summary: { score_rules: 1, automation_rules: 1, provider_versions: 0 },
      items: [
        {
          id: "auto-55",
          name: "隔离自动化",
          status: "active",
          version: 3,
          updated_at: "2026-09-08T00:00:00.000Z",
        },
      ],
      pagination: { page: 1, page_size: 20, total: 1, total_pages: 1 },
      observed_at: "2026-09-08T00:00:00.000Z",
    },
  },
  synthetic: {
    score_rules: {
      domain: "governance",
      section: "score_rules",
      summary: {
        score_rules: 21,
        cost_rules: 1,
        approval_templates: 1,
        automation_rules: 1,
        releases: 1,
        provider_versions: 2,
      },
      items: [
        {
          id: "synthetic-score_rules",
          name: "合成 · 评分规则",
          status: "draft",
          updated_at: "2026-09-08T00:00:00.000Z",
          organization_name: "合成组织",
          workspace_name: "合成工作区",
          revision: 2,
          version_code: "score-demo-v2",
        },
      ],
      pagination: { page: 1, page_size: 20, total: 1, total_pages: 1 },
      observed_at: "2026-09-08T00:00:00.000Z",
      provider_versions_latest_at: "2026-09-08T00:00:00.000Z",
    },
    cost_rules: {
      domain: "governance",
      section: "cost_rules",
      summary: {
        score_rules: 21,
        cost_rules: 1,
        approval_templates: 1,
        automation_rules: 1,
        releases: 1,
        provider_versions: 2,
      },
      items: [
        {
          id: "synthetic-cost_rules",
          name: "合成 · 费用与风险",
          status: "draft",
          updated_at: "2026-09-08T00:00:00.000Z",
          organization_name: "合成组织",
          workspace_name: "合成工作区",
          revision: 4,
          version_code: "cost-demo-v4",
          market: "US",
          platform: "Amazon",
        },
      ],
      pagination: { page: 1, page_size: 20, total: 1, total_pages: 1 },
      observed_at: "2026-09-08T00:00:00.000Z",
      provider_versions_latest_at: "2026-09-08T00:00:00.000Z",
    },
    approval_templates: {
      domain: "governance",
      section: "approval_templates",
      summary: {
        score_rules: 21,
        cost_rules: 1,
        approval_templates: 1,
        automation_rules: 1,
        releases: 1,
        provider_versions: 2,
      },
      items: [
        {
          id: "synthetic-approval_templates",
          name: "合成 · 审批工作流",
          status: "draft",
          updated_at: "2026-09-08T00:00:00.000Z",
          organization_name: "合成组织",
          workspace_name: "合成工作区",
          current_version: 3,
          revision: 8,
          resource_type: "score_rule",
        },
      ],
      pagination: { page: 1, page_size: 20, total: 1, total_pages: 1 },
      observed_at: "2026-09-08T00:00:00.000Z",
      provider_versions_latest_at: "2026-09-08T00:00:00.000Z",
    },
    automation_rules: {
      domain: "governance",
      section: "automation_rules",
      summary: {
        score_rules: 21,
        cost_rules: 1,
        approval_templates: 1,
        automation_rules: 1,
        releases: 1,
        provider_versions: 2,
      },
      items: [
        {
          id: "synthetic-automation_rules",
          name: "合成 · 自动化规则",
          status: "active",
          updated_at: "2026-09-08T00:00:00.000Z",
          organization_name: "合成组织",
          workspace_name: "合成工作区",
          version: 3,
          trigger_event_type: "competitor.changed",
          condition_severity: "any",
          action_type: "notify_owner",
          action_title: "合成：通知负责人",
          rate_limit_count: 3,
          rate_limit_window_minutes: 60,
        },
      ],
      pagination: { page: 1, page_size: 20, total: 1, total_pages: 1 },
      observed_at: "2026-09-08T00:00:00.000Z",
      provider_versions_latest_at: "2026-09-08T00:00:00.000Z",
    },
    releases: {
      domain: "governance",
      section: "releases",
      summary: {
        score_rules: 21,
        cost_rules: 1,
        approval_templates: 1,
        automation_rules: 1,
        releases: 1,
        provider_versions: 2,
      },
      items: [
        {
          id: "synthetic-releases",
          name: "demo-1.0.0",
          status: "planned",
          updated_at: "2026-09-08T00:00:00.000Z",
          version_code: "demo-build-sha",
          stage: "canary",
        },
      ],
      pagination: { page: 1, page_size: 20, total: 1, total_pages: 1 },
      observed_at: "2026-09-08T00:00:00.000Z",
      provider_versions_latest_at: "2026-09-08T00:00:00.000Z",
    },
  },
  sections: [
    {
      value: "score_rules",
      label: "评分规则",
      action: "进入评分规则",
      href: "/opportunities/scoring-rules",
    },
    {
      value: "cost_rules",
      label: "费用与风险",
      action: "进入费用规则",
      href: "/sourcing/cost-rules",
    },
    {
      value: "approval_templates",
      label: "审批工作流",
      action: "进入组织审批",
      href: "/org-admin/approvals",
    },
    {
      value: "automation_rules",
      label: "自动化规则",
      action: "进入自动化规则",
      href: "/automations",
    },
    {
      value: "releases",
      label: "灰度与回滚",
      action: "进入发布控制",
      href: "/platform-admin/releases",
    },
  ],
  statuses: {
    score_rules: [
      "draft",
      "pending_approval",
      "approved",
      "active",
      "retired",
      "rejected",
      "rolled_back",
    ],
    cost_rules: [
      "draft",
      "pending_approval",
      "approved",
      "active",
      "retired",
      "rejected",
      "rolled_back",
    ],
    approval_templates: ["draft", "published", "archived"],
    automation_rules: ["active", "paused"],
    releases: ["planned", "preflight_passed", "deploying", "healthy", "failed", "rolled_back"],
  },
  statusNames: {
    draft: "草稿",
    pending_approval: "待审批",
    approved: "已批准",
    active: "启用",
    retired: "已退役",
    rejected: "已驳回",
    rolled_back: "已回滚",
    published: "已发布",
    archived: "已归档",
    paused: "暂停",
    planned: "已计划",
    preflight_passed: "预检通过",
    deploying: "发布中",
    healthy: "运行健康",
    failed: "失败",
  },
  typeNames: {
    "approval.overdue": "审批节点超时",
    "approval.node.rejected": "审批被驳回",
    "competitor.alert.queued": "竞品告警入队",
    "competitor.changed": "竞品发生变化",
    "task.created": "任务创建",
    notify_owner: "通知负责人",
    create_task: "创建人工任务",
    score_rules: "评分规则",
    cost_rules: "费用规则",
    approval_templates: "审批工作流",
    automation_rules: "自动化规则",
    releases: "发布版本",
  },
};
