// Generated by scripts/build-ui-phase2-data-composed-c.mjs.
window.DATA_COMPOSED_MOUNT_QUALITY = function (document, history, location, scrollTo) {
  /* Design-only local prototype. No fetch, grant, audit, storage, clipboard or production write. */
  (() => {
    const D = window.DATA_QUALITY_DATA,
      O = D.originals;
    const clone = (v) => JSON.parse(JSON.stringify(v));
    const esc = (v) =>
      String(v ?? "—").replace(
        /[&<>"']/g,
        (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c],
      );
    const labels = {
      title_accuracy: "标题准确率",
      price_accuracy: "价格准确率",
      currency_accuracy: "币种准确率",
      external_id_accuracy: "商品 ID 准确率",
      canonical_url_accuracy: "规范 URL 准确率",
      duplicate_ratio: "重复比例",
      source_freshness: "来源新鲜度",
      source_success_rate: "来源成功率",
      supplier_mismatch: "供应商误匹配",
      ai_classification_approval: "AI 分类抽检",
    };
    const codes = Object.keys(labels).slice(0, 7);
    const states = {
      passed: "通过",
      failed: "未通过",
      insufficient_sample: "样本不足",
      open: "待处理",
      resolved: "已解决",
      warning: "警告",
      critical: "严重",
    };
    const tabs = { evidence: "证据", issues: "质量问题", runs: "核对记录" };
    const actions = { attribute: "记录归因", assign: "指派成员", close: "批量解决" };
    const pct = (v) => (v == null ? "—" : `${(v * 100).toFixed(1)}%`);
    const time = (v) =>
      Number.isFinite(Date.parse(v))
        ? new Intl.DateTimeFormat("zh-CN", {
            timeZone: "Asia/Shanghai",
            year: "numeric",
            month: "2-digit",
            day: "2-digit",
            hour: "2-digit",
            minute: "2-digit",
            hour12: false,
          }).format(new Date(v))
        : "未知";
    const pill = (v) => `<span class="pill ${esc(v)}">${esc(states[v] || "状态未知")}</span>`;
    const btn = (id, text, cls = "", disabled = false) =>
      `<button id="${id}" class="${cls}" ${disabled ? "disabled" : ""}>${text}</button>`;
    let s,
      dialogKind = "",
      opener = null,
      serial = 0;
    const modal = document.querySelector("#modal");
    const initial = () => ({
      tab: "evidence",
      data: clone(O.dashboard),
      query: "",
      runId: "",
      selected: [],
      page: 1,
      total: 1,
      phase: "ready",
      notice: "",
      result: "",
      synthetic: false,
      item: null,
      action: "attribute",
      reason: "",
      assignee: "",
      phrase: "",
      pending: null,
      writes: [],
      downloads: 0,
      columns: [true, true, true, true, true],
      compact: false,
      freeze: false,
      theme: "",
      detailPhase: "ready",
    });
    const notice = (text, cls = "") =>
      text ? `<div class="notice ${cls}" role="status">${esc(text)}</div>` : "";
    const selected = () =>
      s.data.issues.filter((i) => s.selected.includes(i.id) && i.status === "open");
    const filtered = () =>
      (s.tab === "evidence" ? s.data.evidence : s.data.issues).filter(
        (i) =>
          (s.tab !== "issues" || !s.runId || i.reconciliation_run_id === s.runId) &&
          (!s.query ||
            (s.tab === "evidence"
              ? [i.id, i.provider_name, i.canonical_url, i.content_sha256]
              : [i.id, i.metric_code, i.provider_name, i.field_path]
            ).some((v) => v?.toLowerCase().includes(s.query.toLowerCase()))),
      );
    const retention = (item) => {
      const o = Date.parse(s.data.observedAt),
        e = Date.parse(item.retention_until);
      if (!Number.isFinite(o) || !Number.isFinite(e)) return "到期风险未知";
      return e <= o
        ? "已到期 · 等待受控治理"
        : e - o <= 7 * 86400000
          ? `${Math.ceil((e - o) / 86400000)} 天内到期`
          : `剩余 ${Math.ceil((e - o) / 86400000)} 天`;
    };
    const technical = (item, keys) =>
      `<details class="technical"><summary>技术标识与版本</summary><dl class="kv">${keys.map((k) => `<dt>${esc(k)}</dt><dd><code>${esc(item[k])}</code></dd>`).join("")}</dl>${btn("copy-intent", "复制请求编号（模拟）")}<p id="copy-message" class="small"></p></details>`;
    const kv = (items) =>
      `<dl class="kv">${items.map(([a, b]) => `<dt>${esc(a)}</dt><dd>${esc(b)}</dd>`).join("")}</dl>`;
    function metrics() {
      return `<section class="metrics"><h2>逐项核对，不合成总分</h2><p class="small">各指标取返回的最近 20 次核对中首次出现值；不同指标可能来自不同来源或时间。</p><div class="metric-list">${codes
        .map((c) => {
          const r = s.data.reconciliationRuns.find((r) => r.metrics.some((m) => m.code === c)),
            m = r?.metrics.find((m) => m.code === c);
          return `<article class="metric"><h3>${esc(labels[c])}</h3>${m ? `<p>${pill(m.status)}　<strong>${pct(m.value)}</strong> / 阈值 ${pct(m.threshold)}</p><small>${esc(r.provider_name)} · ${m.denominator ?? r.sample_count} 个样本<br>${time(r.window_ended_at)}</small>` : '<p class="muted">暂无核对数据</p><small>缺项不是 0，也不代表通过。</small>'}</article>`;
        })
        .join("")}</div></section>`;
    }
    function list() {
      if (s.tab === "runs")
        return s.data.reconciliationRuns.length
          ? s.data.reconciliationRuns
              .map(
                (r, i) =>
                  `<article class="run"><header><div><h3>${esc(r.provider_name)}</h3><p>${esc(r.market)} · ${esc(r.parser_version)}</p></div>${pill(r.status)}</header><p class="small">${r.sample_count} 个样本 · 窗口结束 ${time(r.window_ended_at)}</p><div class="metric-list">${r.metrics.map((m) => `<div class="metric"><b>${esc(labels[m.code] || m.code)}</b><p>${pct(m.value)} / 阈值 ${pct(m.threshold)}　${pill(m.status)}</p></div>`).join("")}</div><div class="actions">${btn(`drill-${i}`, "查看本次关联问题")}</div><p class="small">只查当前已加载问题，不代表本次核对全部异常。</p></article>`,
              )
              .join("")
          : '<div class="empty"><h3>暂无核对记录</h3><p>这不代表证据通过质量检查。</p></div>';
      const rows = filtered();
      if (!rows.length)
        return '<div class="empty"><h3>当前页没有匹配记录</h3><p>搜索与核对下钻仅作用于当前页。清除条件或翻页继续定位，不据此断言全局无问题。</p></div>';
      const evidence = s.tab === "evidence",
        headers = evidence
          ? ["来源与证据", "格式与大小", "捕获与保留", "绑定范围", "操作"]
          : ["选择与问题", "来源与字段", "状态与数值", "责任与版本", "操作"];
      const cells = (i, n) =>
        evidence
          ? [
              `${btn(`evidence-${n}`, esc(i.provider_name), "title")}<small>${esc(i.canonical_url)}</small>`,
              `${esc(i.content_type)}<small>${(i.size_bytes / 1024).toFixed(1)} KB</small>`,
              `${time(i.captured_at)}<small>保留至 ${time(i.retention_until)}</small><small>${retention(i)}</small>`,
              `组织与工作区已绑定<small>不等于当前组织过滤</small>`,
              `<div class="actions">${btn(`lineage-${n}`, "完整溯源")}${btn(`download-${n}`, "受控下载")}</div>`,
            ]
          : [
              `<label class="check"><input data-select="${esc(i.id)}" type="checkbox" ${s.selected.includes(i.id) ? "checked" : ""} ${i.status !== "open" ? "disabled" : ""} aria-label="选择 ${esc(i.id)}"/>选择</label>${btn(`issue-${n}`, esc(labels[i.metric_code] || i.metric_code), "title")}`,
              `${esc(i.provider_name)}<small>${esc(i.field_path)} · ${esc(i.parser_version)}</small>`,
              `${pill(i.status)} ${pill(i.severity)}<small>实际 ${pct(i.actual_value)} / 阈值 ${pct(i.threshold_value)}</small>`,
              `${esc(i.assigned_member_label || "未指派")}<small>版本 ${i.version} · ${time(i.updated_at)}</small>`,
              `<div class="actions">${i.raw_evidence_id ? btn(`related-${n}`, "关联证据") : ""}${btn(`resolve-${n}`, "记录解决", "", i.status !== "open")}</div>`,
            ];
      return `<div class="table-wrap desktop"><table class="${s.compact ? "compact" : ""} ${s.freeze ? "freeze" : ""}"><thead><tr>${headers
        .filter((_, i) => s.columns[i])
        .map((h) => `<th>${h}</th>`)
        .join("")}</tr></thead><tbody>${rows
        .map(
          (i, n) =>
            `<tr>${cells(i, n)
              .filter((_, j) => s.columns[j])
              .map((v) => `<td>${v}</td>`)
              .join("")}</tr>`,
        )
        .join(
          "",
        )}</tbody></table></div><div class="mobile">${rows.map((i, n) => `<article class="card">${evidence ? "" : `<label class="check"><input data-select="${esc(i.id)}" type="checkbox" ${s.selected.includes(i.id) ? "checked" : ""} ${i.status !== "open" ? "disabled" : ""} aria-label="选择 ${esc(i.id)}"/>选择本问题</label>`}<h3>${esc(evidence ? i.provider_name : labels[i.metric_code] || i.metric_code)}</h3><p>${evidence ? `${esc(i.content_type)} · ${(i.size_bytes / 1024).toFixed(1)} KB` : `${pill(i.status)} ${pill(i.severity)}`}</p><p class="small">${evidence ? `${time(i.captured_at)} · ${retention(i)}` : `${esc(i.provider_name)} · 版本 ${i.version}`}</p><div class="actions">${btn(`${evidence ? "mobile-evidence" : "mobile-issue"}-${n}`, "查看完整记录")}</div></article>`).join("")}</div>`;
    }
    function render() {
      document.body.className = s.theme;
      const ready = s.phase === "ready",
        o = s.data.observedAt;
      const riskKnown = Number.isFinite(Date.parse(o));
      const risks = s.data.evidence.reduce(
        (a, i) => {
          const t = Date.parse(i.retention_until) - Date.parse(o);
          if (Number.isFinite(t)) {
            if (t <= 0) a.expired++;
            else if (t <= 7 * 86400000) a.expiring++;
          }
          return a;
        },
        { expired: 0, expiring: 0 },
      );
      const failed = {
        loading: ["正在读取质量数据", "首次读取尚无统计结果。"],
        empty: ["暂无质量数据", "证据、问题和核对记录均为空；并不等于质量达标。"],
        expired: ["会话已过期", "重新登录后再读取；当前不能查看数据。"],
        forbidden: ["没有平台操作权限", "请由管理员核对 platform:operate；不会显示旧数据。"],
        blocked: ["依赖暂不可用", "服务或网络异常。恢复后可重试读取。"],
        error: ["读取失败", "检查请求状态后重试，未显示任何虚构统计。"],
      };
      document.querySelector("#app").innerHTML =
        `<div class="shell"><aside class="sidebar"><div class="brand">ScoutOps<span class="small"> / 运营</span></div><p class="nav-caption eyebrow">平台数据</p><a href="../data-records-direction-c/index.html">近期业务记录 ↗</a><div class="active">证据与质量</div><div class="side-note"><p>事实先于结论</p><small>原始证据 → 规范版本<br>字段溯源 → 质量问题</small><p class="draft-note">平台范围 · 不随当前组织自动过滤</p></div></aside><main><header class="header"><div><p class="eyebrow">数据中心 / 证据与质量</p><h1>从证据，核对每个结论</h1><p class="muted">查看来源与版本，确认问题范围，再记录处置。</p></div><span class="review">C 方向 · 具体稿待审核</span></header><section class="scope"><div><strong>${ready ? s.data.totalEvidence : "—"}</strong><small>全量证据</small></div><div><strong>${ready ? (s.data.openIssues ?? s.data.issues.filter((i) => i.status === "open").length) : "—"}</strong><small>${ready && s.data.openIssues == null ? "开放问题（本页回退）" : "全量开放问题"}</small></div><div><strong>${ready ? (s.data.criticalIssues ?? s.data.issues.filter((i) => i.status === "open" && i.severity === "critical").length) : "—"}</strong><small>${ready && s.data.criticalIssues == null ? "严重问题（本页回退）" : "全量严重问题"}</small></div><div class="risk"><strong>${ready && riskKnown ? risks.expiring : "—"}</strong><small>当前证据页 7 天内到期 · ${ready && riskKnown ? risks.expired : "—"} 条已到期</small></div></section><div class="observed"><span>观测时间：${ready ? time(o) : "尚未读取"}（北京时间）</span><span>${s.synthetic ? "补充合成状态 / 非原始结果" : "原始 E2E 夹具 / 非生产数据"}</span></div><nav class="tabs" aria-label="数据质量视图">${Object.entries(
          tabs,
        )
          .map(
            ([k, v]) =>
              `<button data-tab="${k}" ${s.tab === k ? 'aria-current="page"' : ""}>${v}</button>`,
          )
          .join(
            "",
          )}</nav>${notice(s.result)}${notice(s.notice, "warn")}<section class="workspace">${!ready ? `<div class="empty"><h2>${failed[s.phase][0]}</h2><p>${failed[s.phase][1]}</p>${btn("retry", "重新读取", "primary", s.phase === "loading" || s.phase === "forbidden")}</div>` : `<h2>${tabs[s.tab]}</h2><p class="small">${s.tab === "runs" ? `始终为最近 20 次；当前返回 ${s.data.reconciliationRuns.length} 次，通过 ${s.data.reconciliationRuns.filter((r) => r.status === "passed").length} 次，不随证据分页。` : `服务端每页 20 条；当前第 ${s.page} 页，搜索只过滤本页，不请求全局检索。`}</p>${s.tab !== "runs" ? `<div class="toolbar"><div class="search"><label>搜索当前页<input id="search" value="${esc(s.query)}" placeholder="${s.tab === "evidence" ? "来源 / URL / 哈希 / 证据 ID" : "来源 / 指标代码 / 字段 / 问题 ID"}"/></label>${btn("clear-search", "清除")}</div><div class="actions">${btn("refresh", "刷新读取")}${btn("settings", "显示设置")}</div></div>` : ""}${s.runId ? notice("当前仅查看所选核对关联的已加载问题；不是全部异常。") + btn("clear-run", "返回本页全部问题") : ""}${s.tab === "issues" ? `<div class="toolbar"><p>已选 <strong id="selection-count">${selected().length}</strong> 项${s.selected.length > 0 ? "（含筛选隐藏项，预览逐项列明）" : ""}</p><div class="actions">${btn("clear-selection", "清空选择", "", !s.selected.length)}${btn("batch", "批量处理", "primary", !selected().length)}</div></div>` : ""}${list()}${s.tab !== "runs" ? `<div class="pagination"><span>当前显示 ${filtered().length} 条 · 服务端总数 ${s.tab === "evidence" ? s.data.totalEvidence : s.data.totalIssues}</span><div class="actions">${btn("previous", "上一页", "", s.page <= 1)}<span>第 ${s.page} 页</span>${btn("next", "下一页", "", s.page >= Math.ceil((s.tab === "evidence" ? s.data.totalEvidence : s.data.totalIssues) / 20))}</div></div>` : ""}`}</section>${ready ? metrics() : ""}<p class="draft-note">设计原型：不连接 API，不生成授权，不下载原文，不修改问题。模态详情、手机批选、提交范围锁定与独立刷新结果为待审改进，生产尚未修改。</p><details class="scene-review"><summary>审核工具 · 切换场景</summary><label>预览场景<select id="scene-picker">${Object.entries(
          scenes,
        )
          .map(([k, v]) => `<option value="${k}">${esc(v)}</option>`)
          .join("")}</select></label></details></main></div>`;
      bind();
    }
    const on = (id, fn, event = "click") =>
      document.getElementById(id)?.addEventListener(event, fn);
    function open(kind, item = s.item) {
      if (!modal.open)
        opener =
          document.activeElement !== document.body
            ? document.activeElement
            : document.querySelector(`[data-tab="${s.tab}"]`);
      serial++;
      s.item = item;
      dialogKind = kind;
      s.detailPhase = "ready";
      drawDialog();
      if (!modal.open) modal.showModal();
      focusDialog();
    }
    function focusDialog() {
      (
        modal.querySelector("textarea,input:not([type=checkbox]),select") ||
        modal.querySelector("button")
      )?.focus();
      modal.scrollTop = 0;
    }
    function close() {
      if (s.pending) return;
      modal.close();
      dialogKind = "";
      serial++;
      const previous = opener;
      if (previous?.isConnected && previous !== document.body && !modal.contains(previous))
        previous.focus();
      else document.querySelector(`[data-tab="${s.tab}"]`)?.focus();
    }
    function drawDialog() {
      const i = s.item || O.evidence,
        isBatch = dialogKind.startsWith("batch"),
        isConfirm = dialogKind.endsWith("confirm");
      let title = "",
        desc = "",
        body = "",
        footer = "";
      if (dialogKind === "evidence" || dialogKind === "lineage") {
        title = dialogKind === "lineage" ? "完整证据溯源" : "证据记录";
        desc = "元数据与来源关系，不展示原文或授权字符串。";
        body =
          s.detailPhase !== "ready"
            ? notice(
                s.detailPhase === "loading"
                  ? "正在读取完整溯源…"
                  : "溯源读取失败，未用其他证据内容替代。",
                "warn",
              ) + btn("detail-retry", "重试读取", "", s.detailPhase === "loading")
            : kv([
                ["来源", i.provider_name],
                ["规范 URL", i.canonical_url],
                ["格式 / 大小", `${i.content_type} / ${(i.size_bytes / 1024).toFixed(1)} KB`],
                ["捕获时间", time(i.captured_at)],
                ["保留期限", `${time(i.retention_until)} · ${retention(i)}`],
                ["解析 / 适配版本", `${i.parser_version} / ${i.adapter_version}`],
              ]) +
              (dialogKind === "lineage"
                ? `<section><h3>01 · 规范记录版本</h3>${O.lineage.normalized_records
                    .map((r) =>
                      kv([
                        ["记录键", r.record_key],
                        ["记录 / Schema 版本", `${r.record_version} / ${r.schema_version}`],
                        ["状态", r.status],
                      ]),
                    )
                    .join("")}</section><section><h3>02 · 字段溯源</h3>${O.lineage.field_provenance
                    .map((p) =>
                      kv([
                        ["字段", p.field_path],
                        ["原文路径", p.source_path],
                        ["变换版本", p.transform_version],
                        ["原值摘要", p.source_value_sha256],
                      ]),
                    )
                    .join(
                      "",
                    )}</section><section><h3>03 · 关联质量问题</h3><p>${O.lineage.quality_issues.length} 项 · 标题准确率 · 待处理</p><p class="small">现有详情响应包含此数组，旧内嵌详情未渲染；此只读区为提案。</p></section>`
                : "") +
              technical(i, [
                "id",
                "organization_id",
                "workspace_id",
                "content_sha256",
                "parser_version",
                "request_id",
                "trace_id",
              ]);
        footer =
          (dialogKind === "evidence" ? btn("full-lineage", "完整溯源") : "") +
          btn("grant", "受控下载", "primary", s.detailPhase !== "ready");
      } else if (dialogKind === "issue") {
        title = labels[i.metric_code] || i.metric_code;
        desc = "查看问题事实与版本，解决不会改写原始证据或历史核对。";
        body =
          kv([
            ["来源", i.provider_name],
            ["字段 / 解析器", `${i.field_path ?? "—"} / ${i.parser_version ?? "—"}`],
            ["状态 / 严重度", `${states[i.status]} / ${states[i.severity]}`],
            ["实际 / 阈值", `${pct(i.actual_value)} / ${pct(i.threshold_value)}`],
            ["指派成员", i.assigned_member_label || "未指派"],
            ["归因原因", i.attribution_reason ?? "—"],
            ["解决原因", i.resolution_reason ?? "—"],
            ["版本 / 更新时间", `${i.version} / ${time(i.updated_at)}`],
          ]) + technical(i, ["id"]);
        footer =
          (i.raw_evidence_id ? btn("issue-evidence", "关联证据") : "") +
          btn("single-resolve", "记录解决", "primary", i.status !== "open");
      } else if (dialogKind === "download") {
        title = "受控原文下载";
        desc = "签发授权与实际访问分别审计，签发成功不等于下载成功。";
        body =
          kv([
            ["证据", i.id],
            ["来源", i.provider_name],
            ["范围", "绑定组织、工作区、证据和存储路径"],
            ["校验", "有效状态、授权期限、字节数与 SHA-256"],
          ]) +
          notice(s.result || "本地演示只记录下载意图，不产生真实 grant、文件或访问审计。") +
          notice(s.notice, "warn");
        footer = btn(
          "grant-submit",
          s.pending ? "签发中…" : "演示授权签发",
          "primary",
          !!s.pending || s.result.includes("未知") || s.result.includes("签发完成"),
        );
      } else if (dialogKind === "settings") {
        title = "显示设置";
        desc = "只影响本次原型显示，不持久化，也不改变服务端范围。";
        body = `<div class="settings">${["主要记录", "格式或字段", "状态与时间", "范围或责任", "操作"].map((t, n) => `<label class="check"><input type="checkbox" data-column="${n}" ${s.columns[n] ? "checked" : ""}/> ${t}</label>`).join("")}</div><label class="check"><input type="checkbox" id="compact" ${s.compact ? "checked" : ""}/>紧凑行距（热区仍为 44px）</label><label class="check"><input type="checkbox" id="freeze" ${s.freeze ? "checked" : ""}/>冻结首个可见列</label><p class="small">手机使用完整记录卡片，不隐藏业务字段。</p>`;
      } else {
        title = isBatch
          ? isConfirm
            ? "确认批量处理"
            : "批量处理范围与原因"
          : isConfirm
            ? "确认记录解决"
            : "记录解决原因";
        desc = "只更新问题并追加事件与 Outbox；原始证据、规范版本和历史核对不删除、不覆盖。";
        const targets = isConfirm
          ? s.snapshot.items.map((t) => s.snapshot.rows.find((r) => r.id === t.id))
          : isBatch
            ? selected()
            : [i];
        body = `<div class="steps"><span>01 范围</span><span>02 原因</span><span>03 短语确认</span></div><section><h3>本次处理 ${targets.length} 个问题</h3>${targets.map((t) => `<p class="small">${esc(t.id)} · 版本 ${t.version} · ${esc(t.provider_name)}</p>`).join("")}<p class="small">包含筛选隐藏项；不自动扩大或缩小处理范围。</p></section>`;
        if (isConfirm) {
          const snap = s.snapshot;
          body +=
            kv([
              ["操作", snap.action === "resolve" ? "记录解决" : actions[snap.action]],
              ["处理原因", snap.reason],
              ["成员", snap.assigneeLabel || "不适用"],
            ]) +
            notice(
              "任一问题已变化或不再开放时，整批拒绝；指派还需验证全部记录所属组织的活动成员。",
            ) +
            `<label>输入“${isBatch ? "确认处理" : "确认解决"}”<input id="phrase" value="${esc(s.phrase)}" autocomplete="off"/></label><p class="small">此合同仅输入短语，不额外增加影响勾选。</p>` +
            notice(s.notice, "warn") +
            notice(s.result);
          footer =
            btn("back-form", "返回修改", "", !!s.pending) +
            btn(
              "submit",
              s.pending ? "处理中…" : "确认提交（模拟）",
              "primary",
              !!s.pending || s.phrase !== (isBatch ? "确认处理" : "确认解决") || !!s.result,
            );
        } else {
          body +=
            (isBatch
              ? `<label>处理动作<select id="batch-action">${Object.entries(actions)
                  .map(
                    ([k, v]) =>
                      `<option value="${k}" ${s.action === k ? "selected" : ""}>${v}</option>`,
                  )
                  .join("")}</select></label>${
                  s.action === "assign"
                    ? `<label>同组织活动成员<select id="assignee"><option value="">请选择成员</option>${(
                        s.data.memberOptions || []
                      )
                        .filter(
                          (m) =>
                            targets.length &&
                            targets.every((t) => t.organization_id === m.organization_id),
                        )
                        .map(
                          (m) =>
                            `<option value="${esc(m.id)}" ${s.assignee === m.id ? "selected" : ""}>${esc(m.label)}</option>`,
                        )
                        .join(
                          "",
                        )}</select></label><p class="small">原始夹具没有成员选项；演示成员均单独标记为合成。</p>`
                    : ""
                }`
              : "") +
            `<label>处理原因（2–500 字）<textarea id="reason" maxlength="500" placeholder="说明处理方式与核对依据">${esc(s.reason)}</textarea></label><p id="reason-count" class="small">${s.reason.length}/500</p>` +
            notice(s.notice, "warn");
          footer = btn(
            "preview",
            "确认前检查",
            "primary",
            s.reason.trim().length < 2 ||
              targets.length < 1 ||
              targets.length > 50 ||
              (isBatch &&
                s.action === "assign" &&
                !(s.data.memberOptions || []).some(
                  (m) =>
                    m.id === s.assignee &&
                    targets.every((t) => t.organization_id === m.organization_id),
                )),
          );
        }
      }
      modal.innerHTML = `<header><div><p class="eyebrow">证据与质量 / 受控工作区</p><h2 id="dialog-title">${esc(title)}</h2></div>${btn("close-dialog", "关闭", "", !!s.pending)}</header><p id="dialog-description" class="muted">${esc(desc)}</p>${body}<footer>${footer}${btn("cancel", "取消 / 返回", "", !!s.pending)}</footer>`;
      on("close-dialog", close);
      on("cancel", close);
      on(
        "copy-intent",
        () =>
          (document.querySelector("#copy-message").textContent =
            "模拟：复制不可用，请手动选择编号；没有访问系统剪贴板。"),
      );
      on("full-lineage", () => open("lineage", s.item));
      on("issue-evidence", () => open("lineage", O.evidence));
      on("single-resolve", () => {
        s.reason = "";
        open("resolve", s.item);
      });
      on("grant", () => {
        s.notice = "";
        s.result = "";
        open("download", s.item);
      });
      on("grant-submit", () => {
        if (s.pending) return;
        s.pending = { token: ++serial, kind: "download", id: s.item.id };
        s.downloads++;
        drawDialog();
      });
      on("detail-retry", () => {
        s.detailPhase = "loading";
        drawDialog();
      });
      on(
        "reason",
        () => {
          s.reason = document.querySelector("#reason").value;
          document.querySelector("#reason-count").textContent = `${s.reason.length}/500`;
          const t = dialogKind === "batch" ? selected() : [s.item];
          document.querySelector("#preview").disabled =
            s.reason.trim().length < 2 ||
            t.length < 1 ||
            t.length > 50 ||
            (dialogKind === "batch" &&
              s.action === "assign" &&
              !(s.data.memberOptions || []).some(
                (m) =>
                  m.id === s.assignee && t.every((i) => i.organization_id === m.organization_id),
              ));
        },
        "input",
      );
      on(
        "batch-action",
        () => {
          s.action = document.querySelector("#batch-action").value;
          s.assignee = "";
          drawDialog();
          document.querySelector("#batch-action").focus();
        },
        "change",
      );
      on(
        "assignee",
        () => {
          s.assignee = document.querySelector("#assignee").value;
          drawDialog();
          document.querySelector("#assignee").focus();
        },
        "change",
      );
      on("preview", () => {
        const batch = dialogKind === "batch",
          rows = clone(batch ? selected() : [s.item]);
        if (
          !rows.length ||
          rows.length > 50 ||
          s.reason.trim().length < 2 ||
          s.reason.trim().length > 500
        )
          return;
        const member = (s.data.memberOptions || []).find(
          (m) => m.id === s.assignee && rows.every((i) => i.organization_id === m.organization_id),
        );
        if (batch && s.action === "assign" && !member) return;
        s.snapshot = {
          items: rows.map((i) => ({ id: i.id, expected_version: i.version })),
          rows,
          action: batch ? s.action : "resolve",
          reason: s.reason.trim(),
          assignee_membership_id: batch && s.action === "assign" ? s.assignee : null,
          assigneeLabel: member?.label,
        };
        s.phrase = "";
        s.result = "";
        s.notice = "";
        open(batch ? "batch-confirm" : "resolve-confirm", s.item);
      });
      on(
        "phrase",
        () => {
          s.phrase = document.querySelector("#phrase").value;
          document.querySelector("#submit").disabled =
            !!s.pending ||
            s.phrase !== (dialogKind === "batch-confirm" ? "确认处理" : "确认解决") ||
            !!s.result;
        },
        "input",
      );
      on("back-form", () => {
        s.phrase = "";
        open(isBatch ? "batch" : "resolve", s.item);
      });
      on("submit", () => {
        if (s.pending || s.result || s.phrase !== (isBatch ? "确认处理" : "确认解决")) return;
        s.pending = { token: ++serial, kind: "write", snapshot: clone(s.snapshot) };
        const p = s.pending.snapshot;
        s.writes.push(
          p.action === "resolve"
            ? {
                path: `/platform/data-quality/issues/${p.items[0].id}/resolve`,
                body: { reason: p.reason, expected_version: p.items[0].expected_version },
              }
            : {
                path: "/platform/data-quality/issues/batch",
                body: {
                  items: p.items,
                  action: p.action,
                  reason: p.reason,
                  assignee_membership_id: p.assignee_membership_id,
                },
              },
        );
        drawDialog();
      });
      modal.querySelectorAll("[data-column]").forEach((n) =>
        n.addEventListener("change", () => {
          const k = Number(n.dataset.column);
          if (!n.checked && s.columns.filter(Boolean).length === 1) {
            n.checked = true;
            return;
          }
          s.columns[k] = n.checked;
          render();
        }),
      );
      for (const k of ["compact", "freeze"])
        on(
          k,
          () => {
            s[k] = document.getElementById(k).checked;
            render();
          },
          "change",
        );
    }
    function bind() {
      document.querySelectorAll("[data-tab]").forEach((n) =>
        n.addEventListener("click", () => {
          s.tab = n.dataset.tab;
          s.page = 1;
          s.query = "";
          s.runId = "";
          s.selected = [];
          render();
        }),
      );
      on(
        "search",
        () => {
          s.query = document.querySelector("#search").value;
          const start = document.querySelector("#search").selectionStart;
          render();
          const q = document.querySelector("#search");
          q.focus();
          q.setSelectionRange(start, start);
        },
        "input",
      );
      on("clear-search", () => {
        s.query = "";
        render();
        document.querySelector("#search").focus();
      });
      on("clear-run", () => {
        s.runId = "";
        render();
      });
      on("refresh", () => {
        s.notice = "读取中；仍显示上一份成功快照及其页码。";
        s.pending = { token: ++serial, kind: "read" };
        render();
      });
      on("retry", () => {
        s.phase = "loading";
        s.pending = { token: ++serial, kind: "read" };
        render();
      });
      on("settings", () => open("settings"));
      on("batch", () => {
        s.action = "attribute";
        s.reason = "";
        s.assignee = "";
        s.notice = "";
        open("batch");
      });
      on("clear-selection", () => {
        s.selected = [];
        render();
      });
      document.querySelectorAll("[data-select]").forEach((n) =>
        n.addEventListener("change", () => {
          const id = n.dataset.select;
          s.selected = n.checked
            ? [...new Set([...s.selected, id])]
            : s.selected.filter((v) => v !== id);
          render();
        }),
      );
      if (s.tab !== "runs")
        filtered().forEach((i, n) => {
          for (const key of ["evidence", "mobile-evidence"])
            on(`${key}-${n}`, () => open("evidence", i));
          for (const key of ["issue", "mobile-issue"]) on(`${key}-${n}`, () => open("issue", i));
          on(`lineage-${n}`, () => open("lineage", i));
          on(`related-${n}`, () => open("lineage", O.evidence));
          on(`resolve-${n}`, () => {
            s.reason = "";
            s.notice = "";
            open("resolve", i);
          });
          on(`download-${n}`, () => {
            s.notice = "";
            s.result = "";
            open("download", i);
          });
        });
      s.data.reconciliationRuns.forEach((r, n) =>
        on(`drill-${n}`, () => {
          s.tab = "issues";
          s.runId = r.id;
          s.query = "";
          render();
        }),
      );
      on("previous", () => pageIntent(s.page - 1));
      on("next", () => pageIntent(s.page + 1));
      on("scene-picker", () => scene(document.querySelector("#scene-picker").value), "change");
    }
    function pageIntent(page) {
      if (s.pending) return;
      s.pending = { token: ++serial, kind: "page", page };
      s.notice = `正在读取第 ${page} 页；当前仍是第 ${s.page} 页快照。`;
      render();
    }
    function complete(outcome, token = s.pending?.token) {
      if (!s.pending || s.pending.token !== token) return;
      const p = s.pending;
      s.pending = null;
      if (p.kind === "download")
        s.result =
          outcome === "success"
            ? "模拟授权签发完成；实际下载、字节数及 SHA-256 均未验证。"
            : outcome === "unknown"
              ? "签发结果未知；不自动重新签发。先核对请求记录。"
              : "授权被拒绝或依赖不可用；未生成本地授权。";
      else if (p.kind === "write") {
        if (outcome === "unknown")
          s.result = "处理结果未知；保留固定请求范围，不自动重发。请先核对问题版本与操作记录。";
        else if (outcome === "conflict") {
          s.result = "版本冲突后请关闭并刷新，重新选择范围。";
          s.notice = "版本或成员资格冲突，整批未执行。刷新后重新选择范围与原因。";
        } else {
          s.result = "模拟写入已确认；本地未写入任何事件或审计。";
          s.notice =
            outcome === "read-failed"
              ? "随后读取失败，页面仍为旧快照；不要再次提交已确认的操作。"
              : "模拟重新读取完成；不代表真实数据已更新。";
        }
      } else if (outcome === "success") {
        s.phase = "ready";
        s.notice = "模拟读取完成";
        s.selected = [];
        if (p.kind === "page") {
          s.page = p.page;
          s.data.evidence =
            p.page === 2
              ? [clone(O.evidence)]
              : Array.from({ length: 20 }, (_, n) => ({
                  ...clone(O.evidence),
                  id: `synthetic-page-${n}`,
                }));
          s.data.issues =
            p.page === 2
              ? [clone(O.issue)]
              : Array.from({ length: 20 }, (_, n) => ({
                  ...clone(O.issue),
                  id: `synthetic-page-issue-${n}`,
                }));
        }
      } else {
        s.notice = "读取失败；保留上一份快照、原页码与观测时间。";
        if (s.phase === "loading") s.phase = "blocked";
      }
      render();
      if (modal.open) drawDialog();
    }
    modal.addEventListener("cancel", (e) => {
      e.preventDefault();
      close();
    });
    modal.addEventListener("click", (e) => {
      if (e.target !== modal) return;
      const r = modal.getBoundingClientRect();
      if (e.clientX < r.left || e.clientX > r.right || e.clientY < r.top || e.clientY > r.bottom)
        close();
    });
    modal.addEventListener("keydown", (e) => {
      if (e.key !== "Tab") return;
      const nodes = [
        ...modal.querySelectorAll(
          "button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),summary",
        ),
      ].filter((n) => n.getClientRects().length);
      if (!nodes.length) {
        e.preventDefault();
        return;
      }
      if (e.shiftKey && document.activeElement === nodes[0]) {
        e.preventDefault();
        nodes.at(-1).focus();
      } else if (!e.shiftKey && document.activeElement === nodes.at(-1)) {
        e.preventDefault();
        nodes[0].focus();
      }
    });
    const scenes = {
      default: "证据 / 原始夹具",
      issues: "问题 / 原始夹具",
      runs: "核对 / 原始夹具",
      "metrics-mixed": "七指标混合状态（合成）",
      "metrics-empty": "七指标均缺失（合成）",
      "risk-expired": "当前页已到期（合成）",
      "risk-unknown": "观测缺失 / 风险未知（合成）",
      "local-empty": "本地搜索无结果",
      "run-empty": "核对下钻无本页匹配",
      "run-match": "核对下钻有匹配",
      "selection-hidden": "隐藏选择仍在预览范围",
      "issue-resolved": "已解决 / 原因与责任（合成）",
      "issue-null": "缺少关联及数值（合成）",
      "evidence-detail": "证据完整记录",
      lineage: "完整溯源",
      "lineage-technical": "完整溯源 / 技术标识展开",
      "issue-technical": "问题 / 技术标识展开",
      "copy-failed": "技术编号 / 复制失败模拟",
      "lineage-loading": "溯源读取中",
      "lineage-error": "溯源失败",
      "long-lineage": "长中文 / URL 与技术标识",
      "issue-detail": "质量问题详情",
      "download-ready": "受控下载说明",
      "download-busy": "授权签发中",
      "download-success": "签发不等于下载完成",
      "download-unknown": "授权结果未知",
      "download-error": "授权拒绝 / 依赖失败",
      "download-expired": "服务合同 / 授权失效 403",
      "download-missing": "服务合同 / 证据不存在或非活动 404",
      "download-integrity": "服务合同 / 完整性失败 409",
      "download-no-key": "服务合同 / 未配置签名 503",
      "resolve-empty": "解决原因 / 空",
      "resolve-short": "解决原因 / 1 字禁用",
      "resolve-valid": "解决原因 / 可预检查",
      "resolve-limit": "解决原因 / 500 字",
      "resolve-confirm": "解决 / 短语待输入",
      "resolve-ready": "解决 / 短语正确",
      "resolve-busy": "解决 / 提交中",
      "resolve-conflict": "解决 / 版本冲突",
      "resolve-unknown": "解决 / 结果未知",
      "resolve-read-failed": "解决写成功 / 读取失败",
      "resolve-success": "解决 / 模拟反馈",
      "batch-attribute": "批量归因",
      "batch-assign": "批量指派（合成成员）",
      "batch-assign-confirm": "批量指派 / 固定成员确认",
      "batch-no-member": "无可用同组织成员",
      "batch-close": "批量解决",
      "batch-close-confirm": "批量解决 / 固定范围确认",
      "batch-confirm": "批处理 / 范围确认",
      "batch-ready": "批处理 / 短语正确",
      "batch-busy": "批处理 / 提交中",
      "batch-conflict": "批处理 / 整批冲突",
      "batch-unknown": "批处理 / 结果未知",
      "batch-read-failed": "批处理写成功 / 读取失败",
      "batch-success": "批处理 / 模拟反馈",
      "page-first": "20/21 条分页（合成）",
      "page-last": "最后 1/21 条（合成）",
      "page-wait": "翻页中保留原页",
      "page-failed": "翻页失败保留原页",
      settings: "列 / 密度 / 冻结设置",
      compact: "紧凑列表",
      dark: "深色主题草案",
      contrast: "高对比主题草案",
      loading: "首次加载",
      empty: "全空",
      expired: "会话过期",
      forbidden: "无权限",
      blocked: "依赖受阻",
      error: "首次错误",
      hover: "按钮悬停",
      focus: "按钮键盘焦点",
      pressed: "按钮按下",
    };
    function scene(key) {
      if (!scenes[key]) throw new Error("Unknown scene");
      modal.close();
      dialogKind = "";
      serial++;
      s = initial();
      if (["loading", "empty", "expired", "forbidden", "blocked", "error"].includes(key))
        s.phase = key;
      if (
        key === "issues" ||
        key.startsWith("issue-") ||
        key.startsWith("resolve-") ||
        key.startsWith("batch-") ||
        key === "selection-hidden"
      )
        s.tab = "issues";
      if (key === "runs") s.tab = "runs";
      if (key === "metrics-mixed") {
        s.synthetic = true;
        s.data.reconciliationRuns = [
          {
            ...O.run,
            metrics: codes.map((code, n) => ({
              code,
              value: n === 5 ? 0.04 : 0.97,
              threshold: n === 5 ? 0.05 : 0.98,
              status: ["passed", "failed", "insufficient_sample"][n % 3],
              denominator: n === 2 ? 3 : 100,
            })),
          },
        ];
      }
      if (key === "metrics-empty") {
        s.synthetic = true;
        s.data.reconciliationRuns = [];
      }
      if (key === "risk-expired") {
        s.synthetic = true;
        s.data.observedAt = O.evidence.retention_until;
      }
      if (key === "risk-unknown") {
        s.synthetic = true;
        s.data.observedAt = "";
      }
      if (key === "local-empty") s.query = "未匹配样例";
      if (key.startsWith("run-")) {
        s.tab = "issues";
        s.runId = key === "run-match" ? O.run.id : "synthetic-other-run";
        s.synthetic = key === "run-empty";
      }
      if (key === "selection-hidden") {
        s.selected = [O.issue.id];
        s.query = "未匹配样例";
      }
      if (key === "issue-resolved") {
        s.synthetic = true;
        Object.assign(s.data.issues[0], {
          status: "resolved",
          version: 2,
          assigned_member_label: "reviewer@example.test",
          attribution_reason: "合成：解析字段差异",
          resolution_reason: "合成：依据原文完成核对",
        });
      }
      if (key === "issue-null") {
        s.synthetic = true;
        Object.assign(s.data.issues[0], {
          raw_evidence_id: null,
          actual_value: null,
          threshold_value: null,
          parser_version: null,
          field_path: null,
        });
      }
      if (key.startsWith("page-")) {
        s.synthetic = true;
        s.data.totalEvidence = 21;
        s.data.totalIssues = 21;
        if (key !== "page-last") {
          s.data.evidence = Array.from({ length: 20 }, (_, n) => ({
            ...O.evidence,
            id: `synthetic-page-${n}`,
          }));
        } else s.page = 2;
      }
      if (key === "compact") s.compact = true;
      if (key === "dark" || key === "contrast") s.theme = key;
      render();
      if (key === "evidence-detail") open("evidence", O.evidence);
      if (["lineage", "lineage-loading", "lineage-error", "long-lineage"].includes(key)) {
        const item = clone(O.evidence);
        if (key === "long-lineage") {
          s.synthetic = true;
          item.provider_name = "长中文来源名称与受控证据核验场景".repeat(8);
          item.canonical_url = "https://example.test/" + "long-evidence-path-".repeat(30);
          render();
        }
        open("lineage", item);
        if (key !== "lineage" && key !== "long-lineage") {
          s.detailPhase = key === "lineage-loading" ? "loading" : "error";
          drawDialog();
        }
      }
      if (key.startsWith("issue-") && key !== "issues") open("issue", s.data.issues[0]);
      if (key.startsWith("download-")) {
        open("download", O.evidence);
        if (key !== "download-ready") {
          document.querySelector("#grant-submit").click();
          if (key !== "download-busy") complete(key.slice(9));
          const contractFailures = {
            "download-expired": "403：授权无效、过期或绑定不符，服务要求重新申请短时授权。",
            "download-missing": "404：证据不存在或非活动，先刷新并核对证据状态。",
            "download-integrity": "409：大小或 SHA-256 不符，停止使用并联系平台管理员隔离核查。",
            "download-no-key":
              "503：未配置签名密钥，联系管理员在宝塔受限环境配置；不要把密钥填入浏览器。",
          };
          if (contractFailures[key]) {
            s.result = "仅演示服务错误合同；没有执行下载。";
            s.notice =
              contractFailures[key] + " 原导航下载不回传此结果到面板；这不是现有应用内错误回执。";
            drawDialog();
          }
        }
      }
      if (key.startsWith("resolve-") || key.startsWith("batch-")) {
        const batch = key.startsWith("batch-");
        s.selected = [O.issue.id];
        s.item = O.issue;
        s.reason = ["resolve-empty", "resolve-short"].includes(key)
          ? key === "resolve-short"
            ? "字"
            : ""
          : key === "resolve-limit"
            ? "字".repeat(500)
            : "已按原文重新核对标题字段";
        if (key === "batch-assign" || key === "batch-assign-confirm") {
          s.synthetic = true;
          s.action = "assign";
          s.data.memberOptions = [
            {
              id: "00000000-0000-4000-8000-000000000b01",
              organization_id: O.ids.org,
              label: "合成成员 · reviewer@example.test",
            },
          ];
          s.assignee = s.data.memberOptions[0].id;
        }
        if (key === "batch-no-member") s.action = "assign";
        if (key === "batch-close" || key === "batch-close-confirm") s.action = "close";
        render();
        open(batch ? "batch" : "resolve", O.issue);
        const suffix = ["batch-assign-confirm", "batch-close-confirm"].includes(key)
          ? "confirm"
          : key.slice(batch ? 6 : 8);
        if (
          ["confirm", "ready", "busy", "conflict", "unknown", "read-failed", "success"].includes(
            suffix,
          )
        ) {
          document.querySelector("#preview").click();
          if (suffix !== "confirm") {
            s.phrase = batch ? "确认处理" : "确认解决";
            drawDialog();
          }
          if (["busy", "conflict", "unknown", "read-failed", "success"].includes(suffix)) {
            document.querySelector("#submit").click();
            if (suffix !== "busy") complete(suffix);
          }
        }
      }
      if (key === "settings") open("settings");
      if (["lineage-technical", "copy-failed"].includes(key)) open("lineage", O.evidence);
      if (["lineage-technical", "issue-technical", "copy-failed"].includes(key)) {
        modal.querySelector(".technical").open = true;
        if (key === "copy-failed") document.querySelector("#copy-intent").click();
      }
      if (key === "focus") document.querySelector("#refresh").focus();
      if (key === "page-wait" || key === "page-failed") {
        pageIntent(2);
        if (key === "page-failed") complete("error");
      }
    }
    window.DATA_QUALITY_C = {
      scenes,
      scene,
      complete,
      state: () => clone(s),
      close,
      open,
      detailComplete: (token, outcome) => {
        if (token !== serial || !modal.open || dialogKind !== "lineage") return;
        s.detailPhase = outcome;
        drawDialog();
      },
      token: () => serial,
    };
    scene("default");
  })();
};
