import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

const required=["database/migrations/0033_file_resilience_m08_04.up.sql","database/migrations/0033_file_resilience_m08_04.down.sql","apps/api/src/file-resilience-probe.ts","apps/api/src/file-resilience-service.ts","apps/api/src/file-resilience-repository.ts","apps/api/src/file-resilience-routes.ts","apps/web/src/components/FileResilienceCenter.vue","apps/web/src/file-resilience.css","infra/baota/local-file-storage-manifest.json","verification/file-resilience-production-evidence.schema.json","scripts/verify-file-resilience-production.mjs","scripts/verify-file-resilience-live.mjs","docs/architecture/m08-04-file-resilience.md","docs/runbooks/m08-04-file-resilience.md","tests/e2e/m08-04-file-resilience.spec.ts","verification/modules/M08-04.json"];
test("M08-04.A01-A17 deliver a BaoTa-only local-file resilience boundary",async()=>{const all=(await Promise.all(required.map(path=>readFile(path,"utf8")))).join("\n");for(const token of ["M08-04","local_managed_directories","checksum","organization","platform:operate","request_id","trace_id","rollback","baota"])assert.match(all,new RegExp(token,"i"));assert.doesNotMatch(all,/NFS|Ceph|MinIO|systemctl\s|pm2\s+start|docker(?:-|\s)compose\s+up/i);});

test("M08-04.A02/A04/A12 evaluates roots integrity capacity and explicit recovery facts",async()=>{const {evaluateFileResilience}=await import("../../packages/storage/dist/index.js");const policy={usageWarningBasisPoints:7500,usageStopBasisPoints:9000,maximumRecoveryDrillAgeDays:90};const root=(kind,availableBytes=800)=>({kind,available:true,writable:true,totalBytes:1000,availableBytes,activeFiles:1,indexedBytes:10});const base={roots:[root("evidence"),root("export")],checksumSampledFiles:2,checksumVerifiedFiles:2,checksumMismatchFiles:0,missingFiles:0,recoveryStatus:"verified",encryptedSameHostCopy:true,isolatedRestoreVerified:true,recoveryDrillAgeDays:1,publicDirectoryExposed:false,sharedStorageEnabled:false,backupServerUsed:false};assert.equal(evaluateFileResilience(base,policy).state,"ready");const warning=evaluateFileResilience({...base,roots:[root("evidence",200),root("export")]},policy);assert.equal(warning.state,"warning");assert.ok(warning.findings.some(item=>item.code==="file_capacity_warning"));const blocked=evaluateFileResilience({...base,checksumMismatchFiles:1,encryptedSameHostCopy:false},policy);assert.equal(blocked.state,"blocked");assert.ok(blocked.findings.some(item=>item.code==="file_checksum_mismatch"));assert.ok(blocked.findings.some(item=>item.code==="file_recovery_unverified"));assert.throws(()=>evaluateFileResilience(base,{...policy,usageWarningBasisPoints:9000}),/warning threshold/);});

test("M08-04.A04/A06/A09 service and operations route preserve explicit recovery truth and authorization",async()=>{const {FileResilienceService}=await import("../../apps/api/dist/file-resilience-service.js");const snapshot={roots:[{kind:"evidence",available:true,writable:true,totalBytes:1000,availableBytes:900,activeFiles:1,indexedBytes:10},{kind:"export",available:true,writable:true,totalBytes:1000,availableBytes:900,activeFiles:1,indexedBytes:10}],checksumSampledFiles:2,checksumVerifiedFiles:2,checksumMismatchFiles:0,missingFiles:0,recoveryStatus:"blocked",encryptedSameHostCopy:true,isolatedRestoreVerified:false,recoveryDrillAgeDays:1,publicDirectoryExposed:false,sharedStorageEnabled:false,backupServerUsed:false};const recorded=[];const service=new FileResilienceService({snapshot:async()=>snapshot},{record:async input=>recorded.push(input)},{usageWarningBasisPoints:7500,usageStopBasisPoints:9000,maximumRecoveryDrillAgeDays:90},()=>new Date("2026-08-15T08:00:00.000Z"));const dto=await service.read({actorId:"actor",requestId:"request",traceId:"trace"});assert.equal(dto.state,"blocked");assert.equal(dto.recovery.encrypted_same_host_copy,true);assert.equal(dto.recovery.isolated_restore_verified,false);assert.equal(recorded.length,1);
  const {buildApp}=await import("../../apps/api/dist/app.js");const calls=[];const routeService={read:async input=>{calls.push(["read",input]);return dto;}};const authorization={authorize:async input=>calls.push(["authorize",input])};const auth={authenticate:async()=>({user:{id:"00000000-0000-4000-8000-000000000804"},session:{id:"session"}})};const app=buildApp({fileResilience:{service:routeService,authorization,auth,secureCookie:false}});const response=await app.inject({method:"GET",url:"/api/v1/platform/operations/files",headers:{cookie:"scoutops_session=test","x-request-id":"file-request","x-trace-id":"file-trace"}});assert.equal(response.statusCode,200);assert.equal(response.headers["cache-control"],"private, no-store");assert.equal(calls[0][1].capability,"platform:operate");assert.equal(calls[1][1].requestId,"file-request");assert.doesNotMatch(response.body,/EVIDENCE_ROOT|EXPORT_ROOT|content_sha256|organizations\//i);await app.close();});

test("M08-04.A03/A05/A10/A13 migration config worker and manifests stay MySQL57 and backend-only",async()=>{const [{loadRuntimeConfig},up,down,worker,rollout,schema,env,openapi,featureMap,manifest,evidenceSchema]=await Promise.all([import("../../packages/config/dist/index.js"),...[
  "database/migrations/0033_file_resilience_m08_04.up.sql","database/migrations/0033_file_resilience_m08_04.down.sql","apps/worker/src/report-export-worker.ts","scripts/run-baota-release-rollout.mjs","config/schema.json","config/env.example","docs/openapi.yaml","docs/feature-map.json","infra/baota/local-file-storage-manifest.json","verification/file-resilience-production-evidence.schema.json"].map(path=>readFile(path,"utf8"))]);assert.match(up,/utf8mb4/);assert.match(up,/content_sha256/);assert.doesNotMatch(up,/CHECK\s*\(|utf8mb4_0900|INVISIBLE\s+INDEX/i);assert.match(down,/DROP COLUMN `content_sha256`/);assert.match(worker,/createHash\("sha256"\)/);assert.match(rollout,/0033_file_resilience_m08_04\.up\.sql/);const config=loadRuntimeConfig({NODE_ENV:"test",FILE_STORAGE_WARNING_PERCENT:"70",FILE_STORAGE_STOP_PERCENT:"85",FILE_STORAGE_CHECKSUM_SAMPLE_LIMIT:"7",FILE_STORAGE_RECOVERY_DRILL_MAX_AGE_DAYS:"60"},"api");assert.equal(config.fileResilience.usageWarningBasisPoints,7000);assert.equal(config.fileResilience.usageStopBasisPoints,8500);assert.equal(config.fileResilience.checksumSampleLimit,7);assert.equal(config.fileResilience.maximumRecoveryDrillAgeDays,60);assert.throws(()=>loadRuntimeConfig({FILE_STORAGE_WARNING_PERCENT:"90",FILE_STORAGE_STOP_PERCENT:"80"},"api"),/FILE_STORAGE/);for(const key of ["FILE_STORAGE_WARNING_PERCENT","FILE_STORAGE_STOP_PERCENT","FILE_STORAGE_CHECKSUM_SAMPLE_LIMIT","FILE_STORAGE_RECOVERY_DRILL_MAX_AGE_DAYS","FILE_STORAGE_PRODUCTION_EVIDENCE_FILE","FILE_STORAGE_EVIDENCE_MAX_AGE_MINUTES"]){assert.match(schema,new RegExp(key));assert.match(env,new RegExp(key));}for(const source of [openapi,featureMap,manifest,evidenceSchema])assert.match(source,/M08-04|file resilience|本机文件韧性/i);});

test("M08-04.A04/A09/A14 persists observation view and audit in one transaction",async()=>{const {FileResilienceRepository}=await import("../../apps/api/dist/file-resilience-repository.js");const calls=[];const connection={beginTransaction:async()=>calls.push("begin"),commit:async()=>calls.push("commit"),rollback:async()=>calls.push("rollback"),release:()=>calls.push("release"),query:async(sql,values=[])=>{assert.equal(values.length,(sql.match(/\?/g)??[]).length,`placeholder mismatch: ${sql}`);calls.push(sql);return[[],[]];}};const repository=new FileResilienceRepository({getConnection:async()=>connection});const root=kind=>({kind,available:true,writable:true,totalBytes:1000,availableBytes:900,activeFiles:1,indexedBytes:10});await repository.record({actorId:"00000000-0000-4000-8000-000000000804",requestId:"request",traceId:"trace",observedAt:new Date("2026-08-15T08:00:00.000Z"),snapshot:{roots:[root("evidence"),root("export")],checksumSampledFiles:2,checksumVerifiedFiles:2,checksumMismatchFiles:0,missingFiles:0,recoveryStatus:"verified",encryptedSameHostCopy:true,isolatedRestoreVerified:true,recoveryDrillAgeDays:1,publicDirectoryExposed:false,sharedStorageEnabled:false,backupServerUsed:false},evaluation:{state:"ready",maximumUsageBasisPoints:1000,findings:[]}});assert.deepEqual(calls.filter(item=>["begin","commit","rollback","release"].includes(item)),["begin","commit","release"]);assert.equal(calls.filter(item=>typeof item==="string"&&item.startsWith("INSERT INTO")).length,3);});

test("M08-04.A07/A08/A15/A16 UI evidence and rollback cover full states and image contract",async()=>{const [ui,e2e,architecture,runbook,verifier]=await Promise.all(["apps/web/src/components/FileResilienceCenter.vue","tests/e2e/m08-04-file-resilience.spec.ts","docs/architecture/m08-04-file-resilience.md","docs/runbooks/m08-04-file-resilience.md","scripts/verify-file-resilience-production.mjs"].map(path=>readFile(path,"utf8")));for(const state of ["loading","ready","warning","blocked","empty","forbidden","expired","rate_limited","unavailable","recovering"])assert.match(ui,new RegExp(state));assert.match(e2e,/390/);for(const image of ["61_平台运营-概览.jpg","64_系统监控.jpg","69_异常告警.jpg","10_霓虹科技平台驾驶舱_dashboard.png"])assert.match(architecture,new RegExp(image.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(runbook,/## 回滚/);assert.match(verifier,/sharedStorageEnabled===false/);assert.doesNotMatch(`${ui}\n${e2e}\n${runbook}`,/共享存储已启用|备用服务器已启用|容量已验证/i);});
