window.SECURITY_DATA = {
  sourcePaths: [
    "apps/web/src/components/SecurityOperationsCenter.vue",
    "apps/api/src/security-operations-service.ts",
    "apps/api/src/mysql-security-operations-repository.ts",
    "apps/api/src/security-operations-routes.ts",
    "apps/web/src/components/ResponsiveDataView.vue",
    "apps/web/src/components/TableViewControls.vue",
    "apps/web/src/api-client.ts",
    "config/route-catalog.json",
    "tests/e2e/m06-04-security-operations.spec.ts",
    "tests/m06-04/security-operations.test.mjs",
  ],
  sourceChecks: [
    "Actual Vue route watcher + pending single-flight reproduces lost credential read, mismatched response view and overwritten page; 15-second timer and 20/20 query sizes.",
    "Actual Vue zero-summary ready behavior preserved; unrelated route watcher and abort-ignoring late response reproduced using manual lifecycle callbacks.",
    "Actual first-read 401/403/429/503/400 state mapping, misleading initial-timeout copy and existing snapshot retained on 403 verified.",
    "Actual URL defaults/view reset, four status menus/search labels, unknown-label fallback, five ResponsiveDataView consumers and three input bindings; missing shared Tab trap is static evidence only.",
    "Actual service 48 window/view/status combinations, query120, bounded independent page sizes/pages and dependency error mapping verified; no service connection.",
    "Actual repository four view branches with inert SQL: separate 20/20 paging/clamp, raw-device-to-coarse-label transform, scope JSON removal, effective-status predicates, escaped query and two read-audit INSERT intents after listing. No SQL/RBAC transaction proof.",
    "Actual route static read-only capability/cache contract; live authentication, row safety and MySQL are not validated by inert adapters.",
  ],
  original: {
    window: "24h",
    summary: {
      security_events: 14,
      risk_events: 2,
      active_sessions: 8,
      active_credentials: 3,
      credentials_expiring: 1,
      active_org_tokens: 5,
    },
    security_events: [
      {
        id: "e1",
        user_id: "00000000-0000-4000-8000-000000000641",
        event_type: "login.failed",
        outcome: "failed",
        request_id: "r",
        trace_id: "trace-0604",
        occurred_at: "2026-08-08T12:00:00Z",
      },
    ],
    sessions: [
      {
        id: "s1",
        user_id: "u1",
        email: "security@example.test",
        status: "active",
        device_label: "Windows Chrome",
        expires_at: "2026-08-09T12:00:00Z",
        last_seen_at: "2026-08-08T12:00:00Z",
        created_at: "2026-08-01T00:00:00Z",
      },
    ],
    credential_assets: [
      {
        id: "c1",
        provider_id: "p1",
        provider_name: "公开趋势 RSS",
        name: "生产读取凭证",
        kind: "api_key",
        key_version: "v3",
        fingerprint: "0123456789abcdef",
        status: "active",
        expires_at: "2026-08-15T00:00:00Z",
        rotated_at: "2026-08-01T00:00:00Z",
        version: 3,
        updated_at: "2026-08-08T00:00:00Z",
      },
    ],
    organization_tokens: [
      {
        id: "t1",
        organization_id: "o1",
        name: "报表客户端",
        token_prefix: "sco_org_public",
        status: "active",
        scopes: ["report:read"],
        expires_at: "2026-09-01T00:00:00Z",
        last_used_at: null,
        version: 1,
        updated_at: "2026-08-08T00:00:00Z",
      },
    ],
    audit_events: [
      {
        id: "a1",
        actor_id: "00000000-0000-4000-8000-000000000642",
        action: "platform.security.operations.read",
        resource_type: "security_operations",
        resource_id: null,
        outcome: "succeeded",
        request_id: "audit-request",
        trace_id: "audit-trace",
        occurred_at: "2026-08-08T12:05:00Z",
      },
    ],
    pagination: {
      security_events: { page: 1, page_size: 20, total: 41, total_pages: 3 },
      sessions: { page: 1, page_size: 20, total: 1, total_pages: 1 },
      credential_assets: { page: 1, page_size: 20, total: 1, total_pages: 1 },
      organization_tokens: { page: 1, page_size: 20, total: 1, total_pages: 1 },
      audit_events: { page: 1, page_size: 20, total: 1, total_pages: 1 },
    },
    links: {
      credential_assets: "/platform-admin/credentials",
      audit_search: "/platform-admin/security?view=audit",
    },
    observed_at: "2026-08-08T12:00:00Z",
  },
  findings: [
    {
      id: "CS-G04",
      title: "快速路由切换丢失目标读取",
      observed:
        "事件读取在途时切到凭证，watch更新activeView但load单飞早退；旧事件响应仍写入，页面目标与data.view不一致。",
      proposal:
        "请求快照、已读范围和草稿分开；新请求序号使旧终态失效，避免将事件结果套进凭证列表。",
    },
    {
      id: "CS-G04-LIFECYCLE",
      title: "缓存路由与忽略abort的迟到响应",
      observed:
        "route watcher未限定本页路径；惰性请求忽略abort时，卸载后结果仍写入ref。成功零摘要保留历史记录的既有修复有效。",
      proposal: "进入/离开与请求终态需要实例归属；惰性复现不是挂载Vue、KeepAlive或真实网络验收。",
    },
    {
      id: "CS-G04-ERROR",
      title: "首次超时与已有快照错误不混淆",
      observed: "首次超时仍提示保留上次成功数据；已有数据时403保留ready与旧记录。",
      proposal: "首次明确没有快照；保留快照的错误说明归属和时点，不擅自改变访问控制合同。",
    },
    {
      id: "CS-G07",
      title: "五类共享详情需完整模态验证",
      observed: "共享详情当前只有Escape/关闭/返焦，没有完整Tab圈定；字段由五个消费者分别提供。",
      proposal: "原型用原生模态及显式焦点循环验证五类；桌面列设置分别归属，不能隐藏令牌分页。",
    },
  ],
  views: {
    events: ["security_events"],
    sessions: ["sessions"],
    credentials: ["credential_assets", "organization_tokens"],
    audit: ["audit_events"],
  },
};
