window.ACCEPTANCE_C_DATA = {
  original: {
    provider_id: "10000000-0000-4000-8000-000000000003",
    source_status: "disabled",
    owner_label: "平台来源中心",
    overall: "setup_required",
    gates: [
      {
        key: "login",
        state: "passed",
        evidence_at: "2026-08-21T07:12:00.000Z",
        reason: "当前有效浏览器档案已完成一次登录态运行。",
      },
      {
        key: "captcha",
        state: "passed",
        evidence_at: "2026-08-21T07:12:00.000Z",
        reason: "最近登录态运行未被验证码阻断。",
      },
      {
        key: "parser",
        state: "pending",
        evidence_at: null,
        reason: "需要用真实登录样本完成当前解析器版本回放。",
      },
    ],
    latest_run: {
      status: "succeeded",
      error_code: null,
      started_at: "2026-08-21T07:10:00.000Z",
      finished_at: "2026-08-21T07:12:00.000Z",
    },
    coverage_matrix: {
      parser_version: "1688-browser-contract-v3",
      observed_at: "2026-08-21T07:12:00.000Z",
      rows: [
        {
          key: "search",
          contract: "1688.search.v1",
          state: "covered",
          observed_count: 12,
          reason: "搜索快照通过当前合同，共 12 条。",
        },
        {
          key: "detail",
          contract: "1688.offer-detail.v1",
          state: "covered",
          observed_count: 3,
          reason: "商品详情快照全部通过当前合同，共 3 条。",
        },
        {
          key: "pagination",
          contract: "browser-plan-pagination-v1",
          state: "not_exercised",
          observed_count: 1,
          reason: "执行计划只允许 1 页，本次未演练翻页。",
        },
      ],
    },
    pending_reasons: ["需要用真实登录样本完成当前解析器版本回放。"],
  },
  pending: {
    provider_id: "10000000-0000-4000-8000-000000000003",
    source_status: "disabled",
    owner_label: "平台来源中心",
    overall: "setup_required",
    gates: [
      {
        key: "login",
        state: "pending",
        evidence_at: null,
        reason: "需要有效浏览器档案并完成一次登录态运行。",
      },
      {
        key: "captcha",
        state: "pending",
        evidence_at: null,
        reason: "尚无可证明验证码未阻断的成功登录态运行。",
      },
      {
        key: "parser",
        state: "pending",
        evidence_at: null,
        reason: "需要用真实登录样本完成当前解析器版本回放并通过人工审批。",
      },
    ],
    latest_run: null,
    coverage_matrix: {
      parser_version: "1688-browser-contract-v3",
      observed_at: null,
      rows: [
        {
          key: "search",
          contract: "1688.search.v1",
          state: "not_observed",
          observed_count: 0,
          reason: "尚无真实浏览器作业可验证搜索覆盖。",
        },
        {
          key: "detail",
          contract: "1688.offer-detail.v1",
          state: "not_observed",
          observed_count: 0,
          reason: "尚无真实浏览器作业可验证详情覆盖。",
        },
        {
          key: "pagination",
          contract: "browser-plan-pagination-v1",
          state: "not_observed",
          observed_count: 0,
          reason: "尚无真实浏览器作业可验证翻页覆盖。",
        },
      ],
    },
    pending_reasons: ["需要有效浏览器档案并完成一次登录态运行。"],
  },
  organizations: [
    {
      id: "00000000-0000-4000-8000-000000000b72",
      name: "一次性验收组织",
      slug: "acceptance-org",
      status: "active",
      default_workspace_id: "00000000-0000-4000-8000-000000000b73",
      membership_status: "active",
    },
  ],
  workspaces: [
    {
      id: "00000000-0000-4000-8000-000000000b73",
      organization_id: "00000000-0000-4000-8000-000000000b72",
      name: "1688 验收工作区",
      slug: "1688-acceptance",
      status: "active",
      version: 1,
    },
  ],
  scheduled: { task_id: "00000000-0000-4000-8000-000000001688", status: "scheduled" },
  variants: {
    "no-profile-draft": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "draft",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要有效浏览器档案并完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "需要有效浏览器档案并完成一次登录态运行。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "no-profile-disabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "disabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要有效浏览器档案并完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "需要有效浏览器档案并完成一次登录态运行。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "no-profile-enabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "enabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要有效浏览器档案并完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "需要有效浏览器档案并完成一次登录态运行。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "no-run-draft": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "draft",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要有效浏览器档案并完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "pending",
          evidence_at: null,
          reason: "尚无可证明验证码未阻断的成功登录态运行。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: null,
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "需要有效浏览器档案并完成一次登录态运行。",
        "尚无可证明验证码未阻断的成功登录态运行。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "no-run-disabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "disabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要有效浏览器档案并完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "pending",
          evidence_at: null,
          reason: "尚无可证明验证码未阻断的成功登录态运行。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: null,
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "需要有效浏览器档案并完成一次登录态运行。",
        "尚无可证明验证码未阻断的成功登录态运行。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "no-run-enabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "enabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要有效浏览器档案并完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "pending",
          evidence_at: null,
          reason: "尚无可证明验证码未阻断的成功登录态运行。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: null,
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "需要有效浏览器档案并完成一次登录态运行。",
        "尚无可证明验证码未阻断的成功登录态运行。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "login-expired-draft": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "draft",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "blocked",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近运行返回登录失效，需要续期档案后重试。",
        },
        {
          key: "captcha",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "尚无可证明验证码未阻断的成功登录态运行。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "blocked",
        error_code: "session_expired",
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "最近运行返回登录失效，需要续期档案后重试。",
        "尚无可证明验证码未阻断的成功登录态运行。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "login-expired-disabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "disabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "blocked",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近运行返回登录失效，需要续期档案后重试。",
        },
        {
          key: "captcha",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "尚无可证明验证码未阻断的成功登录态运行。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "blocked",
        error_code: "session_expired",
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "最近运行返回登录失效，需要续期档案后重试。",
        "尚无可证明验证码未阻断的成功登录态运行。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "login-expired-enabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "enabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "blocked",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近运行返回登录失效，需要续期档案后重试。",
        },
        {
          key: "captcha",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "尚无可证明验证码未阻断的成功登录态运行。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "blocked",
        error_code: "session_expired",
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "最近运行返回登录失效，需要续期档案后重试。",
        "尚无可证明验证码未阻断的成功登录态运行。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "captcha-blocked-draft": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "draft",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要有效浏览器档案并完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "blocked",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近运行被验证码阻断，需要人工完成验证后重试。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "blocked",
        error_code: "captcha",
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "需要有效浏览器档案并完成一次登录态运行。",
        "最近运行被验证码阻断，需要人工完成验证后重试。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "captcha-blocked-disabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "disabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要有效浏览器档案并完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "blocked",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近运行被验证码阻断，需要人工完成验证后重试。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "blocked",
        error_code: "captcha",
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "需要有效浏览器档案并完成一次登录态运行。",
        "最近运行被验证码阻断，需要人工完成验证后重试。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "captcha-blocked-enabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "enabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要有效浏览器档案并完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "blocked",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近运行被验证码阻断，需要人工完成验证后重试。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "blocked",
        error_code: "captcha",
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "需要有效浏览器档案并完成一次登录态运行。",
        "最近运行被验证码阻断，需要人工完成验证后重试。",
        "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
      ],
    },
    "old-parser-draft": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "draft",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason:
            "现有固定样本最近回放使用 1688-browser-contract-v2，需要用真实登录作业创建并回放当前 1688-browser-contract-v3 样本，再由另一名来源管理员审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "现有固定样本最近回放使用 1688-browser-contract-v2，需要用真实登录作业创建并回放当前 1688-browser-contract-v3 样本，再由另一名来源管理员审批。",
      ],
    },
    "old-parser-disabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "disabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason:
            "现有固定样本最近回放使用 1688-browser-contract-v2，需要用真实登录作业创建并回放当前 1688-browser-contract-v3 样本，再由另一名来源管理员审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "现有固定样本最近回放使用 1688-browser-contract-v2，需要用真实登录作业创建并回放当前 1688-browser-contract-v3 样本，再由另一名来源管理员审批。",
      ],
    },
    "old-parser-enabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "enabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason:
            "现有固定样本最近回放使用 1688-browser-contract-v2，需要用真实登录作业创建并回放当前 1688-browser-contract-v3 样本，再由另一名来源管理员审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [
        "现有固定样本最近回放使用 1688-browser-contract-v2，需要用真实登录作业创建并回放当前 1688-browser-contract-v3 样本，再由另一名来源管理员审批。",
      ],
    },
    "parser-changed-draft": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "draft",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "blocked",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要用真实登录样本完成当前解析器版本回放并通过人工审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: ["需要用真实登录样本完成当前解析器版本回放并通过人工审批。"],
    },
    "parser-changed-disabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "disabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "blocked",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要用真实登录样本完成当前解析器版本回放并通过人工审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: ["需要用真实登录样本完成当前解析器版本回放并通过人工审批。"],
    },
    "parser-changed-enabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "enabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "blocked",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "需要用真实登录样本完成当前解析器版本回放并通过人工审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: ["需要用真实登录样本完成当前解析器版本回放并通过人工审批。"],
    },
    "review-pending-draft": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "draft",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: ["当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。"],
    },
    "review-pending-disabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "disabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: ["当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。"],
    },
    "review-pending-enabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "enabled",
      owner_label: "平台来源中心",
      overall: "setup_required",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "pending",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: ["当前解析器版本的固定样本回放已通过，仍需另一名来源管理员完成人工审批。"],
    },
    "all-passed-draft": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "draft",
      owner_label: "平台来源中心",
      overall: "ready_for_enable",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放和人工审批均已通过。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [],
    },
    "all-passed-disabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "disabled",
      owner_label: "平台来源中心",
      overall: "ready_for_enable",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放和人工审批均已通过。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [],
    },
    "all-passed-enabled": {
      provider_id: "10000000-0000-4000-8000-000000000003",
      source_status: "enabled",
      owner_label: "平台来源中心",
      overall: "production_ready",
      gates: [
        {
          key: "login",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前有效浏览器档案已完成一次登录态运行。",
        },
        {
          key: "captcha",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "最近登录态运行未被验证码阻断。",
        },
        {
          key: "parser",
          state: "passed",
          evidence_at: "2026-08-21T07:12:00.000Z",
          reason: "当前解析器版本的固定样本回放和人工审批均已通过。",
        },
      ],
      latest_run: {
        status: "succeeded",
        error_code: null,
        started_at: "2026-08-21T07:12:00.000Z",
        finished_at: "2026-08-21T07:12:00.000Z",
      },
      coverage_matrix: {
        parser_version: "1688-browser-contract-v3",
        observed_at: null,
        rows: [
          {
            key: "search",
            contract: "1688.search.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证搜索覆盖。",
          },
          {
            key: "detail",
            contract: "1688.offer-detail.v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证详情覆盖。",
          },
          {
            key: "pagination",
            contract: "browser-plan-pagination-v1",
            state: "not_observed",
            observed_count: 0,
            reason: "尚无真实浏览器作业可验证翻页覆盖。",
          },
        ],
      },
      pending_reasons: [],
    },
  },
  checks: [
    "Original 2/3 gates and 12/3/1 coverage, independent all-pending fixture, exact links and nine run labels from actual source",
    "Actual active scope/default workspace, trim/exact four-field POST, duplicate guard, one follow-up GET; reproduced scheduled success overwriting failed refresh notice while old facts remain",
    "Eight actual first/existing read error paths, 12-second timer callback, single flight and unmount abort; no real elapsed network timeout or KeepAlive proof",
    "24 actual repository read-method combinations using inert SQL rows; aggregate SQL not executed, coverage adapter deliberately returns no observations; enabled plus setup_required retained, no automatic disabling inferred",
  ],
  sourcePaths: [
    "apps/web/src/components/Alibaba1688AcceptanceCenter.vue",
    "apps/api/src/mysql-provider-source-sample-repository.ts",
    "apps/api/src/provider-source-service.ts",
    "apps/api/src/provider-source-routes.ts",
    "apps/api/src/mysql-provider-source-repository.ts",
    "tests/e2e/m03-07-provider-sources.spec.ts",
  ],
};
