import {createHash,randomUUID} from 'node:crypto';
import type {AuthorizationSurface,Capability,ResourceGrantAuthorizationInput,ResourceGrantAuthorizer} from '@scoutops/authorization';

export const RESOURCE_GRANT_ACTIONS={
 task:['task:read','task:update'],
 opportunity:['opportunity:read','opportunity:decide'],
 competitor:['competitor:read'],
 sourcing:['sourcing:read','supplier_quote:manage','cost:confirm']
} as const satisfies Record<string,readonly Capability[]>;
export type ResourceGrantType=keyof typeof RESOURCE_GRANT_ACTIONS;
export type ResourceGrantAction=(typeof RESOURCE_GRANT_ACTIONS)[ResourceGrantType][number];
export type ResourceGrantStatus='active'|'revoked'|'expired';
export interface ResourceGrant{ id:string;organization_id:string;workspace_id:string;resource_type:ResourceGrantType;resource_id:string;grantee_membership_id:string;grantor_id:string;reason:string;status:'active'|'revoked';expires_at:Date;revoked_at:Date|null;revoked_by:string|null;revocation_reason:string|null;version:number;created_at:Date;updated_at:Date;actions:ResourceGrantAction[];effective_status?:ResourceGrantStatus; }
export interface ResourceGrantAuditEvent{id:string;grant_id:string;organization_id:string;workspace_id:string;actor_id:string;event_type:'created'|'extended'|'revoked'|'expired'|'accessed'|'access_denied';resource_type:ResourceGrantType;resource_id:string;capability:ResourceGrantAction|null;surface:AuthorizationSurface|null;outcome:'allowed'|'denied';reason:string;request_id:string;trace_id:string;occurred_at:Date;schema_version:1;}
export interface MembershipTarget{id:string;organization_id:string;status:'active'|'disabled';}
export interface WorkspaceTarget{id:string;organization_id:string;status:'active'|'archived';}
export interface EligibleGrantMember{id:string;user_id:string;email:string;status:'active';}
export interface OperationReplay{request_hash:string;grant:ResourceGrant;}
export interface ResourceGrantOperation{actor_id:string;organization_id:string;operation:string;key_hash:string;request_hash:string;occurred_at:Date;}
export interface ResourceGrantRepository{
 getMembership(id:string):Promise<MembershipTarget|null>;getWorkspace(id:string):Promise<WorkspaceTarget|null>;getGrant(id:string):Promise<ResourceGrant|null>;listEligibleMembers(organizationId:string):Promise<EligibleGrantMember[]>;
 findOperation(actorId:string,operation:string,keyHash:string):Promise<OperationReplay|null>;saveOperation(actorId:string,organizationId:string,operation:string,keyHash:string,requestHash:string,grant:ResourceGrant,at:Date):Promise<void>;
 insertGrant(grant:ResourceGrant):Promise<void>;updateGrant(grant:ResourceGrant,expectedVersion:number):Promise<boolean>;appendAudit(event:ResourceGrantAuditEvent):Promise<void>;
 commitCreate(grant:ResourceGrant,audit:ResourceGrantAuditEvent,operation:ResourceGrantOperation):Promise<void>;commitUpdate(grant:ResourceGrant,expectedVersion:number,audit:ResourceGrantAuditEvent,operation:ResourceGrantOperation):Promise<boolean>;
 findGrantForAccess(input:{membershipId:string;organizationId:string;workspaceId?:string;resourceType:ResourceGrantType;resourceId:string;capability:ResourceGrantAction}):Promise<ResourceGrant|null>;
 listForMembership(membershipId:string,organizationId:string,now:Date):Promise<ResourceGrant[]>;listForOrganization(organizationId:string,filter:{status?:ResourceGrantStatus;limit:number;offset:number},now:Date):Promise<{items:ResourceGrant[];total:number}>;
}
export class ResourceGrantError extends Error{constructor(readonly code:string,readonly statusCode:number,readonly actionHint:string){super(code);this.name='ResourceGrantError';}}
export interface GrantContext{actorId:string;organizationId:string;requestId:string;traceId:string;idempotencyKey:string;}
export interface CreateGrantInput{workspace_id:string;resource_type:ResourceGrantType;resource_id:string;grantee_membership_id:string;actions:ResourceGrantAction[];reason:string;expires_at:Date;}
export interface ExtendGrantInput{grant_id:string;expected_version:number;reason:string;expires_at:Date;}
export interface RevokeGrantInput{grant_id:string;expected_version:number;reason:string;}
const MAX_DURATION_MS=30*24*60*60*1000;
const BLOCKED_MARKERS=['evidence','export','credential','replay'];
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const stable=(value:unknown)=>JSON.stringify(value,Object.keys(value as object).sort());
const isUuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);

export class ResourceGrantService implements ResourceGrantAuthorizer{
 constructor(private readonly repository:ResourceGrantRepository,private readonly now:()=>Date=()=>new Date()){}
 async create(input:CreateGrantInput,context:GrantContext){this.validateContext(context);this.validateCreate(input);const now=this.now();this.validateExpiry(input.expires_at,now);const member=await this.repository.getMembership(input.grantee_membership_id);if(!member||member.organization_id!==context.organizationId||member.status!=='active')throw new ResourceGrantError('grant_target_forbidden',403,'先把目标用户邀请为当前组织的活动成员。');const workspace=await this.repository.getWorkspace(input.workspace_id);if(!workspace||workspace.organization_id!==context.organizationId||workspace.status!=='active')throw new ResourceGrantError('grant_workspace_forbidden',403,'选择当前组织的活动工作区。');const normalized={...input,actions:[...new Set(input.actions)].sort(),reason:input.reason.trim(),expires_at:input.expires_at.toISOString()},operation='create',requestHash=hash(stable(normalized)),keyHash=hash(context.idempotencyKey);const replay=await this.replay(context,operation,keyHash,requestHash);if(replay)return replay;const grant:ResourceGrant={id:randomUUID(),organization_id:context.organizationId,workspace_id:input.workspace_id,resource_type:input.resource_type,resource_id:input.resource_id,grantee_membership_id:input.grantee_membership_id,grantor_id:context.actorId,reason:input.reason.trim(),status:'active',expires_at:input.expires_at,revoked_at:null,revoked_by:null,revocation_reason:null,version:1,created_at:now,updated_at:now,actions:[...new Set(input.actions)].sort() as ResourceGrantAction[]};try{await this.repository.commitCreate(grant,this.auditEvent(grant,context.actorId,'created','allowed','created',context,null,null,now),this.operation(context,operation,keyHash,requestHash,now));return grant;}catch(error){const concurrent=await this.replay(context,operation,keyHash,requestHash);if(concurrent)return concurrent;throw error;}}
 async extend(input:ExtendGrantInput,context:GrantContext){this.validateContext(context);this.validateReason(input.reason);if(!Number.isInteger(input.expected_version)||input.expected_version<1)throw new ResourceGrantError('grant_version_invalid',400,'提交当前授权版本。');const now=this.now();this.validateExpiry(input.expires_at,now);const operation=`extend:${input.grant_id}`,requestHash=hash(stable({...input,expires_at:input.expires_at.toISOString()})),keyHash=hash(context.idempotencyKey);const replay=await this.replay(context,operation,keyHash,requestHash);if(replay)return replay;const grant=await this.requiredGrant(input.grant_id,context.organizationId);if(grant.status!=='active'||grant.expires_at<=now)throw new ResourceGrantError('grant_not_active',409,'已撤销或过期的授权不能延长，请创建新授权。');if(input.expires_at<=grant.expires_at)throw new ResourceGrantError('grant_expiry_not_extended',400,'新到期时间必须晚于当前到期时间。');const updated={...grant,reason:input.reason.trim(),expires_at:input.expires_at,version:grant.version+1,updated_at:now};if(!await this.repository.commitUpdate(updated,input.expected_version,this.auditEvent(updated,context.actorId,'extended','allowed',input.reason.trim(),context,null,null,now),this.operation(context,operation,keyHash,requestHash,now))){const concurrent=await this.replay(context,operation,keyHash,requestHash);if(concurrent)return concurrent;throw new ResourceGrantError('grant_version_conflict',409,'刷新授权后按最新版本重试。');}return updated;}
 async revoke(input:RevokeGrantInput,context:GrantContext){this.validateContext(context);this.validateReason(input.reason);if(!Number.isInteger(input.expected_version)||input.expected_version<1)throw new ResourceGrantError('grant_version_invalid',400,'提交当前授权版本。');const now=this.now(),operation=`revoke:${input.grant_id}`,requestHash=hash(stable(input)),keyHash=hash(context.idempotencyKey);const replay=await this.replay(context,operation,keyHash,requestHash);if(replay)return replay;const grant=await this.requiredGrant(input.grant_id,context.organizationId);if(grant.status!=='active'||grant.expires_at<=now)throw new ResourceGrantError('grant_not_active',409,'授权已经撤销或过期。');const updated={...grant,status:'revoked' as const,revoked_at:now,revoked_by:context.actorId,revocation_reason:input.reason.trim(),version:grant.version+1,updated_at:now};if(!await this.repository.commitUpdate(updated,input.expected_version,this.auditEvent(updated,context.actorId,'revoked','allowed',input.reason.trim(),context,null,null,now),this.operation(context,operation,keyHash,requestHash,now))){const concurrent=await this.replay(context,operation,keyHash,requestHash);if(concurrent)return concurrent;throw new ResourceGrantError('grant_version_conflict',409,'刷新授权后按最新版本重试。');}return updated;}
 async authorizeResourceGrant(input:ResourceGrantAuthorizationInput){const type=input.resourceType as ResourceGrantType;if(!this.isAllowedAction(type,input.capability))return{allowed:false,reason:'grant_action_not_allowed'};const grant=await this.repository.findGrantForAccess({membershipId:input.membershipId,organizationId:input.organizationId,...(input.workspaceId?{workspaceId:input.workspaceId}:{}),resourceType:type,resourceId:input.resourceId,capability:input.capability as ResourceGrantAction});if(!grant)return{allowed:false,reason:'grant_not_found'};const now=this.now(),context={requestId:input.requestId,traceId:input.traceId};if(grant.status!=='active'){await this.audit(grant,input.actorId,'access_denied','denied','revoked',context,input.capability as ResourceGrantAction,input.surface,now);return{allowed:false,reason:'grant_revoked',grantId:grant.id};}if(grant.expires_at<=now){await this.audit(grant,input.actorId,'expired','denied','expired',context,input.capability as ResourceGrantAction,input.surface,now);return{allowed:false,reason:'grant_expired',grantId:grant.id};}await this.audit(grant,input.actorId,'accessed','allowed','exact_resource',context,input.capability as ResourceGrantAction,input.surface,now);return{allowed:true,reason:'allowed_resource_grant',grantId:grant.id};}
 listMine(membershipId:string,organizationId:string){return this.repository.listForMembership(membershipId,organizationId,this.now());}
 listEligibleMembers(organizationId:string){return this.repository.listEligibleMembers(organizationId);}
 listOrganization(organizationId:string,filter:{status?:ResourceGrantStatus;page:number;limit:number}){if(filter.page<1||filter.limit<1||filter.limit>100)throw new ResourceGrantError('pagination_invalid',400,'page 至少为 1，limit 为 1 至 100。');return this.repository.listForOrganization(organizationId,{...(filter.status?{status:filter.status}:{}),limit:filter.limit,offset:(filter.page-1)*filter.limit},this.now());}
 private validateContext(context:GrantContext){if(!context.idempotencyKey?.trim()||context.idempotencyKey.length>128)throw new ResourceGrantError('idempotency_key_required',400,'提供 1 至 128 字符的 Idempotency-Key。');}
 private validateCreate(input:CreateGrantInput){if(!isUuid(input.workspace_id)||!isUuid(input.resource_id)||!isUuid(input.grantee_membership_id))throw new ResourceGrantError('grant_target_invalid',400,'工作区、资源和成员标识必须为 UUID。');this.validateReason(input.reason);if(!Array.isArray(input.actions)||!input.actions.length||input.actions.length>8)throw new ResourceGrantError('grant_actions_invalid',400,'至少选择一个最小必要动作。');if(!input.actions.every(action=>this.isAllowedAction(input.resource_type,action)))throw new ResourceGrantError('grant_action_not_allowed',400,'动作必须与指定资源匹配，且不得包含下载、导出、凭证或重放。');}
 private validateReason(reason:string){if(!reason?.trim()||reason.trim().length>500)throw new ResourceGrantError('grant_reason_required',400,'填写 1 至 500 字符的业务原因。');}
 private validateExpiry(expiry:Date,now:Date){if(!(expiry instanceof Date)||Number.isNaN(expiry.getTime())||expiry<=now||expiry.getTime()-now.getTime()>MAX_DURATION_MS)throw new ResourceGrantError('grant_expiry_invalid',400,'到期时间必须晚于当前时间且不超过 30 天。');}
 private isAllowedAction(type:ResourceGrantType,capability:string):capability is ResourceGrantAction{return Boolean(RESOURCE_GRANT_ACTIONS[type]?.includes(capability as never))&&!BLOCKED_MARKERS.some(marker=>capability.includes(marker));}
 private async requiredGrant(id:string,organizationId:string){if(!isUuid(id))throw new ResourceGrantError('grant_not_found',404,'授权不存在。');const grant=await this.repository.getGrant(id);if(!grant||grant.organization_id!==organizationId)throw new ResourceGrantError('grant_not_found',404,'授权不存在。');return grant;}
 private async replay(context:GrantContext,operation:string,keyHash:string,requestHash:string){const found=await this.repository.findOperation(context.actorId,operation,keyHash);if(!found)return null;if(found.request_hash!==requestHash)throw new ResourceGrantError('idempotency_conflict',409,'此 Idempotency-Key 已用于不同请求。');return found.grant;}
 private audit(grant:ResourceGrant,actorId:string,eventType:ResourceGrantAuditEvent['event_type'],outcome:ResourceGrantAuditEvent['outcome'],reason:string,context:{requestId:string;traceId:string},capability:ResourceGrantAction|null,surface:AuthorizationSurface|null,at:Date){return this.repository.appendAudit(this.auditEvent(grant,actorId,eventType,outcome,reason,context,capability,surface,at));}
 private auditEvent(grant:ResourceGrant,actorId:string,eventType:ResourceGrantAuditEvent['event_type'],outcome:ResourceGrantAuditEvent['outcome'],reason:string,context:{requestId:string;traceId:string},capability:ResourceGrantAction|null,surface:AuthorizationSurface|null,at:Date):ResourceGrantAuditEvent{return{id:randomUUID(),grant_id:grant.id,organization_id:grant.organization_id,workspace_id:grant.workspace_id,actor_id:actorId,event_type:eventType,resource_type:grant.resource_type,resource_id:grant.resource_id,capability,surface,outcome,reason,request_id:context.requestId,trace_id:context.traceId,occurred_at:at,schema_version:1};}
 private operation(context:GrantContext,operation:string,keyHash:string,requestHash:string,at:Date):ResourceGrantOperation{return{actor_id:context.actorId,organization_id:context.organizationId,operation,key_hash:keyHash,request_hash:requestHash,occurred_at:at};}
}

export class InMemoryResourceGrantRepository implements ResourceGrantRepository{
 memberships=new Map<string,MembershipTarget>();memberProfiles=new Map<string,EligibleGrantMember>();workspaces=new Map<string,WorkspaceTarget>();grants=new Map<string,ResourceGrant>();audits:ResourceGrantAuditEvent[]=[];operations=new Map<string,{request_hash:string;grant_id:string}>();
 async getMembership(id:string){return this.memberships.get(id)??null;}async getWorkspace(id:string){return this.workspaces.get(id)??null;}async getGrant(id:string){return this.grants.get(id)??null;}
 async listEligibleMembers(org:string){return[...this.memberProfiles.values()].filter(profile=>this.memberships.get(profile.id)?.organization_id===org&&this.memberships.get(profile.id)?.status==='active');}
 async findOperation(actor:string,operation:string,key:string){const value=this.operations.get(`${actor}:${operation}:${key}`);const grant=value&&this.grants.get(value.grant_id);return value&&grant?{request_hash:value.request_hash,grant}:null;}async saveOperation(actor:string,_org:string,operation:string,key:string,requestHash:string,grant:ResourceGrant){this.operations.set(`${actor}:${operation}:${key}`,{request_hash:requestHash,grant_id:grant.id});}
 async insertGrant(grant:ResourceGrant){this.grants.set(grant.id,grant);}async updateGrant(grant:ResourceGrant,expected:number){const current=this.grants.get(grant.id);if(!current||current.version!==expected)return false;this.grants.set(grant.id,grant);return true;}async appendAudit(event:ResourceGrantAuditEvent){this.audits.push(event);}
 async commitCreate(grant:ResourceGrant,audit:ResourceGrantAuditEvent,operation:ResourceGrantOperation){this.grants.set(grant.id,grant);this.audits.push(audit);this.operations.set(`${operation.actor_id}:${operation.operation}:${operation.key_hash}`,{request_hash:operation.request_hash,grant_id:grant.id});}
 async commitUpdate(grant:ResourceGrant,expected:number,audit:ResourceGrantAuditEvent,operation:ResourceGrantOperation){const current=this.grants.get(grant.id);if(!current||current.version!==expected)return false;this.grants.set(grant.id,grant);this.audits.push(audit);this.operations.set(`${operation.actor_id}:${operation.operation}:${operation.key_hash}`,{request_hash:operation.request_hash,grant_id:grant.id});return true;}
 async findGrantForAccess(input:{membershipId:string;organizationId:string;workspaceId?:string;resourceType:ResourceGrantType;resourceId:string;capability:ResourceGrantAction}){return[...this.grants.values()].filter(g=>g.grantee_membership_id===input.membershipId&&g.organization_id===input.organizationId&&g.workspace_id===(input.workspaceId??g.workspace_id)&&g.resource_type===input.resourceType&&g.resource_id===input.resourceId&&g.actions.includes(input.capability)).sort((a,b)=>b.created_at.getTime()-a.created_at.getTime())[0]??null;}
 async listForMembership(membership:string,org:string,now:Date){return[...this.grants.values()].filter(g=>g.grantee_membership_id===membership&&g.organization_id===org).map(g=>({...g,effective_status:g.status==='revoked'?'revoked':g.expires_at<=now?'expired':'active'} as ResourceGrant));}
 async listForOrganization(org:string,filter:{status?:ResourceGrantStatus;limit:number;offset:number},now:Date){const all=[...this.grants.values()].filter(g=>g.organization_id===org).map(g=>({...g,effective_status:g.status==='revoked'?'revoked':g.expires_at<=now?'expired':'active'} as ResourceGrant)).filter(g=>!filter.status||g.effective_status===filter.status).sort((a,b)=>b.created_at.getTime()-a.created_at.getTime());return{items:all.slice(filter.offset,filter.offset+filter.limit),total:all.length};}
}
