window.REPORT_C_DATA = {
  provenance:
    "Existing M05-06 E2E fixtures; not live data. Synthetic variants are labeled separately.",
  now: "2026-09-08T00:00:00Z",
  reports: {
    opportunity: {
      type: "opportunity",
      summary: {
        total: 28,
        adopted: 8,
        observing: 9,
        rejected: 4,
        complete_coverage: 17,
        average_score: 78.6,
      },
      series: [
        {
          label: "recommend",
          value: 12,
        },
        {
          label: "observe",
          value: 9,
        },
        {
          label: "not_recommend",
          value: 4,
        },
        {
          label: "insufficient_data",
          value: 3,
        },
      ],
      observed_at: "2026-08-08T12:00:00.000Z",
    },
    trend: {
      type: "trend",
      summary: {
        total: 16,
        signals: 128,
        sources: 34,
        average_momentum: 13.5,
        average_confidence: 76,
      },
      series: [
        {
          label: "active",
          value: 12,
        },
        {
          label: "stale",
          value: 3,
        },
        {
          label: "irrelevant",
          value: 1,
        },
      ],
      observed_at: "2026-08-08T12:00:00.000Z",
    },
    team: {
      type: "team",
      summary: {
        members: 6,
        total: 42,
        completed: 29,
        overdue: 3,
      },
      series: [
        {
          label: "member-a@example.test",
          value: 9,
        },
        {
          label: "member-b@example.test",
          value: 7,
        },
        {
          label: "member-c@example.test",
          value: 6,
        },
      ],
      observed_at: "2026-08-08T12:00:00.000Z",
    },
  },
  exports: [
    {
      id: "00000000-0000-4000-8000-000000000563",
      report_type: "opportunity",
      format: "csv",
      status: "succeeded",
      attempt_count: 1,
      filename: "scoutops-opportunity.csv",
      row_count: 28,
      byte_size: 4096,
      expires_at: "2026-09-09T12:00:00.000Z",
      last_error_code: null,
      queue_position: null,
      estimated_completion_at: null,
      estimate_sample_size: 0,
      version: 3,
      created_at: "2026-08-08T12:00:00.000Z",
      updated_at: "2026-08-08T12:01:00.000Z",
    },
    {
      id: "00000000-0000-4000-8000-000000000564",
      report_type: "trend",
      format: "csv",
      status: "leased",
      attempt_count: 1,
      filename: "scoutops-trend.csv",
      row_count: null,
      byte_size: null,
      expires_at: "2026-09-09T12:00:00.000Z",
      last_error_code: null,
      queue_position: 1,
      estimated_completion_at: "2026-08-08T12:04:00.000Z",
      estimate_sample_size: 10,
      version: 2,
      created_at: "2026-08-08T12:02:00.000Z",
      updated_at: "2026-08-08T12:02:01.000Z",
    },
    {
      id: "00000000-0000-4000-8000-000000000565",
      report_type: "team",
      format: "csv",
      status: "expired",
      attempt_count: 1,
      filename: "scoutops-team.csv",
      row_count: 6,
      byte_size: 2048,
      expires_at: "2026-08-09T12:00:00.000Z",
      last_error_code: null,
      queue_position: null,
      estimated_completion_at: null,
      estimate_sample_size: 0,
      version: 4,
      created_at: "2026-08-07T12:00:00.000Z",
      updated_at: "2026-08-09T12:00:00.000Z",
    },
    {
      id: "00000000-0000-4000-8000-000000000567",
      report_type: "opportunity",
      format: "csv",
      status: "queued",
      attempt_count: 0,
      filename: "scoutops-opportunity-new.csv",
      row_count: null,
      byte_size: null,
      expires_at: "2026-09-09T12:00:00.000Z",
      last_error_code: null,
      queue_position: 2,
      estimated_completion_at: "2026-08-08T12:06:00.000Z",
      estimate_sample_size: 10,
      version: 1,
      created_at: "2026-08-08T12:03:00.000Z",
      updated_at: "2026-08-08T12:03:00.000Z",
    },
  ],
  replacement: {
    id: "00000000-0000-4000-8000-000000000566",
    report_type: "team",
    format: "csv",
    status: "queued",
    attempt_count: 0,
    filename: "scoutops-team-regenerated.csv",
    row_count: null,
    byte_size: null,
    expires_at: "2026-09-19T12:00:00.000Z",
    last_error_code: null,
    queue_position: 3,
    estimated_completion_at: "2026-08-08T12:08:00.000Z",
    estimate_sample_size: 10,
    version: 1,
    created_at: "2026-08-08T12:04:00.000Z",
    updated_at: "2026-08-08T12:04:00.000Z",
  },
  labels: {
    opportunity: "机会分析",
    trend: "趋势分析",
    team: "团队绩效",
  },
  metricLabels: {
    opportunity: {
      total: "总量",
      adopted: "已采纳",
      observing: "观察中",
      rejected: "已驳回",
      complete_coverage: "证据完整",
      average_score: "平均评分",
    },
    trend: {
      total: "总量",
      signals: "信号数",
      sources: "来源数",
      average_momentum: "平均动量",
      average_confidence: "平均置信度",
    },
    team: {
      members: "成员数",
      total: "任务总数",
      completed: "已完成任务",
      overdue: "逾期任务",
    },
  },
  seriesLabels: {
    opportunity: {
      recommend: "推荐",
      observe: "继续观察",
      not_recommend: "不推荐",
      insufficient_data: "数据不足",
    },
    trend: {
      active: "活跃",
      stale: "观测过期",
      irrelevant: "无关",
    },
    team: {
      "member-a@example.test": "member-a@example.test",
      "member-b@example.test": "member-b@example.test",
      "member-c@example.test": "member-c@example.test",
    },
  },
  contracts: {
    opportunity: {
      url: "/report-exports",
      method: "POST",
      body: {
        report_type: "opportunity",
        format: "csv",
      },
    },
    trend: {
      url: "/report-exports",
      method: "POST",
      body: {
        report_type: "trend",
        format: "csv",
      },
    },
    team: {
      url: "/report-exports",
      method: "POST",
      body: {
        report_type: "team",
        format: "csv",
      },
    },
    regenerate: {
      url: "/report-exports/00000000-0000-4000-8000-000000000565/regenerate",
      method: "POST",
    },
  },
  sourceChecks: [
    "Vue three exact CSV bodies and bodyless regeneration",
    "Vue default report query, close context, replacement ID",
    "Vue null/zero and inclusive expiry",
    "SQL organization active members with current workspace tasks via inert pool",
    "Service download state-before-expiry, missing file and regeneration via inert repository; status-only expired mismatch preserved",
  ],
};
