INSERT INTO `capabilities` (`code`,`description`,`version`,`created_at`) VALUES ('competitor:manage','创建竞品监控、写入来源快照并维护阈值规则',1,UTC_TIMESTAMP(3));
INSERT INTO `role_capabilities` (`role_code`,`capability_code`,`created_at`) VALUES
 ('member','competitor:manage',UTC_TIMESTAMP(3)),('selection_manager','competitor:manage',UTC_TIMESTAMP(3)),('organization_admin','competitor:manage',UTC_TIMESTAMP(3)),('platform_super_admin','competitor:manage',UTC_TIMESTAMP(3));

CREATE TABLE `competitors` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`opportunity_id` CHAR(36) CHARACTER SET ascii NULL,`provider_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `market` VARCHAR(40) CHARACTER SET ascii NOT NULL,`source_site` VARCHAR(120) NOT NULL,`external_id` VARCHAR(255) CHARACTER SET ascii NOT NULL,`product_url` VARCHAR(2048) NOT NULL,`title` VARCHAR(500) NOT NULL,
 `status` ENUM('active','paused') NOT NULL DEFAULT 'active',`latest_snapshot_id` CHAR(36) CHARACTER SET ascii NULL,`revision` INT UNSIGNED NOT NULL DEFAULT 1,`created_by` CHAR(36) CHARACTER SET ascii NOT NULL,`created_at` DATETIME(3) NOT NULL,`updated_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `uq_competitor_identity`(`organization_id`,`workspace_id`,`market`,`source_site`,`external_id`),KEY `idx_competitor_scope`(`organization_id`,`workspace_id`,`status`,`updated_at`),KEY `idx_competitor_opportunity`(`opportunity_id`),
 CONSTRAINT `fk_competitor_org` FOREIGN KEY(`organization_id`) REFERENCES `organizations`(`id`),CONSTRAINT `fk_competitor_workspace` FOREIGN KEY(`workspace_id`) REFERENCES `workspaces`(`id`),CONSTRAINT `fk_competitor_opportunity` FOREIGN KEY(`opportunity_id`) REFERENCES `opportunities`(`id`) ON DELETE SET NULL,CONSTRAINT `fk_competitor_provider` FOREIGN KEY(`provider_id`) REFERENCES `providers`(`id`),CONSTRAINT `fk_competitor_creator` FOREIGN KEY(`created_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `competitor_snapshots` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`competitor_id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`provider_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `current_price` DECIMAL(18,6) NOT NULL,`currency` CHAR(3) CHARACTER SET ascii NOT NULL,`rank_value` INT UNSIGNED NOT NULL,`review_count` INT UNSIGNED NOT NULL,`rating_value` DECIMAL(4,2) NOT NULL,`availability` ENUM('in_stock','out_of_stock','unknown') NOT NULL,
 `captured_at` DATETIME(3) NOT NULL,`freshness` ENUM('fresh','stale') NOT NULL,`source_status` ENUM('healthy','degraded','unavailable') NOT NULL,`source_ref_id` VARCHAR(255) CHARACTER SET ascii NOT NULL,`evidence_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`created_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `uq_competitor_snapshot_source`(`competitor_id`,`source_ref_id`),KEY `idx_competitor_snapshot_timeline`(`competitor_id`,`captured_at`),CONSTRAINT `fk_competitor_snapshot_competitor` FOREIGN KEY(`competitor_id`) REFERENCES `competitors`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_competitor_snapshot_provider` FOREIGN KEY(`provider_id`) REFERENCES `providers`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE `competitors` ADD CONSTRAINT `fk_competitor_latest_snapshot` FOREIGN KEY(`latest_snapshot_id`) REFERENCES `competitor_snapshots`(`id`) ON DELETE SET NULL;

CREATE TABLE `competitor_monitor_rules` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`competitor_id` CHAR(36) CHARACTER SET ascii NULL,
 `metric` ENUM('price','rank','review_count','availability') NOT NULL,`direction` ENUM('increase','decrease','change','became_unavailable') NOT NULL,`threshold_value` DECIMAL(18,6) NULL,`status` ENUM('enabled','disabled') NOT NULL DEFAULT 'enabled',`revision` INT UNSIGNED NOT NULL DEFAULT 1,
 `created_by` CHAR(36) CHARACTER SET ascii NOT NULL,`created_at` DATETIME(3) NOT NULL,`updated_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),KEY `idx_competitor_rule_scope`(`organization_id`,`workspace_id`,`status`,`metric`),KEY `idx_competitor_rule_target`(`competitor_id`,`status`),CONSTRAINT `fk_competitor_rule_target` FOREIGN KEY(`competitor_id`) REFERENCES `competitors`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_competitor_rule_creator` FOREIGN KEY(`created_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `competitor_snapshot_jobs` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`competitor_id` CHAR(36) CHARACTER SET ascii NOT NULL,`snapshot_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `status` ENUM('queued','leased','retry_scheduled','succeeded','failed_terminal','dead_letter') NOT NULL DEFAULT 'queued',`attempt_count` INT UNSIGNED NOT NULL DEFAULT 0,`available_at` DATETIME(3) NOT NULL,`lease_owner` VARCHAR(120) NULL,`lease_expires_at` DATETIME(3) NULL,`last_error_code` VARCHAR(120) NULL,`request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`created_at` DATETIME(3) NOT NULL,`updated_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `uq_competitor_snapshot_job`(`snapshot_id`),KEY `idx_competitor_job_claim`(`status`,`available_at`,`lease_expires_at`),CONSTRAINT `fk_competitor_job_competitor` FOREIGN KEY(`competitor_id`) REFERENCES `competitors`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_competitor_job_snapshot` FOREIGN KEY(`snapshot_id`) REFERENCES `competitor_snapshots`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `competitor_changes` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`competitor_id` CHAR(36) CHARACTER SET ascii NOT NULL,`snapshot_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `field_name` ENUM('current_price','rank_value','review_count','rating_value','availability') NOT NULL,`previous_value` VARCHAR(255) NOT NULL,`current_value` VARCHAR(255) NOT NULL,`changed_at` DATETIME(3) NOT NULL,`evidence_id` CHAR(36) CHARACTER SET ascii NOT NULL,`impact_explanation` VARCHAR(1000) NOT NULL,`created_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `uq_competitor_change_field`(`snapshot_id`,`field_name`),KEY `idx_competitor_change_timeline`(`competitor_id`,`changed_at`),CONSTRAINT `fk_competitor_change_competitor` FOREIGN KEY(`competitor_id`) REFERENCES `competitors`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_competitor_change_snapshot` FOREIGN KEY(`snapshot_id`) REFERENCES `competitor_snapshots`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `competitor_alerts` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`competitor_id` CHAR(36) CHARACTER SET ascii NOT NULL,`change_id` CHAR(36) CHARACTER SET ascii NOT NULL,`rule_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `notification_status` ENUM('queued','delivered','failed') NOT NULL DEFAULT 'queued',`task_status` ENUM('queued','created','failed') NOT NULL DEFAULT 'queued',`payload_json` JSON NOT NULL,`created_at` DATETIME(3) NOT NULL,`updated_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `uq_competitor_alert_rule_change`(`change_id`,`rule_id`),KEY `idx_competitor_alert_delivery`(`organization_id`,`workspace_id`,`notification_status`,`task_status`),CONSTRAINT `fk_competitor_alert_competitor` FOREIGN KEY(`competitor_id`) REFERENCES `competitors`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_competitor_alert_change` FOREIGN KEY(`change_id`) REFERENCES `competitor_changes`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_competitor_alert_rule` FOREIGN KEY(`rule_id`) REFERENCES `competitor_monitor_rules`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `competitor_events` (`id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`competitor_id` CHAR(36) CHARACTER SET ascii NOT NULL,`event_type` VARCHAR(120) CHARACTER SET ascii NOT NULL,`actor_id` VARCHAR(120) CHARACTER SET ascii NOT NULL,`payload_json` JSON NOT NULL,`request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`created_at` DATETIME(3) NOT NULL,PRIMARY KEY(`id`),KEY `idx_competitor_event_scope`(`organization_id`,`workspace_id`,`competitor_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `competitor_outbox` (`id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`aggregate_id` CHAR(36) CHARACTER SET ascii NOT NULL,`event_type` VARCHAR(120) CHARACTER SET ascii NOT NULL,`payload_json` JSON NOT NULL,`status` ENUM('pending','delivered','failed') NOT NULL DEFAULT 'pending',`available_at` DATETIME(3) NOT NULL,`created_at` DATETIME(3) NOT NULL,PRIMARY KEY(`id`),KEY `idx_competitor_outbox_delivery`(`status`,`available_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `competitor_operations` (`id` CHAR(36) CHARACTER SET ascii NOT NULL,`actor_id` CHAR(36) CHARACTER SET ascii NOT NULL,`route` VARCHAR(255) NOT NULL,`idempotency_key` VARCHAR(128) CHARACTER SET ascii NOT NULL,`resource_id` CHAR(36) CHARACTER SET ascii NOT NULL,`result_json` JSON NOT NULL,`created_at` DATETIME(3) NOT NULL,PRIMARY KEY(`id`),UNIQUE KEY `uq_competitor_operation`(`actor_id`,`route`,`idempotency_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
