CREATE TABLE `cost_rules` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `market` VARCHAR(40) CHARACTER SET ascii NOT NULL,`platform` VARCHAR(80) CHARACTER SET ascii NOT NULL,`version_code` VARCHAR(64) CHARACTER SET ascii NOT NULL,`name` VARCHAR(160) NOT NULL,
 `status` ENUM('draft','pending_approval','approved','active','retired','rejected','rolled_back') NOT NULL DEFAULT 'draft',`fee_lines_json` JSON NOT NULL,`effective_from` DATE NOT NULL,`revision` INT UNSIGNED NOT NULL DEFAULT 1,
 `submitted_by` CHAR(36) CHARACTER SET ascii NULL,`submitted_at` DATETIME(3) NULL,`published_by` CHAR(36) CHARACTER SET ascii NULL,`published_at` DATETIME(3) NULL,`rollback_target_id` CHAR(36) CHARACTER SET ascii NULL,`rolled_back_at` DATETIME(3) NULL,
 `created_by` CHAR(36) CHARACTER SET ascii NOT NULL,`created_at` DATETIME(3) NOT NULL,`updated_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `uq_cost_rule_scope_version`(`organization_id`,`workspace_id`,`market`,`platform`,`version_code`),KEY `idx_cost_rule_scope_status`(`organization_id`,`workspace_id`,`market`,`platform`,`status`,`effective_from`),
 CONSTRAINT `fk_cost_rule_org` FOREIGN KEY(`organization_id`) REFERENCES `organizations`(`id`),CONSTRAINT `fk_cost_rule_workspace` FOREIGN KEY(`workspace_id`) REFERENCES `workspaces`(`id`),CONSTRAINT `fk_cost_rule_creator` FOREIGN KEY(`created_by`) REFERENCES `users`(`id`),CONSTRAINT `fk_cost_rule_submitter` FOREIGN KEY(`submitted_by`) REFERENCES `users`(`id`),CONSTRAINT `fk_cost_rule_publisher` FOREIGN KEY(`published_by`) REFERENCES `users`(`id`),CONSTRAINT `fk_cost_rule_rollback_target` FOREIGN KEY(`rollback_target_id`) REFERENCES `cost_rules`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cost_rule_approvals` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`cost_rule_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `approval_role` ENUM('selection_manager','organization_admin') NOT NULL,`decision` ENUM('approved','rejected') NOT NULL,`reason` VARCHAR(1000) NOT NULL,`actor_id` CHAR(36) CHARACTER SET ascii NOT NULL,`request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`created_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `uq_cost_rule_approval_role`(`cost_rule_id`,`approval_role`),KEY `idx_cost_rule_approval_scope`(`organization_id`,`workspace_id`,`cost_rule_id`,`created_at`),CONSTRAINT `fk_cost_rule_approval_rule` FOREIGN KEY(`cost_rule_id`) REFERENCES `cost_rules`(`id`),CONSTRAINT `fk_cost_rule_approval_actor` FOREIGN KEY(`actor_id`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `exchange_rate_quotes` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`provider_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `base_currency` CHAR(3) CHARACTER SET ascii NOT NULL,`quote_currency` CHAR(3) CHARACTER SET ascii NOT NULL,`rate_value` DECIMAL(20,10) NOT NULL,`quote_date` DATE NOT NULL,`observed_at` DATETIME(3) NOT NULL,`source_ref_id` VARCHAR(255) CHARACTER SET ascii NOT NULL,`evidence_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `created_by` VARCHAR(120) CHARACTER SET ascii NOT NULL,`request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`created_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `uq_exchange_quote_source`(`organization_id`,`workspace_id`,`provider_id`,`base_currency`,`quote_currency`,`quote_date`,`source_ref_id`),KEY `idx_exchange_quote_lookup`(`organization_id`,`workspace_id`,`base_currency`,`quote_currency`,`quote_date`),CONSTRAINT `fk_exchange_quote_provider` FOREIGN KEY(`provider_id`) REFERENCES `providers`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `opportunity_cost_inputs` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`opportunity_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `platform` VARCHAR(80) CHARACTER SET ascii NOT NULL,`input_type` ENUM('sale_price','purchase_price','logistics') NOT NULL,`amount_value` DECIMAL(18,6) NOT NULL,`currency` CHAR(3) CHARACTER SET ascii NOT NULL,
 `source_type` VARCHAR(80) CHARACTER SET ascii NOT NULL,`source_ref_id` VARCHAR(255) CHARACTER SET ascii NOT NULL,`evidence_id` CHAR(36) CHARACTER SET ascii NOT NULL,`observed_at` DATETIME(3) NOT NULL,`input_version` INT UNSIGNED NOT NULL,`is_current` TINYINT(1) NOT NULL DEFAULT 1,
 `confirmed_by` CHAR(36) CHARACTER SET ascii NOT NULL,`request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`created_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),UNIQUE KEY `uq_cost_input_version`(`opportunity_id`,`platform`,`input_type`,`input_version`),KEY `idx_cost_input_current`(`organization_id`,`workspace_id`,`opportunity_id`,`platform`,`is_current`,`input_type`),CONSTRAINT `fk_cost_input_opportunity` FOREIGN KEY(`opportunity_id`) REFERENCES `opportunities`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_cost_input_confirmer` FOREIGN KEY(`confirmed_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `opportunity_profit_jobs` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`opportunity_id` CHAR(36) CHARACTER SET ascii NOT NULL,`cost_rule_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `status` ENUM('queued','leased','retry_scheduled','succeeded','completed_with_warnings','failed_terminal','dead_letter') NOT NULL DEFAULT 'queued',`attempt_count` INT UNSIGNED NOT NULL DEFAULT 0,`available_at` DATETIME(3) NOT NULL,`lease_owner` VARCHAR(120) NULL,`lease_expires_at` DATETIME(3) NULL,`last_error_code` VARCHAR(120) NULL,
 `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`created_at` DATETIME(3) NOT NULL,`updated_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),KEY `idx_profit_job_claim`(`status`,`available_at`,`lease_expires_at`),CONSTRAINT `fk_profit_job_opportunity` FOREIGN KEY(`opportunity_id`) REFERENCES `opportunities`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_profit_job_rule` FOREIGN KEY(`cost_rule_id`) REFERENCES `cost_rules`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `opportunity_profit_runs` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,`workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,`opportunity_id` CHAR(36) CHARACTER SET ascii NOT NULL,`cost_rule_id` CHAR(36) CHARACTER SET ascii NOT NULL,
 `rule_version_code` VARCHAR(64) CHARACTER SET ascii NOT NULL,`platform` VARCHAR(80) CHARACTER SET ascii NOT NULL,`market` VARCHAR(40) CHARACTER SET ascii NOT NULL,`status` ENUM('calculated','insufficient_data') NOT NULL,`currency` CHAR(3) CHARACTER SET ascii NULL,
 `sale_price` DECIMAL(18,6) NULL,`total_cost` DECIMAL(18,6) NULL,`net_profit` DECIMAL(18,6) NULL,`net_margin_percent` DECIMAL(9,4) NULL,`missing_fields_json` JSON NOT NULL,`input_snapshot_json` JSON NOT NULL,`exchange_snapshot_json` JSON NOT NULL,
 `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,`calculated_at` DATETIME(3) NOT NULL,
 PRIMARY KEY(`id`),KEY `idx_profit_run_scope`(`organization_id`,`workspace_id`,`opportunity_id`,`calculated_at`),CONSTRAINT `fk_profit_run_opportunity` FOREIGN KEY(`opportunity_id`) REFERENCES `opportunities`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_profit_run_rule` FOREIGN KEY(`cost_rule_id`) REFERENCES `cost_rules`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `opportunity_profit_components` (
 `id` CHAR(36) CHARACTER SET ascii NOT NULL,`profit_run_id` CHAR(36) CHARACTER SET ascii NOT NULL,`component_type` ENUM('sale_price','purchase_price','logistics','platform_fee','payment_fee','tax','fulfillment') NOT NULL,`source_amount` DECIMAL(18,6) NULL,`source_currency` CHAR(3) CHARACTER SET ascii NULL,`converted_amount` DECIMAL(18,6) NULL,`target_currency` CHAR(3) CHARACTER SET ascii NULL,`source_ref_id` VARCHAR(255) CHARACTER SET ascii NULL,`evidence_id` CHAR(36) CHARACTER SET ascii NULL,`exchange_quote_id` CHAR(36) CHARACTER SET ascii NULL,`missing_reason` VARCHAR(160) NULL,
 PRIMARY KEY(`id`),KEY `idx_profit_component_run`(`profit_run_id`,`component_type`),CONSTRAINT `fk_profit_component_run` FOREIGN KEY(`profit_run_id`) REFERENCES `opportunity_profit_runs`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_profit_component_exchange` FOREIGN KEY(`exchange_quote_id`) REFERENCES `exchange_rate_quotes`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cost_operations` (`id` CHAR(36) CHARACTER SET ascii NOT NULL,`actor_id` CHAR(36) CHARACTER SET ascii NOT NULL,`route` VARCHAR(255) NOT NULL,`idempotency_key` VARCHAR(128) CHARACTER SET ascii NOT NULL,`resource_id` CHAR(36) CHARACTER SET ascii NOT NULL,`result_json` JSON NOT NULL,`created_at` DATETIME(3) NOT NULL,PRIMARY KEY(`id`),UNIQUE KEY `uq_cost_operation`(`actor_id`,`route`,`idempotency_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
