CREATE TABLE `backup_recovery_runs` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `run_type` enum('backup','restore_drill') NOT NULL,
  `scope_type` enum('platform','organization','workspace') NOT NULL DEFAULT 'platform',
  `organization_id` char(36) CHARACTER SET ascii DEFAULT NULL,
  `workspace_id` char(36) CHARACTER SET ascii DEFAULT NULL,
  `primary_region` varchar(64) NOT NULL,
  `recovery_region` varchar(64) NOT NULL,
  `status` enum('planned','running','verified','failed','blocked') NOT NULL,
  `rpo_target_minutes` int unsigned NOT NULL,
  `rto_target_minutes` int unsigned NOT NULL,
  `actual_rpo_minutes` decimal(10,2) unsigned DEFAULT NULL,
  `actual_rto_minutes` decimal(10,2) unsigned DEFAULT NULL,
  `source_cutoff_at` datetime(3) DEFAULT NULL,
  `started_at` datetime(3) NOT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `isolated` tinyint(1) NOT NULL DEFAULT 0,
  `encrypted` tinyint(1) NOT NULL DEFAULT 0,
  `integrity_verified` tinyint(1) NOT NULL DEFAULT 0,
  `permission_boundary_verified` tinyint(1) NOT NULL DEFAULT 0,
  `audit_chain_verified` tinyint(1) NOT NULL DEFAULT 0,
  `evidence_hash_verified` tinyint(1) NOT NULL DEFAULT 0,
  `failure_code` varchar(100) DEFAULT NULL,
  `request_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `trace_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `metadata` json DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_backup_runs_status_started` (`status`,`started_at`),
  KEY `idx_backup_runs_scope_started` (`organization_id`,`workspace_id`,`started_at`),
  KEY `idx_backup_runs_request` (`request_id`),
  CONSTRAINT `fk_backup_runs_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`),
  CONSTRAINT `fk_backup_runs_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `backup_recovery_assets` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `run_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `asset_kind` enum('mysql_full','mysql_binlog','evidence','export','config') NOT NULL,
  `organization_id` char(36) CHARACTER SET ascii DEFAULT NULL,
  `workspace_id` char(36) CHARACTER SET ascii DEFAULT NULL,
  `region` varchar(64) NOT NULL,
  `storage_role` enum('primary_backup','recovery_copy') NOT NULL,
  `bundle_name` varchar(255) NOT NULL,
  `bundle_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `plaintext_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `size_bytes` bigint unsigned NOT NULL,
  `encrypted` tinyint(1) NOT NULL DEFAULT 1,
  `integrity_verified` tinyint(1) NOT NULL DEFAULT 0,
  `retention_until` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_backup_asset_hash_role` (`bundle_sha256`,`storage_role`),
  KEY `idx_backup_assets_run_kind` (`run_id`,`asset_kind`,`storage_role`),
  KEY `idx_backup_assets_scope` (`organization_id`,`workspace_id`,`created_at`),
  CONSTRAINT `fk_backup_assets_run` FOREIGN KEY (`run_id`) REFERENCES `backup_recovery_runs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_backup_assets_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`),
  CONSTRAINT `fk_backup_assets_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
