CREATE TABLE `deployment_release_gates` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `release_id` char(36) CHARACTER SET ascii NOT NULL,
  `gate_kind` enum('preflight','backup','migration','canary_5','canary_25','canary_100','automatic_stop','rollback') NOT NULL,
  `status` enum('pending','running','passed','stopped','failed','rolled_back') NOT NULL,
  `traffic_percent` tinyint unsigned NOT NULL DEFAULT 0,
  `observe_seconds` int unsigned NOT NULL DEFAULT 0,
  `sample_count` int unsigned NOT NULL DEFAULT 0,
  `error_rate_percent` decimal(7,4) unsigned DEFAULT NULL,
  `read_p95_ms` int unsigned DEFAULT NULL,
  `write_p95_ms` int unsigned DEFAULT NULL,
  `async_lag_seconds` int unsigned DEFAULT NULL,
  `failure_code` varchar(100) DEFAULT NULL,
  `started_at` datetime(3) NOT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `request_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `trace_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `metadata` json DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_release_gate_kind` (`release_id`,`gate_kind`),
  KEY `idx_release_gate_status_finished` (`status`,`finished_at`),
  KEY `idx_release_gate_trace` (`trace_id`),
  CONSTRAINT `fk_release_gate_release` FOREIGN KEY (`release_id`) REFERENCES `deployment_releases` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `deployment_release_gate_events` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `release_id` char(36) CHARACTER SET ascii NOT NULL,
  `gate_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `event_type` enum('planned','started','passed','automatic_stop','rollback_started','rolled_back','failed') NOT NULL,
  `actor_type` enum('baota_task','platform_operator') NOT NULL,
  `actor_id` char(36) CHARACTER SET ascii DEFAULT NULL,
  `reason_code` varchar(100) DEFAULT NULL,
  `request_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `trace_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` datetime(3) NOT NULL,
  `metadata` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_release_gate_events_release_time` (`release_id`,`occurred_at`),
  KEY `idx_release_gate_events_request` (`request_id`),
  CONSTRAINT `fk_release_gate_event_release` FOREIGN KEY (`release_id`) REFERENCES `deployment_releases` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_release_gate_event_gate` FOREIGN KEY (`gate_id`) REFERENCES `deployment_release_gates` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
