CREATE TABLE `redis_resilience_observations` (
  `id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `organization_id` CHAR(36) CHARACTER SET ascii NULL,
  `workspace_id` CHAR(36) CHARACTER SET ascii NULL,
  `manager` ENUM('baota') NOT NULL DEFAULT 'baota',
  `mode` ENUM('single_instance') NOT NULL DEFAULT 'single_instance',
  `state` ENUM('ready','warning','blocked') NOT NULL,
  `appendonly_enabled` TINYINT(1) NOT NULL,
  `rdb_enabled` TINYINT(1) NOT NULL,
  `aof_last_write_status` ENUM('ok','err','unknown') NOT NULL,
  `rdb_last_save_status` ENUM('ok','err','unknown') NOT NULL,
  `used_memory_bytes` BIGINT UNSIGNED NOT NULL,
  `maxmemory_bytes` BIGINT UNSIGNED NOT NULL,
  `memory_usage_basis_points` INT UNSIGNED NOT NULL,
  `connected_clients` INT UNSIGNED NOT NULL,
  `maxclients` INT UNSIGNED NOT NULL,
  `connection_usage_basis_points` INT UNSIGNED NOT NULL,
  `rejected_connections` BIGINT UNSIGNED NOT NULL,
  `evicted_keys` BIGINT UNSIGNED NOT NULL,
  `finding_codes_json` JSON NOT NULL,
  `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `observed_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_redis_resilience_observed` (`observed_at`),
  KEY `idx_redis_resilience_state_time` (`state`,`observed_at`),
  KEY `idx_redis_resilience_scope_time` (`organization_id`,`workspace_id`,`observed_at`),
  CONSTRAINT `fk_redis_resilience_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_redis_resilience_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `redis_resilience_views` (
  `id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `actor_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `observation_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `observed_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_redis_resilience_views_actor_time` (`actor_id`,`observed_at`),
  KEY `idx_redis_resilience_views_request` (`request_id`),
  CONSTRAINT `fk_redis_resilience_views_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_redis_resilience_views_observation` FOREIGN KEY (`observation_id`) REFERENCES `redis_resilience_observations` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
