CREATE TABLE `mysql_resilience_observations` (
  `id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `organization_id` CHAR(36) CHARACTER SET ascii NULL,
  `workspace_id` CHAR(36) CHARACTER SET ascii NULL,
  `manager` ENUM('baota') NOT NULL DEFAULT 'baota',
  `mode` ENUM('single_primary') NOT NULL DEFAULT 'single_primary',
  `state` ENUM('ready','warning','blocked') NOT NULL,
  `mysql_version` VARCHAR(64) NOT NULL,
  `read_only_enabled` TINYINT(1) NOT NULL,
  `log_bin_enabled` TINYINT(1) NOT NULL,
  `binlog_format` ENUM('ROW','MIXED','STATEMENT','unknown') NOT NULL,
  `product_database_binlog_excluded` TINYINT(1) NOT NULL,
  `innodb_flush_log_at_trx_commit` INT UNSIGNED NOT NULL,
  `sync_binlog` INT UNSIGNED NOT NULL,
  `master_status_available` TINYINT(1) NOT NULL,
  `replica_configured` TINYINT(1) NOT NULL,
  `buffer_pool_bytes` BIGINT UNSIGNED NOT NULL,
  `buffer_pool_data_bytes` BIGINT UNSIGNED NOT NULL,
  `buffer_pool_hit_rate_basis_points` INT UNSIGNED NOT NULL,
  `threads_connected` INT UNSIGNED NOT NULL,
  `threads_running` INT UNSIGNED NOT NULL,
  `max_connections` INT UNSIGNED NOT NULL,
  `connection_usage_basis_points` INT UNSIGNED NOT NULL,
  `slow_queries_total` BIGINT UNSIGNED NOT NULL,
  `slow_queries_per_minute` DECIMAL(12,3) UNSIGNED NOT NULL,
  `long_query_time_seconds` DECIMAL(10,3) UNSIGNED NOT NULL,
  `data_filesystem_total_bytes` BIGINT UNSIGNED NOT NULL,
  `data_filesystem_available_bytes` BIGINT UNSIGNED NOT NULL,
  `data_usage_basis_points` INT UNSIGNED NOT NULL,
  `innodb_log_waits` BIGINT UNSIGNED NOT NULL,
  `innodb_row_lock_waits` BIGINT UNSIGNED NOT NULL,
  `backup_status` ENUM('verified','stale','blocked','empty') NOT NULL,
  `actual_rpo_minutes` DECIMAL(10,2) UNSIGNED NULL,
  `actual_rto_minutes` DECIMAL(10,2) UNSIGNED NULL,
  `recovery_drill_age_days` DECIMAL(10,2) UNSIGNED NULL,
  `finding_codes_json` JSON NOT NULL,
  `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `observed_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mysql_resilience_observed` (`observed_at`),
  KEY `idx_mysql_resilience_state_time` (`state`,`observed_at`),
  KEY `idx_mysql_resilience_scope_time` (`organization_id`,`workspace_id`,`observed_at`),
  CONSTRAINT `fk_mysql_resilience_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_mysql_resilience_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mysql_resilience_views` (
  `id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `actor_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `observation_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `observed_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mysql_resilience_views_actor_time` (`actor_id`,`observed_at`),
  KEY `idx_mysql_resilience_views_request` (`request_id`),
  CONSTRAINT `fk_mysql_resilience_views_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_mysql_resilience_views_observation` FOREIGN KEY (`observation_id`) REFERENCES `mysql_resilience_observations` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
