CREATE TABLE `crawler_scheduler_leases` (
  `slot_type` ENUM('worker','crawler','provider') NOT NULL,
  `slot_key` VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `slot_no` SMALLINT UNSIGNED NOT NULL,
  `organization_id` CHAR(36) CHARACTER SET ascii NULL,
  `workspace_id` CHAR(36) CHARACTER SET ascii NULL,
  `task_id` CHAR(36) CHARACTER SET ascii NULL,
  `run_id` CHAR(36) CHARACTER SET ascii NULL,
  `lease_owner` VARCHAR(160) CHARACTER SET ascii NOT NULL,
  `lease_token_hash` BINARY(32) NOT NULL,
  `leased_at` DATETIME(3) NOT NULL,
  `heartbeat_at` DATETIME(3) NOT NULL,
  `expires_at` DATETIME(3) NOT NULL,
  `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  PRIMARY KEY (`slot_type`,`slot_key`,`slot_no`),
  UNIQUE KEY `uq_crawler_scheduler_task_slot` (`task_id`,`slot_type`,`slot_key`),
  UNIQUE KEY `uq_crawler_scheduler_run_slot` (`run_id`,`slot_type`,`slot_key`),
  KEY `idx_crawler_scheduler_expiry` (`expires_at`),
  KEY `idx_crawler_scheduler_scope` (`organization_id`,`workspace_id`,`expires_at`),
  CONSTRAINT `fk_crawler_scheduler_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_crawler_scheduler_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_crawler_scheduler_task` FOREIGN KEY (`task_id`) REFERENCES `collection_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_crawler_scheduler_run` FOREIGN KEY (`run_id`) REFERENCES `crawler_browser_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `crawler_scheduler_observations` (
  `id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `source` ENUM('api_full','worker_resource') NOT NULL DEFAULT 'worker_resource',
  `state` ENUM('ready','warning','blocked') NOT NULL,
  `worker_instances` SMALLINT UNSIGNED NOT NULL,
  `crawler_instances` SMALLINT UNSIGNED NOT NULL,
  `active_worker_leases` SMALLINT UNSIGNED NOT NULL,
  `active_crawler_leases` SMALLINT UNSIGNED NOT NULL,
  `duplicate_lease_count` SMALLINT UNSIGNED NOT NULL,
  `load_basis_points` INT UNSIGNED NOT NULL,
  `available_memory_mb` BIGINT UNSIGNED NOT NULL,
  `free_disk_mb` BIGINT UNSIGNED NOT NULL,
  `provider_count` INT UNSIGNED NOT NULL,
  `profile_count` INT UNSIGNED NOT NULL,
  `finding_codes_json` JSON NOT NULL,
  `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `observed_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_crawler_scheduler_observed` (`observed_at`),
  KEY `idx_crawler_scheduler_state_time` (`state`,`observed_at`),
  KEY `idx_crawler_scheduler_source_time` (`source`,`observed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `crawler_scheduler_operations` (
  `id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `actor_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `route` VARCHAR(180) CHARACTER SET ascii NOT NULL,
  `idempotency_key` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `result_json` JSON NOT NULL,
  `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `created_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_crawler_scheduler_operation` (`actor_id`,`route`,`idempotency_key`),
  KEY `idx_crawler_scheduler_operation_request` (`request_id`),
  CONSTRAINT `fk_crawler_scheduler_operation_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
