CREATE TABLE `browser_collection_jobs` (
  `id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `collection_task_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `collection_subquery_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `provider_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `crawler_profile_id` CHAR(36) CHARACTER SET ascii NULL,
  `crawler_run_id` CHAR(36) CHARACTER SET ascii NULL,
  `status` ENUM('queued','leased','succeeded','blocked','failed','timed_out','cancelled') NOT NULL,
  `execution_request_json` JSON NOT NULL,
  `result_json` JSON NULL,
  `error_code` VARCHAR(80) CHARACTER SET ascii NULL,
  `lease_owner` VARCHAR(160) CHARACTER SET ascii NULL,
  `lease_token_hash` BINARY(32) NULL,
  `leased_at` DATETIME(3) NULL,
  `heartbeat_at` DATETIME(3) NULL,
  `lease_expires_at` DATETIME(3) NULL,
  `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `finished_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_browser_collection_subquery` (`collection_subquery_id`),
  UNIQUE KEY `uq_browser_collection_run` (`crawler_run_id`),
  KEY `idx_browser_collection_ready` (`status`,`created_at`),
  KEY `idx_browser_collection_lease` (`lease_expires_at`),
  KEY `idx_browser_collection_scope` (`organization_id`,`workspace_id`,`updated_at`),
  KEY `idx_browser_collection_trace` (`trace_id`),
  CONSTRAINT `fk_browser_collection_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`),
  CONSTRAINT `fk_browser_collection_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_browser_collection_task` FOREIGN KEY (`collection_task_id`) REFERENCES `collection_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_browser_collection_subquery` FOREIGN KEY (`collection_subquery_id`) REFERENCES `collection_subqueries` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_browser_collection_provider` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`),
  CONSTRAINT `fk_browser_collection_profile` FOREIGN KEY (`crawler_profile_id`) REFERENCES `crawler_profiles` (`id`),
  CONSTRAINT `fk_browser_collection_run` FOREIGN KEY (`crawler_run_id`) REFERENCES `crawler_browser_runs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
