CREATE TABLE `browser_evidence_artifacts` (
  `id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `collection_task_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `collection_subquery_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `provider_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `browser_job_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `file_asset_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `kind` ENUM('dom_fragment','screenshot') NOT NULL,
  `source_url` VARCHAR(2048) NOT NULL,
  `content_type` VARCHAR(180) CHARACTER SET ascii NOT NULL,
  `content_sha256` CHAR(64) CHARACTER SET ascii NOT NULL,
  `size_bytes` BIGINT UNSIGNED NOT NULL,
  `captured_at` DATETIME(3) NOT NULL,
  `parser_version` VARCHAR(120) CHARACTER SET ascii NOT NULL,
  `retention_until` DATETIME(3) NOT NULL,
  `status` ENUM('active','expired','deleted') NOT NULL DEFAULT 'active',
  `request_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `trace_id` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `created_by` CHAR(36) CHARACTER SET ascii NOT NULL,
  `created_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_browser_evidence_job_kind` (`browser_job_id`,`kind`),
  KEY `idx_browser_evidence_scope` (`organization_id`,`workspace_id`,`captured_at`),
  KEY `idx_browser_evidence_task` (`collection_task_id`,`collection_subquery_id`,`captured_at`),
  KEY `idx_browser_evidence_provider_version` (`provider_id`,`parser_version`,`captured_at`),
  CONSTRAINT `fk_browser_evidence_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`),
  CONSTRAINT `fk_browser_evidence_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_browser_evidence_task` FOREIGN KEY (`collection_task_id`) REFERENCES `collection_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_browser_evidence_subquery` FOREIGN KEY (`collection_subquery_id`) REFERENCES `collection_subqueries` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_browser_evidence_provider` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`),
  CONSTRAINT `fk_browser_evidence_job` FOREIGN KEY (`browser_job_id`) REFERENCES `browser_collection_jobs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_browser_evidence_file` FOREIGN KEY (`file_asset_id`) REFERENCES `file_assets` (`id`),
  CONSTRAINT `fk_browser_evidence_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
