CREATE TABLE `provider_parser_samples` (
  `id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `organization_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `workspace_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `provider_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `browser_job_id` CHAR(36) CHARACTER SET ascii NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `input_sha256` CHAR(64) CHARACTER SET ascii NOT NULL,
  `snapshots_json` JSON NOT NULL,
  `baseline_output_json` JSON NOT NULL,
  `baseline_output_sha256` CHAR(64) CHARACTER SET ascii NOT NULL,
  `baseline_parser_version` VARCHAR(120) CHARACTER SET ascii NOT NULL,
  `last_replay_status` ENUM('never','passed','changed','failed') NOT NULL DEFAULT 'never',
  `last_replay_at` DATETIME(3) NULL,
  `status` ENUM('active','archived') NOT NULL DEFAULT 'active',
  `created_by` CHAR(36) CHARACTER SET ascii NOT NULL,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_provider_parser_sample_job` (`browser_job_id`),
  UNIQUE KEY `uq_provider_parser_sample_input` (`provider_id`,`input_sha256`),
  KEY `idx_provider_parser_sample_scope` (`organization_id`,`workspace_id`,`provider_id`,`status`),
  CONSTRAINT `fk_provider_parser_sample_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`),
  CONSTRAINT `fk_provider_parser_sample_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_provider_parser_sample_provider` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`),
  CONSTRAINT `fk_provider_parser_sample_job` FOREIGN KEY (`browser_job_id`) REFERENCES `browser_collection_jobs` (`id`),
  CONSTRAINT `fk_provider_parser_sample_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
