CREATE TABLE opportunity_operating_facts (
  id CHAR(36) CHARACTER SET ascii NOT NULL,
  organization_id CHAR(36) CHARACTER SET ascii NOT NULL,
  workspace_id CHAR(36) CHARACTER SET ascii NOT NULL,
  opportunity_id CHAR(36) CHARACTER SET ascii NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  sales_units INT UNSIGNED NOT NULL,
  revenue_amount DECIMAL(18,6) NOT NULL,
  ad_spend_amount DECIMAL(18,6) NOT NULL,
  returned_units INT UNSIGNED NOT NULL,
  purchase_lead_time_days INT UNSIGNED NOT NULL,
  actual_profit_amount DECIMAL(18,6) NOT NULL,
  currency CHAR(3) CHARACTER SET ascii NOT NULL,
  source_ref VARCHAR(255) NOT NULL,
  notes VARCHAR(1000) NULL,
  score_rule_version_snapshot VARCHAR(64) CHARACTER SET ascii NULL,
  profit_rule_version_snapshot VARCHAR(64) CHARACTER SET ascii NULL,
  decision_status_snapshot ENUM('pending','adopted','observing','rejected') NOT NULL,
  predicted_profit_amount DECIMAL(18,6) NULL,
  predicted_currency CHAR(3) CHARACTER SET ascii NULL,
  quoted_lead_time_days INT UNSIGNED NULL,
  observed_at DATETIME(3) NOT NULL,
  request_id VARCHAR(128) CHARACTER SET ascii NOT NULL,
  trace_id VARCHAR(128) CHARACTER SET ascii NOT NULL,
  created_by CHAR(36) CHARACTER SET ascii NOT NULL,
  created_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_operating_fact_scope_time (organization_id,workspace_id,opportunity_id,period_end,created_at),
  KEY idx_operating_fact_trace (trace_id),
  CONSTRAINT fk_operating_fact_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  CONSTRAINT fk_operating_fact_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE RESTRICT,
  CONSTRAINT fk_operating_fact_opportunity FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE,
  CONSTRAINT fk_operating_fact_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
