// Generated from current route catalog, permission helpers and reviewed M02-03 fixtures.
window.SCOUTOPS_SHELL_DESIGN = {
  profiles: {
    member: {
      guard: {
        shell: "member",
        organization_id: "00000000-0000-4000-8000-000000000103",
        workspace_id: "00000000-0000-4000-8000-000000000104",
        roles: ["member"],
        capabilities: [
          "task:read",
          "trend:read",
          "opportunity:read",
          "competitor:read",
          "sourcing:read",
          "notification:read",
        ],
        platform_roles: [],
        platform_capabilities: [],
        guard_reason: "navigation_member_allowed",
      },
      kind: "M02-03 summary fixture",
      items: [
        {
          label: "今日行动",
          icon: "home",
          group: "工作台",
          path: "/home",
          capabilities: ["task:read"],
        },
        {
          label: "今日工作",
          icon: "check",
          group: "工作台",
          path: "/work",
          capabilities: ["task:read"],
        },
        {
          label: "热点趋势",
          icon: "trend",
          group: "洞察与选品",
          path: "/trends",
          capabilities: ["trend:read"],
        },
        {
          label: "选品机会",
          icon: "diamond",
          group: "洞察与选品",
          path: "/opportunities",
          capabilities: ["opportunity:read"],
        },
        {
          label: "竞品监控",
          icon: "target",
          group: "洞察与选品",
          path: "/competitors",
          capabilities: ["competitor:read"],
        },
        {
          label: "供应链与利润",
          icon: "box",
          group: "洞察与选品",
          path: "/sourcing",
          capabilities: ["sourcing:read"],
        },
        {
          label: "任务中心",
          icon: "list",
          group: "工作台",
          path: "/tasks",
          capabilities: ["task:read"],
        },
        {
          label: "审批中心",
          icon: "check",
          group: "工作台",
          path: "/tasks/approvals",
          capabilities: ["task:read"],
        },
        {
          label: "通知中心",
          icon: "bell",
          group: "工作台",
          path: "/notifications",
          capabilities: ["notification:read"],
        },
      ],
      roleLabel: "普通成员",
      allowedPaths: [
        "/home",
        "/work",
        "/trends",
        "/opportunities",
        "/opportunities/scoring-rules",
        "/opportunities/:opportunityId",
        "/competitors",
        "/competitors/monitoring-rules",
        "/sourcing",
        "/sourcing/cost-rules",
        "/tasks",
        "/tasks/:taskId",
        "/tasks/approvals",
        "/notifications",
      ],
    },
    organization_admin: {
      guard: {
        shell: "organization_admin",
        organization_id: "00000000-0000-4000-8000-000000000103",
        workspace_id: "00000000-0000-4000-8000-000000000104",
        roles: ["organization_admin"],
        capabilities: ["task:read", "organization:manage"],
        platform_roles: [],
        platform_capabilities: [],
        guard_reason: "navigation_organization_admin_allowed",
      },
      kind: "M02-03 summary fixture",
      items: [
        { label: "治理概览", icon: "home", group: "概览", path: "/org-admin", capabilities: [] },
        {
          label: "成员与邀请",
          icon: "users",
          group: "人员与权限",
          path: "/org-admin/members",
          capabilities: [],
        },
        {
          label: "角色与权限",
          icon: "shield",
          group: "人员与权限",
          path: "/org-admin/roles",
          capabilities: [],
        },
        {
          label: "工作区管理",
          icon: "building",
          group: "组织结构",
          path: "/org-admin/workspaces",
          capabilities: [],
        },
        {
          label: "团队管理",
          icon: "users",
          group: "组织结构",
          path: "/org-admin/teams",
          capabilities: [],
        },
        {
          label: "审批模板",
          icon: "check",
          group: "组织治理",
          path: "/org-admin/approvals",
          capabilities: [],
        },
        {
          label: "组织令牌",
          icon: "key",
          group: "安全与审计",
          path: "/org-admin/tokens",
          capabilities: [],
        },
      ],
      roleLabel: "组织管理员",
      allowedPaths: [
        "/org-admin",
        "/org-admin/members",
        "/org-admin/roles",
        "/org-admin/workspaces",
        "/org-admin/teams",
        "/org-admin/approvals",
        "/org-admin/tokens",
      ],
    },
    platform_admin: {
      guard: {
        shell: "platform_admin",
        organization_id: null,
        workspace_id: null,
        roles: [],
        capabilities: [],
        platform_roles: ["platform_super_admin"],
        platform_capabilities: ["platform:operate", "platform:secure", "platform:superadmin"],
        guard_reason: "navigation_platform_admin_allowed",
      },
      kind: "M02-03 summary fixture",
      items: [
        {
          label: "平台概览",
          icon: "home",
          group: "业务运营",
          path: "/platform-admin",
          capabilities: ["platform:operate", "platform:superadmin"],
        },
        {
          label: "组织管理",
          icon: "building",
          group: "业务运营",
          path: "/platform-admin/organizations",
          capabilities: ["platform:superadmin"],
        },
        {
          label: "用户管理",
          icon: "person",
          group: "业务运营",
          path: "/platform-admin/users",
          capabilities: ["platform:superadmin"],
        },
        {
          label: "管理员管理",
          icon: "shield",
          group: "业务运营",
          path: "/platform-admin/admins",
          capabilities: ["platform:superadmin"],
        },
        {
          label: "角色权限",
          icon: "key",
          group: "治理与安全",
          path: "/platform-admin/permissions",
          capabilities: ["platform:superadmin"],
        },
        {
          label: "来源设置",
          icon: "settings",
          group: "采集与数据",
          path: "/platform-admin/providers",
          capabilities: ["platform:operate", "platform:superadmin"],
        },
        {
          label: "热点来源",
          icon: "trend",
          group: "采集与数据",
          path: "/platform-admin/providers/sources",
          capabilities: ["platform:operate", "platform:superadmin"],
        },
        {
          label: "采集管理",
          icon: "automation",
          group: "采集与数据",
          path: "/platform-admin/collection/overview",
          capabilities: ["platform:operate", "platform:superadmin"],
        },
        {
          label: "数据中心",
          icon: "database",
          group: "治理与安全",
          path: "/platform-admin/data",
          capabilities: ["platform:operate", "platform:superadmin"],
        },
        {
          label: "质量与规则",
          icon: "settings",
          group: "治理与安全",
          path: "/platform-admin/governance",
          capabilities: ["platform:operate", "platform:superadmin"],
        },
        {
          label: "内容运营",
          icon: "list",
          group: "业务运营",
          path: "/platform-admin/content",
          capabilities: ["platform:operate", "platform:superadmin"],
        },
        {
          label: "通知运营",
          icon: "bell",
          group: "业务运营",
          path: "/platform-admin/notifications",
          capabilities: ["platform:operate", "platform:superadmin"],
        },
        {
          label: "配额管理",
          icon: "chart",
          group: "业务运营",
          path: "/platform-admin/commercial",
          capabilities: ["platform:operate", "platform:superadmin"],
        },
        {
          label: "安全与审计",
          icon: "shield",
          group: "治理与安全",
          path: "/platform-admin/security",
          capabilities: ["platform:secure", "platform:superadmin"],
        },
        {
          label: "系统运维",
          icon: "target",
          group: "高级运维",
          path: "/platform-admin/status",
          capabilities: ["platform:operate", "platform:superadmin"],
        },
      ],
      roleLabel: "平台超级管理员",
      allowedPaths: [
        "/platform-admin",
        "/platform-admin/accounts",
        "/platform-admin/organizations",
        "/platform-admin/organizations/new",
        "/platform-admin/organizations/:organizationId",
        "/platform-admin/users",
        "/platform-admin/admins",
        "/platform-admin/permissions",
        "/platform-admin/providers",
        "/platform-admin/providers/adapters",
        "/platform-admin/providers/sources",
        "/platform-admin/providers/sources/1688-acceptance",
        "/platform-admin/credentials",
        "/platform-admin/collection",
        "/platform-admin/collection/overview",
        "/platform-admin/collection/browser-runtime",
        "/platform-admin/data",
        "/platform-admin/governance",
        "/platform-admin/content",
        "/platform-admin/notifications",
        "/platform-admin/commercial",
        "/platform-admin/security",
        "/platform-admin/status",
        "/platform-admin/logs",
        "/platform-admin/api-coverage",
        "/platform-admin/operations",
        "/platform-admin/releases",
        "/platform-admin/topology",
        "/platform-admin/redis",
        "/platform-admin/mysql",
        "/platform-admin/files",
        "/platform-admin/crawler-scheduler",
        "/platform-admin/capacity",
      ],
    },
    member_platform: {
      guard: {
        shell: "member",
        organization_id: "00000000-0000-4000-8000-000000000103",
        workspace_id: "00000000-0000-4000-8000-000000000104",
        roles: ["member"],
        capabilities: [
          "task:read",
          "trend:read",
          "opportunity:read",
          "competitor:read",
          "sourcing:read",
          "notification:read",
        ],
        platform_roles: ["platform_super_admin"],
        platform_capabilities: [],
        guard_reason: "navigation_member_allowed",
      },
      kind: "M02-03 platform-return fixture override",
      items: [
        {
          label: "今日行动",
          icon: "home",
          group: "工作台",
          path: "/home",
          capabilities: ["task:read"],
        },
        {
          label: "今日工作",
          icon: "check",
          group: "工作台",
          path: "/work",
          capabilities: ["task:read"],
        },
        {
          label: "热点趋势",
          icon: "trend",
          group: "洞察与选品",
          path: "/trends",
          capabilities: ["trend:read"],
        },
        {
          label: "选品机会",
          icon: "diamond",
          group: "洞察与选品",
          path: "/opportunities",
          capabilities: ["opportunity:read"],
        },
        {
          label: "竞品监控",
          icon: "target",
          group: "洞察与选品",
          path: "/competitors",
          capabilities: ["competitor:read"],
        },
        {
          label: "供应链与利润",
          icon: "box",
          group: "洞察与选品",
          path: "/sourcing",
          capabilities: ["sourcing:read"],
        },
        {
          label: "任务中心",
          icon: "list",
          group: "工作台",
          path: "/tasks",
          capabilities: ["task:read"],
        },
        {
          label: "审批中心",
          icon: "check",
          group: "工作台",
          path: "/tasks/approvals",
          capabilities: ["task:read"],
        },
        {
          label: "通知中心",
          icon: "bell",
          group: "工作台",
          path: "/notifications",
          capabilities: ["notification:read"],
        },
      ],
      roleLabel: "普通成员",
      allowedPaths: [
        "/home",
        "/work",
        "/trends",
        "/opportunities",
        "/opportunities/scoring-rules",
        "/opportunities/:opportunityId",
        "/competitors",
        "/competitors/monitoring-rules",
        "/sourcing",
        "/sourcing/cost-rules",
        "/tasks",
        "/tasks/:taskId",
        "/tasks/approvals",
        "/notifications",
      ],
    },
    platform_security: {
      guard: {
        shell: "platform_admin",
        organization_id: null,
        workspace_id: null,
        roles: [],
        capabilities: [],
        platform_roles: ["platform_security_admin"],
        platform_capabilities: ["platform:secure"],
        guard_reason: "navigation_platform_admin_allowed",
      },
      kind: "M02-03 unit security-only subject capability projection",
      items: [
        {
          label: "安全与审计",
          icon: "shield",
          group: "治理与安全",
          path: "/platform-admin/security",
          capabilities: ["platform:secure", "platform:superadmin"],
        },
      ],
      roleLabel: "平台安全管理员",
      allowedPaths: ["/platform-admin/security"],
    },
    organization_auditor: {
      guard: {
        shell: "organization_admin",
        organization_id: "00000000-0000-4000-8000-000000000103",
        workspace_id: "00000000-0000-4000-8000-000000000104",
        roles: ["auditor"],
        capabilities: ["audit:read"],
        platform_roles: [],
        platform_capabilities: [],
        guard_reason: "navigation_organization_admin_allowed",
      },
      kind: "Explicit derived capability boundary; not a real session",
      items: [
        {
          label: "组织审计",
          icon: "shield",
          group: "安全与审计",
          path: "/org-admin/audit",
          capabilities: ["audit:read"],
        },
      ],
      roleLabel: "审计员",
      allowedPaths: ["/org-admin/audit"],
    },
  },
  routes: [
    { path: "/", title: "正在进入", shell: null, surface: "landing", parent: "/", breadcrumb: [] },
    {
      path: "/login",
      title: "登录",
      shell: null,
      surface: "login",
      parent: "/login",
      breadcrumb: [{ label: "登录" }],
    },
    {
      path: "/register",
      title: "注册",
      shell: null,
      surface: "register",
      parent: "/register",
      breadcrumb: [{ label: "注册" }],
    },
    {
      path: "/forgot-password",
      title: "找回密码",
      shell: null,
      surface: "forgot-password",
      parent: "/forgot-password",
      breadcrumb: [{ label: "找回密码" }],
    },
    {
      path: "/verify-email",
      title: "验证邮箱",
      shell: null,
      surface: "verify-email",
      parent: "/verify-email",
      breadcrumb: [{ label: "验证邮箱" }],
    },
    {
      path: "/reset-password",
      title: "重置密码",
      shell: null,
      surface: "reset-password",
      parent: "/reset-password",
      breadcrumb: [{ label: "重置密码" }],
    },
    {
      path: "/security/mfa",
      title: "安全设置",
      shell: null,
      surface: "security-mfa",
      parent: "/security/mfa",
      breadcrumb: [{ label: "账号" }, { label: "安全设置" }],
    },
    {
      path: "/select-context",
      title: "选择组织与工作区",
      shell: null,
      surface: "select-context",
      parent: "/select-context",
      breadcrumb: [{ label: "选择组织与工作区" }],
    },
    {
      path: "/onboarding",
      title: "快速引导",
      shell: null,
      surface: "onboarding",
      parent: "/onboarding",
      breadcrumb: [{ label: "快速引导" }],
    },
    {
      path: "/settings/theme",
      title: "外观偏好",
      shell: null,
      surface: "theme-settings",
      parent: "/settings/theme",
      breadcrumb: [{ label: "账号" }, { label: "外观偏好" }],
    },
    {
      path: "/me",
      title: "个人中心",
      shell: "account",
      surface: "personal-center",
      parent: "/me",
      breadcrumb: [{ label: "账号" }, { label: "个人中心" }],
    },
    {
      path: "/home",
      title: "今日行动",
      shell: "member",
      surface: "home-dashboard",
      parent: "/home",
      breadcrumb: [{ label: "工作台" }, { label: "今日行动" }],
    },
    {
      path: "/work",
      title: "今日工作",
      shell: "member",
      surface: "task-workspace",
      parent: "/work",
      breadcrumb: [{ label: "工作台", path: "/home" }, { label: "今日工作" }],
    },
    {
      path: "/trends",
      title: "热点趋势",
      shell: "member",
      surface: "trend-dashboard",
      parent: "/trends",
      breadcrumb: [{ label: "洞察与选品", path: "/opportunities" }, { label: "热点趋势" }],
    },
    {
      path: "/opportunities",
      title: "选品机会",
      shell: "member",
      surface: "opportunity-workspace",
      parent: "/opportunities",
      breadcrumb: [{ label: "洞察与选品" }, { label: "选品机会" }],
    },
    {
      path: "/opportunities/start",
      title: "创建选品",
      shell: "member",
      surface: "selection-journey",
      parent: "/opportunities/start",
      breadcrumb: [{ label: "洞察与选品", path: "/opportunities" }, { label: "创建选品" }],
    },
    {
      path: "/opportunities/scoring-rules",
      title: "评分规则",
      shell: "member",
      surface: "score-rule-console",
      parent: "/opportunities/scoring-rules",
      breadcrumb: [
        { label: "洞察与选品", path: "/opportunities" },
        { label: "选品机会", path: "/opportunities" },
        { label: "评分规则" },
      ],
    },
    {
      path: "/opportunities/:opportunityId",
      title: "机会详情",
      shell: "member",
      surface: "opportunity-workspace",
      parent: "/opportunities/:opportunityId",
      breadcrumb: [
        { label: "洞察与选品", path: "/opportunities" },
        { label: "选品机会", path: "/opportunities" },
        { label: "机会详情" },
      ],
    },
    {
      path: "/competitors",
      title: "竞品监控",
      shell: "member",
      surface: "competitor-monitor",
      parent: "/competitors",
      breadcrumb: [{ label: "洞察与选品", path: "/opportunities" }, { label: "竞品监控" }],
    },
    {
      path: "/competitors/monitoring-rules",
      title: "竞品监控规则",
      shell: "member",
      surface: "competitor-monitor",
      parent: "/competitors/monitoring-rules",
      breadcrumb: [
        { label: "洞察与选品", path: "/opportunities" },
        { label: "竞品监控" },
        { label: "监控规则" },
      ],
    },
    {
      path: "/sourcing",
      title: "供应链与利润",
      shell: "member",
      surface: "sourcing-workspace",
      parent: "/sourcing",
      breadcrumb: [{ label: "洞察与选品", path: "/opportunities" }, { label: "供应链与利润" }],
    },
    {
      path: "/sourcing/cost-rules",
      title: "费用与利润规则",
      shell: "member",
      surface: "cost-rule-console",
      parent: "/sourcing/cost-rules",
      breadcrumb: [
        { label: "洞察与选品", path: "/opportunities" },
        { label: "供应链与利润", path: "/sourcing" },
        { label: "费用规则" },
      ],
    },
    {
      path: "/tasks",
      title: "全部任务",
      shell: "member",
      surface: "task-workspace",
      parent: "/tasks",
      breadcrumb: [{ label: "工作台", path: "/home" }, { label: "全部任务" }],
    },
    {
      path: "/tasks/:taskId",
      title: "任务详情",
      shell: "member",
      surface: "task-workspace",
      parent: "/tasks/:taskId",
      breadcrumb: [
        { label: "工作台", path: "/home" },
        { label: "全部任务", path: "/tasks" },
        { label: "任务详情" },
      ],
    },
    {
      path: "/tasks/approvals",
      title: "审批中心",
      shell: "member",
      surface: "approval-workspace",
      parent: "/tasks/approvals",
      breadcrumb: [{ label: "工作台", path: "/home" }, { label: "审批中心" }],
    },
    {
      path: "/notifications",
      title: "通知中心",
      shell: "member",
      surface: "notification-center",
      parent: "/notifications",
      breadcrumb: [{ label: "工作台", path: "/home" }, { label: "通知中心" }],
    },
    {
      path: "/automations",
      title: "自动化规则",
      shell: "member",
      surface: "automation-rule-center",
      parent: "/automations",
      breadcrumb: [{ label: "运营工具" }, { label: "自动化规则" }],
    },
    {
      path: "/reports",
      title: "报表与导出",
      shell: "member",
      surface: "report-center",
      parent: "/reports",
      breadcrumb: [{ label: "运营工具", path: "/automations" }, { label: "报表与导出" }],
    },
    {
      path: "/org-admin",
      title: "治理概览",
      shell: "organization_admin",
      surface: "organization-admin-center",
      parent: "/org-admin",
      breadcrumb: [{ label: "组织后台" }, { label: "治理概览" }],
    },
    {
      path: "/org-admin/members",
      title: "成员与邀请",
      shell: "organization_admin",
      surface: "organization-admin-center",
      parent: "/org-admin/members",
      breadcrumb: [{ label: "组织后台", path: "/org-admin" }, { label: "成员与邀请" }],
    },
    {
      path: "/org-admin/roles",
      title: "角色与权限",
      shell: "organization_admin",
      surface: "organization-admin-center",
      parent: "/org-admin/roles",
      breadcrumb: [{ label: "组织后台", path: "/org-admin" }, { label: "角色与权限" }],
    },
    {
      path: "/org-admin/workspaces",
      title: "工作区管理",
      shell: "organization_admin",
      surface: "organization-admin-center",
      parent: "/org-admin/workspaces",
      breadcrumb: [{ label: "组织后台", path: "/org-admin" }, { label: "工作区管理" }],
    },
    {
      path: "/org-admin/teams",
      title: "团队管理",
      shell: "organization_admin",
      surface: "organization-admin-center",
      parent: "/org-admin/teams",
      breadcrumb: [{ label: "组织后台", path: "/org-admin" }, { label: "团队管理" }],
    },
    {
      path: "/org-admin/approvals",
      title: "审批模板",
      shell: "organization_admin",
      surface: "organization-admin-center",
      parent: "/org-admin/approvals",
      breadcrumb: [{ label: "组织后台", path: "/org-admin" }, { label: "审批模板" }],
    },
    {
      path: "/org-admin/data",
      title: "组织数据",
      shell: "organization_admin",
      surface: "organization-admin-center",
      parent: "/org-admin/data",
      breadcrumb: [{ label: "组织后台", path: "/org-admin" }, { label: "组织数据" }],
    },
    {
      path: "/org-admin/tokens",
      title: "组织令牌",
      shell: "organization_admin",
      surface: "organization-admin-center",
      parent: "/org-admin/tokens",
      breadcrumb: [{ label: "组织后台", path: "/org-admin" }, { label: "组织令牌" }],
    },
    {
      path: "/org-admin/audit",
      title: "组织审计",
      shell: "organization_admin",
      surface: "organization-admin-center",
      parent: "/org-admin/audit",
      breadcrumb: [{ label: "组织后台", path: "/org-admin" }, { label: "组织审计" }],
    },
    {
      path: "/platform-admin",
      title: "平台概览",
      shell: "platform_admin",
      surface: "platform-dashboard",
      parent: "/platform-admin",
      breadcrumb: [{ label: "平台后台" }, { label: "平台概览" }],
    },
    {
      path: "/platform-admin/accounts",
      title: "账号与组织",
      shell: "platform_admin",
      surface: "platform-account-center",
      parent: "/platform-admin/organizations",
      breadcrumb: [{ label: "平台后台", path: "/platform-admin" }, { label: "账号与组织" }],
    },
    {
      path: "/platform-admin/organizations",
      title: "组织管理",
      shell: "platform_admin",
      surface: "platform-account-center",
      parent: "/platform-admin/organizations",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "账号与组织", path: "/platform-admin/accounts" },
        { label: "组织管理" },
      ],
    },
    {
      path: "/platform-admin/organizations/new",
      title: "创建组织",
      shell: "platform_admin",
      surface: "platform-account-center",
      parent: "/platform-admin/organizations",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "账号与组织", path: "/platform-admin/accounts" },
        { label: "组织管理" },
        { label: "创建组织" },
      ],
    },
    {
      path: "/platform-admin/organizations/:organizationId",
      title: "组织详情",
      shell: "platform_admin",
      surface: "platform-account-center",
      parent: "/platform-admin/organizations",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "账号与组织", path: "/platform-admin/accounts" },
        { label: "组织管理" },
        { label: "组织详情" },
      ],
    },
    {
      path: "/platform-admin/users",
      title: "用户管理",
      shell: "platform_admin",
      surface: "platform-account-center",
      parent: "/platform-admin/users",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "账号与组织", path: "/platform-admin/accounts" },
        { label: "用户管理" },
      ],
    },
    {
      path: "/platform-admin/admins",
      title: "管理员管理",
      shell: "platform_admin",
      surface: "platform-account-center",
      parent: "/platform-admin/admins",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "账号与组织", path: "/platform-admin/accounts" },
        { label: "管理员管理" },
      ],
    },
    {
      path: "/platform-admin/permissions",
      title: "角色权限",
      shell: "platform_admin",
      surface: "platform-account-center",
      parent: "/platform-admin/admins",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "账号与组织", path: "/platform-admin/accounts" },
        { label: "角色权限" },
      ],
    },
    {
      path: "/platform-admin/providers",
      title: "来源设置",
      shell: "platform_admin",
      surface: "provider-runtime-surface",
      parent: "/platform-admin/providers/sources",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "热点与采集" },
        { label: "来源设置" },
      ],
    },
    {
      path: "/platform-admin/providers/adapters",
      title: "采集程序",
      shell: "platform_admin",
      surface: "provider-runtime-surface",
      parent: "/platform-admin/providers/sources",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "热点与采集", path: "/platform-admin/providers" },
        { label: "采集程序" },
      ],
    },
    {
      path: "/platform-admin/providers/sources",
      title: "热点来源",
      shell: "platform_admin",
      surface: "provider-runtime-surface",
      parent: "/platform-admin/providers/sources",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "热点与采集", path: "/platform-admin/providers" },
        { label: "热点来源" },
      ],
    },
    {
      path: "/platform-admin/providers/sources/1688-acceptance",
      title: "1688 启用检查",
      shell: "platform_admin",
      surface: "provider-runtime-surface",
      parent: "/platform-admin/providers/sources",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "热点与采集", path: "/platform-admin/providers" },
        { label: "1688 启用检查" },
      ],
    },
    {
      path: "/platform-admin/credentials",
      title: "凭证与档案",
      shell: "platform_admin",
      surface: "provider-runtime-surface",
      parent: "/platform-admin/providers/sources",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "热点与采集", path: "/platform-admin/providers" },
        { label: "凭证与档案" },
      ],
    },
    {
      path: "/platform-admin/collection",
      title: "采集任务",
      shell: "platform_admin",
      surface: "collection-runtime-surface",
      parent: "/platform-admin/collection/overview",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "热点与采集", path: "/platform-admin/providers" },
        { label: "采集任务" },
      ],
    },
    {
      path: "/platform-admin/collection/overview",
      title: "采集总览",
      shell: "platform_admin",
      surface: "collection-runtime-surface",
      parent: "/platform-admin/collection/overview",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "热点与采集", path: "/platform-admin/providers" },
        { label: "采集总览" },
      ],
    },
    {
      path: "/platform-admin/collection/browser-runtime",
      title: "网页登录采集",
      shell: "platform_admin",
      surface: "collection-runtime-surface",
      parent: "/platform-admin/collection/overview",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "热点与采集", path: "/platform-admin/providers" },
        { label: "网页登录采集" },
      ],
    },
    {
      path: "/platform-admin/data",
      title: "数据中心",
      shell: "platform_admin",
      surface: "platform-data-center",
      parent: "/platform-admin/data",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "数据治理" },
        { label: "数据中心" },
      ],
    },
    {
      path: "/platform-admin/governance",
      title: "质量与规则",
      shell: "platform_admin",
      surface: "platform-governance-center",
      parent: "/platform-admin/governance",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "数据治理", path: "/platform-admin/data" },
        { label: "质量与规则" },
      ],
    },
    {
      path: "/platform-admin/content",
      title: "内容管理",
      shell: "platform_admin",
      surface: "platform-management-center",
      parent: "/platform-admin/content",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "运营中心" },
        { label: "内容管理" },
      ],
    },
    {
      path: "/platform-admin/notifications",
      title: "通知管理",
      shell: "platform_admin",
      surface: "platform-management-center",
      parent: "/platform-admin/notifications",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "运营中心", path: "/platform-admin/content" },
        { label: "通知管理" },
      ],
    },
    {
      path: "/platform-admin/commercial",
      title: "配额管理",
      shell: "platform_admin",
      surface: "commercial-operations-center",
      parent: "/platform-admin/commercial",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "运营中心", path: "/platform-admin/content" },
        { label: "配额管理" },
      ],
    },
    {
      path: "/platform-admin/security",
      title: "安全中心",
      shell: "platform_admin",
      surface: "security-operations-center",
      parent: "/platform-admin/security",
      breadcrumb: [{ label: "平台后台", path: "/platform-admin" }, { label: "安全中心" }],
    },
    {
      path: "/platform-admin/open-platform",
      title: "开放平台",
      shell: "platform_admin",
      surface: "open-platform-center",
      parent: "/platform-admin/open-platform",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "安全中心", path: "/platform-admin/security" },
        { label: "开放平台" },
      ],
    },
    {
      path: "/platform-admin/status",
      title: "系统状态",
      shell: "platform_admin",
      surface: "platform-management-center",
      parent: "/platform-admin/status",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维" },
        { label: "系统状态" },
      ],
    },
    {
      path: "/platform-admin/logs",
      title: "链路日志",
      shell: "platform_admin",
      surface: "platform-log-center",
      parent: "/platform-admin/status",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维", path: "/platform-admin/status" },
        { label: "链路日志" },
      ],
    },
    {
      path: "/platform-admin/api-coverage",
      title: "接口覆盖证据",
      shell: "platform_admin",
      surface: "platform-management-center",
      parent: "/platform-admin/api-coverage",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维", path: "/platform-admin/status" },
        { label: "接口覆盖证据" },
      ],
    },
    {
      path: "/platform-admin/operations",
      title: "备份与恢复",
      shell: "platform_admin",
      surface: "backup-recovery-center",
      parent: "/platform-admin/status",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维", path: "/platform-admin/status" },
        { label: "备份与恢复" },
      ],
    },
    {
      path: "/platform-admin/releases",
      title: "发布管理",
      shell: "platform_admin",
      surface: "release-rollout-center",
      parent: "/platform-admin/status",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维", path: "/platform-admin/status" },
        { label: "发布管理" },
      ],
    },
    {
      path: "/platform-admin/topology",
      title: "服务拓扑",
      shell: "platform_admin",
      surface: "runtime-topology-center",
      parent: "/platform-admin/status",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维", path: "/platform-admin/status" },
        { label: "服务拓扑" },
      ],
    },
    {
      path: "/platform-admin/redis",
      title: "Redis 运行",
      shell: "platform_admin",
      surface: "redis-resilience-center",
      parent: "/platform-admin/status",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维", path: "/platform-admin/status" },
        { label: "Redis 运行" },
      ],
    },
    {
      path: "/platform-admin/mysql",
      title: "MySQL 运行",
      shell: "platform_admin",
      surface: "mysql-resilience-center",
      parent: "/platform-admin/status",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维", path: "/platform-admin/status" },
        { label: "MySQL 运行" },
      ],
    },
    {
      path: "/platform-admin/files",
      title: "文件存储",
      shell: "platform_admin",
      surface: "file-resilience-center",
      parent: "/platform-admin/status",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维", path: "/platform-admin/status" },
        { label: "文件存储" },
      ],
    },
    {
      path: "/platform-admin/crawler-scheduler",
      title: "采集调度",
      shell: "platform_admin",
      surface: "crawler-scheduler-center",
      parent: "/platform-admin/status",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维", path: "/platform-admin/status" },
        { label: "采集调度" },
      ],
    },
    {
      path: "/platform-admin/capacity",
      title: "容量边界",
      shell: "platform_admin",
      surface: "capacity-boundary-center",
      parent: "/platform-admin/status",
      breadcrumb: [
        { label: "平台后台", path: "/platform-admin" },
        { label: "系统运维", path: "/platform-admin/status" },
        { label: "容量边界" },
      ],
    },
    {
      path: "/:pathMatch(.*)*",
      title: "页面不存在",
      shell: null,
      surface: "not-found",
      parent: "/:pathMatch(.*)*",
      breadcrumb: [{ label: "页面不存在" }],
    },
  ],
  operations: [
    { label: "系统状态", path: "/platform-admin/status" },
    { label: "链路日志", path: "/platform-admin/logs" },
    { label: "服务拓扑", path: "/platform-admin/topology" },
    { label: "采集调度", path: "/platform-admin/crawler-scheduler" },
    { label: "Redis", path: "/platform-admin/redis" },
    { label: "MySQL", path: "/platform-admin/mysql" },
    { label: "文件存储", path: "/platform-admin/files" },
    { label: "备份恢复", path: "/platform-admin/operations" },
    { label: "发布管理", path: "/platform-admin/releases" },
    { label: "容量边界", path: "/platform-admin/capacity" },
  ],
};
