window.FILES_DATA = {
  sourcePaths: [
    "packages/storage/src/index.ts",
    "apps/api/src/file-resilience-probe.ts",
    "apps/api/src/file-resilience-service.ts",
    "apps/api/src/file-resilience-repository.ts",
    "apps/api/src/file-resilience-routes.ts",
    "apps/web/src/components/FileResilienceCenter.vue",
    "apps/web/src/components/TechnicalDetails.vue",
    "tests/e2e/m08-04-file-resilience.spec.ts",
    "infra/baota/local-file-storage-manifest.json",
    "packages/config/src/index.ts",
    "packages/contracts/src/index.ts",
  ],
  sourceChecks: [
    "Actual probe with inert SQL/access/statfs and memory-only SHA256 streams: three roots, retained index counts on access failure, evidence-first remaining-limit export sampling, valid/invalid paths, matching/missing/mismatch, temp excluded, signal before and during stream. SQL text/parameters executed against inert rows, not SQL engine, filesystem, ACL or real stream cancellation.",
    "Actual probe recovery and evaluator/service: recent20 backup/drill, evidence/export encrypted recovery assets, isolation/age rounding/future clamp, stale warning distinct from MySQL, null-age evaluator boundary, probe state versus runtime policy; zero-sample ready preserved, max filesystem usage not sum, 10000 unknown sentinel and negative raw ratio versus used_bytes clamp; public/shared/backup fixed flags never override findings. Original E2E separate; no real recovery or public exposure scan.",
    "Actual Vue script: single-flight exact GET/IDs, 15s, null empty, auth clearing/transient retention, generic empty requestID and unmount abort. Root labels, purpose and one-decimal percent helpers extracted from source; source template progress names bound. Not mounted Vue/preserve or shared clipboard proof.",
    "Actual service abort checkpoints before/after probe and after record; actual repository inert connection verifies three inserts/commit, audit-fail rollback and abort after first insert rollback/release. Service passes signal to probe; cancellation after record may occur after its work. No running-SQL interruption, real durability or transaction proof.",
    "Actual route handler with inert auth/service/timers/events: exact private GET and operate guard before service, default14s race abort, dependency503, correlation and finish cleanup. No real session/RBAC server, socket disconnect or production request executed.",
  ],
  datasets: {
    ready: {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "root-count": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_root_unavailable",
          severity: "blocked",
          action_hint: "在宝塔核对证据、导出与临时受控目录的挂载、权限和可写状态。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "roots-empty": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_root_unavailable",
          severity: "blocked",
          action_hint: "在宝塔核对证据、导出与临时受控目录的挂载、权限和可写状态。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "not-writable": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: false,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_root_unavailable",
          severity: "blocked",
          action_hint: "在宝塔核对证据、导出与临时受控目录的挂载、权限和可写状态。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "public-exposed": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_root_publicly_exposed",
          severity: "blocked",
          action_hint: "立即从宝塔网站静态目录或 Nginx alias 中移除受控文件根。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "shared-boundary": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "shared_storage_unexpected",
          severity: "blocked",
          action_hint: "S0 仅允许当前主机的宝塔受控目录，停止共享存储配置。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "backup-boundary": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "backup_server_unexpected",
          severity: "blocked",
          action_hint: "当前范围不允许备用服务器，请恢复为同机加密恢复副本。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "capacity-warning": {
      state: "warning",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 307200000,
          total_bytes: 409600000,
          usage_basis_points: 7500,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_capacity_warning",
          severity: "warning",
          action_hint: "受控目录接近容量水位，请按保留策略归档并核验恢复副本。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "capacity-stop": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 368640000,
          total_bytes: 409600000,
          usage_basis_points: 9000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_capacity_stop",
          severity: "blocked",
          action_hint: "停止新增大文件任务并通过宝塔释放或扩展当前主机受控目录。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "recovery-unencrypted": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: false,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔任务核验 evidence/同机加密副本及隔离恢复。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "recovery-unisolated": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: false,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔任务核验 evidence/同机加密副本及隔离恢复。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "capacity-unknown": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 0,
          total_bytes: 0,
          usage_basis_points: 10000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_capacity_stop",
          severity: "blocked",
          action_hint: "停止新增大文件任务并通过宝塔释放或扩展当前主机受控目录。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "root-access-failed": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: false,
          writable: false,
          used_bytes: 0,
          total_bytes: 0,
          usage_basis_points: 10000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_root_unavailable",
          severity: "blocked",
          action_hint: "在宝塔核对证据、导出与临时受控目录的挂载、权限和可写状态。",
        },
        {
          code: "file_capacity_stop",
          severity: "blocked",
          action_hint: "停止新增大文件任务并通过宝塔释放或扩展当前主机受控目录。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "root-stat-failed": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: false,
          writable: false,
          used_bytes: 0,
          total_bytes: 0,
          usage_basis_points: 10000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_root_unavailable",
          severity: "blocked",
          action_hint: "在宝塔核对证据、导出与临时受控目录的挂载、权限和可写状态。",
        },
        {
          code: "file_capacity_stop",
          severity: "blocked",
          action_hint: "停止新增大文件任务并通过宝塔释放或扩展当前主机受控目录。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "all-roots-failed": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: false,
          writable: false,
          used_bytes: 0,
          total_bytes: 0,
          usage_basis_points: 10000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: false,
          writable: false,
          used_bytes: 0,
          total_bytes: 0,
          usage_basis_points: 10000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: false,
          writable: false,
          used_bytes: 0,
          total_bytes: 0,
          usage_basis_points: 10000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_root_unavailable",
          severity: "blocked",
          action_hint: "在宝塔核对证据、导出与临时受控目录的挂载、权限和可写状态。",
        },
        {
          code: "file_capacity_stop",
          severity: "blocked",
          action_hint: "停止新增大文件任务并通过宝塔释放或扩展当前主机受控目录。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "same-filesystem": {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "measured-zero": {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 0,
          total_bytes: 409600000,
          usage_basis_points: 0,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 0,
          total_bytes: 409600000,
          usage_basis_points: 0,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 0,
          total_bytes: 409600000,
          usage_basis_points: 0,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "over-capacity": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 410009600,
          total_bytes: 409600000,
          usage_basis_points: 10000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_capacity_stop",
          severity: "blocked",
          action_hint: "停止新增大文件任务并通过宝塔释放或扩展当前主机受控目录。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "negative-ratio": {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 0,
          total_bytes: 409600000,
          usage_basis_points: -1000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "no-samples": {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 0, verified_files: 0, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "no-assets": {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 0, verified_files: 0, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "evidence-first": {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 2, verified_files: 2, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "one-sample": {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 1, verified_files: 1, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "all-mismatch": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 0, mismatch_files: 3, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_checksum_mismatch",
          severity: "blocked",
          action_hint: "隔离哈希不一致文件并由宝塔任务从同机加密副本恢复。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "all-missing": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 0, mismatch_files: 0, missing_files: 3 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_missing",
          severity: "blocked",
          action_hint: "停止相关下载或任务并核对文件资产与受控目录。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "invalid-paths": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 1, mismatch_files: 0, missing_files: 2 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_missing",
          severity: "blocked",
          action_hint: "停止相关下载或任务并核对文件资产与受控目录。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "recovery-empty": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "empty",
        encrypted_same_host_copy: false,
        isolated_restore_verified: false,
        drill_age_days: null,
      },
      findings: [
        {
          code: "file_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔任务核验 evidence/同机加密副本及隔离恢复。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "recovery-history-failed": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "empty",
        encrypted_same_host_copy: false,
        isolated_restore_verified: false,
        drill_age_days: null,
      },
      findings: [
        {
          code: "file_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔任务核验 evidence/同机加密副本及隔离恢复。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "recovery-assets-failed": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "blocked",
        encrypted_same_host_copy: false,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔任务核验 evidence/同机加密副本及隔离恢复。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "recovery-asset-missing": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "blocked",
        encrypted_same_host_copy: false,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔任务核验 evidence/同机加密副本及隔离恢复。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "drill-not-isolated": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "blocked",
        encrypted_same_host_copy: true,
        isolated_restore_verified: false,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔任务核验 evidence/同机加密副本及隔离恢复。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "drill-stale": {
      state: "warning",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "stale",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 90,
      },
      findings: [
        {
          code: "file_recovery_drill_stale",
          severity: "warning",
          action_hint: "最近文件恢复演练超过 90 天。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "drill-boundary": {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 90,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "drill-null": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "blocked",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: null,
      },
      findings: [
        {
          code: "file_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔任务核验 evidence/同机加密副本及隔离恢复。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "drill-future": {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 0,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "public-probe": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_root_publicly_exposed",
          severity: "blocked",
          action_hint: "立即从宝塔网站静态目录或 Nginx alias 中移除受控文件根。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "twenty-drills": {
      state: "blocked",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "blocked",
        encrypted_same_host_copy: false,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [
        {
          code: "file_recovery_unverified",
          severity: "blocked",
          action_hint: "通过宝塔任务核验 evidence/同机加密副本及隔离恢复。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "verified-null-age": {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: null,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "stricter-policy": {
      state: "warning",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 90,
      },
      findings: [
        {
          code: "file_recovery_drill_stale",
          severity: "warning",
          action_hint: "最近文件恢复演练超过 60 天。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    "relaxed-policy": {
      state: "warning",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 100,
          indexed_bytes: 20000000,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "stale",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 90,
      },
      findings: [
        {
          code: "file_recovery_drill_stale",
          severity: "warning",
          action_hint: "最近文件恢复演练超过 120 天。",
        },
      ],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    long: {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 999999999999,
          indexed_bytes: 999999999999999,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 30,
          indexed_bytes: 5000000,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 163840000,
          total_bytes: 409600000,
          usage_basis_points: 4000,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 3, verified_files: 3, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-09-09T08:00:00.000Z",
    },
    original: {
      state: "ready",
      mode: "local_managed_directories",
      directories: [
        {
          kind: "evidence",
          available: true,
          writable: true,
          used_bytes: 10737418240,
          total_bytes: 429496729600,
          usage_basis_points: 250,
          active_files: 132,
          indexed_bytes: 9663676416,
        },
        {
          kind: "export",
          available: true,
          writable: true,
          used_bytes: 21474836480,
          total_bytes: 429496729600,
          usage_basis_points: 500,
          active_files: 26,
          indexed_bytes: 19327352832,
        },
        {
          kind: "temp",
          available: true,
          writable: true,
          used_bytes: 32212254720,
          total_bytes: 429496729600,
          usage_basis_points: 750,
          active_files: 0,
          indexed_bytes: 0,
        },
      ],
      integrity: { sampled_files: 20, verified_files: 20, mismatch_files: 0, missing_files: 0 },
      recovery: {
        status: "verified",
        encrypted_same_host_copy: true,
        isolated_restore_verified: true,
        drill_age_days: 1,
      },
      findings: [],
      organization_scoped: true,
      public_access_enabled: false,
      shared_storage_enabled: false,
      backup_server_used: false,
      capacity_claim: "unverified",
      observed_at: "2026-08-15T08:00:00.000Z",
    },
  },
  labels: {
    ready: "三目录与三个样本的源返回",
    "root-count": "仅两目录（评估边界）",
    "roots-empty": "未返回目录（评估边界）",
    "not-writable": "可用但不可写（评估边界）",
    "public-exposed": "目录落在静态根内",
    "shared-boundary": "非预期共享（评估边界）",
    "backup-boundary": "非预期备用机（评估边界）",
    "capacity-warning": "75%预警边界",
    "capacity-stop": "90%停止边界",
    "recovery-unencrypted": "加密副本条件未满足",
    "recovery-unisolated": "隔离恢复条件未满足",
    "capacity-unknown": "容量0但可用（评估边界）",
    "root-access-failed": "导出根访问失败",
    "root-stat-failed": "临时根容量读取失败",
    "all-roots-failed": "三个根访问均失败",
    "same-filesystem": "同盘相同水位不相加",
    "measured-zero": "文件系统真实零用量",
    "over-capacity": "可用空间负值导致比例封顶",
    "negative-ratio": "可用空间超过总量（源负比例）",
    "no-samples": "活动索引非零但本次样本为空",
    "no-assets": "无活动资产与样本",
    "evidence-first": "证据占满抽样名额",
    "one-sample": "仅一个配置样本",
    "all-mismatch": "所有样本校验不一致",
    "all-missing": "所有样本读取失败",
    "invalid-paths": "证据逃逸与导出片段非法",
    "recovery-empty": "没有恢复记录",
    "recovery-history-failed": "恢复历史查询失败",
    "recovery-assets-failed": "恢复资产查询失败",
    "recovery-asset-missing": "缺少导出恢复副本",
    "drill-not-isolated": "演练未隔离",
    "drill-stale": "略超90天但返回取整90",
    "drill-boundary": "恰好90天",
    "drill-null": "演练没有完成时间",
    "drill-future": "未来演练年龄归零",
    "public-probe": "实际路径包含检查命中",
    "twenty-drills": "最近20条只有演练",
    "verified-null-age": "verified但年龄null（评估边界）",
    "stricter-policy": "60天运行policy",
    "relaxed-policy": "放宽policy不覆盖probe的stale",
    long: "长数值布局压力（非生产）",
    original: "独立原始E2E夹具",
  },
  clock: "2026-09-09T08:00:00.000Z",
  provenance:
    "Synthetic source outputs; original E2E independent; no live database/recovery observations.",
};
