import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

const required=["database/migrations/0035_capacity_boundary_m08_06.up.sql","database/migrations/0035_capacity_boundary_m08_06.down.sql","apps/api/src/capacity-boundary-service.ts","apps/api/src/capacity-boundary-repository.ts","apps/api/src/capacity-boundary-routes.ts","apps/web/src/components/CapacityBoundaryCenter.vue","apps/web/src/capacity-boundary.css","infra/baota/capacity-boundary-manifest.json","verification/capacity-boundary-production-evidence.schema.json","scripts/verify-capacity-boundary-production.mjs","scripts/verify-capacity-boundary-live.mjs","docs/architecture/m08-06-capacity-boundary.md","docs/runbooks/m08-06-capacity-boundary.md","tests/e2e/m08-06-capacity-boundary.spec.ts","verification/modules/M08-06.json"];

test("M08-06.A01-A17 deliver a measured BaoTa-only single-host capacity boundary",async()=>{const all=(await Promise.all(required.map(path=>readFile(path,"utf8")))).join("\n");for(const token of ["M08-06","single_host","measured","degradation","archive","recovery","platform:operate","request_id","trace_id","rollback","baota"])assert.match(all,new RegExp(token,"i"));assert.doesNotMatch(all,/systemctl\s|pm2\s+start|docker(?:-|\s)compose\s+up|multi-node verified|10000 users supported|load balancing enabled|backup server enabled/i);});

test("M08-06.A02/A04/A12 evaluates measured latency error queue resource and recovery gates",async()=>{const {evaluateCapacityBoundary}=await import("../../apps/api/dist/capacity-boundary-service.js");const policy={readP95StopMs:300,writeP95StopMs:600,errorRateStopBasisPoints:100,asyncLagStopSeconds:60,maximumLoadBasisPoints:8500,minimumAvailableMemoryMb:1024,minimumFreeDiskMb:4096,maximumEvidenceAgeMinutes:60};const base={measured_concurrency:10,read_p95_ms:120,write_p95_ms:260,error_rate_basis_points:0,async_lag_seconds:2,load_basis_points:3000,available_memory_mb:4096,free_disk_mb:8192,archive_verified:true,recovery_verified:true,observed_at:"2026-08-15T08:00:00.000Z"};assert.equal(evaluateCapacityBoundary(base,policy,new Date("2026-08-15T08:20:00.000Z")).state,"ready");const warning=evaluateCapacityBoundary({...base,read_p95_ms:270},policy,new Date("2026-08-15T08:20:00.000Z"));assert.equal(warning.state,"warning");assert.ok(warning.findings.some(item=>item.code==="capacity_read_latency_warning"));const blocked=evaluateCapacityBoundary({...base,write_p95_ms:601,recovery_verified:false},policy,new Date("2026-08-15T08:20:00.000Z"));assert.equal(blocked.state,"blocked");for(const code of ["capacity_write_latency_exceeded","capacity_recovery_unverified"])assert.ok(blocked.findings.some(item=>item.code===code));assert.equal(evaluateCapacityBoundary({...base,observed_at:"2026-08-15T06:00:00.000Z"},policy,new Date("2026-08-15T08:20:00.000Z")).state,"blocked");});

test("M08-06.A04/A06/A09 operations routes are platform-only and fail closed",async()=>{const {buildApp}=await import("../../apps/api/dist/app.js");const calls=[],dto={state:"ready",boundary:{measured_concurrency:10,planning_users:100,planning_concurrency_min:5,planning_concurrency_max:20,capacity_claim:"measured_single_host_limited"},performance:{read_p95_ms:120,write_p95_ms:260,error_rate_basis_points:0,async_lag_seconds:2},resource:{load_basis_points:3000,available_memory_mb:4096,free_disk_mb:8192},resilience:{archive_verified:true,recovery_verified:true},degradation:{mode:"normal",actions:[]},findings:[],single_host:true,load_balancing_enabled:false,backup_server_used:false,multi_node_claim:false,observed_at:"2026-08-15T08:00:00.000Z"};const service={read:async input=>(calls.push(["read",input]),dto),attestDrill:async input=>(calls.push(["drill",input]),{status:"verified",observed_at:dto.observed_at})};const authorization={authorize:async input=>calls.push(["authorize",input])},auth={authenticate:async()=>({user:{id:"00000000-0000-4000-8000-000000000806"}})};const app=buildApp({capacityBoundary:{service,authorization,auth,secureCookie:false,webOrigin:"http://127.0.0.1:5173"}});let response=await app.inject({method:"GET",url:"/api/v1/platform/operations/capacity",headers:{cookie:"scoutops_session=test"}});assert.equal(response.statusCode,200);assert.equal(calls[0][1].capability,"platform:operate");assert.doesNotMatch(response.body,/password|credential|cookie|host_path|sql_text/i);response=await app.inject({method:"POST",url:"/api/v1/platform/operations/capacity/drills",headers:{cookie:"scoutops_session=test",origin:"http://127.0.0.1:5173","idempotency-key":"drill-1"},payload:{kind:"archive_recovery",reason:"季度单机收尾演练"}});assert.equal(response.statusCode,200);assert.equal(calls.at(-1)[1].idempotencyKey,"drill-1");assert.equal((await app.inject({method:"POST",url:"/api/v1/platform/operations/capacity/drills",headers:{cookie:"scoutops_session=test",origin:"https://evil.test","idempotency-key":"drill-2"},payload:{kind:"archive_recovery",reason:"季度单机收尾演练"}})).statusCode,403);await app.close();});

test("M08-06.A03/A10/A13 migration configuration and contracts stay MySQL57 and single-host",async()=>{const [up,down,openapi,featureMap,schema,env,manifest,evidenceSchema]=await Promise.all(["database/migrations/0035_capacity_boundary_m08_06.up.sql","database/migrations/0035_capacity_boundary_m08_06.down.sql","docs/openapi.yaml","docs/feature-map.json","config/schema.json","config/env.example","infra/baota/capacity-boundary-manifest.json","verification/capacity-boundary-production-evidence.schema.json"].map(path=>readFile(path,"utf8")));for(const table of ["capacity_boundary_observations","capacity_boundary_drills","capacity_boundary_operations"])assert.ok(up.includes(`CREATE TABLE \`${table}\``));assert.match(up,/utf8mb4/);assert.doesNotMatch(up,/CHECK\s*\(|utf8mb4_0900|INVISIBLE\s+INDEX/i);assert.match(down,/DROP TABLE IF EXISTS `capacity_boundary_observations`/);for(const key of ["CAPACITY_BOUNDARY_READ_P95_MS","CAPACITY_BOUNDARY_WRITE_P95_MS","CAPACITY_BOUNDARY_ERROR_RATE_PERCENT","CAPACITY_BOUNDARY_ASYNC_LAG_SECONDS","CAPACITY_BOUNDARY_PRODUCTION_EVIDENCE_FILE"]){assert.match(schema,new RegExp(key));assert.match(env,new RegExp(key));}for(const source of [openapi,featureMap,manifest,evidenceSchema])assert.match(source,/M08-06|capacity boundary|容量边界/i);assert.doesNotMatch(`${openapi}\n${featureMap}\n${manifest}`,/multi-node verified|10000 users supported|load balancing enabled/i);});

test("M08-06 capacity observation and drill writes are transactional",async()=>{const {CapacityBoundaryRepository}=await import("../../apps/api/dist/capacity-boundary-repository.js");const calls=[];const connection={beginTransaction:async()=>calls.push(["begin"]),query:async(sql,values)=>{calls.push([sql,values]);return[{}];},commit:async()=>calls.push(["commit"]),rollback:async()=>calls.push(["rollback"]),release:()=>calls.push(["release"])};const repository=new CapacityBoundaryRepository({getConnection:async()=>connection});await repository.recordView({actorId:"actor",requestId:"request",traceId:"trace",observedAt:new Date("2026-08-15T08:00:00.000Z"),snapshot:{measured_concurrency:10,read_p95_ms:120,write_p95_ms:260,error_rate_basis_points:0,async_lag_seconds:2,load_basis_points:3000,available_memory_mb:4096,free_disk_mb:8192,archive_verified:true,recovery_verified:true,observed_at:"2026-08-15T08:00:00.000Z"},evaluation:{state:"ready",findings:[]}});const writes=calls.filter(item=>typeof item[0]==="string"&&item[0].startsWith("INSERT"));assert.equal(writes.length,2);for(const [sql,values] of writes)assert.equal((sql.match(/\?/g)??[]).length,values.length);assert.deepEqual(calls.map(item=>item[0]),["begin",writes[0][0],writes[1][0],"commit","release"]);});

test("M08-06 archive recovery drill transaction has exact MySQL placeholders",async()=>{const {CapacityBoundaryRepository}=await import("../../apps/api/dist/capacity-boundary-repository.js");const calls=[];const connection={beginTransaction:async()=>calls.push(["begin"]),query:async(sql,values)=>{calls.push([sql,values]);if(sql.startsWith("SELECT result_json"))return[[]];if(sql.startsWith("SELECT id FROM capacity_boundary_observations"))return[[{id:"observation"}]];return[{}];},commit:async()=>calls.push(["commit"]),rollback:async()=>calls.push(["rollback"]),release:()=>calls.push(["release"])};const repository=new CapacityBoundaryRepository({getConnection:async()=>connection});await repository.attestDrill({actorId:"actor",requestId:"request",traceId:"trace",idempotencyKey:"drill-key",kind:"archive_recovery",reason:"季度演练",now:new Date("2026-08-15T08:00:00.000Z")});const writes=calls.filter(item=>typeof item[0]==="string"&&item[0].startsWith("INSERT"));assert.equal(writes.length,3);for(const[sql,values]of writes)assert.equal((sql.match(/\?/g)??[]).length,values.length);assert.equal(calls.at(-2)[0],"commit");assert.equal(calls.at(-1)[0],"release");});

test("M08-06.A07/A08/A15/A16 UI and rollback cover the complete image-grounded state contract",async()=>{const [ui,e2e,architecture,runbook,verifier]=await Promise.all(["apps/web/src/components/CapacityBoundaryCenter.vue","tests/e2e/m08-06-capacity-boundary.spec.ts","docs/architecture/m08-06-capacity-boundary.md","docs/runbooks/m08-06-capacity-boundary.md","scripts/verify-capacity-boundary-production.mjs"].map(path=>readFile(path,"utf8")));for(const state of ["loading","ready","warning","blocked","empty","forbidden","expired","rate_limited","unavailable","verifying"])assert.match(ui,new RegExp(state));assert.match(e2e,/390/);for(const image of ["61_平台运营-概览.jpg","63_采集任务监控.jpg","64_系统监控.jpg","65_日志中心.jpg","66_安全审计.jpg","69_异常告警.jpg","10_霓虹科技平台驾驶舱_dashboard.png"])assert.match(architecture,new RegExp(image.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(runbook,/## 回滚/);assert.match(verifier,/measuredConcurrentUsers|measuredConcurrency/);assert.doesNotMatch(`${ui}\n${e2e}\n${runbook}`,/多节点已验证|10000 用户已支持|负载均衡已启用|备用服务器已启用/i);});

test("M08-06 BaoTa capacity capture verifies runtime identity without requiring git metadata",async()=>{const source=await readFile("scripts/capture-capacity-boundary-production.mjs","utf8");assert.doesNotMatch(source,/git[\s\S]{0,80}rev-parse|execFileSync/);assert.match(source,/BUILD_SHA/);assert.match(source,/health\/version/);assert.match(source,/status='healthy'/);});
