window.OP_C_DATA = {
  version: "OPPORTUNITY-C-r1",
  provenance:
    "Historical UI2-OP and M04-02 fixtures; rule/pending variants, long names, page two and all UI outcomes are explicitly synthetic, not production facts. Recommended fixture is not evidence that the current evaluator supports skincare.",
  manual: {
    id: "00000000-0000-4000-8000-000000000424",
    name: "隔离机会候选",
    image_url: null,
    market: "US",
    category: null,
    source_type: "manual",
    source_ref_id: null,
    owner_id: "00000000-0000-4000-8000-000000000423",
    lifecycle_status: "ready",
    lifecycle_entered_at: "2026-08-08T00:00:00.000Z",
    lifecycle_dwell_seconds: 60,
    recommendation_status: "insufficient_data",
    overall_score: null,
    trend_score: null,
    competition_score: null,
    profit_status: "insufficient_data",
    risk_level: "unknown",
    confidence: {
      status: "insufficient_data",
      score: null,
    },
    evidence_count: 0,
    source_count: 0,
    competitor_count: 0,
    supplier_candidate_count: 0,
    matched_rule_count: 0,
    selection_stage: "not_eligible",
    quality_gates: {
      score: false,
      market: false,
      competition: false,
      cost: false,
      risk: false,
      all_passed: false,
    },
    coverage_status: "incomplete",
    blocking_reasons: ["evidence_insufficient", "recommendation_insufficient"],
    decision_status: "pending",
    version: 3,
    updated_at: "2026-08-08T00:00:00.000Z",
    operating_feedback: {
      facts: [],
      calibration: null,
    },
    lineage: {
      freshness: {
        observed_at: null,
        age_seconds: null,
      },
      failure_impact: {
        level: "none",
        codes: [],
        affected_stages: [],
      },
      request_ids: [],
      trace_ids: [],
      nodes: [],
    },
    adoption_blockers: [],
    redecision_ready: false,
    score_rule_version: null,
    scored_at: null,
    latest_score_run: null,
    score_components: [],
    evidence: [],
    decisions: [],
    section_status: {
      market: "insufficient_data",
      competition: "insufficient_data",
      profit: "insufficient_data",
      risk: "insufficient_data",
      execution: "not_available",
    },
  },
  rows: {
    recommended: [
      {
        id: "00000000-0000-4000-8000-000000000424",
        name: "AI 驱动的个性化护肤机会",
        market: "US",
        category: "beauty",
        source_type: "trend_topic",
        source_ref_id: "00000000-0000-4000-8000-000000000425",
        owner_id: "00000000-0000-4000-8000-000000000423",
        lifecycle_status: "ready",
        lifecycle_entered_at: "2026-08-07T20:00:00.000Z",
        lifecycle_dwell_seconds: 14400,
        recommendation_status: "recommend",
        overall_score: 86,
        trend_score: 88,
        competition_score: 82,
        profit_status: "calculated",
        risk_level: "low",
        confidence: {
          status: "insufficient_data",
          score: null,
        },
        evidence_count: 8,
        source_count: 3,
        coverage_status: "complete",
        blocking_reasons: [],
        decision_status: "pending",
        version: 1,
        updated_at: "2026-08-08T00:00:00.000Z",
        competitor_count: 5,
        supplier_candidate_count: 4,
        matched_rule_count: 1,
        selection_stage: "recommended",
        quality_gates: {
          score: true,
          market: true,
          competition: true,
          cost: true,
          risk: true,
          all_passed: true,
        },
        image_url: null,
      },
    ],
    rule_candidates: [
      {
        id: "00000000-0000-4000-8000-000000000427",
        name: "隔离规则命中候选",
        image_url: null,
        market: "US",
        category: null,
        source_type: "trend_topic",
        source_ref_id: "00000000-0000-4000-8000-000000000425",
        owner_id: "00000000-0000-4000-8000-000000000423",
        lifecycle_status: "ready",
        lifecycle_entered_at: "2026-08-08T00:00:00.000Z",
        lifecycle_dwell_seconds: 60,
        recommendation_status: "insufficient_data",
        overall_score: null,
        trend_score: null,
        competition_score: null,
        profit_status: "insufficient_data",
        risk_level: "unknown",
        confidence: {
          status: "insufficient_data",
          score: null,
        },
        evidence_count: 2,
        source_count: 2,
        competitor_count: 0,
        supplier_candidate_count: 0,
        matched_rule_count: 1,
        selection_stage: "rule_candidate",
        quality_gates: {
          score: false,
          market: false,
          competition: false,
          cost: false,
          risk: false,
          all_passed: false,
        },
        coverage_status: "partial",
        blocking_reasons: ["evidence_insufficient", "recommendation_insufficient"],
        decision_status: "pending",
        version: 3,
        updated_at: "2026-08-08T00:00:00.000Z",
        operating_feedback: {
          facts: [],
          calibration: null,
        },
        lineage: {
          freshness: {
            observed_at: null,
            age_seconds: null,
          },
          failure_impact: {
            level: "none",
            codes: [],
            affected_stages: [],
          },
          request_ids: [],
          trace_ids: [],
          nodes: [],
        },
        adoption_blockers: [],
        redecision_ready: false,
        score_rule_version: null,
        scored_at: null,
        latest_score_run: null,
        score_components: [],
        evidence: [],
        decisions: [],
        section_status: {
          market: "insufficient_data",
          competition: "insufficient_data",
          profit: "insufficient_data",
          risk: "insufficient_data",
          execution: "not_available",
        },
      },
    ],
    evidence_pending: [
      {
        id: "00000000-0000-4000-8000-000000000428",
        name: "隔离采集中候选",
        image_url: null,
        market: "US",
        category: null,
        source_type: "trend_topic",
        source_ref_id: "00000000-0000-4000-8000-000000000425",
        owner_id: "00000000-0000-4000-8000-000000000423",
        lifecycle_status: "ready",
        lifecycle_entered_at: "2026-08-08T00:00:00.000Z",
        lifecycle_dwell_seconds: 60,
        recommendation_status: "insufficient_data",
        overall_score: null,
        trend_score: null,
        competition_score: null,
        profit_status: "insufficient_data",
        risk_level: "unknown",
        confidence: {
          status: "insufficient_data",
          score: null,
        },
        evidence_count: 1,
        source_count: 1,
        competitor_count: 0,
        supplier_candidate_count: 0,
        matched_rule_count: 1,
        selection_stage: "not_eligible",
        quality_gates: {
          score: false,
          market: false,
          competition: false,
          cost: false,
          risk: false,
          all_passed: false,
        },
        coverage_status: "partial",
        blocking_reasons: ["evidence_insufficient", "recommendation_insufficient"],
        decision_status: "pending",
        version: 3,
        updated_at: "2026-08-08T00:00:00.000Z",
        operating_feedback: {
          facts: [],
          calibration: null,
        },
        lineage: {
          freshness: {
            observed_at: null,
            age_seconds: null,
          },
          failure_impact: {
            level: "none",
            codes: [],
            affected_stages: [],
          },
          request_ids: [],
          trace_ids: [],
          nodes: [],
        },
        adoption_blockers: [],
        redecision_ready: false,
        score_rule_version: null,
        scored_at: null,
        latest_score_run: null,
        score_components: [],
        evidence: [],
        decisions: [],
        section_status: {
          market: "insufficient_data",
          competition: "insufficient_data",
          profit: "insufficient_data",
          risk: "insufficient_data",
          execution: "not_available",
        },
      },
    ],
    all: [
      {
        id: "00000000-0000-4000-8000-000000000424",
        name: "隔离机会候选",
        image_url: null,
        market: "US",
        category: null,
        source_type: "manual",
        source_ref_id: null,
        owner_id: "00000000-0000-4000-8000-000000000423",
        lifecycle_status: "ready",
        lifecycle_entered_at: "2026-08-08T00:00:00.000Z",
        lifecycle_dwell_seconds: 60,
        recommendation_status: "insufficient_data",
        overall_score: null,
        trend_score: null,
        competition_score: null,
        profit_status: "insufficient_data",
        risk_level: "unknown",
        confidence: {
          status: "insufficient_data",
          score: null,
        },
        evidence_count: 0,
        source_count: 0,
        competitor_count: 0,
        supplier_candidate_count: 0,
        matched_rule_count: 0,
        selection_stage: "not_eligible",
        quality_gates: {
          score: false,
          market: false,
          competition: false,
          cost: false,
          risk: false,
          all_passed: false,
        },
        coverage_status: "incomplete",
        blocking_reasons: ["evidence_insufficient", "recommendation_insufficient"],
        decision_status: "pending",
        version: 3,
        updated_at: "2026-08-08T00:00:00.000Z",
        operating_feedback: {
          facts: [],
          calibration: null,
        },
        lineage: {
          freshness: {
            observed_at: null,
            age_seconds: null,
          },
          failure_impact: {
            level: "none",
            codes: [],
            affected_stages: [],
          },
          request_ids: [],
          trace_ids: [],
          nodes: [],
        },
        adoption_blockers: [],
        redecision_ready: false,
        score_rule_version: null,
        scored_at: null,
        latest_score_run: null,
        score_components: [],
        evidence: [],
        decisions: [],
        section_status: {
          market: "insufficient_data",
          competition: "insufficient_data",
          profit: "insufficient_data",
          risk: "insufficient_data",
          execution: "not_available",
        },
      },
      {
        id: "00000000-0000-4000-8000-000000000426",
        name: "第二个隔离候选",
        image_url: null,
        market: "US",
        category: null,
        source_type: "manual",
        source_ref_id: null,
        owner_id: "00000000-0000-4000-8000-000000000423",
        lifecycle_status: "ready",
        lifecycle_entered_at: "2026-08-08T00:00:00.000Z",
        lifecycle_dwell_seconds: 60,
        recommendation_status: "insufficient_data",
        overall_score: null,
        trend_score: null,
        competition_score: null,
        profit_status: "insufficient_data",
        risk_level: "unknown",
        confidence: {
          status: "insufficient_data",
          score: null,
        },
        evidence_count: 0,
        source_count: 0,
        competitor_count: 0,
        supplier_candidate_count: 0,
        matched_rule_count: 0,
        selection_stage: "not_eligible",
        quality_gates: {
          score: false,
          market: false,
          competition: false,
          cost: false,
          risk: false,
          all_passed: false,
        },
        coverage_status: "incomplete",
        blocking_reasons: ["evidence_insufficient", "recommendation_insufficient"],
        decision_status: "pending",
        version: 7,
        updated_at: "2026-08-08T00:00:00.000Z",
        operating_feedback: {
          facts: [],
          calibration: null,
        },
        lineage: {
          freshness: {
            observed_at: null,
            age_seconds: null,
          },
          failure_impact: {
            level: "none",
            codes: [],
            affected_stages: [],
          },
          request_ids: [],
          trace_ids: [],
          nodes: [],
        },
        adoption_blockers: [],
        redecision_ready: false,
        score_rule_version: null,
        scored_at: null,
        latest_score_run: null,
        score_components: [],
        evidence: [],
        decisions: [],
        section_status: {
          market: "insufficient_data",
          competition: "insufficient_data",
          profit: "insufficient_data",
          risk: "insufficient_data",
          execution: "not_available",
        },
      },
    ],
  },
  facts: {
    recommended: [
      [
        {
          label: "综合评分",
          value: "86",
        },
        {
          label: "证据",
          value: "8 条 · 3 源",
        },
        {
          label: "风险",
          value: "低",
        },
      ],
    ],
    rule_candidates: [
      [
        {
          label: "质量门",
          value: "0/5",
        },
        {
          label: "证据",
          value: "2 条 · 2 源",
        },
        {
          label: "下一项",
          value: "评分",
        },
      ],
    ],
    evidence_pending: [
      [
        {
          label: "独立来源",
          value: "1 个",
        },
        {
          label: "证据",
          value: "1 条",
        },
        {
          label: "命中规则",
          value: "1 条",
        },
      ],
    ],
    all: [
      [
        {
          label: "当前结论",
          value: "待判断",
        },
        {
          label: "综合评分",
          value: "—",
        },
        {
          label: "证据",
          value: "0 条 · 0 源",
        },
        {
          label: "风险",
          value: "待识别",
        },
      ],
      [
        {
          label: "当前结论",
          value: "待判断",
        },
        {
          label: "综合评分",
          value: "—",
        },
        {
          label: "证据",
          value: "0 条 · 0 源",
        },
        {
          label: "风险",
          value: "待识别",
        },
      ],
    ],
  },
  views: [
    {
      value: "recommended",
      label: "待我采纳",
    },
    {
      value: "rule_candidates",
      label: "规则命中候选",
    },
    {
      value: "evidence_pending",
      label: "采集中",
    },
    {
      value: "all",
      label: "全部机会",
    },
  ],
  form: {
    name: "",
    market: "US",
    category: "",
    source_topic_id: "",
  },
  filters: {
    q: "",
    market: "",
    decision_status: "",
    coverage_status: "",
    blocking_reason: "",
    lifecycle_status: "",
    owner_id: "",
  },
  edited: {
    name: "新候选草稿",
    market: "CA",
    category: "",
    source_topic_id: "00000000-0000-4000-8000-000000000425",
  },
  createIntent: {
    method: "POST",
    path: "/opportunities",
    body: {
      name: "新候选草稿",
      market: "CA",
      category: null,
      source_topic_id: "00000000-0000-4000-8000-000000000425",
    },
  },
  batchIntents: {
    assign: {
      method: "POST",
      path: "/opportunities/batch",
      body: {
        action: "assign",
        items: [
          {
            id: "00000000-0000-4000-8000-000000000424",
            expected_version: 3,
          },
          {
            id: "00000000-0000-4000-8000-000000000426",
            expected_version: 7,
          },
        ],
        reason: "已核对当前页范围",
        assignee_id: "00000000-0000-4000-8000-000000000423",
      },
    },
    review: {
      method: "POST",
      path: "/opportunities/batch",
      body: {
        action: "review",
        items: [
          {
            id: "00000000-0000-4000-8000-000000000424",
            expected_version: 3,
          },
          {
            id: "00000000-0000-4000-8000-000000000426",
            expected_version: 7,
          },
        ],
        reason: "已核对当前页范围",
        assignee_id: null,
      },
    },
    archive: {
      method: "POST",
      path: "/opportunities/batch",
      body: {
        action: "archive",
        items: [
          {
            id: "00000000-0000-4000-8000-000000000424",
            expected_version: 3,
          },
          {
            id: "00000000-0000-4000-8000-000000000426",
            expected_version: 7,
          },
        ],
        reason: "已核对当前页范围",
        assignee_id: null,
      },
    },
  },
  queries: {
    applyListFilters: {
      query: {
        q: "候选",
        view: "all",
      },
    },
    resetListFilters: {
      query: {
        view: "all",
      },
    },
    setSelectionView: {
      query: {
        q: "候选",
        view: "rule_candidates",
      },
    },
    goListPage: {
      query: {
        scope: "all",
        q: "候选",
      },
    },
  },
  erpFile: {
    items: [
      {
        spu: "UI2-LOCAL-ERP",
        product: {
          title: "隔离导入商品",
        },
        last_sync_time: "2026-08-08T00:00:00.000Z",
      },
    ],
    source_url: "https://medou.medouai.com/#/ProductList",
  },
  emptySetup: {
    available: true,
    readyCount: 0,
    allReady: false,
    steps: [
      {
        code: "score",
        label: "评分规则",
        description: "创建、审批并启用评分权重与推荐阈值。",
        ready: false,
        route: "/opportunities/scoring-rules",
      },
      {
        code: "market",
        label: "市场质量门",
        description: "在评分规则中启用市场证据维度。",
        ready: false,
        route: "/opportunities/scoring-rules",
      },
      {
        code: "competition",
        label: "竞争质量门",
        description: "启用竞争证据维度，并创建竞品监控规则。",
        ready: false,
        route: "/competitors/monitoring-rules",
      },
      {
        code: "cost",
        label: "成本质量门",
        description: "启用成本维度，并发布含物流与换算依据的费用规则。",
        ready: false,
        route: "/sourcing/cost-rules",
      },
      {
        code: "risk",
        label: "风险质量门",
        description: "在评分规则中启用风险维度。",
        ready: false,
        route: "/opportunities/scoring-rules",
      },
    ],
  },
  members: [
    {
      id: "00000000-0000-4000-8000-000000000423",
      label: "隔离复核成员",
    },
  ],
  knownGaps: {
    batchScope: {
      selectedCount: 2,
      submittedCount: 1,
      submittedId: "00000000-0000-4000-8000-000000000426",
      sourceFixed: false,
    },
    filterCount:
      "Actual activeFilterCount uses mutable draft fields rather than URL; proposal labels drafts separately.",
    imageFailure:
      "Actual list has no image error handler; proposal shows unavailable state without inventing product art.",
  },
};
