import { createHash } from 'node:crypto';

export const QUALITY_METRIC_CODES=['title_accuracy','price_accuracy','currency_accuracy','external_id_accuracy','canonical_url_accuracy','duplicate_ratio','supplier_mismatch_ratio','ai_classification_approval','source_freshness','source_success_rate'] as const;
export type QualityMetricCode=typeof QUALITY_METRIC_CODES[number];
export type QualityStatus='passed'|'failed'|'insufficient_sample';
export const QUALITY_THRESHOLDS:Record<QualityMetricCode,{direction:'minimum'|'maximum';threshold:number;minimumSample:number}>={title_accuracy:{direction:'minimum',threshold:.98,minimumSample:1},price_accuracy:{direction:'minimum',threshold:.99,minimumSample:1},currency_accuracy:{direction:'minimum',threshold:.99,minimumSample:1},external_id_accuracy:{direction:'minimum',threshold:.995,minimumSample:1},canonical_url_accuracy:{direction:'minimum',threshold:.99,minimumSample:1},duplicate_ratio:{direction:'maximum',threshold:.02,minimumSample:1},supplier_mismatch_ratio:{direction:'maximum',threshold:.01,minimumSample:1},ai_classification_approval:{direction:'minimum',threshold:.90,minimumSample:30},source_freshness:{direction:'minimum',threshold:.95,minimumSample:20},source_success_rate:{direction:'minimum',threshold:.95,minimumSample:20}};
export class DataQualityError extends Error{constructor(readonly code:string){super(code);this.name='DataQualityError';}}
export interface EvidenceFieldProvenance{fieldPath:string;sourcePath:string;transformVersion:string;sourceValueHash:string;}
export interface EvidencePersistInput{organizationId:string;workspaceId:string;taskId:string;subqueryId:string;providerId:string;sourceUrl:string;canonicalUrl:string;dedupeKey:string;contentType:string;content:Uint8Array;capturedAt:Date;parserVersion:string;adapterVersion:string;recordKey:string;recordSchemaVersion:string;normalizedPayload:Record<string,unknown>;provenance:EvidenceFieldProvenance[];requestId:string;traceId:string;actorId:string;}
const safe=/^[A-Za-z0-9._:-]{1,200}$/;
const sourcePath=/^[A-Za-z0-9_$.[\]:'"-]{1,200}$/;
export function normalizeCanonicalUrl(value:string){let url:URL;try{url=new URL(value);}catch{throw new DataQualityError('canonical_url_invalid');}if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.hash)throw new DataQualityError('canonical_url_invalid');url.hostname=url.hostname.toLowerCase();return url.toString();}
export function sha256(value:Uint8Array|string){return createHash('sha256').update(value).digest('hex');}
export function validateEvidenceInput(input:EvidencePersistInput,maxBytes:number){if(!safe.test(input.organizationId)||!safe.test(input.workspaceId)||!safe.test(input.taskId)||!safe.test(input.subqueryId)||!safe.test(input.providerId)||!safe.test(input.dedupeKey)||!safe.test(input.recordKey)||!safe.test(input.parserVersion)||!safe.test(input.adapterVersion)||!safe.test(input.recordSchemaVersion)||!safe.test(input.requestId)||!safe.test(input.traceId)||!safe.test(input.actorId))throw new DataQualityError('evidence_identifier_invalid');if(!Number.isSafeInteger(maxBytes)||maxBytes<1024||input.content.byteLength<1||input.content.byteLength>maxBytes)throw new DataQualityError('evidence_content_size_invalid');if(!/^[a-z0-9][a-z0-9.+-]{0,79}\/[-a-z0-9.+]{1,100}$/i.test(input.contentType))throw new DataQualityError('evidence_content_type_invalid');const source=normalizeCanonicalUrl(input.sourceUrl),canonical=normalizeCanonicalUrl(input.canonicalUrl);if(!Number.isFinite(input.capturedAt.getTime())||input.capturedAt>new Date(Date.now()+300000))throw new DataQualityError('evidence_captured_at_invalid');if(!input.provenance.length||input.provenance.some(item=>!safe.test(item.fieldPath)||!sourcePath.test(item.sourcePath)||!safe.test(item.transformVersion)||!/^[a-f0-9]{64}$/.test(item.sourceValueHash)))throw new DataQualityError('field_provenance_invalid');return{...input,sourceUrl:source,canonicalUrl:canonical,contentHash:sha256(input.content)};}
export function evaluateQualityMetric(code:QualityMetricCode,numerator:number,denominator:number){const policy=QUALITY_THRESHOLDS[code];if(!policy||!Number.isSafeInteger(numerator)||!Number.isSafeInteger(denominator)||numerator<0||denominator<1||numerator>denominator)throw new DataQualityError('quality_metric_input_invalid');const value=numerator/denominator,status:QualityStatus=denominator<policy.minimumSample?'insufficient_sample':policy.direction==='minimum'?value>=policy.threshold?'passed':'failed':value<=policy.threshold?'passed':'failed';return{code,numerator,denominator,value,threshold:policy.threshold,direction:policy.direction,minimumSample:policy.minimumSample,status};}
