export type CrawlerSchedulerState="ready"|"warning"|"blocked";
export interface CrawlerSchedulerPolicy{maximumWorkers:1;maximumCrawlers:1;maximumProviderConcurrency:1;maximumLoadBasisPoints:number;minimumAvailableMemoryMb:number;minimumFreeDiskMb:number;staleAfterSeconds:number}
export interface CrawlerSchedulerProvider{id:string;code:string;configured_concurrency:number;effective_concurrency:number;active_leases:number}
export interface CrawlerSchedulerProfile{id:string;active_leases:number}
export interface CrawlerSchedulerSnapshot{worker_instances:number;crawler_instances:number;active_worker_leases:number;active_crawler_leases:number;duplicate_lease_count:number;providers:CrawlerSchedulerProvider[];profiles:CrawlerSchedulerProfile[];resource:{load_basis_points:number;available_memory_mb:number;free_disk_mb:number;observed_at:string}}
export interface CrawlerSchedulerFinding{code:string;severity:"warning"|"blocked";action_hint:string}
export interface CrawlerSchedulerEvaluation{state:CrawlerSchedulerState;findings:CrawlerSchedulerFinding[]}
export interface CrawlerSchedulerRepository{snapshot(now:Date):Promise<Omit<CrawlerSchedulerSnapshot,"worker_instances"|"crawler_instances"|"resource">>;record(input:{actorId:string;requestId:string;traceId:string;observedAt:Date;snapshot:CrawlerSchedulerSnapshot;evaluation:CrawlerSchedulerEvaluation}):Promise<void>;recoverExpired(input:{actorId:string;requestId:string;traceId:string;idempotencyKey:string;now:Date}):Promise<{recovered:number}>}
export interface CrawlerSchedulerHostProbe{snapshot():Promise<Pick<CrawlerSchedulerSnapshot,"worker_instances"|"crawler_instances"|"resource">>}
export class CrawlerSchedulerError extends Error{constructor(readonly code:string,readonly statusCode:number,readonly actionHint:string){super(code);this.name="CrawlerSchedulerError";}}

export function evaluateCrawlerScheduler(snapshot:CrawlerSchedulerSnapshot,policy:CrawlerSchedulerPolicy,now=new Date()):CrawlerSchedulerEvaluation{const findings:CrawlerSchedulerFinding[]=[];const blocked=(code:string,action_hint:string)=>findings.push({code,severity:"blocked",action_hint}),warning=(code:string,action_hint:string)=>findings.push({code,severity:"warning",action_hint});if(snapshot.worker_instances!==policy.maximumWorkers)blocked("crawler_worker_count_exceeded","通过宝塔只保留一个 Node Worker 实例并重新核验。");if(snapshot.crawler_instances!==policy.maximumCrawlers)blocked("crawler_process_count_exceeded","通过宝塔只保留一个 Python Crawler 实例并重新核验。");if(snapshot.active_worker_leases>policy.maximumWorkers||snapshot.active_crawler_leases>policy.maximumCrawlers)blocked("crawler_global_concurrency_exceeded","停止新增任务并等待当前单机租约释放。");if(snapshot.duplicate_lease_count>0||snapshot.profiles.some(item=>item.active_leases>1))blocked("crawler_lease_duplicate","通过宝塔有限任务回收过期租约并检查独占约束。");if(snapshot.providers.some(item=>item.effective_concurrency>policy.maximumProviderConcurrency||item.active_leases>item.effective_concurrency))blocked("crawler_provider_quota_exceeded","降低来源并发或等待该来源的活动租约释放。");const age=(now.getTime()-Date.parse(snapshot.resource.observed_at))/1000;if(!Number.isFinite(age)||age<0||age>policy.staleAfterSeconds)blocked("crawler_resource_observation_stale","刷新当前惠州单机资源观测后再调度。");if(snapshot.resource.load_basis_points>=policy.maximumLoadBasisPoints||snapshot.resource.available_memory_mb<policy.minimumAvailableMemoryMb||snapshot.resource.free_disk_mb<policy.minimumFreeDiskMb)blocked("crawler_resource_stop","资源水位触及停止线，保持任务排队并通过宝塔排查。");else if(snapshot.resource.load_basis_points>=Math.round(policy.maximumLoadBasisPoints*.9)||snapshot.resource.available_memory_mb<Math.ceil(policy.minimumAvailableMemoryMb*1.25)||snapshot.resource.free_disk_mb<Math.ceil(policy.minimumFreeDiskMb*1.25))warning("crawler_resource_warning","资源接近停止线，暂缓扩大任务量并持续观察。");return{state:findings.some(item=>item.severity==="blocked")?"blocked":findings.length?"warning":"ready",findings};}

export class CrawlerSchedulerService{constructor(private readonly repository:CrawlerSchedulerRepository,private readonly hostProbe:CrawlerSchedulerHostProbe,private readonly policy:CrawlerSchedulerPolicy,private readonly now=()=>new Date()){}async read(input:{actorId:string;requestId:string;traceId:string}){const repositoryObservedAt=this.now(),snapshot={...await this.repository.snapshot(repositoryObservedAt),...await this.hostProbe.snapshot()},observedAt=this.now(),evaluation=evaluateCrawlerScheduler(snapshot,this.policy,observedAt);await this.repository.record({...input,observedAt,snapshot,evaluation});return{state:evaluation.state,topology:{mode:"single_host",worker_instances:snapshot.worker_instances,crawler_instances:snapshot.crawler_instances,maximum_workers:1,maximum_crawlers:1},leases:{active_worker:snapshot.active_worker_leases,active_crawler:snapshot.active_crawler_leases,duplicate_count:snapshot.duplicate_lease_count},providers:snapshot.providers,profiles:snapshot.profiles,resource:snapshot.resource,findings:evaluation.findings,observed_at:observedAt.toISOString(),capacity_claim:"unverified"};}async recoverExpired(input:{actorId:string;requestId:string;traceId:string;idempotencyKey:string}){if(!/^[A-Za-z0-9._:-]{1,128}$/.test(input.idempotencyKey))throw new CrawlerSchedulerError("crawler_scheduler_idempotency_invalid",400,"使用有效 Idempotency-Key 重试。");return{...await this.repository.recoverExpired({...input,now:this.now()}),observed_at:this.now().toISOString()};}}
