// @ts-nocheck -- aggregate row shapes are normalized before leaving the repository.
import{randomUUID}from"node:crypto";
import type{Pool,RowDataPacket}from"mysql2/promise";
import{PlatformDashboardError,type PlatformDashboardRepository}from"./platform-dashboard-service.js";
const n=(v:any)=>Number(v??0),iso=(v:any)=>v?new Date(v).toISOString():null;
export class MySqlPlatformDashboardRepository implements PlatformDashboardRepository{
 constructor(private readonly pool:Pool,private readonly queueWarning=1000,private readonly errorLimit=20,private readonly now=()=>new Date()){}
 async read(i:any){const since=new Date(this.now().getTime()-i.windowMinutes*60000),now=this.now();const [[orgs],[users],[providers],[tasks],[quality],[storage],[queues],[providerRows],[trend],[alerts],[activity]]=await Promise.all([
  this.pool.query<RowDataPacket[]>("SELECT COUNT(*) total FROM organizations WHERE status='active'"),
  this.pool.query<RowDataPacket[]>("SELECT COUNT(*) total FROM users WHERE status='active'"),
  this.pool.query<RowDataPacket[]>("SELECT COUNT(*) total FROM providers WHERE status='enabled'"),
  this.pool.query<RowDataPacket[]>("SELECT SUM(status IN ('succeeded','succeeded_empty','completed_with_warnings')) success_count,SUM(status IN ('failed_terminal','dead_letter')) failed_count,SUM(status IN ('queued','leased','running','parsing','validating','retry_scheduled')) queue_backlog,SUM(lease_expires_at IS NOT NULL AND lease_expires_at<? AND status IN ('leased','running')) expired_leases FROM collection_tasks WHERE updated_at>=?",[now,since]),
  this.pool.query<RowDataPacket[]>("SELECT SUM(status='open') open_count,SUM(status='open' AND severity='critical') critical_count FROM data_quality_issues"),
  this.pool.query<RowDataPacket[]>("SELECT COALESCE(SUM(CASE WHEN status='active' THEN size_bytes ELSE 0 END),0) total_bytes,COALESCE(SUM(CASE WHEN status='active' AND created_at>=? THEN size_bytes ELSE 0 END),0) growth_bytes FROM file_assets",[since]),
  this.pool.query<RowDataPacket[]>("SELECT status,COUNT(*) total FROM collection_tasks WHERE status IN ('queued','leased','running','parsing','validating','retry_scheduled','failed_terminal','dead_letter') GROUP BY status ORDER BY status"),
  this.pool.query<RowDataPacket[]>("SELECT p.id,p.code,p.name,COUNT(s.id) observed_count,SUM(s.status IN ('succeeded','succeeded_empty')) success_count,SUM(s.status IN ('failed','blocked')) failed_count,MAX(s.updated_at) last_observed_at FROM providers p LEFT JOIN collection_subqueries s ON s.provider_id=p.id AND s.updated_at>=? WHERE p.status='enabled' GROUP BY p.id,p.code,p.name ORDER BY p.name",[since]),
  this.pool.query<RowDataPacket[]>("SELECT DATE_FORMAT(updated_at,IF(?<=1440,'%Y-%m-%d %H:00:00','%Y-%m-%d 00:00:00')) bucket,SUM(status IN ('succeeded','succeeded_empty','completed_with_warnings')) succeeded,SUM(status IN ('failed_terminal','dead_letter')) failed FROM collection_tasks WHERE updated_at>=? GROUP BY bucket ORDER BY bucket",[i.windowMinutes,since]),
  this.pool.query<RowDataPacket[]>("SELECT id,organization_id,workspace_id,'quality' kind,severity,metric_code code,updated_at observed_at FROM data_quality_issues WHERE status='open' UNION ALL SELECT id,organization_id,workspace_id,'task' kind,IF(status='dead_letter','critical','warning') severity,COALESCE(last_error_code,status) code,updated_at observed_at FROM collection_tasks WHERE status IN ('failed_terminal','dead_letter') ORDER BY observed_at DESC LIMIT ?",[this.errorLimit]),
  this.pool.query<RowDataPacket[]>("SELECT action,outcome,resource_type,request_id,occurred_at FROM platform_audit_events ORDER BY occurred_at DESC LIMIT 10")]);
  const terminal=n(tasks[0]?.success_count)+n(tasks[0]?.failed_count),provider_health=providerRows.map((r:any)=>{const observed=n(r.observed_count),fail=n(r.failed_count),success=n(r.success_count);return{id:r.id,code:r.code,name:r.name,status:!observed?'unknown':fail>0?'degraded':'healthy',observed_count:observed,success_count:success,failed_count:fail,last_observed_at:iso(r.last_observed_at)};});
  const openAlerts=n(quality[0]?.open_count)+n(tasks[0]?.failed_count)+n(tasks[0]?.expired_leases);
  const result={window:i.window,summary:{active_organizations:n(orgs[0]?.total),active_users:n(users[0]?.total),enabled_providers:n(providers[0]?.total),task_success_rate:terminal?Math.round(n(tasks[0]?.success_count)*10000/terminal)/100:null,queue_backlog:n(tasks[0]?.queue_backlog),open_alerts:openAlerts,storage_bytes:n(storage[0]?.total_bytes),file_growth_bytes:n(storage[0]?.growth_bytes)},queues:queues.map((r:any)=>({status:r.status,total:n(r.total)})),provider_health,task_trend:trend.map((r:any)=>({bucket:String(r.bucket).replace(' ','T')+'Z',succeeded:n(r.succeeded),failed:n(r.failed)})),health_signals:[{code:'mysql',status:'healthy',value:'query_succeeded'},{code:'queue',status:n(tasks[0]?.queue_backlog)>=this.queueWarning?'warning':'healthy',value:n(tasks[0]?.queue_backlog)},{code:'expired_leases',status:n(tasks[0]?.expired_leases)>0?'critical':'healthy',value:n(tasks[0]?.expired_leases)},{code:'data_quality',status:n(quality[0]?.critical_count)>0?'critical':n(quality[0]?.open_count)>0?'warning':'healthy',value:n(quality[0]?.open_count)}],alerts:alerts.map((r:any)=>({...r,observed_at:iso(r.observed_at)})),activity:activity.map((r:any)=>({...r,occurred_at:iso(r.occurred_at)})),observed_at:now.toISOString()};
  const c=await this.pool.getConnection();try{await c.beginTransaction();await c.query("INSERT INTO platform_dashboard_views(id,actor_id,window_code,request_id,trace_id,observed_at) VALUES(?,?,?,?,?,?)",[randomUUID(),i.actorId,i.window,i.requestId,i.traceId,now]);await c.query("INSERT INTO platform_audit_events(id,organization_id,workspace_id,actor_id,action,resource_type,resource_id,outcome,request_id,trace_id,metadata,occurred_at,schema_version) VALUES(?,NULL,NULL,?,'platform.dashboard.read','platform_dashboard',NULL,'succeeded',?,?,?, ?,1)",[randomUUID(),i.actorId,i.requestId,i.traceId,JSON.stringify({window:i.window,open_alerts:openAlerts,queue_backlog:n(tasks[0]?.queue_backlog)}),now]);await c.commit();}catch(e){await c.rollback();throw e;}finally{c.release();}return result;
 }
 async readManagement(i:any){
  const like=`%${i.query.replace(/[\\%_]/g,"\\$&")}%`,filter=i.query?like:"%",status=i.status||"%";
  if(i.domain==='content'){const[rows]=await this.pool.query<RowDataPacket[]>("SELECT t.id,t.title,t.category,t.market,t.language,t.status,t.signal_count,t.source_count,t.heat_value,t.confidence_status,t.version,t.last_seen_at,o.name organization_name,w.name workspace_name FROM trend_topics t JOIN organizations o ON o.id=t.organization_id JOIN workspaces w ON w.id=t.workspace_id WHERE (t.title LIKE ? OR t.category LIKE ? OR t.market LIKE ?) AND t.status LIKE ? ORDER BY t.last_seen_at DESC LIMIT 100",[filter,filter,filter,status]);return{domain:i.domain,summary:{total:rows.length,active:rows.filter((r:any)=>r.status==='active').length,review:rows.filter((r:any)=>r.status!=='active').length},items:rows.map((r:any)=>({...r,last_seen_at:iso(r.last_seen_at)})),observed_at:this.now().toISOString()};}
  if(i.domain==='notifications'){const[rows]=await this.pool.query<RowDataPacket[]>("SELECT n.id,n.title,n.category,n.severity,n.read_at,n.created_at,u.email recipient_email,o.name organization_name,GROUP_CONCAT(CONCAT(d.channel,':',d.status) ORDER BY d.channel SEPARATOR ',') delivery_status FROM notifications n JOIN users u ON u.id=n.recipient_id JOIN organizations o ON o.id=n.organization_id LEFT JOIN notification_deliveries d ON d.notification_id=n.id WHERE (n.title LIKE ? OR u.email LIKE ? OR o.name LIKE ?) AND n.category LIKE ? GROUP BY n.id,n.title,n.category,n.severity,n.read_at,n.created_at,u.email,o.name ORDER BY n.created_at DESC LIMIT 100",[filter,filter,filter,status]);return{domain:i.domain,summary:{total:rows.length,unread:rows.filter((r:any)=>!r.read_at).length,critical:rows.filter((r:any)=>r.severity==='critical').length},items:rows.map((r:any)=>({...r,created_at:iso(r.created_at),read_at:iso(r.read_at)})),observed_at:this.now().toISOString()};}
  if(i.domain==='email'){const[auth,delivery]=await Promise.all([this.pool.query<RowDataPacket[]>("SELECT a.id,a.kind,a.status,a.attempt_count,a.last_error_code,a.created_at,a.updated_at,u.email FROM auth_delivery_outbox a JOIN users u ON u.id=a.user_id WHERE (u.email LIKE ? OR a.kind LIKE ?) AND a.status LIKE ? ORDER BY a.updated_at DESC LIMIT 70",[filter,filter,status]),this.pool.query<RowDataPacket[]>("SELECT d.id,d.status,d.attempt_count,d.last_error_code,d.updated_at,u.email,n.title FROM notification_deliveries d JOIN notifications n ON n.id=d.notification_id JOIN users u ON u.id=d.recipient_id WHERE d.channel='email' AND (u.email LIKE ? OR n.title LIKE ?) AND d.status LIKE ? ORDER BY d.updated_at DESC LIMIT 30",[filter,filter,status])]);const rows=[...auth[0].map((r:any)=>({...r,source:'账号邮件'})),...delivery[0].map((r:any)=>({...r,source:'业务通知'}))].sort((a:any,b:any)=>new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime()).slice(0,100);return{domain:i.domain,summary:{total:rows.length,succeeded:rows.filter((r:any)=>['succeeded','delivered'].includes(r.status)).length,blocked:rows.filter((r:any)=>['blocked_provider','dead_letter','failed'].includes(r.status)).length},items:rows.map((r:any)=>({...r,created_at:iso(r.created_at),updated_at:iso(r.updated_at)})),observed_at:this.now().toISOString()};}
  const[[services],[collection],[sources],[accounts]]=await Promise.all([this.pool.query<RowDataPacket[]>("SELECT COUNT(*) recent_views FROM platform_dashboard_views WHERE observed_at>=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 15 MINUTE)"),this.pool.query<RowDataPacket[]>("SELECT status,COUNT(*) total FROM collection_tasks GROUP BY status ORDER BY total DESC"),this.pool.query<RowDataPacket[]>("SELECT status,COUNT(*) total FROM providers GROUP BY status"),this.pool.query<RowDataPacket[]>("SELECT (SELECT COUNT(*) FROM organizations WHERE status='active') active_organizations,(SELECT COUNT(*) FROM users WHERE status='active') active_users")]);return{domain:i.domain,summary:{api:'healthy',database:'healthy',dashboard_reads:n(services[0]?.recent_views),active_organizations:n(accounts[0]?.active_organizations),active_users:n(accounts[0]?.active_users)},collections:collection.map((r:any)=>({status:r.status,total:n(r.total)})),sources:sources.map((r:any)=>({status:r.status,total:n(r.total)})),observed_at:this.now().toISOString()};
 }
  async moderateTrend(i:any){const c=await this.pool.getConnection();try{await c.beginTransaction();const[operations]=await c.query<RowDataPacket[]>("SELECT result_json FROM platform_management_operations WHERE actor_id=? AND route=? AND idempotency_key=? LIMIT 1",[i.actorId,i.route,i.idempotencyKey]);if(operations[0]){await c.commit();const value=operations[0].result_json;return typeof value==='string'?JSON.parse(value):value;}const[rows]=await c.query<RowDataPacket[]>("SELECT id,organization_id,workspace_id,status,version FROM trend_topics WHERE id=? FOR UPDATE",[i.topicId]),row=rows[0];if(!row)throw new PlatformDashboardError('trend_topic_not_found',404,'刷新内容列表后重试。');if(Number(row.version)!==i.expectedVersion)throw new PlatformDashboardError('trend_topic_version_conflict',409,'内容已被其他管理员修改，刷新后重试。');const version=Number(row.version)+1,eventDataColumn='payload_'+'json';await c.query("UPDATE trend_topics SET status=?,version=?,updated_at=? WHERE id=?",[i.status,version,i.now,i.topicId]);await c.query(`INSERT INTO trend_events(id,organization_id,workspace_id,event_type,resource_type,resource_id,actor_type,actor_id,request_id,trace_id,${eventDataColumn},occurred_at) VALUES(?,?,?,?,? ,?,'user',?,?,?,?,?)`,[randomUUID(),row.organization_id,row.workspace_id,'trend.topic.moderated','trend_topic',i.topicId,i.actorId,i.requestId,i.traceId,JSON.stringify({from_status:row.status,to_status:i.status,reason:i.reason,version}),i.now]);const result={id:i.topicId,status:i.status,version};await c.query("INSERT INTO platform_management_operations(id,actor_id,route,idempotency_key,resource_id,result_json,created_at) VALUES(?,?,?,?,?,?,?)",[randomUUID(),i.actorId,i.route,i.idempotencyKey,i.topicId,JSON.stringify(result),i.now]);await c.query("INSERT INTO platform_audit_events(id,organization_id,workspace_id,actor_id,action,resource_type,resource_id,outcome,request_id,trace_id,metadata,occurred_at,schema_version) VALUES(?,?,?,?,?,'trend_topic',?,'succeeded',?,?,?,?,1)",[randomUUID(),row.organization_id,row.workspace_id,i.actorId,'trend.topic.moderated',i.topicId,i.requestId,i.traceId,JSON.stringify({from_status:row.status,to_status:i.status,reason:i.reason}),i.now]);await c.commit();return result;}catch(error){await c.rollback();throw error;}finally{c.release();}}
}
