import type { Pool, RowDataPacket } from 'mysql2/promise';
import type { AuthorizationDecisionEvent, AuthorizationRepository, AuthorizationSubject, Capability, DataScopeType, RoleCategory, RoleDefinition } from '@scoutops/authorization';

export class MySqlAuthorizationRepository implements AuthorizationRepository{
 constructor(private readonly pool:Pool){}
 async loadSubject(actorId:string,organizationId?:string):Promise<AuthorizationSubject>{
  const[platformRows]=await this.pool.query<RowDataPacket[]>("SELECT DISTINCT pra.role_code,rc.capability_code FROM platform_role_assignments pra JOIN roles r ON r.code=pra.role_code AND r.category='platform' AND r.status='active' LEFT JOIN role_capabilities rc ON rc.role_code=r.code WHERE pra.user_id=?",[actorId]);
  let membershipId:string|null=null,membershipActive=false;let roleRows:RowDataPacket[]=[];let scopeRows:RowDataPacket[]=[];
  if(organizationId){const[memberships]=await this.pool.query<RowDataPacket[]>("SELECT id,status FROM memberships WHERE user_id=? AND organization_id=? LIMIT 1",[actorId,organizationId]);const membership=memberships[0];membershipId=membership?.id??null;membershipActive=membership?.status==='active';if(membershipActive){[roleRows]=await this.pool.query<RowDataPacket[]>("SELECT DISTINCT mra.role_code,rc.capability_code FROM membership_role_assignments mra JOIN roles r ON r.code=mra.role_code AND r.category='organization' AND r.status='active' LEFT JOIN role_capabilities rc ON rc.role_code=r.code WHERE mra.membership_id=?",[membershipId]);[scopeRows]=await this.pool.query<RowDataPacket[]>('SELECT scope_type,workspace_id,team_id FROM membership_data_scopes WHERE membership_id=?',[membershipId]);}}
  const values=(rows:RowDataPacket[],field:string)=>[...new Set(rows.map(row=>row[field]).filter(Boolean))] as string[];
  const platformRoles=values(platformRows,'role_code');return{actor_id:actorId,membership_id:membershipId,membership_active:membershipActive,role_codes:values(roleRows,'role_code'),capabilities:values(roleRows,'capability_code') as Capability[],scopes:[...scopeRows.map(row=>({scope:row.scope_type as DataScopeType,workspace_id:row.workspace_id,team_id:row.team_id})),...(platformRoles.length?[{scope:'platform' as const}]:[])],platform_role_codes:platformRoles,platform_capabilities:values(platformRows,'capability_code') as Capability[]};
 }
 async appendDecision(event:AuthorizationDecisionEvent){await this.pool.query('INSERT INTO authorization_decisions (id,actor_id,organization_id,workspace_id,team_id,capability,surface,outcome,reason,request_id,trace_id,occurred_at,schema_version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[event.id,event.actor_id,event.organization_id,event.workspace_id,event.team_id,event.capability,event.surface,event.outcome,event.reason,event.request_id,event.trace_id,event.occurred_at,event.schema_version]);}
 async listRoles(category?:RoleCategory){const params=category?[category]:[];const where=category?'WHERE r.category=? AND r.status=\'active\'':'WHERE r.status=\'active\'';const[rows]=await this.pool.query<RowDataPacket[]>(`SELECT r.code,r.name,r.category,r.description,rc.capability_code FROM roles r LEFT JOIN role_capabilities rc ON rc.role_code=r.code ${where} ORDER BY r.category,r.code,rc.capability_code`,params);const roles=new Map<string,RoleDefinition>();for(const row of rows){if(!roles.has(row.code))roles.set(row.code,{code:row.code,name:row.name,category:row.category,description:row.description,capabilities:[]});if(row.capability_code)roles.get(row.code)!.capabilities.push(row.capability_code);}return[...roles.values()];}
 async findSessionContext(sessionId:string,userId:string){const[rows]=await this.pool.query<RowDataPacket[]>('SELECT organization_id,workspace_id FROM user_session_contexts WHERE session_id=? AND user_id=? LIMIT 1',[sessionId,userId]);return rows[0]?{organization_id:rows[0].organization_id,workspace_id:rows[0].workspace_id}:null;}
}
