import {randomUUID} from 'node:crypto';
import type {Pool,PoolConnection,RowDataPacket} from 'mysql2/promise';
import type {EligibleGrantMember,MembershipTarget,OperationReplay,ResourceGrant,ResourceGrantAction,ResourceGrantAuditEvent,ResourceGrantOperation,ResourceGrantRepository,ResourceGrantStatus,ResourceGrantType,WorkspaceTarget} from '@scoutops/resource-grants';

const toGrant=(rows:RowDataPacket[]):ResourceGrant=>{const row=rows[0]!;return{id:row.id,organization_id:row.organization_id,workspace_id:row.workspace_id,resource_type:row.resource_type as ResourceGrantType,resource_id:row.resource_id,grantee_membership_id:row.grantee_membership_id,grantor_id:row.grantor_id,reason:row.reason,status:row.status,expires_at:new Date(row.expires_at),revoked_at:row.revoked_at?new Date(row.revoked_at):null,revoked_by:row.revoked_by,revocation_reason:row.revocation_reason,version:Number(row.version),created_at:new Date(row.created_at),updated_at:new Date(row.updated_at),actions:[...new Set(rows.map(item=>item.capability_code).filter(Boolean))] as ResourceGrantAction[],effective_status:row.status==='revoked'?'revoked':new Date(row.expires_at)<=new Date()?'expired':'active'};};
const select=`SELECT rg.*,rga.capability_code FROM resource_grants rg LEFT JOIN resource_grant_actions rga ON rga.grant_id=rg.id`;
export class MySqlResourceGrantRepository implements ResourceGrantRepository{
 constructor(private readonly pool:Pool){}
 async getMembership(id:string){const[rows]=await this.pool.query<RowDataPacket[]>('SELECT id,organization_id,status FROM memberships WHERE id=? LIMIT 1',[id]);return rows[0] as MembershipTarget??null;}
 async getWorkspace(id:string){const[rows]=await this.pool.query<RowDataPacket[]>('SELECT id,organization_id,status FROM workspaces WHERE id=? LIMIT 1',[id]);return rows[0] as WorkspaceTarget??null;}
 async getGrant(id:string){const[rows]=await this.pool.query<RowDataPacket[]>(`${select} WHERE rg.id=? ORDER BY rga.capability_code`,[id]);return rows.length?toGrant(rows):null;}
 async listEligibleMembers(organizationId:string){const[rows]=await this.pool.query<RowDataPacket[]>("SELECT m.id,m.user_id,u.email,m.status FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=? AND m.status='active' AND u.status='active' ORDER BY u.email",[organizationId]);return rows as EligibleGrantMember[];}
 async findOperation(actorId:string,operation:string,keyHash:string):Promise<OperationReplay|null>{const[rows]=await this.pool.query<RowDataPacket[]>('SELECT request_hash,grant_id FROM resource_grant_operations WHERE actor_id=? AND operation=? AND idempotency_key_hash=? LIMIT 1',[actorId,operation,keyHash]);if(!rows[0])return null;const grant=await this.getGrant(rows[0].grant_id);return grant?{request_hash:rows[0].request_hash,grant}:null;}
 async saveOperation(actorId:string,organizationId:string,operation:string,keyHash:string,requestHash:string,grant:ResourceGrant,at:Date){await this.pool.query('INSERT INTO resource_grant_operations (id,organization_id,actor_id,operation,idempotency_key_hash,request_hash,grant_id,grant_version,created_at) VALUES (?,?,?,?,?,?,?,?,?)',[randomUUID(),organizationId,actorId,operation,keyHash,requestHash,grant.id,grant.version,at]);}
 async insertGrant(grant:ResourceGrant){const connection=await this.pool.getConnection();try{await connection.beginTransaction();await connection.query('INSERT INTO resource_grants (id,organization_id,workspace_id,resource_type,resource_id,grantee_membership_id,grantor_id,reason,status,expires_at,revoked_at,revoked_by,revocation_reason,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[grant.id,grant.organization_id,grant.workspace_id,grant.resource_type,grant.resource_id,grant.grantee_membership_id,grant.grantor_id,grant.reason,grant.status,grant.expires_at,grant.revoked_at,grant.revoked_by,grant.revocation_reason,grant.version,grant.created_at,grant.updated_at]);for(const action of grant.actions)await connection.query('INSERT INTO resource_grant_actions (grant_id,capability_code,created_at) VALUES (?,?,?)',[grant.id,action,grant.created_at]);await connection.commit();}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
 async updateGrant(grant:ResourceGrant,expectedVersion:number){const[result]=await this.pool.query('UPDATE resource_grants SET reason=?,status=?,expires_at=?,revoked_at=?,revoked_by=?,revocation_reason=?,version=?,updated_at=? WHERE id=? AND organization_id=? AND version=?',[grant.reason,grant.status,grant.expires_at,grant.revoked_at,grant.revoked_by,grant.revocation_reason,grant.version,grant.updated_at,grant.id,grant.organization_id,expectedVersion]);return Number((result as{affectedRows:number}).affectedRows)===1;}
 async appendAudit(event:ResourceGrantAuditEvent){await this.pool.query('INSERT INTO resource_grant_audit_events (id,grant_id,organization_id,workspace_id,actor_id,event_type,resource_type,resource_id,capability,surface,outcome,reason,request_id,trace_id,occurred_at,schema_version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[event.id,event.grant_id,event.organization_id,event.workspace_id,event.actor_id,event.event_type,event.resource_type,event.resource_id,event.capability,event.surface,event.outcome,event.reason,event.request_id,event.trace_id,event.occurred_at,event.schema_version]);}
 async commitCreate(grant:ResourceGrant,audit:ResourceGrantAuditEvent,operation:ResourceGrantOperation){const connection=await this.pool.getConnection();try{await connection.beginTransaction();await connection.query('INSERT INTO resource_grants (id,organization_id,workspace_id,resource_type,resource_id,grantee_membership_id,grantor_id,reason,status,expires_at,revoked_at,revoked_by,revocation_reason,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[grant.id,grant.organization_id,grant.workspace_id,grant.resource_type,grant.resource_id,grant.grantee_membership_id,grant.grantor_id,grant.reason,grant.status,grant.expires_at,grant.revoked_at,grant.revoked_by,grant.revocation_reason,grant.version,grant.created_at,grant.updated_at]);for(const action of grant.actions)await connection.query('INSERT INTO resource_grant_actions (grant_id,capability_code,created_at) VALUES (?,?,?)',[grant.id,action,grant.created_at]);await this.insertAudit(connection,audit);await this.insertOperation(connection,grant,operation);await connection.commit();}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
 async commitUpdate(grant:ResourceGrant,expectedVersion:number,audit:ResourceGrantAuditEvent,operation:ResourceGrantOperation){const connection=await this.pool.getConnection();try{await connection.beginTransaction();const[result]=await connection.query('UPDATE resource_grants SET reason=?,status=?,expires_at=?,revoked_at=?,revoked_by=?,revocation_reason=?,version=?,updated_at=? WHERE id=? AND organization_id=? AND version=?',[grant.reason,grant.status,grant.expires_at,grant.revoked_at,grant.revoked_by,grant.revocation_reason,grant.version,grant.updated_at,grant.id,grant.organization_id,expectedVersion]);if(Number((result as{affectedRows:number}).affectedRows)!==1){await connection.rollback();return false;}await this.insertAudit(connection,audit);await this.insertOperation(connection,grant,operation);await connection.commit();return true;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
 async findGrantForAccess(input:{membershipId:string;organizationId:string;workspaceId?:string;resourceType:ResourceGrantType;resourceId:string;capability:ResourceGrantAction}){if(!input.workspaceId)return null;const[rows]=await this.pool.query<RowDataPacket[]>(`${select} WHERE rg.grantee_membership_id=? AND rg.organization_id=? AND rg.workspace_id=? AND rg.resource_type=? AND rg.resource_id=? AND EXISTS (SELECT 1 FROM resource_grant_actions permitted WHERE permitted.grant_id=rg.id AND permitted.capability_code=?) ORDER BY rg.created_at DESC,rga.capability_code`,[input.membershipId,input.organizationId,input.workspaceId,input.resourceType,input.resourceId,input.capability]);if(!rows.length)return null;const id=rows[0]!.id;return toGrant(rows.filter(row=>row.id===id));}
 async listForMembership(membershipId:string,organizationId:string,now:Date){const[rows]=await this.pool.query<RowDataPacket[]>(`${select} WHERE rg.grantee_membership_id=? AND rg.organization_id=? ORDER BY rg.created_at DESC,rga.capability_code`,[membershipId,organizationId]);return this.group(rows,now);}
 async listForOrganization(organizationId:string,filter:{status?:ResourceGrantStatus;limit:number;offset:number},now:Date){const statusSql=filter.status==='revoked'?"AND rg.status='revoked'":filter.status==='active'?"AND rg.status='active' AND rg.expires_at>?":filter.status==='expired'?"AND rg.status='active' AND rg.expires_at<=?":'';const statusParams=filter.status?[now]:[];if(filter.status==='revoked')statusParams.length=0;const[countRows]=await this.pool.query<RowDataPacket[]>(`SELECT COUNT(*) total FROM resource_grants rg WHERE rg.organization_id=? ${statusSql}`,[organizationId,...statusParams]);const[idRows]=await this.pool.query<RowDataPacket[]>(`SELECT rg.id FROM resource_grants rg WHERE rg.organization_id=? ${statusSql} ORDER BY rg.created_at DESC,rg.id LIMIT ? OFFSET ?`,[organizationId,...statusParams,filter.limit,filter.offset]);if(!idRows.length)return{items:[],total:Number(countRows[0]!.total)};const ids=idRows.map(row=>row.id),placeholders=ids.map(()=>'?').join(',');const[rows]=await this.pool.query<RowDataPacket[]>(`${select} WHERE rg.id IN (${placeholders}) ORDER BY rg.created_at DESC,rga.capability_code`,ids);return{items:this.group(rows,now),total:Number(countRows[0]!.total)};}
 private group(rows:RowDataPacket[],now:Date){const grouped=new Map<string,RowDataPacket[]>();for(const row of rows)grouped.set(row.id,[...(grouped.get(row.id)??[]),row]);return[...grouped.values()].map(group=>{const grant=toGrant(group);grant.effective_status=grant.status==='revoked'?'revoked':grant.expires_at<=now?'expired':'active';return grant;});}
 private insertAudit(connection:PoolConnection,event:ResourceGrantAuditEvent){return connection.query('INSERT INTO resource_grant_audit_events (id,grant_id,organization_id,workspace_id,actor_id,event_type,resource_type,resource_id,capability,surface,outcome,reason,request_id,trace_id,occurred_at,schema_version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[event.id,event.grant_id,event.organization_id,event.workspace_id,event.actor_id,event.event_type,event.resource_type,event.resource_id,event.capability,event.surface,event.outcome,event.reason,event.request_id,event.trace_id,event.occurred_at,event.schema_version]);}
 private insertOperation(connection:PoolConnection,grant:ResourceGrant,operation:ResourceGrantOperation){return connection.query('INSERT INTO resource_grant_operations (id,organization_id,actor_id,operation,idempotency_key_hash,request_hash,grant_id,grant_version,created_at) VALUES (?,?,?,?,?,?,?,?,?)',[randomUUID(),operation.organization_id,operation.actor_id,operation.operation,operation.key_hash,operation.request_hash,grant.id,grant.version,operation.occurred_at]);}
}
