// @ts-nocheck -- aggregate result rows are normalized below.
import{randomUUID}from"node:crypto";import type{Pool,RowDataPacket}from"mysql2/promise";import{CollectionConsoleError,type CollectionConsoleRepository}from"./collection-console-service.js";const n=(v:any)=>Number(v??0),iso=(v:any)=>v?new Date(v).toISOString():null;
export class MySqlCollectionConsoleRepository implements CollectionConsoleRepository{constructor(private readonly pool:Pool,private readonly now=()=>new Date()){}async read(i:any){if(i.organizationId){const[r]=await this.pool.query<RowDataPacket[]>("SELECT id FROM organizations WHERE id=?",[i.organizationId]);if(!r[0])throw new CollectionConsoleError("collection_console_organization_not_found",404,"选择存在的组织。");}if(i.workspaceId){const[r]=await this.pool.query<RowDataPacket[]>("SELECT organization_id FROM workspaces WHERE id=?",[i.workspaceId]);if(!r[0])throw new CollectionConsoleError("collection_console_workspace_not_found",404,"选择存在的工作区。");if(i.organizationId&&r[0].organization_id!==i.organizationId)throw new CollectionConsoleError("collection_console_scope_mismatch",409,"选择属于该组织的工作区。");}const where=[],values=[];if(i.organizationId){where.push("organization_id=?");values.push(i.organizationId);}if(i.workspaceId){where.push("workspace_id=?");values.push(i.workspaceId);}const clause=where.length?`WHERE ${where.join(" AND ")}`:"",taskClause=clause,qualityClause=clause,deadClause=clause;const[[sources],[tasks],[dead],[quality],[attempts]]=await Promise.all([
this.pool.query<RowDataPacket[]>("SELECT p.id,p.code,p.name,p.status,p.owner_label,p.schedule_minutes,p.concurrency_limit,p.parser_version,h.health_status,h.last_checked_at,h.last_latency_ms,h.last_error_code,h.consecutive_failures FROM providers p LEFT JOIN provider_adapter_health h ON h.provider_id=p.id ORDER BY p.status='enabled' DESC,p.name"),
this.pool.query<RowDataPacket[]>(`SELECT status,COUNT(*) total FROM collection_tasks ${taskClause} GROUP BY status ORDER BY status`,values),
this.pool.query<RowDataPacket[]>(`SELECT id,task_id,organization_id,workspace_id,error_code,status,created_at FROM collection_dead_letters ${deadClause} ORDER BY created_at DESC LIMIT ?`,[...values,i.recentLimit]),
this.pool.query<RowDataPacket[]>(`SELECT severity,status,COUNT(*) total FROM data_quality_issues ${qualityClause} GROUP BY severity,status ORDER BY status,severity`,values),
this.pool.query<RowDataPacket[]>(`SELECT a.id,a.task_id,t.organization_id,t.workspace_id,a.attempt_number,a.worker_id,a.status,a.error_code,a.started_at,a.finished_at,a.trace_id FROM collection_task_attempts a JOIN collection_tasks t ON t.id=a.task_id ${taskClause?taskClause.replaceAll("organization_id","t.organization_id").replaceAll("workspace_id","t.workspace_id"):""} ORDER BY a.created_at DESC LIMIT ?`,[...values,i.recentLimit])]);
const result={filters:{organization_id:i.organizationId,workspace_id:i.workspaceId},sources:sources.map((r:any)=>({...r,schedule_minutes:n(r.schedule_minutes),concurrency_limit:n(r.concurrency_limit),last_latency_ms:r.last_latency_ms==null?null:n(r.last_latency_ms),consecutive_failures:n(r.consecutive_failures),last_checked_at:iso(r.last_checked_at),health_status:r.health_status??"unknown"})),task_states:tasks.map((r:any)=>({status:r.status,total:n(r.total)})),dead_letters:dead.map((r:any)=>({...r,created_at:iso(r.created_at)})),quality:quality.map((r:any)=>({...r,total:n(r.total)})),attempts:attempts.map((r:any)=>({...r,attempt_number:n(r.attempt_number),started_at:iso(r.started_at),finished_at:iso(r.finished_at)})),links:{provider_registry:"/platform-admin/providers",adapter_health:"/platform-admin/providers/adapters",source_catalog:"/platform-admin/providers/sources",task_monitor:"/platform-admin/collection",browser_runtime:"/platform-admin/collection/browser-runtime",data_quality:"/platform-admin/data"},observed_at:this.now().toISOString()};const c=await this.pool.getConnection();try{await c.beginTransaction();await c.query("INSERT INTO collection_console_views(id,actor_id,organization_filter_id,workspace_filter_id,request_id,trace_id,observed_at) VALUES(?,?,?,?,?,?,?)",[randomUUID(),i.actorId,i.organizationId,i.workspaceId,i.requestId,i.traceId,this.now()]);await c.query("INSERT INTO platform_audit_events(id,organization_id,workspace_id,actor_id,action,resource_type,resource_id,outcome,request_id,trace_id,metadata,occurred_at,schema_version) VALUES(?,?,?,?,?,'collection_console',NULL,'succeeded',?,?,?,?,1)",[randomUUID(),i.organizationId,i.workspaceId,i.actorId,"platform.collection.console.read",i.requestId,i.traceId,JSON.stringify({organization_filter_id:i.organizationId,workspace_filter_id:i.workspaceId}),this.now()]);await c.commit();}catch(e){await c.rollback();throw e;}finally{c.release();}return result;}}
