import{ApiError}from'./api-foundation.js';
export class PlatformAccountError extends ApiError{constructor(code:string,statusCode:number,actionHint:string){super(statusCode,code,code,actionHint);this.name='PlatformAccountError';}}
export interface PlatformAccountRepository{
  overview(input:{query:string;status:string;limit:number}):Promise<unknown>;
  createOrganization(input:{name:string;slug:string;actorId:string;idempotencyKey:string;requestId:string;traceId:string;now:Date}):Promise<unknown>;
  setOrganizationStatus(input:{organizationId:string;status:'active'|'archived';reason:string;actorId:string;idempotencyKey:string;requestId:string;traceId:string;now:Date}):Promise<unknown>;
  setUserStatus(input:{userId:string;status:'active'|'disabled';reason:string;actorId:string;idempotencyKey:string;requestId:string;traceId:string;now:Date}):Promise<unknown>;
  setPlatformRole(input:{userId:string;roleCode:'platform_operations_admin'|'platform_security_admin'|'platform_super_admin';enabled:boolean;reason:string;actorId:string;idempotencyKey:string;requestId:string;traceId:string;now:Date}):Promise<unknown>;
}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const reason=(value:unknown)=>{if(typeof value!=='string'||value.trim().length<2||value.trim().length>300)throw new PlatformAccountError('reason_invalid',400,'填写 2–300 字的操作原因。');return value.trim();};
export class PlatformAccountService{
  constructor(private readonly repository:PlatformAccountRepository,private readonly now:()=>Date=()=>new Date()){}
  overview(query:unknown,status:unknown){return this.repository.overview({query:typeof query==='string'?query.trim().slice(0,120):'',status:typeof status==='string'?status.trim().slice(0,30):'',limit:200});}
  createOrganization(value:any,context:{actorId:string;idempotencyKey:string;requestId:string;traceId:string}){const name=String(value?.name??'').trim(),slug=String(value?.slug??'').trim().toLowerCase();if(name.length<2||name.length>120)throw new PlatformAccountError('organization_name_invalid',400,'组织名称需 2–120 个字。');if(!/^[a-z0-9][a-z0-9-]{1,62}$/.test(slug))throw new PlatformAccountError('organization_slug_invalid',400,'组织标识使用 2–63 位小写字母、数字或连字符。');return this.repository.createOrganization({name,slug,...context,now:this.now()});}
  organizationStatus(id:string,value:any,context:{actorId:string;idempotencyKey:string;requestId:string;traceId:string}){if(!uuid.test(id))throw new PlatformAccountError('organization_id_invalid',400,'刷新组织列表后重试。');const status=value?.status;if(!['active','archived'].includes(status))throw new PlatformAccountError('organization_status_invalid',400,'选择启用或停用。');return this.repository.setOrganizationStatus({organizationId:id,status,reason:reason(value?.reason),...context,now:this.now()});}
  userStatus(id:string,value:any,context:{actorId:string;idempotencyKey:string;requestId:string;traceId:string}){if(!uuid.test(id))throw new PlatformAccountError('user_id_invalid',400,'刷新用户列表后重试。');const status=value?.status;if(!['active','disabled'].includes(status))throw new PlatformAccountError('user_status_invalid',400,'选择启用或停用。');if(id===context.actorId&&status==='disabled')throw new PlatformAccountError('cannot_disable_self',409,'不能停用当前登录账号，请由另一位超级管理员操作。');return this.repository.setUserStatus({userId:id,status,reason:reason(value?.reason),...context,now:this.now()});}
  platformRole(id:string,value:any,context:{actorId:string;idempotencyKey:string;requestId:string;traceId:string}){if(!uuid.test(id))throw new PlatformAccountError('user_id_invalid',400,'刷新管理员列表后重试。');const roleCode=value?.role_code;if(!['platform_operations_admin','platform_security_admin','platform_super_admin'].includes(roleCode)||typeof value?.enabled!=='boolean')throw new PlatformAccountError('platform_role_invalid',400,'选择有效的平台角色和授权状态。');if(id===context.actorId&&roleCode==='platform_super_admin'&&!value.enabled)throw new PlatformAccountError('cannot_revoke_self_superadmin',409,'不能撤销自己的超级管理员角色。');return this.repository.setPlatformRole({userId:id,roleCode,enabled:value.enabled,reason:reason(value?.reason),...context,now:this.now()});}
}
