import type {FastifyInstance,FastifyRequest} from 'fastify';
import {AuthError,LocalAuthService} from '@scoutops/auth';
import {AuthorizationError,AuthorizationService} from '@scoutops/authorization';
import {RESOURCE_GRANT_ACTIONS,ResourceGrantError,ResourceGrantService,type ResourceGrantStatus,type ResourceGrantType} from '@scoutops/resource-grants';
export interface ResourceGrantRouteOptions{service:ResourceGrantService;authorization:AuthorizationService;auth:LocalAuthService;secureCookie:boolean;}
const cookieName=(secure:boolean)=>secure?'__Host-scoutops_session':'scoutops_session';
function sessionToken(request:FastifyRequest,secure:boolean){for(const part of(request.headers.cookie??'').split(';')){const[name,...value]=part.trim().split('=');if(name===cookieName(secure))return decodeURIComponent(value.join('='));}throw new AuthError('session_invalid',401,'重新登录后重试。');}
const envelope=<T>(data:T,request:FastifyRequest,meta?:Record<string,unknown>)=>({data,...(meta?{meta}:{}),request_id:request.headers['x-request-id']!.toString(),trace_id:request.headers['x-trace-id']!.toString()});
const ids=(request:FastifyRequest)=>({requestId:request.headers['x-request-id']!.toString(),traceId:request.headers['x-trace-id']!.toString()});
const grantView=(grant:any,now=new Date())=>({...grant,expires_at:grant.expires_at.toISOString(),revoked_at:grant.revoked_at?.toISOString()??null,created_at:grant.created_at.toISOString(),updated_at:grant.updated_at.toISOString(),effective_status:grant.status==='revoked'?'revoked':grant.expires_at<=now?'expired':'active'});
const uuid={type:'string',format:'uuid'} as const,actions=[...new Set(Object.values(RESOURCE_GRANT_ACTIONS).flat())];
export function registerResourceGrantRoutes(app:FastifyInstance,options:ResourceGrantRouteOptions){
 const current=async(request:FastifyRequest)=>options.auth.authenticate(sessionToken(request,options.secureCookie));
 const selected=async(request:FastifyRequest)=>{const authenticated=await current(request);const resolved=await options.authorization.resolveSession(authenticated.user.id,authenticated.session.id);return{authenticated,resolved};};
 const organization=async(request:FastifyRequest,organizationId:string,capability:'role:read'|'role:manage'|'membership:read')=>{const session=await selected(request);if(session.resolved.context.organization_id!==organizationId)throw new AuthorizationError('tenancy_context_mismatch',409,'先切换到目标组织。');await options.authorization.authorize({actorId:session.authenticated.user.id,organizationId,capability,surface:'api',...ids(request)});return session;};
 const mutationContext=(request:FastifyRequest,actorId:string,organizationId:string)=>{const raw=request.headers['idempotency-key'];if(typeof raw!=='string')throw new ResourceGrantError('idempotency_key_required',400,'提供 Idempotency-Key。');return{actorId,organizationId,idempotencyKey:raw,...ids(request)};};
 app.get('/api/v1/me/resource-grants',async(request,reply)=>{const session=await selected(request),membershipId=session.resolved.subject.membership_id!;reply.header('cache-control','no-store');return envelope((await options.service.listMine(membershipId,session.resolved.context.organization_id)).map(item=>grantView(item)),request);});
 app.get('/api/v1/org/:organizationId/resource-grant-targets',{schema:{params:{type:'object',required:['organizationId'],properties:{organizationId:uuid},additionalProperties:false}}},async(request,reply)=>{const{organizationId}=request.params as{organizationId:string};await organization(request,organizationId,'membership:read');reply.header('cache-control','no-store');return envelope(await options.service.listEligibleMembers(organizationId),request);});
 app.get('/api/v1/org/:organizationId/resource-grants',{schema:{params:{type:'object',required:['organizationId'],properties:{organizationId:uuid},additionalProperties:false},querystring:{type:'object',properties:{page:{type:'integer',minimum:1,default:1},limit:{type:'integer',minimum:1,maximum:100,default:20},status:{type:'string',enum:['active','revoked','expired']}},additionalProperties:false}}},async(request,reply)=>{const{organizationId}=request.params as{organizationId:string},query=request.query as{page?:number;limit?:number;status?:ResourceGrantStatus};await organization(request,organizationId,'role:read');const result=await options.service.listOrganization(organizationId,{page:query.page??1,limit:query.limit??20,...(query.status?{status:query.status}:{})});reply.header('cache-control','no-store');return envelope(result.items.map(item=>grantView(item)),request,{page:query.page??1,limit:query.limit??20,total:result.total});});
 app.post('/api/v1/org/:organizationId/resource-grants',{schema:{params:{type:'object',required:['organizationId'],properties:{organizationId:uuid},additionalProperties:false},body:{type:'object',required:['workspace_id','resource_type','resource_id','grantee_membership_id','actions','reason','expires_at'],properties:{workspace_id:uuid,resource_type:{type:'string',enum:Object.keys(RESOURCE_GRANT_ACTIONS)},resource_id:uuid,grantee_membership_id:uuid,actions:{type:'array',minItems:1,maxItems:8,uniqueItems:true,items:{type:'string',enum:actions}},reason:{type:'string',minLength:1,maxLength:500},expires_at:{type:'string',format:'date-time'}},additionalProperties:false}}},async(request,reply)=>{const{organizationId}=request.params as{organizationId:string},session=await organization(request,organizationId,'role:manage'),body=request.body as any;const grant=await options.service.create({...body,resource_type:body.resource_type as ResourceGrantType,expires_at:new Date(body.expires_at)},mutationContext(request,session.authenticated.user.id,organizationId));reply.code(201).header('cache-control','no-store');return envelope(grantView(grant),request);});
 app.patch('/api/v1/org/:organizationId/resource-grants/:grantId/expiry',{schema:{params:{type:'object',required:['organizationId','grantId'],properties:{organizationId:uuid,grantId:uuid},additionalProperties:false},body:{type:'object',required:['expected_version','reason','expires_at'],properties:{expected_version:{type:'integer',minimum:1},reason:{type:'string',minLength:1,maxLength:500},expires_at:{type:'string',format:'date-time'}},additionalProperties:false}}},async request=>{const{organizationId,grantId}=request.params as{organizationId:string;grantId:string},session=await organization(request,organizationId,'role:manage'),body=request.body as{expected_version:number;reason:string;expires_at:string};const grant=await options.service.extend({grant_id:grantId,expected_version:body.expected_version,reason:body.reason,expires_at:new Date(body.expires_at)},mutationContext(request,session.authenticated.user.id,organizationId));return envelope(grantView(grant),request);});
 app.post('/api/v1/org/:organizationId/resource-grants/:grantId/revoke',{schema:{params:{type:'object',required:['organizationId','grantId'],properties:{organizationId:uuid,grantId:uuid},additionalProperties:false},body:{type:'object',required:['expected_version','reason'],properties:{expected_version:{type:'integer',minimum:1},reason:{type:'string',minLength:1,maxLength:500}},additionalProperties:false}}},async request=>{const{organizationId,grantId}=request.params as{organizationId:string;grantId:string},session=await organization(request,organizationId,'role:manage'),body=request.body as{expected_version:number;reason:string};const grant=await options.service.revoke({grant_id:grantId,...body},mutationContext(request,session.authenticated.user.id,organizationId));return envelope(grantView(grant),request);});
}
