// Source-derived UI2-DI fixtures and current presentation contracts; not live data.
window.SCOUTOPS_DISCOVERY_DESIGN = {
  scope: { organization_name: "隔离组织", workspace_name: "隔离工作区" },
  result: {
    id: "00000000-0000-4000-8000-000000000510",
    resource_id: "00000000-0000-4000-8000-000000000510",
    resource_type: "task",
    title: "隔离目标任务",
    subtitle: null,
    status: "todo",
    assignee_id: null,
    assignee_name: null,
    route: "/tasks/00000000-0000-4000-8000-000000000510",
    updated_at: "2026-08-07T15:00:00.000Z",
  },
  actions: [
    {
      id: "task",
      label: "创建任务",
      description: "进入任务创建页",
      route: "/tasks?create=1",
      required_capability: "task:create",
    },
    {
      id: "sourcing",
      label: "发起找货",
      description: "进入供应链搜索",
      route: "/sourcing?create=1",
      required_capability: "sourcing:read",
    },
  ],
  oneAction: [
    {
      id: "task",
      label: "创建任务",
      description: "进入任务创建页",
      route: "/tasks?create=1",
      required_capability: "task:create",
    },
  ],
  actionPreviews: {
    organization_admin: [
      {
        id: "member",
        label: "邀请成员",
        description: "进入当前组织成员管理",
        route: "/org-admin/members?create=1",
        required_capability: "membership:manage",
      },
      {
        id: "workspace",
        label: "创建工作区",
        description: "进入当前组织工作区管理",
        route: "/org-admin/workspaces?create=1",
        required_capability: "workspace:manage",
      },
    ],
    platform_admin: [
      {
        id: "provider",
        label: "配置来源",
        description: "进入平台来源注册中心",
        route: "/platform-admin/providers?create=1",
        required_capability: "provider:configure",
      },
    ],
    all_registered: [
      {
        id: "task",
        label: "创建任务",
        description: "进入任务创建页",
        route: "/tasks?create=1",
        required_capability: "task:create",
      },
      {
        id: "sourcing",
        label: "发起找货",
        description: "进入供应链搜索",
        route: "/sourcing?create=1",
        required_capability: "sourcing:read",
      },
      {
        id: "member",
        label: "邀请成员",
        description: "进入当前组织成员管理",
        route: "/org-admin/members?create=1",
        required_capability: "membership:manage",
      },
      {
        id: "workspace",
        label: "创建工作区",
        description: "进入当前组织工作区管理",
        route: "/org-admin/workspaces?create=1",
        required_capability: "workspace:manage",
      },
      {
        id: "provider",
        label: "配置来源",
        description: "进入平台来源注册中心",
        route: "/platform-admin/providers?create=1",
        required_capability: "provider:configure",
      },
    ],
  },
  statusOptions: {
    task: [
      { value: "todo", label: "待处理" },
      { value: "in_progress", label: "进行中" },
      { value: "paused", label: "已暂停" },
      { value: "completed", label: "已完成" },
      { value: "cancelled", label: "已取消" },
    ],
    opportunity: [
      { value: "candidate", label: "候选" },
      { value: "validating", label: "验证中" },
      { value: "ready", label: "待决策" },
      { value: "adopted", label: "已采纳" },
      { value: "observing", label: "观察中" },
      { value: "rejected", label: "已拒绝" },
    ],
    evidence: [
      { value: "active", label: "有效" },
      { value: "quarantined", label: "已隔离" },
      { value: "expired", label: "已过期" },
    ],
    collection_task: [
      { value: "queued", label: "排队中" },
      { value: "running", label: "运行中" },
      { value: "retry_scheduled", label: "等待重试" },
      { value: "succeeded", label: "已成功" },
      { value: "succeeded_empty", label: "成功但无结果" },
      { value: "failed_terminal", label: "最终失败" },
      { value: "dead_letter", label: "死信" },
    ],
  },
  stateCopy: {
    loading: {
      eyebrow: "LOADING",
      title: "正在读取真实数据",
      description: "请求完成前不显示旧数据或推测结果。",
      primary: "请稍候",
    },
    empty: {
      eyebrow: "EMPTY",
      title: "这里还没有内容",
      description: "当前范围内没有结果；可调整条件或执行明确的首次操作。",
      primary: "开始创建",
      secondary: "调整筛选",
    },
    error: {
      eyebrow: "ERROR",
      title: "操作未完成",
      description: "请求失败且没有写入成功；请按提示重试。",
      primary: "重新尝试",
      secondary: "返回上一页",
    },
    forbidden: {
      eyebrow: "PERMISSION",
      title: "你没有此项权限",
      description: "服务端已拒绝访问；页面不会展示受限数据。",
      primary: "返回工作台",
      secondary: "申请权限",
    },
    expired: {
      eyebrow: "SESSION",
      title: "登录已失效",
      description: "重新登录后再继续，未提交的敏感操作不会自动重放。",
      primary: "重新登录",
    },
    blocked: {
      eyebrow: "BLOCKED",
      title: "依赖暂时受阻",
      description: "请求因限流、超时或依赖不可用而停止；不会伪装为成功。",
      primary: "稍后重试",
      secondary: "查看影响",
    },
    recovery: {
      eyebrow: "RECOVERED",
      title: "服务已恢复",
      description: "最新检查已通过；后续数据仍以服务端时间和来源为准。",
      primary: "继续",
    },
    not_found: {
      eyebrow: "404 / LOST IN SIGNAL",
      title: "没有找到这个页面",
      description: "地址可能已变更，或该入口不属于当前角色。",
      primary: "返回今日行动",
      secondary: "返回上一页",
    },
  },
  failure: { hint: "当前请求受阻", requestId: "ui2-previous-read", traceId: "ui2-previous-trace" },
};
