// Reviewed subset of m06-02-platform-dashboard.spec.ts, not a live observation.
window.SCOUTOPS_STATUS_DESIGN = {
  observed_at: "2026-08-18T12:00:00.000Z",
  summary: {
    api: "ready",
    database: "healthy",
    dashboard_reads: 5,
    active_organizations: 2,
    active_users: 8,
  },
  services: [
    {
      code: "api",
      name: "Node API",
      status: "ready",
      detail: "0.1.0 · abcdef123456",
      observed_at: "2026-08-18T12:00:00.000Z",
      href: "/platform-admin/topology",
    },
    {
      code: "mysql",
      name: "MySQL",
      status: "healthy",
      detail: "最近一次韧性检查",
      observed_at: "2026-08-18T12:00:00.000Z",
      href: "/platform-admin/mysql",
    },
    {
      code: "redis",
      name: "Redis",
      status: "warning",
      detail: "最近一次韧性检查",
      observed_at: "2026-08-18T11:59:00.000Z",
      href: "/platform-admin/redis",
    },
    {
      code: "files",
      name: "文件存储",
      status: "stale",
      detail: "最近一次存储检查",
      observed_at: "2026-08-18T10:00:00.000Z",
      href: "/platform-admin/files",
    },
    {
      code: "worker",
      name: "Node Worker",
      status: "ready",
      detail: "1 个实例 · 1 个活动任务",
      observed_at: "2026-08-18T12:00:00.000Z",
      href: "/platform-admin/crawler-scheduler",
    },
    {
      code: "crawler",
      name: "Python Crawler",
      status: "ready",
      detail: "1 个实例 · 0 个活动运行",
      observed_at: "2026-08-18T12:00:00.000Z",
      href: "/platform-admin/crawler-scheduler",
    },
  ],
  collections: [{ status: "running", total: 1 }],
  sources: [{ status: "enabled", total: 138 }],
  metrics: {
    session_started_at: "2026-08-18T11:30:00.000Z",
    connection_open_count: 8,
    reconnect_count: 2,
    fallback_poll_count: 2,
    last_open_at: "2026-08-18T11:59:30.000Z",
    last_reconnect_at: "2026-08-18T11:59:00.000Z",
    last_fallback_poll_at: "2026-08-18T11:59:01.000Z",
    reconnecting: false,
  },
};
// Exact relationships/fallbacks from platform-status-topology.ts.
window.SCOUTOPS_STATUS_TOPOLOGY = [
  {
    code: "api",
    fallbackName: "后端接口",
    lane: "entry",
    dependencies: ["mysql", "redis"],
    impact: "网页请求、平台操作与内部采集回调",
    href: "/platform-admin/topology",
  },
  {
    code: "mysql",
    fallbackName: "数据库",
    lane: "shared",
    dependencies: [],
    impact: "API 读写、异步任务与业务事实",
    href: "/platform-admin/mysql",
  },
  {
    code: "redis",
    fallbackName: "缓存与任务队列",
    lane: "shared",
    dependencies: [],
    impact: "API 就绪、队列协调、限流与实时通知",
    href: "/platform-admin/redis",
  },
  {
    code: "files",
    fallbackName: "文件存储",
    lane: "shared",
    dependencies: [],
    impact: "证据保存、报表导出与采集回执暂存",
    href: "/platform-admin/files",
  },
  {
    code: "worker",
    fallbackName: "任务处理服务",
    lane: "execution",
    dependencies: ["mysql", "redis", "files"],
    impact: "采集任务、异步投影、通知与报表导出",
    href: "/platform-admin/crawler-scheduler",
  },
  {
    code: "crawler",
    fallbackName: "网页采集服务",
    lane: "execution",
    dependencies: ["api", "worker", "files"],
    impact: "需要登录档案的网页采集子查询",
    href: "/platform-admin/crawler-scheduler",
  },
];
