window.COMMERCIAL_DATA = {
  sourcePaths: [
    "apps/web/src/components/CommercialOperationsCenter.vue",
    "apps/api/src/commercial-service.ts",
    "apps/api/src/mysql-commercial-repository.ts",
    "apps/api/src/commercial-routes.ts",
    "apps/web/src/use-modal-dialog.ts",
    "apps/web/src/api-client.ts",
    "config/route-catalog.json",
    "tests/e2e/m06-06-commercial.spec.ts",
    "tests/m06-06/commercial.test.mjs",
  ],
  sourceChecks: [
    "Actual Vue read single-flight, 15-second timer, 20/10 query sizes and stale organization target mismatch reproduced without HTTP.",
    "Actual Vue selectable-current-plan fallback versus preview lookup, future adjustment and clamped-negative reverse-calculation limitations reproduced.",
    "Actual Vue create single-flight and retained idempotency key verified; late response closes newer dialog and overwrites reload error reproduced.",
    "Actual Vue edit-to-impact frozen full PATCH/version, confirmation single-flight, pending key retention on 409 and zero-adjustment guard verified.",
    "Actual service validation executed: three quota keys, integer/max/zero bounds, UUIDs, dates, three editable states, one-character service reason and lowercase code normalization.",
    "Actual repository read with inert SQL adapter verifies global catalog/paging, escaped search, all-status period COUNT, assignment-scoped effective SUM and zero clamp plus read-audit query intent; no MySQL executed.",
    "Static boundaries: 26 model fields, three native business dialogs, platform:operate/origin/idempotency route predicates; not authentication or transaction acceptance.",
  ],
  original: {
    summary: { total: 1, draft: 0, active: 1, retired: 0 },
    pagination: { page: 1, page_size: 20, total: 1, total_pages: 1 },
    adjustment_pagination: { page: 1, page_size: 10, total: 1, total_pages: 1 },
    plans: [
      {
        id: "p1",
        code: "growth",
        name: "成长配额方案",
        description: "当前只展示已配置额度，不包含价格或计费",
        quotas: { collection_tasks: 100, open_api_requests: 1000, report_exports: 20 },
        status: "active",
        version: 2,
        assignment_count: 3,
        updated_at: "2026-08-08T00:00:00Z",
      },
    ],
    organization: { id: "o1", name: "测试组织", status: "active" },
    assignment: {
      id: "a1",
      organization_id: "o1",
      plan_id: "p1",
      plan_code: "growth",
      plan_name: "成长配额方案",
      quotas: { collection_tasks: 100, open_api_requests: 1000, report_exports: 20 },
      period_start: "2026-08-01T00:00:00Z",
      period_end: "2026-09-01T00:00:00Z",
      status: "active",
      version: 1,
      updated_at: "2026-08-08T00:00:00Z",
    },
    adjustments: [
      {
        id: "q1",
        quota_key: "open_api_requests",
        delta_value: 50,
        reason: "运营核准",
        status: "active",
        effective_at: "2026-08-08T00:00:00Z",
        expires_at: null,
        version: 1,
        updated_at: "2026-08-08T00:00:00Z",
      },
    ],
    usage: { collection_tasks: 42, open_api_requests: 380, report_exports: 4 },
    effective_quotas: { collection_tasks: 100, open_api_requests: 1050, report_exports: 20 },
    observed_at: "2026-08-08T00:00:00Z",
    scope: { organization_id: "o1" },
  },
  findings: [
    {
      id: "CS-G01",
      title: "组织目标与保留快照分离不足",
      observed: "读取 o2 失败后 data.organization=o1，但分配请求目标=o2。",
      proposal: "已读取组织与输入/请求分开；切换失败不能沿用旧事实生成新目标确认。",
    },
    {
      id: "CS-G02",
      title: "影响值不足以作为执行事实",
      observed:
        "当前方案可选但分页外预览显示未选择；未来 +50 也立即预览为150；截零后不能恢复原负调整总额。",
      proposal:
        "缺失方案/未到期/过期/截零反推场景展示限制与待核对值，不猜变更后余量。需实现阶段修正预览算法。",
    },
    {
      id: "CS-G03",
      title: "写入结果与刷新、窗口实例需要分开",
      observed:
        "创建单飞与原幂等键重试存在；旧创建成功仍关闭新开窗口，重读失败被创建成功提示覆盖。",
      proposal:
        "保留写事务身份；窗内错误、旧结果单独通知、成功/刷新失败双结果；关闭不声称撤回事务。",
    },
    {
      id: "CS-G06",
      title: "服务与表单约束差异保留",
      observed:
        "服务原因 trim 后1–500；编辑与分配前端 minlength=2；服务 code 先小写化而前端只收小写。",
      proposal: "逐字段保留来源约束并展示差异，不新增收费字段或扩大服务规则。",
    },
  ],
  models: [
    "organizationInput",
    "assignment.plan_id",
    "assignment.period_start",
    "assignment.period_end",
    "assignment.reason",
    "adjustment.quota_key",
    "adjustment.delta_value",
    "adjustment.effective_at",
    "adjustment.expires_at",
    "adjustment.reason",
    "query",
    "status",
    "plan.code",
    "plan.name",
    "plan.description",
    "plan.collection_tasks",
    "plan.open_api_requests",
    "plan.report_exports",
    "plan.reason",
    "editingPlan.name",
    "editingPlan.description",
    "editingPlan.collection_tasks",
    "editingPlan.open_api_requests",
    "editingPlan.report_exports",
    "editingPlan.status",
    "editingPlan.reason",
  ],
  quotaNames: {
    collection_tasks: "采集任务",
    open_api_requests: "外部接口请求",
    report_exports: "报表导出",
  },
};
