window.HOME_C_DATA = {
  form: {
    name: "",
    include_keywords: "",
    negative_keywords: "",
    market: "US",
    category: "",
    collection_interval_minutes: 60,
    recommendation_min_source_count: 1,
  },
  options: {
    market: [
      {
        value: "US",
        label: "美国",
      },
      {
        value: "GB",
        label: "英国",
      },
      {
        value: "DE",
        label: "德国",
      },
      {
        value: "FR",
        label: "法国",
      },
      {
        value: "JP",
        label: "日本",
      },
      {
        value: "KR",
        label: "韩国",
      },
      {
        value: "AU",
        label: "澳大利亚",
      },
      {
        value: "CA",
        label: "加拿大",
      },
      {
        value: "SG",
        label: "新加坡",
      },
      {
        value: "GLOBAL",
        label: "全球",
      },
    ],
    collection_interval_minutes: [
      {
        value: 15,
        label: "每 15 分钟",
      },
      {
        value: 60,
        label: "每小时",
      },
      {
        value: 360,
        label: "每 6 小时",
      },
      {
        value: 720,
        label: "每 12 小时",
      },
      {
        value: 1440,
        label: "每天",
      },
    ],
    recommendation_min_source_count: [
      {
        value: 1,
        label: "命中 1 个真实来源",
      },
      {
        value: 2,
        label: "至少 2 个独立来源",
      },
      {
        value: 3,
        label: "至少 3 个独立来源",
      },
    ],
  },
  edited: {
    name: "",
    include_keywords: " coffee brush，portable washer,coffee brush ",
    negative_keywords: " used, replacement ",
    market: "US",
    category: " Home & Kitchen ",
    collection_interval_minutes: 360,
    recommendation_min_source_count: 2,
  },
  paused: [
    {
      id: "00000000-0000-4000-8000-000000000941",
      name: "隔离暂停规则 1",
      include_keywords: ["coffee brush"],
      negative_keywords: [],
      market: "US",
      language: "en-US",
      category: null,
      collection_interval_minutes: 720,
      recommendation_min_source_count: 3,
      status: "paused",
      version: 4,
    },
    {
      id: "00000000-0000-4000-8000-000000000942",
      name: "隔离暂停规则 2",
      include_keywords: ["coffee brush"],
      negative_keywords: [],
      market: "US",
      language: "en-US",
      category: null,
      collection_interval_minutes: 60,
      recommendation_min_source_count: 1,
      status: "paused",
      version: 8,
    },
  ],
  createCases: [
    {
      form: {
        name: "",
        include_keywords: " coffee brush，portable washer,coffee brush ",
        negative_keywords: " used, replacement ",
        market: "US",
        category: " Home & Kitchen ",
        collection_interval_minutes: 360,
        recommendation_min_source_count: 2,
      },
      result: {
        calls: [
          {
            path: "/trends/monitoring-rules",
            method: "POST",
            body: {
              name: "自动选品 · coffee brush",
              include_keywords: ["coffee brush", "portable washer", "coffee brush"],
              negative_keywords: ["used", "replacement"],
              market: "US",
              language: "en-US",
              category: "Home & Kitchen",
              notification_channel: "in_app",
              collection_interval_minutes: 360,
              recommendation_min_source_count: 2,
            },
          },
        ],
        message: "规则已启用，系统会立即开始首轮采集。",
        setupOpen: false,
      },
    },
    {
      form: {
        name: "",
        include_keywords: " coffee brush，portable washer,coffee brush ",
        negative_keywords: " used, replacement ",
        market: "GB",
        category: " Home & Kitchen ",
        collection_interval_minutes: 360,
        recommendation_min_source_count: 2,
      },
      result: {
        calls: [
          {
            path: "/trends/monitoring-rules",
            method: "POST",
            body: {
              name: "自动选品 · coffee brush",
              include_keywords: ["coffee brush", "portable washer", "coffee brush"],
              negative_keywords: ["used", "replacement"],
              market: "GB",
              language: "en-US",
              category: "Home & Kitchen",
              notification_channel: "in_app",
              collection_interval_minutes: 360,
              recommendation_min_source_count: 2,
            },
          },
        ],
        message: "规则已启用，系统会立即开始首轮采集。",
        setupOpen: false,
      },
    },
    {
      form: {
        name: "",
        include_keywords: " coffee brush，portable washer,coffee brush ",
        negative_keywords: " used, replacement ",
        market: "DE",
        category: " Home & Kitchen ",
        collection_interval_minutes: 360,
        recommendation_min_source_count: 2,
      },
      result: {
        calls: [
          {
            path: "/trends/monitoring-rules",
            method: "POST",
            body: {
              name: "自动选品 · coffee brush",
              include_keywords: ["coffee brush", "portable washer", "coffee brush"],
              negative_keywords: ["used", "replacement"],
              market: "DE",
              language: "de-DE",
              category: "Home & Kitchen",
              notification_channel: "in_app",
              collection_interval_minutes: 360,
              recommendation_min_source_count: 2,
            },
          },
        ],
        message: "规则已启用，系统会立即开始首轮采集。",
        setupOpen: false,
      },
    },
    {
      form: {
        name: "",
        include_keywords: " coffee brush，portable washer,coffee brush ",
        negative_keywords: " used, replacement ",
        market: "FR",
        category: " Home & Kitchen ",
        collection_interval_minutes: 360,
        recommendation_min_source_count: 2,
      },
      result: {
        calls: [
          {
            path: "/trends/monitoring-rules",
            method: "POST",
            body: {
              name: "自动选品 · coffee brush",
              include_keywords: ["coffee brush", "portable washer", "coffee brush"],
              negative_keywords: ["used", "replacement"],
              market: "FR",
              language: "fr-FR",
              category: "Home & Kitchen",
              notification_channel: "in_app",
              collection_interval_minutes: 360,
              recommendation_min_source_count: 2,
            },
          },
        ],
        message: "规则已启用，系统会立即开始首轮采集。",
        setupOpen: false,
      },
    },
    {
      form: {
        name: "",
        include_keywords: " coffee brush，portable washer,coffee brush ",
        negative_keywords: " used, replacement ",
        market: "JP",
        category: " Home & Kitchen ",
        collection_interval_minutes: 360,
        recommendation_min_source_count: 2,
      },
      result: {
        calls: [
          {
            path: "/trends/monitoring-rules",
            method: "POST",
            body: {
              name: "自动选品 · coffee brush",
              include_keywords: ["coffee brush", "portable washer", "coffee brush"],
              negative_keywords: ["used", "replacement"],
              market: "JP",
              language: "ja-JP",
              category: "Home & Kitchen",
              notification_channel: "in_app",
              collection_interval_minutes: 360,
              recommendation_min_source_count: 2,
            },
          },
        ],
        message: "规则已启用，系统会立即开始首轮采集。",
        setupOpen: false,
      },
    },
    {
      form: {
        name: "",
        include_keywords: " coffee brush，portable washer,coffee brush ",
        negative_keywords: " used, replacement ",
        market: "KR",
        category: " Home & Kitchen ",
        collection_interval_minutes: 360,
        recommendation_min_source_count: 2,
      },
      result: {
        calls: [
          {
            path: "/trends/monitoring-rules",
            method: "POST",
            body: {
              name: "自动选品 · coffee brush",
              include_keywords: ["coffee brush", "portable washer", "coffee brush"],
              negative_keywords: ["used", "replacement"],
              market: "KR",
              language: "ko-KR",
              category: "Home & Kitchen",
              notification_channel: "in_app",
              collection_interval_minutes: 360,
              recommendation_min_source_count: 2,
            },
          },
        ],
        message: "规则已启用，系统会立即开始首轮采集。",
        setupOpen: false,
      },
    },
    {
      form: {
        name: "",
        include_keywords: " coffee brush，portable washer,coffee brush ",
        negative_keywords: " used, replacement ",
        market: "AU",
        category: " Home & Kitchen ",
        collection_interval_minutes: 360,
        recommendation_min_source_count: 2,
      },
      result: {
        calls: [
          {
            path: "/trends/monitoring-rules",
            method: "POST",
            body: {
              name: "自动选品 · coffee brush",
              include_keywords: ["coffee brush", "portable washer", "coffee brush"],
              negative_keywords: ["used", "replacement"],
              market: "AU",
              language: "en-US",
              category: "Home & Kitchen",
              notification_channel: "in_app",
              collection_interval_minutes: 360,
              recommendation_min_source_count: 2,
            },
          },
        ],
        message: "规则已启用，系统会立即开始首轮采集。",
        setupOpen: false,
      },
    },
    {
      form: {
        name: "",
        include_keywords: " coffee brush，portable washer,coffee brush ",
        negative_keywords: " used, replacement ",
        market: "CA",
        category: " Home & Kitchen ",
        collection_interval_minutes: 360,
        recommendation_min_source_count: 2,
      },
      result: {
        calls: [
          {
            path: "/trends/monitoring-rules",
            method: "POST",
            body: {
              name: "自动选品 · coffee brush",
              include_keywords: ["coffee brush", "portable washer", "coffee brush"],
              negative_keywords: ["used", "replacement"],
              market: "CA",
              language: "en-US",
              category: "Home & Kitchen",
              notification_channel: "in_app",
              collection_interval_minutes: 360,
              recommendation_min_source_count: 2,
            },
          },
        ],
        message: "规则已启用，系统会立即开始首轮采集。",
        setupOpen: false,
      },
    },
    {
      form: {
        name: "",
        include_keywords: " coffee brush，portable washer,coffee brush ",
        negative_keywords: " used, replacement ",
        market: "SG",
        category: " Home & Kitchen ",
        collection_interval_minutes: 360,
        recommendation_min_source_count: 2,
      },
      result: {
        calls: [
          {
            path: "/trends/monitoring-rules",
            method: "POST",
            body: {
              name: "自动选品 · coffee brush",
              include_keywords: ["coffee brush", "portable washer", "coffee brush"],
              negative_keywords: ["used", "replacement"],
              market: "SG",
              language: "en-US",
              category: "Home & Kitchen",
              notification_channel: "in_app",
              collection_interval_minutes: 360,
              recommendation_min_source_count: 2,
            },
          },
        ],
        message: "规则已启用，系统会立即开始首轮采集。",
        setupOpen: false,
      },
    },
    {
      form: {
        name: "",
        include_keywords: " coffee brush，portable washer,coffee brush ",
        negative_keywords: " used, replacement ",
        market: "GLOBAL",
        category: " Home & Kitchen ",
        collection_interval_minutes: 360,
        recommendation_min_source_count: 2,
      },
      result: {
        calls: [
          {
            path: "/trends/monitoring-rules",
            method: "POST",
            body: {
              name: "自动选品 · coffee brush",
              include_keywords: ["coffee brush", "portable washer", "coffee brush"],
              negative_keywords: ["used", "replacement"],
              market: "GLOBAL",
              language: "en-US",
              category: "Home & Kitchen",
              notification_channel: "in_app",
              collection_interval_minutes: 360,
              recommendation_min_source_count: 2,
            },
          },
        ],
        message: "规则已启用，系统会立即开始首轮采集。",
        setupOpen: false,
      },
    },
  ],
  resume: {
    calls: [
      {
        path: "/trends/monitoring-rules/00000000-0000-4000-8000-000000000941",
        method: "PATCH",
        body: {
          status: "enabled",
          expected_version: 4,
          collection_interval_minutes: 720,
          recommendation_min_source_count: 3,
        },
      },
    ],
    message: "“隔离暂停规则 1”已恢复，系统会立即开始采集。",
    setupOpen: true,
  },
  noKeywords: {
    calls: [],
    message: "至少填写一个希望持续寻找的商品关键词。",
    setupOpen: true,
  },
  noManage: {
    calls: [],
    message: "至少填写一个希望持续寻找的商品关键词。",
    setupOpen: true,
  },
  gaps: [
    {
      hasSelection: true,
      state: "empty",
      rules: [],
      setupOpen: true,
      displayedSelection: {
        state: "not_configured",
        enabled_rule_count: 0,
        candidate_count: 0,
        rule_candidate_count: 0,
        recommended_count: 0,
        awaiting_evidence_count: 0,
        adopted_count: 0,
        recommended_items: [],
        last_collection_at: null,
        next_collection_at: null,
      },
      status: "known-gap-not-fixed",
    },
    {
      hasSelection: false,
      state: "empty",
      rules: [],
      setupOpen: false,
      displayedSelection: {
        state: "not_configured",
        enabled_rule_count: 0,
        candidate_count: 0,
        rule_candidate_count: 0,
        recommended_count: 0,
        awaiting_evidence_count: 0,
        adopted_count: 0,
        recommended_items: [],
        last_collection_at: null,
        next_collection_at: null,
      },
      status: "known-gap-not-fixed",
    },
  ],
  summary: {
    actions: [
      {
        id: "00000000-0000-4000-8000-000000000952",
        kind: "action",
        title: "隔离样例 · 补齐来源核验",
        reason: "隔离样例：按当前工作项事实进入详情复核。",
        route: "/tasks/00000000-0000-4000-8000-000000000952",
        source_module: "task",
        source_label: "隔离工作项",
        context_label: "去处理",
        priority: "overdue",
        risk_level: "normal",
        value_score: null,
        blocked: false,
        owner_label: null,
        due_at: "2026-09-07T00:00:00.000Z",
        source_count: null,
        observed_at: "2026-09-07T00:00:00.000Z",
        severity: "warning",
        source_version: 1,
      },
      {
        id: "00000000-0000-4000-8000-000000000953",
        kind: "action",
        title: "隔离样例 · 当前节点待审批",
        reason: "隔离样例：按当前工作项事实进入详情复核。",
        route: "/tasks/approvals?approval=00000000-0000-4000-8000-000000000953",
        source_module: "approval",
        source_label: "隔离工作项",
        context_label: "去处理",
        priority: "blocking",
        risk_level: "normal",
        value_score: null,
        blocked: true,
        owner_label: null,
        due_at: null,
        source_count: null,
        observed_at: "2026-09-07T00:00:00.000Z",
        severity: "info",
        source_version: 1,
      },
      {
        id: "00000000-0000-4000-8000-000000000951",
        kind: "action",
        title: "隔离样例 · 便携清洁工具",
        reason: "隔离样例：按当前工作项事实进入详情复核。",
        route: "/opportunities/00000000-0000-4000-8000-000000000951",
        source_module: "opportunity",
        source_label: "隔离工作项",
        context_label: "去处理",
        priority: "high_value",
        risk_level: "normal",
        value_score: 86.5,
        blocked: false,
        owner_label: null,
        due_at: null,
        source_count: null,
        observed_at: "2026-09-07T00:00:00.000Z",
        severity: "info",
        source_version: 1,
      },
    ],
    changes: [
      {
        id: "00000000-0000-4000-8000-000000000955",
        kind: "change",
        title: "隔离样例 · 来源变化",
        reason: "隔离样例：按当前工作项事实进入详情复核。",
        route: "/trends?topic=00000000-0000-4000-8000-000000000955",
        source_module: "projection",
        source_label: "隔离工作项",
        context_label: "去处理",
        priority: null,
        risk_level: "normal",
        value_score: null,
        blocked: false,
        owner_label: null,
        due_at: null,
        source_count: null,
        observed_at: "2026-09-07T00:00:00.000Z",
        severity: "info",
        source_version: 1,
      },
    ],
    follows: [
      {
        id: "00000000-0000-4000-8000-000000000956",
        kind: "follow",
        title: "隔离样例 · 我的关注",
        reason: "隔离样例：按当前工作项事实进入详情复核。",
        route: "/trends?topic=00000000-0000-4000-8000-000000000956",
        source_module: "projection",
        source_label: "隔离工作项",
        context_label: "去处理",
        priority: null,
        risk_level: "normal",
        value_score: null,
        blocked: false,
        owner_label: null,
        due_at: null,
        source_count: null,
        observed_at: "2026-09-07T00:00:00.000Z",
        severity: "info",
        source_version: 1,
      },
    ],
    health: [
      {
        id: "00000000-0000-4000-8000-000000000954",
        kind: "health",
        title: "隔离样例 · 本人采集任务受阻",
        reason: "隔离样例：按当前工作项事实进入详情复核。",
        route: "/tasks/00000000-0000-4000-8000-000000000954",
        source_module: "projection",
        source_label: "隔离工作项",
        context_label: "去处理",
        priority: "blocking",
        risk_level: "normal",
        value_score: null,
        blocked: true,
        owner_label: null,
        due_at: null,
        source_count: null,
        observed_at: "2026-09-07T00:00:00.000Z",
        severity: "critical",
        source_version: 1,
      },
    ],
    automatic_selection: {
      state: "running",
      enabled_rule_count: 3,
      candidate_count: 17,
      rule_candidate_count: 5,
      recommended_count: 4,
      awaiting_evidence_count: 8,
      adopted_count: 2,
      recommended_items: [
        {
          id: "00000000-0000-4000-8000-000000000951",
          kind: "action",
          title: "隔离样例 · 便携清洁工具",
          reason: "隔离样例：按当前工作项事实进入详情复核。",
          route: "/opportunities/00000000-0000-4000-8000-000000000951",
          source_module: "opportunity",
          source_label: "隔离工作项",
          context_label: "去处理",
          priority: "high_value",
          risk_level: "normal",
          value_score: 86.5,
          blocked: false,
          owner_label: null,
          due_at: null,
          source_count: null,
          observed_at: "2026-09-07T00:00:00.000Z",
          severity: "info",
          source_version: 1,
        },
      ],
      last_collection_at: "2026-09-07T00:00:00.000Z",
      next_collection_at: "2026-09-07T01:00:00.000Z",
    },
    scope: {
      organization_id: "sample-org",
      workspace_id: "sample-workspace",
    },
    generated_at: "2026-09-07T00:00:00.000Z",
  },
  zero: {
    state: "not_configured",
    enabled_rule_count: 0,
    candidate_count: 0,
    rule_candidate_count: 0,
    recommended_count: 0,
    awaiting_evidence_count: 0,
    adopted_count: 0,
    recommended_items: [],
    last_collection_at: null,
    next_collection_at: null,
  },
  priorities: {
    overdue: "逾期",
    blocking: "阻断",
    high_risk: "高风险",
    high_value: "高价值",
    normal: "普通",
  },
};
