window.CONTENT_DATA = {
  sourcePaths: [
    "apps/web/src/components/use-platform-content-list.ts",
    "apps/web/src/components/use-platform-content-review.ts",
    "apps/web/src/components/platform-management-presentation.ts",
    "apps/web/src/components/PlatformManagementCenter.vue",
    "apps/web/src/components/PlatformManagementFilter.vue",
    "apps/web/src/components/PlatformManagementRecordList.vue",
    "apps/web/src/components/PlatformContentPagination.vue",
    "apps/web/src/components/ResponsiveDataView.vue",
    "apps/web/src/components/ResponsiveFilterDrawer.vue",
    "apps/web/src/components/TableViewControls.vue",
    "apps/web/src/use-modal-dialog.ts",
    "apps/api/src/platform-dashboard-service.ts",
    "apps/api/src/platform-dashboard-routes.ts",
    "apps/api/src/mysql-platform-dashboard-repository.ts",
    "tests/unit/platform-content.test.mjs",
    "tests/e2e/m06-02-platform-dashboard.spec.ts",
  ],
  sourceChecks: [
    "Actual list: 15s timeout, replacement abort/sequence; edited pending query changes success URL without changing request; stop alone does not invalidate ignored-abort response. These are source boundaries, not fixed production code.",
    "Actual first and retained timeout states; parent wrapper discards structured failure kind and empty branch hides summary/list/pagination (static consumer boundary).",
    "Actual review: same-status body, duplicate submit reaches two PATCH adapters; old response closes newly opened item; successful write hides reload error. No HTTP or business writes occurred.",
    "Actual service: four read/three write statuses, numeric-string version conversion, trimmed 2–300 reason boundary, loose 36-character hex/hyphen ID; no fabricated strict UUID or current-state rejection.",
    "Actual read repository in inert adapter: summary query-only versus status-filtered total, escaped title/category/market LIKE, 0/1/20/21/135 counts, clamped page and deterministic LIMIT/OFFSET. Original fixture has one row, not 135 real records.",
    "Actual moderation repository with inert connection: same-status increments version and writes three records, conflict/missing rolls back, idempotent result skips writes, connection always releases. No database was connected.",
  ],
  original: {
    domain: "content",
    summary: { total: 135, active: 90, irrelevant: 25, stale: 19, archived: 1 },
    items: [
      {
        id: "00000000-0000-4000-8000-000000000701",
        title: "便携式照明热度上升",
        category: "home",
        market: "US",
        language: "en-US",
        status: "active",
        signal_count: 18,
        source_count: 5,
        heat_value: 82,
        confidence_status: "measured",
        version: 1,
        last_seen_at: "2026-08-08T12:00:00.000Z",
        organization_name: "米豆选品",
        workspace_name: "默认工作区",
      },
    ],
    pagination: { page: 1, page_size: 20, total: 135, total_pages: 7 },
    observed_at: "2026-08-08T12:00:00.000Z",
  },
  statuses: ["active", "irrelevant", "stale", "archived"],
  stateNames: {
    active: "展示中",
    irrelevant: "无关",
    stale: "已过期",
    archived: "已归档",
    measured: "已测量",
    insufficient_data: "数据不足",
  },
};
