window.PERMISSION_C_DATA = {
  roles: [
    {
      code: "platform_operations_admin",
      name: "平台运营管理员",
      category: "platform",
      description: "管理平台运营，不可读取密钥明文。",
      capabilities: ["platform:operate", "collection:replay", "report:read"],
    },
    {
      code: "platform_security_admin",
      name: "平台安全管理员",
      category: "platform",
      description: "安全治理，对业务数据只读。",
      capabilities: ["platform:secure", "audit:read", "session:manage"],
    },
    {
      code: "platform_super_admin",
      name: "平台超级管理员",
      category: "platform",
      description: "初始化、授权和紧急处置，全部操作审计。",
      capabilities: [
        "platform:operate",
        "platform:secure",
        "platform:superadmin",
        "collection:replay",
        "report:read",
        "audit:read",
        "session:manage",
      ],
    },
  ],
  capabilityLabels: {
    "platform:operate": {
      label: "管理平台运营",
      group: "平台治理",
    },
    "collection:replay": {
      label: "重放采集任务",
      group: "采集治理",
    },
    "report:read": {
      label: "查看报表",
      group: "通知与报表",
    },
    "platform:secure": {
      label: "管理平台安全",
      group: "平台治理",
    },
    "audit:read": {
      label: "查看审计",
      group: "安全治理",
    },
    "session:manage": {
      label: "管理登录会话",
      group: "安全治理",
    },
    "platform:superadmin": {
      label: "管理平台角色与账号",
      group: "平台治理",
    },
  },
  cases: [
    {
      key: "default",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_security_admin",
        differencesOnly: true,
        capabilityQuery: "",
        capabilityGroup: "",
      },
      rows: [
        {
          capability: "report:read",
          label: "查看报表",
          group: "通知与报表",
          left: true,
          right: false,
          difference: "仅平台运营管理员",
        },
        {
          capability: "audit:read",
          label: "查看审计",
          group: "安全治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
        {
          capability: "session:manage",
          label: "管理登录会话",
          group: "安全治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
        {
          capability: "platform:secure",
          label: "管理平台安全",
          group: "平台治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
        {
          capability: "platform:operate",
          label: "管理平台运营",
          group: "平台治理",
          left: true,
          right: false,
          difference: "仅平台运营管理员",
        },
        {
          capability: "collection:replay",
          label: "重放采集任务",
          group: "采集治理",
          left: true,
          right: false,
          difference: "仅平台运营管理员",
        },
      ],
    },
    {
      key: "all",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_security_admin",
        differencesOnly: false,
        capabilityQuery: "",
        capabilityGroup: "",
      },
      rows: [
        {
          capability: "report:read",
          label: "查看报表",
          group: "通知与报表",
          left: true,
          right: false,
          difference: "仅平台运营管理员",
        },
        {
          capability: "audit:read",
          label: "查看审计",
          group: "安全治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
        {
          capability: "session:manage",
          label: "管理登录会话",
          group: "安全治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
        {
          capability: "platform:secure",
          label: "管理平台安全",
          group: "平台治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
        {
          capability: "platform:operate",
          label: "管理平台运营",
          group: "平台治理",
          left: true,
          right: false,
          difference: "仅平台运营管理员",
        },
        {
          capability: "collection:replay",
          label: "重放采集任务",
          group: "采集治理",
          left: true,
          right: false,
          difference: "仅平台运营管理员",
        },
      ],
    },
    {
      key: "same-differences",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_operations_admin",
        differencesOnly: true,
        capabilityQuery: "",
        capabilityGroup: "",
      },
      rows: [],
    },
    {
      key: "same-all",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_operations_admin",
        differencesOnly: false,
        capabilityQuery: "",
        capabilityGroup: "",
      },
      rows: [
        {
          capability: "report:read",
          label: "查看报表",
          group: "通知与报表",
          left: true,
          right: true,
          difference: "两者相同",
        },
        {
          capability: "platform:operate",
          label: "管理平台运营",
          group: "平台治理",
          left: true,
          right: true,
          difference: "两者相同",
        },
        {
          capability: "collection:replay",
          label: "重放采集任务",
          group: "采集治理",
          left: true,
          right: true,
          difference: "两者相同",
        },
      ],
    },
    {
      key: "super-operations",
      controls: {
        compareLeft: "platform_super_admin",
        compareRight: "platform_operations_admin",
        differencesOnly: true,
        capabilityQuery: "",
        capabilityGroup: "",
      },
      rows: [
        {
          capability: "audit:read",
          label: "查看审计",
          group: "安全治理",
          left: true,
          right: false,
          difference: "仅平台超级管理员",
        },
        {
          capability: "session:manage",
          label: "管理登录会话",
          group: "安全治理",
          left: true,
          right: false,
          difference: "仅平台超级管理员",
        },
        {
          capability: "platform:secure",
          label: "管理平台安全",
          group: "平台治理",
          left: true,
          right: false,
          difference: "仅平台超级管理员",
        },
        {
          capability: "platform:superadmin",
          label: "管理平台角色与账号",
          group: "平台治理",
          left: true,
          right: false,
          difference: "仅平台超级管理员",
        },
      ],
    },
    {
      key: "super-operations-all",
      controls: {
        compareLeft: "platform_super_admin",
        compareRight: "platform_operations_admin",
        differencesOnly: false,
        capabilityQuery: "",
        capabilityGroup: "",
      },
      rows: [
        {
          capability: "report:read",
          label: "查看报表",
          group: "通知与报表",
          left: true,
          right: true,
          difference: "两者相同",
        },
        {
          capability: "audit:read",
          label: "查看审计",
          group: "安全治理",
          left: true,
          right: false,
          difference: "仅平台超级管理员",
        },
        {
          capability: "session:manage",
          label: "管理登录会话",
          group: "安全治理",
          left: true,
          right: false,
          difference: "仅平台超级管理员",
        },
        {
          capability: "platform:secure",
          label: "管理平台安全",
          group: "平台治理",
          left: true,
          right: false,
          difference: "仅平台超级管理员",
        },
        {
          capability: "platform:superadmin",
          label: "管理平台角色与账号",
          group: "平台治理",
          left: true,
          right: false,
          difference: "仅平台超级管理员",
        },
        {
          capability: "platform:operate",
          label: "管理平台运营",
          group: "平台治理",
          left: true,
          right: true,
          difference: "两者相同",
        },
        {
          capability: "collection:replay",
          label: "重放采集任务",
          group: "采集治理",
          left: true,
          right: true,
          difference: "两者相同",
        },
      ],
    },
    {
      key: "reverse",
      controls: {
        compareLeft: "platform_security_admin",
        compareRight: "platform_operations_admin",
        differencesOnly: true,
        capabilityQuery: "",
        capabilityGroup: "",
      },
      rows: [
        {
          capability: "report:read",
          label: "查看报表",
          group: "通知与报表",
          left: false,
          right: true,
          difference: "仅平台运营管理员",
        },
        {
          capability: "audit:read",
          label: "查看审计",
          group: "安全治理",
          left: true,
          right: false,
          difference: "仅平台安全管理员",
        },
        {
          capability: "session:manage",
          label: "管理登录会话",
          group: "安全治理",
          left: true,
          right: false,
          difference: "仅平台安全管理员",
        },
        {
          capability: "platform:secure",
          label: "管理平台安全",
          group: "平台治理",
          left: true,
          right: false,
          difference: "仅平台安全管理员",
        },
        {
          capability: "platform:operate",
          label: "管理平台运营",
          group: "平台治理",
          left: false,
          right: true,
          difference: "仅平台运营管理员",
        },
        {
          capability: "collection:replay",
          label: "重放采集任务",
          group: "采集治理",
          left: false,
          right: true,
          difference: "仅平台运营管理员",
        },
      ],
    },
    {
      key: "code-search",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_security_admin",
        differencesOnly: true,
        capabilityQuery: "  PLATFORM:  ",
        capabilityGroup: "",
      },
      rows: [
        {
          capability: "platform:secure",
          label: "管理平台安全",
          group: "平台治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
        {
          capability: "platform:operate",
          label: "管理平台运营",
          group: "平台治理",
          left: true,
          right: false,
          difference: "仅平台运营管理员",
        },
      ],
    },
    {
      key: "name-search",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_security_admin",
        differencesOnly: true,
        capabilityQuery: "管理",
        capabilityGroup: "",
      },
      rows: [
        {
          capability: "session:manage",
          label: "管理登录会话",
          group: "安全治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
        {
          capability: "platform:secure",
          label: "管理平台安全",
          group: "平台治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
        {
          capability: "platform:operate",
          label: "管理平台运营",
          group: "平台治理",
          left: true,
          right: false,
          difference: "仅平台运营管理员",
        },
      ],
    },
    {
      key: "group-security",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_security_admin",
        differencesOnly: true,
        capabilityQuery: "",
        capabilityGroup: "安全治理",
      },
      rows: [
        {
          capability: "audit:read",
          label: "查看审计",
          group: "安全治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
        {
          capability: "session:manage",
          label: "管理登录会话",
          group: "安全治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
      ],
    },
    {
      key: "group-collection",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_security_admin",
        differencesOnly: true,
        capabilityQuery: "",
        capabilityGroup: "采集治理",
      },
      rows: [
        {
          capability: "collection:replay",
          label: "重放采集任务",
          group: "采集治理",
          left: true,
          right: false,
          difference: "仅平台运营管理员",
        },
      ],
    },
    {
      key: "group-reports",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_security_admin",
        differencesOnly: true,
        capabilityQuery: "",
        capabilityGroup: "通知与报表",
      },
      rows: [
        {
          capability: "report:read",
          label: "查看报表",
          group: "通知与报表",
          left: true,
          right: false,
          difference: "仅平台运营管理员",
        },
      ],
    },
    {
      key: "combined",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_security_admin",
        differencesOnly: true,
        capabilityQuery: "会话",
        capabilityGroup: "安全治理",
      },
      rows: [
        {
          capability: "session:manage",
          label: "管理登录会话",
          group: "安全治理",
          left: false,
          right: true,
          difference: "仅平台安全管理员",
        },
      ],
    },
    {
      key: "no-match",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_security_admin",
        differencesOnly: true,
        capabilityQuery: "不存在的能力",
        capabilityGroup: "",
      },
      rows: [],
    },
    {
      key: "unknown-group",
      controls: {
        compareLeft: "platform_operations_admin",
        compareRight: "platform_security_admin",
        differencesOnly: true,
        capabilityQuery: "",
        capabilityGroup: "旧目录分组",
      },
      rows: [],
    },
  ],
  checks: [
    "Original three-role/seven-capability fixture extracted unchanged; 15 actual computed full-row comparison cases",
    "Actual refs/watch callbacks: URL five keys, preserve unrelated keys, omit defaults, 80/40 bounds, invalid/zero/single roles, P44 no persistence; not mounted Vue",
    "Actual reset: enabled only by query/group; single non-default role reset leaves both selectors unresolved until roles array changes",
    "No reverse route-query watch; same-instance browser history synchronization not established",
    "Actual loadPlatformRoles: one in-flight GET, real 12000ms abort callback invoked inertly, first failure versus retained matrix including supplied 401/403 hints, timestamp and empty success",
    "Actual MySQL repository method run against inert rows: active platform parameter, left join, grouped projection and empty capabilities; no SQL executed",
    "No production API, authentication, authorization, database, audit, Vue lifecycle or deployment verification",
  ],
  sourcePaths: [
    "apps/web/src/components/PlatformRoleComparison.vue",
    "apps/web/src/components/PlatformAccountCenter.vue",
    "apps/api/src/authorization-routes.ts",
    "apps/api/src/mysql-authorization-repository.ts",
    "packages/authorization/src/index.ts",
    "tests/e2e/m06-01-platform-accounts.spec.ts",
  ],
};
